### ISSUE TITLE
woocommerce-ordering not rendered in reusable block

### ISSUE THREAD

**Issue by fotovat** [woocommerce/woocommerce-gutenberg-products-block#3191] opened 2020-09-24 09:13 UTC
## Describe the bug
"Products by Category" or "Newest Products" grid rendered without Ordering dropdown when they are in reusable blocks.

## To reproduce

1. create a reusable block
2. add "Newest Products"
3. use the reusable block by in single.php : 

```
$reuse_block_id = 534;
$reuse_block = get_post($reuse_block_id);
$reuse_block_content = apply_filters('the_content', $reuse_block->post_content);
echo $reuse_block_content;
```

4. products rendered successfully without ordering dropdown.

## Expected behavior
Show ordering drop down

### WordPress
* Core version: 5.1.1
* Gutenberg version : 9.0.0
* WooCommerce version: 5.4.2
* WooCommerce Blocks version: 3.4.0
* Site language: English
* Any other plugins installed:

**Comment by nerrad** [comment] 2020-09-24 11:27
Hi there 👋 

Thanks for taking the time to report the issue you discovered. You mentioned that when you use the Products by Category or the Newest Products block via reusable blocks, that an "ordering dropdown" is not rendered. I just want to clarify a couple things around "ordering dropdown". Neither of these blocks have a user facing "ordering dropdown" feature with them usable by visitors on the frontend so it's a bit unclear what you're referring to. I'm _guessing_ you may be referring to the "Order Products By" control that is available when the block is selected in the block editor like the below screenshot:

<img width="322" alt="Image 2020-09-24 at 7 24 00 AM" src="https://user-images.githubusercontent.com/1429108/94139068-0cd28100-fe37-11ea-9ef5-4b3d0a0f8331.png">

Is that correct? If so, there isn't a bug here, after you save a block (or multiple block(s)) as a reusable block, the controls for the individual blocks are not available until you click to _edit_ the reusable block. At that point you should be able to configure the controls and save them again.

If my guess was incorrect (which also could be the case given that with your example it sounds like you may be talking about something on the frontend), I'll need you to clarify exactly what you mean by "ordering dropdown" feature. Could you share some screenshots to illustrate?

**Comment by fotovat** [comment] 2020-09-24 12:28
Hi there,
Thank you for your replay, actually in frontend the highlighted items are missing.

the following picture taken when reusable block included normally: 
![correct](https://user-images.githubusercontent.com/33073559/94144810-788c0c80-fe7e-11ea-9655-443d81e1fafa.JPG)

the following picture taken when same as above reusable block included programmatically" by this code in single.php
```
$reuse_block_id = 534;
$reuse_block = get_post($reuse_block_id);
$reuse_block_content = apply_filters('the_content', $reuse_block->post_content);
echo $reuse_block_content;
```
![incorrect](https://user-images.githubusercontent.com/33073559/94144948-acffc880-fe7e-11ea-9332-c1fe1c603974.JPG)

**Comment by nerrad** [comment] 2020-09-24 13:50
Thanks for the expanded explanation, unfortunately there's nothing I can do to help here as this is not something I can reproduce. It looks like this is specific to the customizations being done on your site. What I can tell you is that the blocks you've mentioned in this issue do not add any results indicator or sort selector (at least the blocks included in this feature plugin). I don't know where those elements are coming from in your screenshot.  The snippet you've shared for programmatically adding a reusable block might not be accounting for whatever additional code is on your site that adds the elements. Providing support for that kind of customization is outside the scope of what can be obtained in this repository.

Since there's nothing actionable at this time, I'm going to close this issue. However, if you're able to provide additional information that would help us with reproducing something that is a clear bug with the WooCommerce Blocks feature plugin, I'll be happy to take another look, just leave a comment. I'd need clear steps that I could use to reproduce the same issue on a store with no customizations adding additional features not included in the blocks.

**Closed by nerrad** 2020-09-24 13:50 UTC
Labels: action: needs feedback, type: support
