### ISSUE TITLE
Incompatibility with Woocommerce 5.6.0

### ISSUE THREAD

**Issue by Seventoor** [woocommerce/woocommerce-gutenberg-products-block#4601] opened 2021-08-18 10:15 UTC
If I update to the newest Woocommerce Version 5.6.0 I get a critical Error and can't access my site without rolling back.

Log: 

```
An error of type E_ERROR was caused in line 89 of the file /home/elyotdes/domains/printnaut.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/Container.php. Error message: Uncaught Exception: Cannot construct an instance of Automattic\WooCommerce\Blocks\Assets\AssetDataRegistry because it has not been registered. in /home/elyotdes/domains/printnaut.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/Container.php:89
Stack trace:
#0 /home/elyotdes/domains/printnaut.com/public_html/wp-content/plugins/woo-stripe-payment/packages/blocks/src/Config.php(68): Automattic\WooCommerce\Blocks\Registry\Container->get('Automattic\\WooC...')
#1 /home/elyotdes/domains/printnaut.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/AbstractDependencyType.php(42): PaymentPlugins\Blocks\Stripe\Config->PaymentPlugins\Blocks\Stripe\{closure}(Object(Automattic\WooCommerce\Blocks\Registry\Container))
#2 /home/elyotdes/domains/printnaut.com/public_html/wp-content/plugins/woo-gutenberg-products-block/src/Registry/SharedType.php(28): Automattic\WooCommerce\Blocks\Registry\AbstractDependencyType->resolve_value(Object(Automattic\WooCommerce\Blocks\Registry\
```

WordPress:
* Core version: 5.8.0
* WooCommerce version: 5.6.0
* WooCommerce Blocks version: 5.7.0
* Site language: English
* Any other plugins installed: 
- Ajax add to cart for WooCommerce
- Elementor Pro
- Germanized for Woocommerce
- Jetpack
- Litespeed Cache
- Mailchimp for Woocommerce
- Stripe for Woocommerce
- Yoast SEO

**Comment by opr** [comment] 2021-08-18 15:07
Hi there, thanks for reporting this issue - I just tried an upgrade on a test site of mine but I could not reproduce this.

Please could you try disabling all plugins besides WooCommerce and WooCommerce Blocks? Also, instead of trying to upgrade could you try deleting the plugins and reinstalling them?

If this fails, please send us a System Status report by going to your WordPress dashboard then: WooCommerce -> Status -> Get system report. Please then copy and paste that report into a reply here.

I look forward to hearing how you get on with these steps.

**Comment by ralucaStan** [comment] 2021-08-27 14:07
Hi @Seventoor 👋 ,
I'm going to close this because there still isn't anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we're able to reproduce we can re-open as necessary.

**Closed as completed by ralucaStan** 2021-08-27 14:07 UTC
