### ISSUE TITLE
PropTypes error in Package component when add-to-cart from grouped product page

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2839] opened 2020-07-09 04:24 UTC
**Describe the bug**
Getting a JS error in console when the quantity is a string instead of a number.

Saw this when working on #2838 - I thought I'd introduced it, was confused, but have now reproduced on `main` branch. 

```
react.js?ver=16.9.0:1750 Warning: Failed prop type: Invalid prop `shippingRates[0].items[1].quantity` of type `string` supplied to `Packages`, expected `number`.
    in Packages (created by ShippingRatesControl)
    in ShippingRatesControl (created by ShippingRateSelector)
    in fieldset (created by ShippingRateSelector)
    in ShippingRateSelector (created by TotalsShippingItem)
    in div (created by TotalsShippingItem)
    in TotalsShippingItem (created by Cart)
    in div (created by Sidebar)
    in Sidebar (created by Cart)
    in div (created by ContainerWidthContextProvider)
    in ContainerWidthContextProvider (created by SidebarLayout)
    in SidebarLayout (created by Cart)
    in Cart (created by Block)
    in PaymentMethodDataProvider (created by CartProvider)
    in ShippingDataProvider (created by CartProvider)
    in CheckoutStateProvider (created by CartProvider)
    in CartProvider (created by Block)
    in ValidationContextProvider (created by Block)
    in LoadingMask (created by Block)
    in Block (created by CartFrontend)
    in StoreNoticesProvider (created by CartFrontend)
    in CartFrontend
    in Unknown
    in Unknown
    in BlockErrorBoundary
```

We probably need to convert this quantity to a number in some API somewhere, or allow more flexibility on the component/client interface (e.g. allow string or number).

**To Reproduce**

1. Go to a grouped product page, e.g. `Logo Collection` from sample product data.
2. Pick a quantity and add something to cart.
3. Go to cart block page or checkout bock page with dev tools.
4. See JS error.

**Expected behavior**
No JS errors.

**Screenshots**

<img width="1057" alt="Screen Shot 2020-07-09 at 4 22 43 PM" src="https://user-images.githubusercontent.com/4167300/86996711-6f38bf80-c200-11ea-9d61-71ffc8adfbdc.png">

**Comment by nerrad** [comment] 2020-07-09 15:30
I can reproduce. This isn't a blocker, but definitely still should be fixed.

**Comment by Aljullu** [comment] 2020-08-04 13:06
After some investigation, I think that's an issue in Core. The behavior of the 'add to cart' action in the single product page differs whether the product added is a grouped product or a single/variable product. In the latter, the value is filtered and it becomes an integer, but that's not happening on grouped products.

I filled an issue in https://github.com/woocommerce/woocommerce/issues/27218 and created a PR in https://github.com/woocommerce/woocommerce/pull/27219. Depending on their resolution, we might not need to change anything in WC Blocks, I will add the `Blocked` label for now.

**Comment by Aljullu** [comment] 2020-09-14 08:37
Closing this since https://github.com/woocommerce/woocommerce/pull/27219 has been merged and the issue is no longer reproducible.

**Closed by Aljullu** 2020-09-14 08:37 UTC
Labels: scope: components, type: bug, ◼️ block: cart, ◼️ block: checkout
