### ISSUE TITLE
WooCommerce PayPal Payments doesn't work with the Cart & Checkout Blocks

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#6816] opened 2022-08-02 11:58 UTC
## This is a ticket that just **highlights the incompatibly of WooCommerce PayPal Payments** with the Cart and Checkout Blocks and tracks user reports

As a merchant, the best course of action right now if you are using a plugin that isn't working with the Cart and Checkout Blocks is to notify the developer of the extension and ask if they can add support.

### It's up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks.
Currently it's up to extension developers to add support for the new checkout flow offered via the Cart and Checkout Blocks. We have some [documentation for Third-party developers](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#third-party-developers) and some [Developer Resources](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs#developer-resources) available to help with their integration efforts.

You can keep on top of the [status of the Cart & Checkout Blocks in this documentation](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/).

------------

**Later edit** 
According to [this comment](https://github.com/woocommerce/woocommerce-paypal-payments/issues/211), from Nov. 4 2022 on [woocommerce-paypal-payments](https://github.com/woocommerce/woocommerce-paypal-payments), support for WC Blocks is coming.
 > Block support is one of the top priority items on the roadmap and is expected to be available in the coming months.
The progress for this will be tracked in [#211](https://github.com/woocommerce/woocommerce-paypal-payments/issues/211), so I am closing this issue.
For any questions regarding the plugin setup, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!

**Comment by ralucaStan** [comment] 2022-08-02 11:59
Related #3986

**Comment by ralucaStan** [comment] 2022-08-02 12:00
Related #3809

**Comment by ralucaStan** [comment] 2022-08-02 12:00
Related #4644

**Comment by ralucaStan** [comment] 2022-08-02 12:00
Related #4632

**Comment by ralucaStan** [comment] 2022-08-02 12:01
Related #4654

**Comment by ralucaStan** [comment] 2022-08-02 12:02
Related #4476

**Comment by ralucaStan** [comment] 2022-08-02 12:02
Related #3901

**Comment by ralucaStan** [comment] 2022-08-02 12:03
Related #3149

**Comment by ralucaStan** [comment] 2022-08-02 12:03
Related #3270

**Comment by ralucaStan** [comment] 2022-08-02 12:04
Related #3357

**Comment by ralucaStan** [comment] 2022-08-02 12:14
related #3072

**Comment by ralucaStan** [comment] 2022-08-02 12:15
related #3149

**Comment by ralucaStan** [comment] 2022-08-02 12:17
related #3872

**Comment by ralucaStan** [comment] 2022-08-02 12:19
related #3471

**Comment by ralucaStan** [comment] 2022-08-02 12:19
related #3615

**Comment by ralucaStan** [comment] 2022-08-02 12:20
related #3701

**Comment by ralucaStan** [comment] 2022-08-02 12:21
related #4380

**Comment by ralucaStan** [comment] 2022-08-02 12:22
related #5620

**Comment by masteradhoc** [comment] 2022-08-02 19:11
See open issue at their repository as reference: https://github.com/woocommerce/woocommerce-paypal-payments/issues/211

**Comment by ralucaStan** [comment] 2022-08-08 13:25
Related https://github.com/woocommerce/woocommerce-blocks/issues/6699#issuecomment-1189046631

**Comment by ralucaStan** [comment] 2022-08-12 13:45
related https://github.com/woocommerce/woocommerce-blocks/issues/6679

**Comment by ralucaStan** [comment] 2022-08-16 10:57
related #6762

**Comment by nielslange** [comment] 2022-09-30 12:37
Related https://wordpress.org/support/topic/paypal-checkout-not-showing/

**Comment by nielslange** [comment] 2022-10-04 08:47
Related https://wordpress.org/support/topic/support-paypal-checkout-plugin/

**Comment by nielslange** [comment] 2022-10-27 03:41
Related #7487

**Comment by thisissandip** [comment] 2022-11-09 12:53
Another one: https://wordpress.org/support/topic/paypal-is-not-working-3/#post-16181315

**Comment by tarhi-saad** [comment] 2022-12-02 11:15
Related #7820

**Comment by shevene** [comment] 2023-02-13 19:01
+1 [5954906-zen](5954906-zd-woothemes)

**Comment by ralucaStan** [comment] 2023-05-24 12:32
According to this https://github.com/woocommerce/woocommerce-paypal-payments/issues/211#issuecomment-1551145433 a new pre-release for the next PayPal Payments 2.0.5 is available [on GitHub](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.5-rc1) with express payment methods support in the WooCommerce blocks.

**Comment by devvnawaz** [comment] 2023-06-04 17:39
6363241-zen

**Comment by thisissandip** [comment] 2023-07-12 06:02
6527492-zen

**Comment by Babylon1999** [comment] 2023-07-25 17:19
zd-6572757

**Comment by ralucaStan** [comment] 2023-08-03 12:26
Happy to update you that PayPal buttons for the Block Cart and Block Express Checkout are now officially released. They were released in the recent v2.2.0 of WooCommerce PayPal Payments. You can read more about the current state and future plans is this documentation: [https://woocommerce.com/document/woocommerce-paypal-payments/#woocommerce-blocks](https://href.li/?https://woocommerce.com/document/woocommerce-paypal-payments/#woocommerce-blocks)

**Comment by sophiegyo** [comment] 2023-08-08 13:53
Related 6635352-zen

My test environment:

WP 6.2
Gutenberg 16.3.0
WooCommerce 7.9.0
WooCommerce Blocks 10.8.1
WooCommerce PayPal Payments 2.2.0

Theme: any FSE theme

Express checkout at the top:
<img width="1528" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/36608681/a8e27592-50e6-447b-820b-ac3940099093">

Regular checkout:
<img width="794" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/36608681/af7f11bb-3a55-482f-b917-fdf777c5adfa">

The Express checkout option at the top of the checkout page was appearing even after I removed the express checkout option - is that expected?
<img width="854" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/36608681/1c6f4a85-6e40-49cd-b3f4-fe6a8192273c">

**Comment by nielslange** [comment] 2023-08-09 10:14
Thanks for reaching out, @sophiegyo.

I could reproduce the first issue you reported, with the PayPal payment not showing up within the "Payment options" section on the checkout page and @ralucaStan will reach out to the developers of the PayPal extension.

As for the second issue, after I removed the option `Block Express Checkout` from the "Smart Button Locations", I could no longer see the PayPal button within the "Express Checkout" section on the checkout page. Would you mind double-checking if you were accidentally facing a caching error when testing this?

**Comment by InpsydeNiklas** [comment] 2023-08-09 11:13
Hello @sophiegyo 
Thank you for the feedback.
The warning `There are no payment methods available` in the payment method area is expected when there is no other Blocks-compatible payment gateway. The regular PayPal payment gateway on the Block Checkout page with the PayPal smart buttons is still in development. So the current iteration of the Blocks support in PayPal Payments includes only the express buttons on the Block Cart and Block Checkout. A PayPal payment gateway is only available when the buyer previously authorized a payment e.g. from the single product page and needs to confirm it from the Checkout page.

Releasing the Block features in different stages helps us to get feedback about the already developed Block features while the development of additional features (such as regular PayPal for Advanced Card Processing gateways) continues.
You can read more about it in the [PayPal Payments Blocks docs](https://woocommerce.com/document/woocommerce-paypal-payments/#woocommerce-blocks) and the [PayPal Payments Blocks FAQ](https://woocommerce.com/document/woocommerce-paypal-payments/#blocks-faq).

> The Express checkout option at the top of the checkout page was appearing even after I removed the express checkout option - is that expected?

This report is rather unusual and, similar to @nielslange I'm not seeing a way to reproduce the behavior. Once the `Block Express Checkout` button location was deselected, the Express area on the Block Checkout page is supposed to disappear entirely (at least if no other express payment methods are registered).
But what's also unusual is the display of the black "Credit or debit card" button visible on your first screenshot. Normally this button should not be present in this location.

I suggest [reaching out to the PayPal Payments support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) to gather more details about your request and for the team to provide appropriate guidance. Thank you!

**Comment by sophiegyo** [comment] 2023-08-19 13:57
Sorry @nielslange and @InpsydeNiklas  it took me a while to get back to this!

So first:
Yes, it looks like it was just caching on my site which was causing the buttons to appear following their removal from the settings :) 

Second:

>But what's also unusual is the display of the black "Credit or debit card" button visible on your first screenshot. Normally this button should not be present in this location.

Good to know! I didn't realise this was the case. I encountered another site having this trouble today; and while I was expecting the card option to be there (as was the user), I can now inform them that the express checkout appears correctly on their site:

<img width="720" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/36608681/075bbb65-e81f-44e5-8193-6b94efff9b7d">

Perhaps that too was just caching on my test site :)

**Comment by nielslange** [comment] 2023-08-21 08:40
Hello @sophiegyo 👋

I'm glad to hear that the issue no longer exists. I'm going to close this issue for now, but please don't hesitate to create another issue if you need more assistance or if you have more questions or suggestions. 😀

**Closed as completed by nielslange** 2023-08-21 08:40 UTC
