### ISSUE TITLE
TT3: Inconsistent WooCommerce button styling

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#7388] opened 2022-10-13 09:16 UTC
## Describe the bug

The WooCommerce buttons are styled differently to the current themes buttons on TT3, **this does not happen on TT2**.

## To reproduce

1. Activated TT3
2. Go To Appearance > Site Editor > Product Catalog and add a button to this template (or filter blocks) > Save.
3. Go to the Shop page
4. View the difference in button styles.
5. Go to the product page and now add to basket a related product at the bottom of the page
6. View another set of different buttons in the Mini Cart.

## Expected behavior

Button styling should be consistent.

## Screenshots

**Shop page**
![Screenshot 2022-10-13 at 10 09 24](https://user-images.githubusercontent.com/8639742/195555930-631376a4-1913-4660-a6cc-c3457e83604e.png)

**Mini Cart**
![Screenshot 2022-10-13 at 10 13 15](https://user-images.githubusercontent.com/8639742/195556008-1ed78626-b2cd-411c-be33-8ade2b9081ca.png)

**Comment by tjcafferkey** [comment] 2022-10-14 12:54
I suspect this will probably be fixed as part of [this epic](https://github.com/woocommerce/woocommerce/issues/34848). Currently WC is missing [theme support](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/includes/theme-support) to load in the relevant [theme assets](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/client/legacy/css) for TT3 which haven't been created yet.

**Comment by gigitux** [comment] 2022-10-27 13:18
I'm testing WC Blocks with this[ WC's PR](https://github.com/woocommerce/woocommerce/pull/35306), and everything look okay:

![image](https://user-images.githubusercontent.com/4463174/198294451-300eb1b5-4b02-4431-9e62-54ab9c2269db.png)
![image](https://user-images.githubusercontent.com/4463174/198294555-dffa75bc-d02f-49fa-ad12-87067ff8f77e.png)
![image](https://user-images.githubusercontent.com/4463174/198294612-a436cc2f-eac9-4322-bb0d-ef5e4771a890.png)
![image](https://user-images.githubusercontent.com/4463174/198294657-05e091de-a3f3-4b6f-9101-bc3af919947c.png)
![image](https://user-images.githubusercontent.com/4463174/198294709-1fe927c3-df52-4b31-abcc-ef4f1b955bc6.png)
![image](https://user-images.githubusercontent.com/4463174/198294838-8b2f9ec5-bdf0-4989-984d-9a1d27c04502.png)



Pretty sure that we consider #7466 as a duplicate of this issue. @Aljullu, what do you think? For me, we can close both issues 👍

**Comment by Aljullu** [comment] 2022-10-27 14:57
Thanks for investigating it! I can still reproduce the issue I reported in #7466. But, it looks like it's only reproducible if the link has never been visited. An easy way to test it is to visit that page from a private browsing window.

![imatge](https://user-images.githubusercontent.com/3616980/198323654-14d20fd4-3393-4899-a392-185a767a3fb6.png)

For reference, the buttons on top are added by an HTML block with these contents:


```HTML
<a href="/" class="wp-block-button__link">Visited link</a>
<a href="/a-route-i-have-never-visited" class="wp-block-button__link">Not visited link</a>
```

Adding `.wp-element-button` to those links, fixes the issue. So I think we should fix it in the same way in the other buttons. Thoughts @gigitux?

**Comment by gigitux** [comment] 2022-10-28 08:24
@Aljullu Oh, I didn't notice! I tested your suggestion, and it fixes the issue. In the same PR, should we address the fix for the Mini Cart Drawer button?

![image](https://user-images.githubusercontent.com/4463174/198540795-024a317c-9b64-462f-8121-ee0dfea0e025.png)

**Comment by Aljullu** [comment] 2022-10-28 08:58
> In the same PR, should we address the fix for the Mini Cart Drawer button?

I don't have a strong opinion. Personally, I don't think it's a blocker, but if you think that's something easy to fix, it would be good to include it. One thing, however, is that we should keep it consistent with Cart & Checkout buttons as well.

**Comment by gigitux** [comment] 2022-10-28 10:03
> I don't have a strong opinion. Personally, I don't think it's a blocker, but if you think that's something easy to fix, it would be good to include it. One thing, however, is that we should keep it consistent with Cart & Checkout buttons as well.

The fix is not immediate, so it is better if we postpone this. Is there a reason why the Cart & Checkout buttons don't inherit the style from the theme?

**Comment by Aljullu** [comment] 2022-10-28 10:41
> The fix is not immediate, so it is better if we postpone this.

Sounds good to me. :+1: It might be worth creating an issue so we don't forget about this.

> Is there a reason why the Cart & Checkout buttons don't inherit the style from the theme?

It has some historical reasons. When we created the Cart & Checkout blocks we wanted to have more opinionated styles so we could apply good practices to increase conversion. However, with time, I think we should revisit that decision and just inherit as much as possible the styles from the theme; at least, text and background colors. Otherwise, those buttons look off compared to the other buttons.

**Comment by gigitux** [comment] 2022-10-28 14:27
> Sounds good to me. 👍 It might be worth creating an issue so we don't forget about this.
> 
> >

I created the issue https://github.com/woocommerce/woocommerce-blocks/issues/7522

**Closed as completed** 2022-10-28 17:07 UTC
Labels: type: bug, block: mini-cart, focus: template
