### ISSUE TITLE
Attribute filter `lexical declaration` error

### ISSUE THREAD

**Issue by grogou** [woocommerce/woocommerce-gutenberg-products-block#5245] opened 2021-11-25 12:42 UTC
## Describe the bug
Attribute filter get crashed and console output is `ReferenceError: can't access lexical declaration 'onSubmit' before initialization`
Not sure, but maybe we need to define `onSubmit` before call.

## To reproduce
Just add attribute filter to empty page and check some attribute. After that it get crashed.

### WordPress
* Core version: latest
* Gutenberg version: latest
* WooCommerce version: latest
* WooCommerce Blocks version: latest

### Desktop
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone
* OS: Windows 11
* Browser: Firefox
* Version: latest 

## Additional context
Theme: TT1 Blocks

**Comment by senadir** [comment] 2021-11-25 19:34
True, I can even see the inline error in vscode
```js
Block-scoped variable 'onSubmit' used before its declaration.
```

And I can confirm the bug.

An easy fix would be to move `onSubmit` just before `useEffect`. A better solution would be to not call `onSubmit` on render (but this might be harder).

**Comment by senadir** [comment] 2021-11-25 19:57
I confirmed this bug on trunk, couldn't reproduce it on 6.4.0 or 6.3.3

**Comment by grogou** [comment] 2021-11-26 06:42
@senadir  if you want, I can fix this and open PR.

**Comment by grogou** [comment] 2021-11-26 06:52
But I think the problem is something else, because as you checked the older versions works properly.

**Comment by grogou** [comment] 2021-11-26 09:04
> True, I can even see the inline error in vscode
> 
> ```js
> Block-scoped variable 'onSubmit' used before its declaration.
> ```
> 
> And I can confirm the bug.
> 
> An easy fix would be to move `onSubmit` just before `useEffect`. A better solution would be to not call `onSubmit` on render (but this might be harder).

Is there a better solution to remove onSubmit from useEffect dependencies? In my opinion it can be better, the only thing I don't understand why it was in dependencies list.

**Comment by senadir** [comment] 2021-11-26 09:33
> But I think the problem is something else, because as you checked the older versions works properly.

Yeah I'm assuming something else changed and just now we're seeing the `useEffect` trigger early, moving the function up would sure fix this up but preferably, we want to know what changed.

> Is there a better solution to remove onSubmit from useEffect dependencies? In my opinion it can be better, the only thing I don't understand why it was in dependencies list.

`onSubmit` is used on the `useEffect` so we can't just remove it from the array, the issue is why that logic in `useEffect` is reached on first render.

**Comment by Aljullu** [comment] 2021-12-02 14:12
After my testing, I think this was introduced in #5212, when we switched the Babel config. I think for now we should go with the easy solution (moving `onSubmit` above its usage) and work on any refactors in another issue. Thoughts?

**Comment by grogou** [comment] 2021-12-02 14:34
@Aljullu I think it is true for now to fix this, but if we think long term, we need to solve this without moving functions up or down to fix problem. And we need to understand how cases like this works on the Gutenberg ( I am about `@wordpress/babel-preset-default` ).

**Comment by senadir** [comment] 2021-12-02 14:46
Generally speaking you shouldn't call a function before defining it, so moving it up is a no brainer really, we can also create a follow up issue here to track the actual issue, which is calling onSubmit too early.

@grogou what do you mean with `And we need to understand how cases like this works on the Gutenberg`? Do you mean why would switching babel config surface this issue now?

**Comment by grogou** [comment] 2021-12-02 14:56
> Generally speaking you shouldn't call a function before defining it, so moving it up is a no brainer really, we can also create a follow up issue here to track the actual issue, which is calling onSubmit too early.

I am not guru, but if I am not right sorry. The function declaration causes its identifier to be bound before anything in its code is executed. So this case is strange for me.

> @grogou what do you mean with `And we need to understand how cases like this works on the Gutenberg`? Do you mean why would switching babel config surface this issue now?

Yes I am about that, Maybe they had same problem, idk.

**Comment by grogou** [comment] 2021-12-02 14:59
@senadir I am sorry it is variable ( const ) for JS not function.

**Comment by senadir** [comment] 2021-12-02 15:09
> I am not guru, but if I am not right sorry. The function declaration causes its identifier to be bound before anything in its code is executed. So this case is strange for me.

I'm struggling to follow here, but are you saying it's weird that this issue surfaced just now? In JS, there's a concept called [Hoising](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting), it would move declarations before calls in a scope (in our case, the scope is the component). Hoising is disabled in strict mode, I'm guessing updating caused strict mode to kick in on those components and this issue to surface.

**Comment by grogou** [comment] 2021-12-02 17:40
> it's weird that this issue surfaced just now?

Yes I am about that.

> I'm guessing updating caused strict mode to kick in on those components and this issue to surface.

It's sounds good. If the new update enabled strict mode, this is wrong. Sorry.

> The function declaration causes its identifier to be bound before anything in its code is executed.

**Closed as completed** 2021-12-06 10:03 UTC
Labels: type: bug, status: blocker, type: good first issue, block: filter by attribute, priority: high
