### ISSUE TITLE
Would be nice if we could remove items from the checkout order summary without having to go back to cart.

### ISSUE THREAD

**Issue by letmework** [woocommerce/woocommerce-gutenberg-products-block#2582] opened 2020-05-28 10:20 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nerrad** [comment] 2020-06-02 12:53
This is a duplicate of #2583 so I'm going to close in favor of the other issue.

**Closed by nerrad** 2020-06-02 12:53 UTC
