### ISSUE TITLE
A few issues i have ran into but overall happy with the blocks! 

### ISSUE THREAD

**Issue by K13NN13** [woocommerce/woocommerce-gutenberg-products-block#7784] opened 2022-11-30 05:34 UTC
Hey I am using the Woocommerce blocks for the cart and checkout which I love the style of, there are just three issues I have noticed and was wondering if there is a solution to them.

1.  The "County (optional) field will highlight in red and state "Please fill in this field" if the checkout button is pressed with no information entered in that field, if I try to check out again without the information entered it is fine and it goes through as it should as it is an optional field.

2. On the first load if there is nothing in the basket the basket will have the skeleton loader constantly loading and it won’t show the " basket is empty" screen, it will only show this screen when an item is added to the basket and removed. After adding and removing an item if I then go into the basket the "basket is empty" screen is shown as expected. There is an error in the console stating the following  
`
Uncaught SyntaxError: Invalid regular expression: /^?\d+\.[\t]/: Nothing to repeat`

3.  The font sizing is very small, I was wondering if there is a way to set the font for it rather than having to use CSS for this? It is taking my themes (Astra) sizing for headers, if I use the default WordPress or elements themes the font sizing is fine, but having controls for the font sizing within the block editor for this block would be great as I have seen it posted in the reviews before.

What do you like about the Cart & Checkout blocks?

I waited to install this blocks plugin, I tested it when it first was released and it wasn't supporting the Woocommerce product-add-ons so I couldn't use it for my site, since then it has matured a lot and is a very viable block plugin for the cart and checkout flow. Just a few minor bugs to iron out, but overall pleased!

**Comment by tarhi-saad** [comment] 2022-12-02 10:56
Hello, @kromeninja! 👋 Thank you for using WooCommerce Blocks! We are delighted to hear you are satisfied with our plugin! 🙌 Also, thank you for letting us know and sharing any issues you are encountering with our plugin.

### 1. The "County (optional)" field bug

I couldn't reproduce this bug! I followed the testing instruction on a fresh WordPress site using the following:

- **WordPress:** Version 6.1.1
- **WooCommerce:** Version 7.1.0
- **WooCommerce Blocks:** Version 9.0.0
- **Theme:** Twenty Twenty-Three

Could you please open a new bug report using [this link](https://github.com/woocommerce/woocommerce-blocks/issues/new?assignees=&labels=type%3A+bug&template=---bug-report.md), and share with us all the required information (e.g., installed plugins, used theme, etc.)? Also, can you test again using one of our default themes (e.g., Twenty Twenty-Three) and enabling only two plugins:

- **WooCommerce:** Version 7.1.0
- **WooCommerce Blocks:** Version 9.0.0

### 2. Cart first load bug

I couldn't reproduce this bug too! On the first load of the Cart Block page, I can see the message "Your cart is currently empty!" as expected:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/14235870/205272291-d1ab8dbb-11d6-49ad-9a25-ecbdac3e568a.png">

 @kromeninja, could you do another test using the `Twenty Twenty-Three` theme? If the still persists, please open a new issue using our [bug report link](https://github.com/woocommerce/woocommerce-blocks/issues/new?assignees=&labels=type%3A+bug&template=---bug-report.md), and share with us all the required information in there.

### 3. Font size control

> The font sizing is very small, I was wondering if there is a way to set the font for it rather than having to use CSS for this?

Could you share with us which Block you are having issues with? On some Blocks we have the font control feature (e.g. `Product Search Block`), you can find it on the editor page: `Settings -> Block -> Typography`

![image](https://user-images.githubusercontent.com/14235870/205276732-b1730b87-9167-47d9-8e2b-80803b56475a.png)

You can also share with us a screenshot of the block with the small font size!

**Comment by K13NN13** [comment] 2022-12-03 16:16
Hey @tarhi-saad thank you for getting back! Much appreciated :)

So since posting this there are a few updates will i'll provide below:


**1. The "County (optional)" field bug:**

So I think this is related to the litespeed cache as i disabled the plugin on the staging wesbite and it doesn't ask me to enter the field when i try to checkout when its empty, I need to test this on my live site, but i currently have the checkout disabled as I will talk about in #4


**2. Cart first load bug**

This was related to the cache on the cart page, I excluded the cache within litespeed for the cart page and the page now loads with no issue when the basket is empty

**3. Font size control**

This has been mostly solved with CSS, Astra for sure was taking over the styling for the font, but the latest Astra updates also started using a lower font weight which i updated to when i was installing the cart and checkout block, so when i rolled the update for Astra back the font was a higher font weight + size. With that I have updated Astra again and made changes to the font to make it similar to the default on the woocommerce storefront theme, no problem with that now 👌

**4. Affiliate amount issue with the block checkout**

I use an affiliate plugin on my store which works fine with the default woocommerce checkout, but the checkout block doesn't work with it sadly, the coupon will discount the price of the item/s but the affiliate kickback isnt added to the order when the customer checksout sadly. Going back to the default woocommerce checkout the affiliate amount is added to the order correctly. I can still use the woocommerce block cart with no issue to the affliate amount.

I have messaged the plugin developers incase this is their end, but I thought i would mention it here as its the only reason i can't use the new checkout sadly. The plugin name is the following: 
[Ultimate Affiliate Pro](https://codecanyon.net/item/ultimate-affiliate-pro-wordpress-plugin/16527729)


**5. Coupon automatically being applied**

I was wondering if it is possibl to make a previously entered coupon not apply the next time the customer goes to the basket? With the previous version the coupon is only added for that cart/ checkout session once the code was used for the order the same coupon wouldn't get added to the next order automatically on the basket, so the customer would have to enter the coupon they wish to use eachtime

Thanks for all the help 👌

**Comment by alexflorisca** [comment] 2022-12-08 16:21
Hi @kromeninja,

Just picking this up from Saad. It sounds like points 1-3 are solved so that's great news!

Regarding point 4 - the affiliate kickback - I'm not entirely sure how this works but it sounds like something on the side of the plugin you are using for this. They may need to make some changes to support the Checkout Block, depending on their implementation. You can point them to [our docs](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility)

> I was wondering if it is possibl to make a previously entered coupon not apply the next time the customer goes to the basket? With the previous version the coupon is only added for that cart/ checkout session once the code was used for the order the same coupon wouldn't get added to the next order automatically on the basket, so the customer would have to enter the coupon they wish to use eachtime

I'm not sure I understand this. 

> I was wondering if it is possibl to make a previously entered coupon not apply the next time the customer goes to the basket

This is how it currently works. You have to enter the coupon manually each time.

> With the previous version the coupon is only added for that cart/ checkout session once the code was used for the order

What do you mean by "previous version" here? 

> so the customer would have to enter the coupon they wish to use eachtime

Do you wish to have a coupon applied automatically?

If you could expand on this a little bit more, I'll see if I can help

**Comment by ralucaStan** [comment] 2022-12-30 13:52
> I was wondering if it is possible to make a previously entered coupon not apply the next time the customer goes to the basket

@kromeninja Supposing you want to limit a code to a single use per user you can use this setting from WC visible when editing a coupon code.
<img width="1056" alt="Screenshot 2022-12-30 at 13 49 54" src="https://user-images.githubusercontent.com/1628454/210077165-62ac09c1-c9cc-494e-8206-9b6dc7baf194.png">

I'm going to close this issue, as there was no interaction for more than 3 weeks.

**Closed as completed by ralucaStan** 2022-12-30 13:52 UTC
