### ISSUE TITLE
Checkout & Cart Block: Add the loading animation

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4648] opened 2021-08-29 17:16 UTC
Hi,
Users see the white space first and then the elements appear. It would be very useful to have some loading animation cart & checkout page.

**Comment by frontdevde** [comment] 2021-09-01 10:07
@msroky Could you elaborate on what you have in mind?

When the Cart & Checkout blocks load on the Frontend of a site (i.e. the part of the store that customers visit), they should already see a loading animation while the blocks are loading (see screenshot below). 

<img width="836" alt="Screenshot 2021-09-01 at 11 58 59" src="https://user-images.githubusercontent.com/1562646/131652235-3745db8f-acb0-4f15-8143-6006ec73a411.png">

**Comment by senadir** [comment] 2021-09-13 14:45
@msroky  I’m going to close this because there still isn’t anything actionable for us on this issue, this feature is already available in Cart and Checkout blocks, if you think it’s broken, we try to identify why it's not working. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce we can re-open as necessary.

**Closed as completed by senadir** 2021-09-13 14:45 UTC
Labels: type: enhancement
