### ISSUE TITLE
Inline price slider stopped working 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7196] opened 2022-09-21 16:52 UTC
I am not sure if it's because of the version I have, but the `inline` option isn't working for me now. 

<img width="835" alt="Screenshot 2022-09-21 at 17 46 13" src="https://user-images.githubusercontent.com/9888201/191564947-b2d8bdf9-0b64-4dfd-8804-f08701bd506d.png">

**Comment by danielwrobert** [comment] 2022-09-21 20:40
@vivialice I'm not able to replicate this - I'm seeing the expected behavior:

https://user-images.githubusercontent.com/481776/191609774-4a1b9f33-5a14-4653-bb1d-25a2b1d1a05a.mp4

What version are you running? It looks like this update came in 8.4.0.

**Comment by vivialice** [comment] 2022-09-22 08:53
> What version are you running? It looks like this update came in 8.4.0.

That is the version I have as well 🤔

**Comment by danielwrobert** [comment] 2022-09-23 17:17
Closing this out as this is now working for you, per our convo. 🎉

**Closed as completed by danielwrobert** 2022-09-23 17:17 UTC
Labels: block: filter by price
