### ISSUE TITLE
woocommerce_loop_add_to_cart_args filter for consistent behavior

### ISSUE THREAD

**Issue by PoeHaH** [woocommerce/woocommerce-gutenberg-products-block#7179] opened 2022-09-19 12:19 UTC
## Describe the bug

All product blocks (such as Newest Products, On-Sale Products, Top-Rated Products, Hand-Picked Products) do not contain filters to be consistent with the WooCommerce shop page.

More specifically, I mean the `woocommerce_loop_add_to_cart_args` filter. It allows developers to edit data and attributes of each "add to cart" button in the shop loop.

## Expected behavior

I would expect the product blocks have the same (or a similar) filter as they serve more or less the same function as the Shop page (= to list products). Many developers wanting to change the "add to cart" button on the Shop page will want the exact same edits on those blocks.

Could the `woocommerce_loop_add_to_cart_args` filter be [added to the `get_add_to_cart` function](https://github.com/woocommerce/woocommerce-blocks/blob/9f9acf943a8fad682428fd6ab2201910379c0c81/src/BlockTypes/AbstractProductGrid.php#L643
)?

**Comment by danielwrobert** [comment] 2022-09-22 16:34
Hi @PoeHaH! 👋 

Thank you for reporting this - much appreciated!

This appears to be a duplicate of woocommerce/woocommerce#42671, so I'm going to go ahead and close this one out. Feel free to follow along over there! 🙂

**Closed as completed by danielwrobert** 2022-09-22 16:34 UTC
Labels: type: enhancement, category: extensibility, focus: blocks, block: hand-picked products, block: top rated products, block-type: product, block: on sale products, block: newest products
