### ISSUE TITLE
Automatically filling out the checkout form does not work

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4572] opened 2021-08-13 02:22 UTC
I noticed an unusual problem when a customer comes to the checkout page and automatically fills out the form via smartphone.

I have hotjar and mouseflow installed on my shop and I monitor customer behavior to improve the web shop and customer experience

Although the field is filled in, when the customer clicks on the order button it shows an error "Please fill in this field".

Take a look at what mouseflow.com has recorded. He saw it on the link below.

https://imgur.com/4lwr7Xc

The same thing was recorded by the hotjar.com

I lose customers every day because of this. Please fix this as soon as possible.

The customer in the video used:
Browser: Facebook 323.0.0
Phone (360 x 632)
Android 11

**Comment by Aljullu** [comment] 2021-08-13 08:35
Thanks for opening this issue @msroky! We are currently investigating this, you can see the progress in this issue: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4495 and this PR: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4561.

For now, I will close this issue as a duplicate of #4495. But if you think it's a mistake let me know! :slightly_smiling_face:

**Closed as completed by Aljullu** 2021-08-13 08:35 UTC
Labels: type: bug, type: duplicate
