### ISSUE TITLE
Gutenberg Category Grid Block

### ISSUE THREAD

**Issue by anteksiler** [woocommerce/woocommerce-gutenberg-products-block#1717] opened 2020-02-04 08:48 UTC
Currently, the only way to display categories using Gutenberg is to use the Product Category List element, which basically displays a menu.

It would greatly improve the homepage building experience with Gutenberg if we were able to display the Product Categories with the same style used on the shop listing like:

![image](https://user-images.githubusercontent.com/1000992/73728339-3c1b6d00-4744-11ea-9588-af05bccf5a01.png)

**Comment by nerrad** [comment] 2020-02-10 20:40
Hi there @anteksiler  👋

Thanks for taking the time to share this idea, we really appreciate your help.  While this is clearly a great idea, we won't be able to tackle it in the upcoming weeks as we're currently focused on finishing all the work that was identified as a priority for the next major release of this plugin.  I'm going to add this to our backlog where it will be considered for future releases.

cc @garymurray for reference.

**Comment by anteksiler** [comment] 2020-02-10 21:03
Hi @nerrad, thanks for the input. I believe this will be a valuable addition to the Gutenberg block lineup as displaying categories on your homepage for any E-commerce website is essential.

Thanks again for consideration. Best regards,

**Comment by nerrad** [comment] 2020-02-10 21:15
> I believe this will be a valuable addition to the Gutenberg block lineup as displaying categories on your homepage for any E-commerce website is essential.

Definitely agree, it's just a matter of when we do it, not if.

**Comment by mikejolley** [comment] 2021-06-17 10:36
FYI this is a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2380 so can be tracked there instead.

**Closed by mikejolley** 2021-06-17 10:36 UTC
Labels: category: blocks, type: enhancement
