### ISSUE TITLE
Section ordering

### ISSUE THREAD

**Issue by damen02** [woocommerce/woocommerce-gutenberg-products-block#6301] opened 2022-04-22 17:39 UTC
## What do you like about the Cart & Checkout blocks?
It is very useful to have a block based checkout!

## What do you think is missing from the Cart & Checkout blocks?
Would be nice to have the ability to re order or even hide its sections: Contact info, Shipping address, ...
A local store doesn't need Country or Region.

**Comment by alexflorisca** [comment] 2022-04-27 10:36
Hey [damen02](https://github.com/damen02) thanks a lot for taking the time to raise an issue here and let us know about your requirement.

Firstly, you can order the blocks inside the order summary by selecting an inner block and clicking on the up and down arrows

https://user-images.githubusercontent.com/3966773/165497085-b7610c12-bcef-4e38-910f-f4f1d4cbf1b2.mov

For now, you cannot move the Checkout sections on the left hand side (Contact Information, Shipping details, etc) as it follows a logical flow. For example, shipping options can be based on the country and region you select at Checkout, so it makes sense for the Shipping Address to come before Shipping. There was also a lot of research done into the most optimal checkout experience that leads to the most conversions for users and we are continually adjusting this.

To your example of hiding the country field, this is needed for calculating shipping and tax, so it needs to be present. However, you can default it to your current country, and the user does not have to take any extra steps to change it.

We're always open to feedback and ideas and it would be good to understand a bit more about your setup and which sections you would like to hide or move and why. 

Look forward to hearing back from you.

**Comment by tarunvijwani** [comment] 2022-05-20 09:44
@damen02 I’m going to close this because there still isn’t anything actionable for us on this issue. If you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2022-05-20 09:44 UTC
