### ISSUE TITLE
`canMakePayment` not running on initial pageload

### ISSUE THREAD

**Issue by pixlmint** [woocommerce/woocommerce-gutenberg-products-block#7158] opened 2022-09-15 08:06 UTC
## Describe the bug

When a signed in user goes to checkout the `canMakePayment` check doesn't run, therefore my custom payment method isn't doing it's checks and doesn't get displayed. The user will first have to change something in the address form for the check to run.

## To reproduce

1. Log in as Customer on a shop that has a custom payment method
2. Add a Product to Cart
3. Click "View Cart"
4. Click "Continue to Checkout"

## Expected behavior

The `canMakePayment` callback should run

### WordPress:

-   Core version: 6.0.2
-   WooCommerce version: 6.8.2
-   WooCommerce Blocks version: 8.4.0
-   Site language: German
-   WooCommerce PayPal Payments: 1.9.3

### Desktop:

-   OS: Ubuntu 22.04
-   Browser firefox
-   Version 104.0.2

## Additional context

I created my Custom Payment Method base on [this](https://github.com/woocommerce/woocommerce-blocks/issues/7041) issue

**Comment by opr** [comment] 2022-09-15 16:45
Hi @ChristianGroeber thank you for reporting this - it may be fixed by #6612 where we refactored the way payment methods are handled internally.

Do you have a staging site where you can check out a version of the plugin which includes the refactor? Please note it has not been fully tested and **should not** be used in production, it's just a zip generated based on the #6612 PR without any further QA.

[woocommerce-gutenberg-products-block.zip](https://github.com/woocommerce/woocommerce-blocks/files/9576962/woocommerce-gutenberg-products-block.zip)

Please let us know how it goes!

**Comment by pixlmint** [comment] 2022-09-15 17:02
Hi @opr yeah, I'll give it a shot, thanks for the feedback!

**Comment by pixlmint** [comment] 2022-09-19 07:20
@opr Okay, I can confirm, the call now gets triggered, so it looks like #6612 fixes this.

**Comment by opr** [comment] 2022-09-26 10:08
Thank you @ChristianGroeber please follow #6612 for updates, and also follow https://developer.woocommerce.com/ where we will announce the release which contains those changes.

**Comment by pixlmint** [comment] 2022-10-05 06:46
@opr I hate to reopen this, but it looks like there's still some issues with this. When a user is logged in and goes to checkout from any other page (hover over the cart and press checkout), canMakePayment gets executed. However, if a user is on the checkout page and hits refresh, canMakePayment does NOT get called.

Should I create a new issue for this? Or can you reopen this one?

**Comment by opr** [comment] 2022-10-06 14:47
Hey @ChristianGroeber I could not reproduce this - I used the [WooCommerce Stripe plugin](https://wordpress.org/plugins/woocommerce-gateway-stripe/) and logged when the `canMakePayment` code was executed, it was executed both when reloading the page and when access the page via a link.

Could you share more info about your custom payment gateway? Is it open source and can we look at it?

**Comment by pixlmint** [comment] 2022-10-10 17:16
Currently it is not open source. 

Might it have something to do with the order in which we load our scripts? 

Here our script gets registered: `wp_enqueue_script($jsFile, RISKCUBE__PLUGIN_URL . 'assets/riskcube.js', [], FileHelper::get_file_version($jsFile), true);`, and our payment option gets registered on the `$(document).ready()` function (since we can't be sure that the `wc` object exists before that)

**Comment by opr** [comment] 2022-10-11 09:20
@ChristianGroeber thanks for the extra information - when registering your script, could you add `wc-blocks-registry` as a dependency?

`wp_enqueue_script($jsFile, RISKCUBE__PLUGIN_URL . 'assets/riskcube.js', [ 'wc-blocks-registry' ], FileHelper::get_file_version($jsFile), true);`

Also we have https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin which is a webpack plugin that will automatically detect dependencies and output them to an `.asset.php` file so you can know which dependencies to register your script with. It's out of scope to discuss further on this issue but more info can be found on that package.

**Comment by nielslange** [comment] 2022-10-25 04:26
Hello @ChristianGroeber 👋 As we haven't heard back from you for a while, I'm closing this issue now. That said, please don't hesitate to create a new issue if you have further questions or suggestions.

**Closed as completed by nielslange** 2022-10-25 04:26 UTC
Labels: type: bug, focus: blocks, block: checkout
