### ISSUE TITLE
Lack of functionality

### ISSUE THREAD

**Issue by qvacode** [woocommerce/woocommerce-gutenberg-products-block#3998] opened 2021-03-24 19:37 UTC
1- I have assigned a method of payment with cryptocurrency and when I use the blocks it does not appear.

2- I have eliminated the address fields. But when the plugin reappear.

**Comment by mikejolley** [comment] 2021-03-25 11:52
Hi @webdavs 

Regarding payment methods (1), these blocks are still in early access (via the feature plugin) and it's expected that some existing payment methods will not work with the blocks. Currently it's up to payment method extension developers to add support for the new checkout flow offered via the cart and checkout blocks. We have [some documentation on that here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/extensibility/payment-method-integration.md) and you can also see this post: https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/

Regarding point 2, it's not clear how you changed fields. The checkout block has some toggle options for some fields (company, address 2, phone), but other fields are only hidden if the country locale does not require them. Extensions like checkout field editor are not yet compatible and are being looked at in the coming months.

I am closing this issue because it lacks clear description. If you find a specific bug with any advertised functionality, please include steps to reproduce the issue, and report one thing per github issue. [The issue template](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/new?assignees=&labels=type%3A+bug&template=---bug-report.md) needs filling out in full for us to better respond.

Thanks

**Closed as completed by mikejolley** 2021-03-25 11:52 UTC
Labels: block: checkout
