### ISSUE TITLE
Checkout Block fails to update Gateways when their availability changes

### ISSUE THREAD

**Issue by dpanta94** [woocommerce/woocommerce-gutenberg-products-block#7200] opened 2022-09-21 21:33 UTC
## Describe the bug

Checkout Block doesn't update available gateways (express and normal) based on changes in the checkout form.

## To reproduce
Any action that would cause a gateway to become unavailable while filling the checkout form should work. For example, changing currency (without refresh) or having specific gateways configured to be available based customer's shipping/billing country.

i will provide a step by step for the case you have configured your gateways to be available only for specific countries/regions by using the plugin [Country Based Payments for WooCommerce](https://wordpress.org/plugins/woocommerce-country-based-payments/)

1. Install the plugin Country Based Payments for WooCommerce
2. Have at least 2 gateways available in order to easier see the results.
3. Go to /wp-admin/admin.php?page=wc-settings&tab=wccbp
4. Configure one of your active gateways to be available only when a selected country is selected (e.g. United Kingdom)
5. Go to the frontend of your store and add a simple product to your cart and go to checkout.
6. While using the checkout block of woocommerce blocks, switch your shipping country from United Kingdom to another one and vice versa.
7. You will notice that the availables gateways do not get updated.
8. If you click on place order while missing required information (so that the validations fails you to proceed with your order ) and you refresh, you will see that the gateways reflect their actual availability based on your selected country.

Note: While using the shortocode version of the checkout this is working as expected.

## Expected behavior

Payment Gateways should reflect their availability while changing values in the checkout form that could affect their availability

### WordPress (please complete the following information):

-   Core version: 6.0.2
-   WooCommerce version: 6.9.1
-   WooCommerce Blocks version: 8.5.0
-   Site language: English (United States)
-   Any other plugins installed:

Country Based Payments for WooCommerce v1.4.2
WooCommerce Pre-Orders v1.55.30
WooCommerce Stripe Gateway v6.7.0
WooCommerce Subscriptions v3.1.6

### Desktop (please complete the following information):

-   OS: Windows
-   Browser chrome
-   Version 105.0.5195.127

**Comment by senadir** [comment] 2022-09-22 12:37
Hey @dpanta94 , thank you for opening this issue.

Payment availability has switched to be controlled on the frontend for now, [this document explains this flow.](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/filtering-payment-methods.md)

A plugin like [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/) has went through that integration process.

Please let me know if the document isn't obvious or you think this approach won't help.

Generally speaking, you have 3 ways to filter out payment methods:
- From the actual payment method code, it can access cart data in its `canMakePayment` function and return false.
- A plugin can use `registerPaymentMethodExtensionCallbacks` to extend one or several payment methods `canMakePayment` function.
- A plugin can define a payment requirement on the server, and only compliment payment method will be visible, this means you can filter out if a payment method doesn't support subscriptions or multiple subscriptions or deposits. 

Such filter happen on the frontend because it is dynamic and depends on user input, so we need the payment method to be initiated always. Server side filtering is only done when you know for certain that a Checkout won't use that payment method (invalid keys, disabled...), this would omit the payment method from loading and its assets from loading as well.

**Comment by dpanta94** [comment] 2022-09-23 20:01
Hey @senadir, thank you very much for your detailed response. If i come up with a follow up question, i'll reach out again!

**Comment by tarunvijwani** [comment] 2022-09-30 11:37
@dpanta94 I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue, and if we’re able to reproduce them, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2022-09-30 11:37 UTC
Labels: block: checkout
