### ISSUE TITLE
[Enhancement]: Support column count change on product page gallery

### ISSUE THREAD

**Issue by ncsramona** [woocommerce/woocommerce-gutenberg-products-block#11118] opened 2023-08-28 10:18 UTC
### Describe the solution you'd like

WooCommerce has a filter to adjust columns on the product page gallery (`woocommerce_product_thumbnails_columns`) located at [product-image.php](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/product-image.php). It would be amazing to support this in the Twenty Twentythree theme, since we already have some [compatibility codes.](https://github.com/woocommerce/woocommerce/blob/8.0.2/plugins/woocommerce/client/legacy/css/twenty-twenty-three.scss)

Example:
When using the following code:
```
add_filter( 'woocommerce_product_thumbnails_columns', 'ncsr_product_thumb_column', 20, 2 );
function ncsr_product_thumb_column() {
	return 3; 
}
```

The product page's gallery should display 3 columns instead of the default 4. 

### Additional context

By default, the Product gallery looks like this:
<img width="400" alt="image" src="https://github.com/woocommerce/woocommerce/assets/133644769/1249cc86-697b-40cb-bb96-bcd4388bc305">

What I'd like is if the code above is used, it would look like this:
<img width="400" alt="image" src="https://github.com/woocommerce/woocommerce/assets/133644769/449ced42-fd9c-4de7-8f13-a85a8b7059e8">

**Comment by nerrad** [comment] 2023-10-03 17:09
Thanks for the report - I can reproduce. Although the block templates provided by WooCommerce should be providing backwards compatibility for this hook, it looks like it isn't working as expected. I'm transferring this to the WooCommerce Blocks repository so a direction can be resolved there.

**Comment by gigitux** [comment] 2023-10-04 12:37
Thanks for the report, @ncsramona!

I'm able to reproduce the issue, but I don't think that it is a filter issue. The filter updates only [the class of the div and the data attribute](https://github.com/woocommerce/woocommerce/blob/0b4c096733c15d379442d4f78cd8b817be231a9a/plugins/woocommerce/templates/single-product/product-image.php/#L34-L35). 

I used your snippet, and the HTML is updated correctly:

![image](https://github.com/woocommerce/woocommerce-blocks/assets/4463174/a22ec1d6-f08c-4d70-8ab2-170f81a77b1e)

I think that the issue is related to the [CSS that should target the div](https://github.com/woocommerce/woocommerce/blob/0b4c096733c15d379442d4f78cd8b817be231a9a/plugins/woocommerce/client/legacy/css/woocommerce.scss/#L272-L291).

I tried with Storefront and TT1 (both classic themes) and the CSS doesn't target the div.

**Comment by ncsramona** [comment] 2023-10-04 13:06
Hm you're right, it's probably not a filter issue. Thanks for looking into it! :)

**Comment by nerrad** [comment] 2023-10-04 13:28
@gigitux it's likely that this will become irrelevant as a part of product gallery refinements (where min/max columns for thumbnails could be a control). Think we should close this issue (the assumption being that any consumer using the filter would be expected to also provide the expected CSS)?

**Comment by gigitux** [comment] 2023-10-04 13:45
@nerrad Yes!

The Product Gallery block will have control to specify the columns of the thumbnails. @ncsramona, you can follow the progress of the block by looking woocommerce/woocommerce#42335.

I’m going to close this issue. If you have additional feedback, you can still add them to this issue and re-open it if necessary.

**Closed as completed by gigitux** 2023-10-04 13:45 UTC
Labels: type: enhancement
