### ISSUE TITLE
Featured Product block API error (Woo 4.2 RC + Blocks 2.6 RC testing)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2510] opened 2020-05-20 00:54 UTC
**Describe the bug**
The `Featured Product` block has an API error when added to a page (breaks "select product" flow).

**To Reproduce**
1. Add a new page.
2. Add `Featured Product` block.
4. Product select UI shows briefly then API error handler shows:

<img width="1221" alt="Screen Shot 2020-05-20 at 12 47 51 PM" src="https://user-images.githubusercontent.com/4167300/82392802-deafef80-9a98-11ea-8b37-54d1c6cf757b.png">

I saw this error on https://ephemeral-haszari-20200519.atomicsites.blog/ when testing Storefront 2.5.7 RC with Woo 4.2.0 and Woo Blocks 2.6.0 RCs installed also. May be an interaction with Woo 4.2.

**Expected behavior**
No error :)

**WordPress (please complete the following information):**

* Core version: 5.4.1 
* Gutenberg version (if installed): none
* WooCommerce version: 4.2.0 RC 1
* WooCommerce Blocks version: 2.6.0 RC 1
* Site language:
* Any other plugins installed: Akismet, AMP, Jetpack, WooCommerce Services
* Theme: Storefront 2.5.7 RC 1

**Comment by haszari** [comment] 2020-05-20 00:59
Seems to be working fine now. I deactivated and reactivated Akismet, AMP & Jetpack plugins, and also reloaded the editor a few times. Happy to close this if I don't see it again ...

**Comment by nerrad** [comment] 2020-05-21 12:51
I'm unable to reproduce this. The error indicates an issue with the REST API request so if this happened shortly after initially setting up the ephemeral site, it's possible there was some things still being configured on the server maybe. So I'm going to close this for now and if it surfaces again we can re-open.

**Closed by nerrad** 2020-05-21 12:51 UTC
