### ISSUE TITLE
WooCommerce block templates load unreliably inside the Site Editor.

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#8378] opened 2023-02-03 09:43 UTC
## Describe the bug

The Site Editor appears to be unreliable at loading the WooCommerce block templates, and on occasions just presents the user with a blank template despite that not being the case.

This has become apparent when testing https://github.com/woocommerce/woocommerce-blocks/pull/8308#issuecomment-1415169797 but is an existing issue.

_In my opinion, this really impacts the user experience of our block template feature and the effort we are currently putting into it. Especially since there is a really high chance the user will be impacted upon their first impression when testing/using this feature._

## To reproduce

1. From the WP dashboard, browser to Appearance > Site Editor
2. Click "Manage templates" to view the template list
3. Click into various WooCommerce block templates making sure you navigate between them using the browsers "Back" button.
4. Observe how at random, some of them do not load and appear as a blank template. (Fixed by refreshing the page on the blank template)

## Expected behavior

The correct block template will load its contents.

## Screenshots

https://user-images.githubusercontent.com/8639742/216566471-65335dab-52a5-4d3e-8916-c4c1a66ea369.mp4

### WordPress:

-   WordPress version: 6.1.1
-   WooCommerce version: 7.3.0
-   WooCommerce Blocks version: 9.5.0

**Comment by dinhtungdu** [comment] 2023-02-13 12:30
Update: Look like we have some issue with template fallback mechanism, I changed the `BlockTemplateUtils::ELIGIBLE_FOR_ARCHIVE_PRODUCT_FALLBACK` array to empty and can't reproduce this issue anymore.

**Comment by dinhtungdu** [comment] 2023-02-13 16:14
Update: template fallback isn't the issue. Gutenberg Site Editor has an issue when switching between templates that have identical content. If we disable template fallback but use the same content for all template files, the issue can be reproduced again.

### Steps to reproduce
1. Change the value of `BlockTemplateUtils::ELIGIBLE_FOR_ARCHIVE_PRODUCT_FALLBACK` to an empty array.
2. See the issue is no longer reproducible.
3. Update the content of the following files to use the content of `woocommerce-blocks/templates/templates/archive-product.html`:
  - `woocommerce-blocks/templates/templates/taxonomy-product_tag.html`
  - `woocommerce-blocks/templates/templates/taxonomy-product_cat.html`
  - `woocommerce-blocks/templates/templates/taxonomy-product_attribute.html`
4. See the issue is reproducible again.

I'm unassigning myself from this issue so others can work on that because I'm AFK tomorrow. I will continue working on this on Wednesday if needed.

**Comment by albarin** [comment] 2023-02-14 16:34
I've been trying to understand what's happening, I haven't managed to do it, but I'll leave here some more info I've discovered today in case it's useful for someone:
- The issue is related to this line https://github.com/woocommerce/woocommerce-blocks/blob/77d72eb7207429947a2231332db9620c25ab4027/src/BlockTemplatesController.php#L439 where we replace the template file for the `archive-product` fallback (after commenting that line the issue stops happening).
- With Gutenberg enabled the issue also stops happening.

**Comment by dinhtungdu** [comment] 2023-02-15 11:09
This is fixed by a side effect of https://github.com/WordPress/gutenberg/pull/47777:
- With 47777, whenever we browse the list of templates, the preview shows the home template.
- When another template is selected, the preview is updated accordingly, which fixes this issue by preventing switching between identical templates.

I opened https://github.com/WordPress/gutenberg/issues/48095 to track the issue upstream. Marking this issue as blocked for now.

**Comment by nefeline** [comment] 2023-05-19 15:57
> The Site Editor appears to be unreliable at loading the WooCommerce block templates, and on occasions just presents the user with a blank template despite that not being the case.

I did some tests today on https://liquid-coral.jurassic.ninja/ , with the latest versions of WooCommerce (7.7.0), WooCommerce Blocks (10.2.0), TT3 theme, and WordPress version 6.2.1 and wasn't able to reproduce this issue:

https://github.com/woocommerce/woocommerce-blocks/assets/15730971/944aa2bb-6a34-4b0d-a073-5fc7244bf37a

I also ran the exact same test while having the latest version of the Gutenberg plugin enabled (15.8.0) and things are working as expected.

@dinhtungdu @albarin @tjcafferkey do you still have any remaining concerns? From my perspective, we are good to close out this issue.

**Comment by tjcafferkey** [comment] 2023-05-19 16:13
I think we can close this issue now based on yours and Tungs feedback.

Thanks for following up on it!

**Closed as completed** 2023-05-21 15:45 UTC
Labels: status: blocked, type: bug, priority: high, focus: template
