### ISSUE TITLE
[WordPress 5.5 beta] Fix REST API notices in endpoints

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#2908] opened 2020-07-22 23:20 UTC
WordPress core had this changeset committed fairly recently: https://core.trac.wordpress.org/changeset/48526

> REST API: Issue a _doing_it_wrong when registering a route without a permission callback.

It looks like this will cause some notices with the endpoints in this plugin because we don't have that property defined in our route registrations that I can tell (likely will break things using the routes too with `WP_DEBUG_DISPLAY` set to true).

**Comment by haszari** [comment] 2020-07-27 01:01
Closing my duplicate report of this. Here's the full description with reproduce steps and link to docs about the change.

**Describe the bug**
In WordPress 5.5, `permission_callback` is [expected to be provided for all rest routes](https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/), and there's a warning generated if it's not present.

`Notice: register_rest_route was called incorrectly. The REST API route definition for wc/store/cart is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /var/www/html/wp-includes/functions.php on line 5225`

**To Reproduce**
1. Update development environment to WordPress 5.5 beta - use [_WordPress Beta Tester_](https://wordpress.org/plugins/wordpress-beta-tester/) plugin, or if using wp-env you can specify `"core": "WordPress/WordPress#master",` in `.wp-env.json`.
2. Set up cart & checkout pages with cart & checkout blocks.
3. Add something to cart, view cart (or checkout).
4. I'm seeing the warning message in front end; the message may be in logs or elsewhere depending on how your site is configured.

**Expected behavior**
No warnings when we register APIs - use `permission_callback` to indicate access control.

**Screenshots**
<img width="1204" alt="Screen Shot 2020-07-27 at 11 30 16 AM" src="https://user-images.githubusercontent.com/4167300/88492121-8ea35b00-cffc-11ea-931f-ae0d85bfdeaf.png">


**WordPress (please complete the following information):**

* Core version: 5.5-beta3-48624
* Gutenberg version (if installed): n/a
* WooCommerce version: 4.4.0-dev
* WooCommerce Blocks version: Version 3.0.0-dev

**Closed** 2020-07-29 08:39 UTC
Labels: scope: rest-api, type: blocker, type: bug
