### ISSUE TITLE
Empty Shopping Cart not displayed - Error

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#6275] opened 2022-04-16 13:36 UTC
## Describe the bug

if you click on the shopping cart, and it is empty there is nothing more previously there was always a smiley and the info that no items are in the cart.

## To reproduce

Click on empty shopping cart

## Expected behavior

Display a sad smiley and the information that there arent items in the cart

## Screenshots

live on site:

<img width="1205" alt="Bildschirmfoto 2022-04-16 um 15 34 02" src="https://user-images.githubusercontent.com/17782319/163676929-1c43e2b0-db1d-4e1c-920c-c0b2c115a9c8.png">

In Preview mode:

<img width="816" alt="Bildschirmfoto 2022-04-16 um 15 31 13" src="https://user-images.githubusercontent.com/17782319/163676918-54849d9c-fcbf-4e3e-b2d9-2ddcf8ca2c86.png">

### WordPress (please complete the following information):

-   Core version: [e.g. 5.9.3]
-   WooCommerce version: [6.4.1]
-   WooCommerce Blocks version: [7.4.2]
-   Site language: german

### Desktop (please complete the following information):

Every Browser, Every OS

### Smartphone (please complete the following information):

Every Smartphone, Every OS

**Comment by nielslange** [comment] 2022-04-20 08:21
Hello @DarianDev 👋 Thanks for reaching out. I tried to reproduce this case on a fresh WordPress installation, but wasn't able of doing so. Can you run a [theme and plugin conflict test](https://woocommerce.com/document/how-to-test-for-conflicts/) to see if that's causing the problem that you're seeing? Alternatively, could you remove the current Cart block and re-add it again, to see if that solves the problem?

**Comment by atomheartbrother** [comment] 2022-04-20 13:51
Hi @DarianDev @nielslange. I'm having the same issue as described. Here's a list of my currently active plugins if that helps.

CheckoutWC v7.0.16
Product Gallery Slider for WooCommerce v2.2
Side Cart WooCommerce v2.1
SiteGround Optimizer v7.09
WooCommerce v6.4.1
WooCommerce Blocks v7.4.2
WooCommerce Payments v4.0.1

**Comment by DarianDev** [comment] 2022-04-20 14:44
> theme and plugin conflict test

already tried re adding without success :/

**Comment by nielslange** [comment] 2022-04-20 15:54
@DarianDev and @DataAutomator Are you seeing any errors in the console? Or do you have any log files, that might indicate the cause of this problem?

**Comment by DarianDev** [comment] 2022-04-20 22:19
no nothing

**Comment by nielslange** [comment] 2022-04-22 08:53
I'll reach out to my colleagues, to check if any of them can reproduce this issue. I'll get back to you, once I have further information.

**Comment by nielslange** [comment] 2022-04-22 09:40
@DarianDev Given the error message, the problem could be related to translations. Can you switch the site language back to English, to see if the error is still visible then?

**Comment by DarianDev** [comment] 2022-04-22 09:44
@nielslange got the same error with english language

**Comment by senadir** [comment] 2022-04-22 09:45
You might have already done this, but did you try editing the page, removing the block and inserting it again?

**Comment by DarianDev** [comment] 2022-04-26 08:28
@senadir yes already tried

**Comment by nielslange** [comment] 2022-07-26 09:56
@DarianDev I just noticed that this issue is still open. I wonder if you're still facing this problem when using the Cart block or is the error resolved in the meantime?

**Comment by senadir** [comment] 2022-08-12 10:33
The error shown on the picture is Error 60 which is :

>  "60": "Can only set one of `children` or `props.dangerouslySetInnerHTML`."

This is additional information in case someone tries to fix this.

**Comment by regedy1** [comment] 2022-12-20 13:23
Just ran into this problem today and fixed this by removing the new product block inside the empty cart block

**Comment by ralucaStan** [comment] 2023-01-31 15:39
Closing as it seems that there is nothing we can do on our side at the moment. Thank you for taking the time to report this and feel free to reopen if you have extra input on this issue.

**Closed as completed by ralucaStan** 2023-01-31 15:39 UTC
Labels: block: cart
