### ISSUE TITLE
Widget Filters by Attribute: Term order

### ISSUE THREAD

**Issue by cam4rgo** [woocommerce/woocommerce-gutenberg-products-block#8608] opened 2022-09-30 19:33 UTC
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Widget filter by attribute does not stay in the correct order of terms.

Hello, I created a topic in the plugin forum and was asked to open a topic here regarding a bug in the Filter By Attribute Widget.

### Expected behavior

The bug is the following:
In the settings of the terms the order is like this and it is the way I want it to appear: P, M, G, GG, XG. 

![Captura de tela 2022-09-23 112100](https://user-images.githubusercontent.com/114769154/193341736-69d4e701-feef-465d-926a-2d0fbbd7d45b.png)
![Captura de tela 2022-09-23 112232](https://user-images.githubusercontent.com/114769154/193341751-22978a45-f0c9-4404-9b41-8b4fe0872b6c.png)

### Actual behavior

However, in the Filter By Attribute Widget the order is different, apparently in alphabetical order, as in the image:
![kBXx8zO](https://user-images.githubusercontent.com/114769154/193341979-489c1ed3-62e8-4b2b-8395-10b62825512c.png)

I noticed that this happens only with the new filter by attribute model, in the legacy widget the order works, but when filtering an item some size options are missing, and in the new one some options are not missing (which is the correct way.)
![Captura de tela 2022-09-28 231303](https://user-images.githubusercontent.com/114769154/193342042-5874ea9e-0243-4b65-83b3-39aa6b279758.png)

By using the YITH WooCommerce Ajax Product Filter Premium plugin I was able to reorder the terms the correct way, as in the image:
![zmB7xd](https://user-images.githubusercontent.com/114769154/193342520-17c51384-727f-4bf1-be3e-9b85f96d6183.png)

If you want to take a look at the topic I opened in the forum regarding this bug, [here is the link.](https://wordpress.org/support/topic/widget-filters-by-attribute-term-order/#post-16059221)

I have tested with the Storefront theme, I have disabled the plugins, I have checked the logs, and the problem persists. Other people have also tested and the problem is the same.

### Steps to reproduce

1. Create an attribute with custom sorting.
2. Put the terms P, M, G, GG, XG.
3. Products>Attibutes>Configure terms - Place them in the above order in the terms' settings.
4. Go to the widgets menu. (Appearance>Widgets)
5. Put the filter by WooCommerce attribute with the created attribute.
![image](https://user-images.githubusercontent.com/114769154/193348265-8cd9777e-305d-4c86-9fe8-c7970fcff38b.png)

6. See the error.

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by swatipawarGS** [comment] 2022-10-04 12:39
Hi @cam4rgo,
Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using the WooCommerce 6.9.4 version, and WordPress 6.0.2 version.

Please find below the screenshots for reference :

![#34910(backend)](https://user-images.githubusercontent.com/94531721/193756566-523f9194-d92f-4995-829e-0edb3eaae488.jpg)

![#34910(frontend)](https://user-images.githubusercontent.com/94531721/193756571-a8dc8d85-7341-4668-b716-f92ae8dad97e.jpg)

Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by clambug** [comment] 2022-12-06 12:24
Hi, facing exact same issue, has this been addressed yet?

**Comment by cam4rgo** [comment] 2022-12-11 22:50
@clambug Not yet. I'm waiting for that as well.

**Comment by Stefan-Ioan** [comment] 2022-12-13 21:17
any news?

**Comment by Stefan-Ioan** [comment] 2022-12-13 23:16
> @clambug Not yet. I'm waiting for that as well.

i find an workaround, 
since is alphabetical sort u can add `&nbsp;` in front of the name

ex for ur issue:
`&nbsp;` `&nbsp;`P
 `&nbsp;`M
G
GG
XG

if u want to remove `&nbsp;` from front page u can use jquery

 jQuery(".wp-block-woocommerce-attribute-filter span").html(function (i, html) {
    return html.replace(/`&nbsp;`/g, '');
});


another workaround is with letter and css
ex:

aP
bM
cG
dGG
eXG

and css

.wc-block-components-checkbox__label:first-letter {
    font-size: 0;
}

**Comment by cam4rgo** [comment] 2022-12-15 12:03
@swatipawarGS Any news on the prioritization of the problem?

**Comment by peterfabian** [comment] 2023-03-02 14:54
Thanks for letting us know about the issue. I've transferred the issue to the Blocks repository since the old widget works, but the Block widget displays the wrong order, I assume the issue comes from the Block.

**Comment by kmanijak** [comment] 2023-03-15 08:29
Hi, thanks for taking the time and letting us know about the issue! 🙌 

I can reproduce it, however, at this moment _Filter by Attribute_ block supports only the alphabetical ordering of attributes. But I agree that's a good idea for an enhancement!

Please bear in mind, we have limited time to work on various projects and at this moment this issue doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. Meanwhile, don’t be alarmed if you don’t see any activity on this issue for a while. 🙏 

---

Technical notes:

- Filter by Attribute uses Store API [`product/attribute/terms` endpoint](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/product-attribute-terms.md) with the default sorting 
- Endpoint supports three types of ordering: name, slug and count
- Filter by Attribute uses the default ordering: [`useCollection` ](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/attribute-filter/block.tsx#L137)

**Comment by cam4rgo** [comment] 2023-03-15 12:15
@kmanijak This worked before Blocks, so I believe it is more a bug than an improvement. In Brazil at least, this bug affects a lot of online stores that use WooCommerce. If you can review the priority of the problem, it would be interesting.

Sorry for any grammatical errors, I'm using a translator to write.

**Comment by kmanijak** [comment] 2023-03-16 11:37
> Sorry for any grammatical errors, I'm using a translator to write.

First of all - no need to apologize, it's all good! 👍 

> This worked before Blocks, so I believe it is more a bug than an improvement.

I totally understand that perspective and we'd love to be able to make a full replacement of every feature existing in the block's equivalents. However, we work in an iterative approach and we try to release blocks as quickly as they are functional and can bring value to the users. But that doesn't mean they will cover 100% of previous functionalities straight away. Then we're iteratively adding other features and functionalities.

However, we keep in mind some of the missing features may be more demanded by the community and issues like this one help us prioritize the work, so thank you for your input, especially since there are more voices in this thread!

---

Last but not least, I'd like to encourage the contribution. It's not an easy task to achieve for sure, but even a draft contribution may be a good trigger for further conversations 🙌

**Comment by DanielDM325** [comment] 2023-10-12 02:41
Is there any progress regarding this problem? I'm suffering from it too.

**Comment by dinhtungdu** [comment] 2023-10-17 04:59
Hey there, we fixed this issue in https://github.com/woocommerce/woocommerce-blocks/pull/11232 so I'm closing this one.

**Closed as completed by dinhtungdu** 2023-10-17 04:59 UTC
Labels: type: bug, type: enhancement, block: filter by attribute
