### ISSUE TITLE
Â - This appears on the payment page

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4465] opened 2021-07-14 14:21 UTC
This appears on the payment page
![Captur3e](https://user-images.githubusercontent.com/12650820/125638105-84611a5e-e8fe-49c5-8ae7-c23c04a16a25.PNG)

Here's what happens with css
![Capture5](https://user-images.githubusercontent.com/12650820/125638287-0f1d935a-6c2b-4a79-acf9-05c6bcdb08bc.PNG)

**Comment by ralucaStan** [comment] 2021-07-15 09:14
Hi there @msroky,
thank you for taking the time to report this.
I tested and I was not able to reproduce.
Do you mind sharing a link for your website? I see you are using a custom font, it might be that the font does not have support for the character we add to the element you selected in your image.

**Comment by mikejolley** [comment] 2021-08-03 15:25
This hasn't had a reply and we are unable to replicate so I am closing this issue. If you're still having this problem and can add more details to help us reproduce the problem, please reply or reopen this issue.

Thanks!

**Closed as completed by mikejolley** 2021-08-03 15:25 UTC
Labels: type: bug
