### ISSUE TITLE
Infinite loop when gutenberg is active in products

### ISSUE THREAD

**Issue by mcalduch** [woocommerce/woocommerce-gutenberg-products-block#4989] opened 2021-10-26 09:54 UTC
## Describe the bug
since version 4.9.0 when we activate Gutenberg manager in the products, an infinite loop is created in the blocks of type list when there is a product with a block of type list in this content

## To reproduce
1. Add Gutenberg feature to products

```php
function activate_gutenberg_products($can_edit, $post_type){
    if($post_type == 'product'){
        $can_edit = true;
    }

    return $can_edit;
}
add_filter('use_block_editor_for_post_type', 'activate_gutenberg_products', 10, 2);
```

2. Create a page with handpicked list
3. Select Product A and B
4. Edit Product A and add a handpicked block

## Expected behavior
the result is as expected for module version < 4.9.0

### WordPress (please complete the following information):
* Core version: all (5.8.1)
* WooCommerce version: >= 5.3.2
* WooCommerce Blocks version: >= 4.9.0
* Site language: en

**Comment by nerrad** [comment] 2021-10-27 19:17
Hi there @mcalduch, 

Thanks for taking the time to report this issue. Currently WooCommerce core doesn't support the block editor for the product editor so we aren't prioritizing fixes for that use case. However, this is definitely something worth nothing for when we do eventually look into that.

**Comment by nerrad** [comment] 2021-10-27 19:30
Actually I'm unable to reproduce this:

![CleanShot 2021-10-27 at 15 29 03](https://user-images.githubusercontent.com/1429108/139133935-1d91b368-1026-4676-872b-83e92c4486bf.gif)

Can you share more about what you are experiencing and what you mean by "infinite loop" please?

**Comment by nerrad** [comment] 2021-11-10 19:16
Given there hasn't been any response in a couple weeks and I was unable to reproduce, I'm going to go ahead and close this issue. If you have any additional details to provide related to my previous comments in the thread, that can still be left. Otherwise, there's nothing currently actionable here.

**Closed as completed by nerrad** 2021-11-10 19:16 UTC
Labels: type: bug, priority: low

**Comment by mcalduch** [comment] 2021-11-30 13:25
I can't find the exact procedure to reproduce the problem but you can see at the end of  these two videos as the cpu goes up to 100%.

https://www.loom.com/share/fb62cebc24aa4e77bc7d655e60ba0ce0?sharedAppSource=personal_library

https://www.loom.com/share/fb7cffad0a5445fdaca8c688cfccbe14?sharedAppSource=personal_library

**Comment by mcalduch** [comment] 2021-11-30 14:34
hi @nerrad 
finaly i found it!
it's simple : 


1. Add the gutenberg capability to the products :
function activate_gutenberg_products($can_edit, $post_type){
    if($post_type == 'product'){
        $can_edit = true;
    }

    return $can_edit;
}
add_filter('use_block_editor_for_post_type', 'activate_gutenberg_products', 10, 2);
2. Edit prouct A 
3. Add a handpicked block with product B and C
4. Edit product B
5.  Add a handpicked block with product A and C

voilà the infinite loop. The method charged to render the blocks, it's rendering de content of the products in a loop! this can cause this loop but it's eating the performance also.

here the video : 
https://www.loom.com/share/d3489b007bee41869d80e4f1eb4c4a50

**Comment by mcalduch** [comment] 2021-11-30 14:39
![loop](https://user-images.githubusercontent.com/1370292/144067541-9b692f97-e64f-47c0-a429-49d33937f3c4.png)

this line

**Comment by nerrad** [comment] 2021-11-30 18:58
Thanks for the additional details @mcalduch! I'm still going to leave this issue closed because this Woo doesn't officially support using the block editor in the product editor yet and that is something that you are reproducing this with. If this was reproducible outside of the product editor then we would definitely take a closer look.  Otherwise, for now, the details here will be useful when we begin work on bringing official support for the block editor to the WooCommerce product management view.
