### ISSUE TITLE
Translation not fully loading from translate.wordpress.org

### ISSUE THREAD

**Issue by guyfullpower** [woocommerce/woocommerce-gutenberg-products-block#4037] opened 2021-04-06 09:23 UTC
i have an issue on the cart page that the words: subtotal, shipping and save arent translated and also cannot be translated using a plugin like Loco Translate as show in the attached image.
(the wordpress and also the plugins are up to date, i just double checked)
![Capture](https://user-images.githubusercontent.com/40365063/113688468-ffddf680-96d1-11eb-90a3-8c9f9d57694c.JPG)

**Comment by senadir** [comment] 2021-04-08 13:58
Hey there @guyfullpower. I can confirm this issue with Spanish which is 100% translated in [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/es/default/) while Loco Translate only shows 377 string in total (PHP and JS)
![image](https://user-images.githubusercontent.com/6165348/114037673-18d4dc00-9879-11eb-8d81-2e68cbfeadfd.png)
![image](https://user-images.githubusercontent.com/6165348/114037379-d9a68b00-9878-11eb-8667-0878a14eeb7d.png)

Running `wp.i18n.getLocaleData('woo-gutenberg-products-block')` on a page with all of our JS blocks shows around 270 which is about right since it only contains JS strings.

I've also made sure I updated my translation 
![image](https://user-images.githubusercontent.com/6165348/114037990-62252b80-9879-11eb-9da5-4b8460d44cbe.png)

I will return to you once I figure out the problem or a workaround.

**Comment by guyfullpower** [comment] 2021-04-08 14:05
great, thanks :)
if you need anything from me please let me know

**Comment by senadir** [comment] 2021-04-08 14:58
Hey again @guyfullpower 
https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/4050 Should fix this issue, it will be released with 4.9.0 next week.

I don't have a workaround since this requires changing the source code.

**Comment by guyfullpower** [comment] 2021-04-08 15:03
no problem i will wait for the release, thanks a lot :)

**Closed as completed** 2021-04-12 10:05 UTC
Labels: type: bug, focus: i18n
