### ISSUE TITLE
filters block lead to 404 error page

### ISSUE THREAD

**Issue by NinjaAtWork** [woocommerce/woocommerce-gutenberg-products-block#8293] opened 2023-01-25 15:22 UTC
Hi
in our shop with more than 20 page of product and 30 product per page, simply this url is gonna work:
`https://website.com/shop/?filter_stock_status=instock` 
also this is working:
`https://website.com/shop/page/2/?filter_stock_status=instock`
but this one rise the 404 error:
`https://website.com/shop/page/4/?filter_stock_status=instock`

how to reproduce:
i have added a filter by stock blocks to the archive product page and now at this page:
`https://website.com/shop/`
i can filter by stock with no problem but through bottom pagination if i navigate to a page like this :
`https://website.com/shop/page/4/` 
then after filter by stock there will by `404 error`

i don't know why page 1,2,3 work and 4,5,6,... will rise error but it seems the error maybe depends on the count of available product which in my case is 57 item available out of 600 item

what can i do ?
thanks in advance

**Comment by gigitux** [comment] 2023-01-26 09:15
Hi, thanks for opening this issue.
I'm not able to replicate the issue following your reproduction steps.

Did you try to disable all the plugins except WooCommerce Core and WC Blocks?

**Comment by NinjaAtWork** [comment] 2023-01-28 14:27
Hi
disabling all the plugin and no luck.
its so simple: when quantity of "in stock" product is about 3 page then the URL of showing page 15 of available product will rise 404.

**Comment by sunyatasattva** [comment] 2023-02-03 23:24
Hello @NinjaAtWork 

Thank you for reporting. We'd love to help, but if we can't reproduce we have no way to figure out the bug. It'd be very helpful if you could provide step by step instructions on how to reproduce your issue, with as much detail as you can regarding your configuration; including, if possibile, screenshots or videos.

I have tried to reproduce your issue, but I cannot. I did the following:

1. Created a new WordPress installation.
2. Installed WooCommerce and WooCommerce Blocks.
3. Created about 60 products on my new store.
4. Navigated to `/shop`.
5. Navigated to `/shop/?filter_stock_status=instock`.
6. Navigated to `/shop/page/4/?filter_stock_status=instock`.

Everything works well for me and I see no 404 errors.

**Comment by imanish003** [comment] 2023-03-03 10:41
Hi @NinjaAtWork,

Thank you for taking the time to report this issue. Unfortunately, we have not received any response from you in a significant amount of time, and therefore, we will be closing this issue.

However, please note that we are committed to resolving any issues that users encounter, and we would be more than happy to reopen this issue if you can provide us with detailed step-by-step instructions on how to reproduce the issue you are facing. This will help us to investigate the problem more efficiently and work towards finding a solution.

**Closed as completed by imanish003** 2023-03-03 10:41 UTC
Labels: type: bug, block: filter by stock
