### ISSUE TITLE
Cart css style <li>

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4835] opened 2021-09-24 01:33 UTC
I’m not sure if this little problem is up to my theme
![Capture](https://user-images.githubusercontent.com/12650820/134604829-05124c8a-68be-4df5-a92e-c16187d24877.PNG)
This little dot appears :)
![Capture2](https://user-images.githubusercontent.com/12650820/134604933-0b7fd24d-6a31-439c-bdda-a122be6891c5.PNG)

**Comment by nielslange** [comment] 2021-09-24 06:45
Hello @msroky 👋

Kindly note that this repository is for development purposes only. Support requests for the WooCommerce Blocks plugin need to be filled on https://wordpress.org/support/plugin/woo-gutenberg-products-block/. 

That said, I looked into the problem that you reported and cannot reproduce it with Storefront, the default WooCommerce theme:

<img width="713" alt="Screenshot 2021-09-24 at 13 34 31" src="https://user-images.githubusercontent.com/3323310/134629084-5417d30c-af89-4892-9901-7c96b6a7a96e.png">

However, please reach out via https://wordpress.org/support/plugin/woo-gutenberg-products-block/ to discuss further steps in this case.

**Comment by msroky** [comment] 2021-09-24 12:30
This happens when you have more colors and variations. <ul> and <li> css elements do not work.

**Comment by nielslange** [comment] 2021-09-25 03:00
> This happens when you have more colors and variations.

I'm still not seeing this, even when adding products with variations to the cart:

<img width="743" alt="Screenshot 2021-09-25 at 09 59 29" src="https://user-images.githubusercontent.com/3323310/134755700-949eb311-9304-4dda-9bed-cb0122342dcb.png">

> css elements do not work

As for the CSS elements, can you point out which CSS elements are not working?

**Comment by tjcafferkey** [comment] 2021-09-29 09:19
@msroky please can you provide some replication steps for this issue which will help us reliably replicate the problem?

>I’m not sure if this little problem is up to my theme

Please will you also let us know further details such as your theme.

**Comment by nerrad** [comment] 2021-10-14 17:16
Hi @msroky,

Thanks for taking the time to leave your original report, however we've been unable to successfully reproduce this. It's been a while with no additional information or answers to the latest questions so I'm going to go ahead and close this issue.

You're still able to leave comments if you have additional info and if that helps us with reproducing we can re-open the issue then.

**Closed as completed by nerrad** 2021-10-14 17:16 UTC
Labels: type: bug
