### ISSUE TITLE
Product Images of Store API sometimes is not an array but dist

### ISSUE THREAD

**Issue by whywilson** [woocommerce/woocommerce-gutenberg-products-block#6182] opened 2022-04-04 00:44 UTC
## Describe the bug

While I request the data of `/wp-json/wc/store/products?per_page=60`, it should contain all products in format type. But some of the product images are array but some are dicts like,
```
"images": {
"0": { 
"id": 50364,
        "src": "",
        "thumbnail": "",
        "srcset": "",
        "sizes": "",
        "name": "",
        "alt": ""
},
"1": { 
}
}
```

## To reproduce

The return of variable products with plenty of variations always returns the images as dict. It happens also with single product fetch.

## Screenshots

<a href="https://ibb.co/Cnm7cXJ"><img src="https://i.ibb.co/Q6pNgq8/Xnip2022-04-04-08-42-13.jpg" alt="Xnip2022-04-04-08-42-13" border="0"></a>

### WordPress (please complete the following information):

-   Core version: 5.9.2
-   WooCommerce version: 6.1
-   WooCommerce Blocks version: 7.0.0

**Comment by frontdevde** [comment] 2022-04-08 14:34
Hey @whywilson, just double-checking: if I understand correctly you're observing an issue where images are not returned as an array but as an object instead? If possible, could you please provide us with steps to reliably reproduce the issue with the latest WooCommerce and WooCommerce Blocks versions? Thank you!

**Comment by whywilson** [comment] 2022-04-09 05:54
WooCommerce Version:  6.3.1.
You can check [the link to the product](https://www.boslla.com/wp-json/wc/store/products/50533) by Store API. The images are in the object with numbers as keys.

**Comment by whywilson** [comment] 2022-04-09 05:54
> Hey @whywilson, just double-checking: if I understand correctly you're observing an issue where images are not returned as an array but as an object instead? If possible, could you please provide us with steps to reliably reproduce the issue with the latest WooCommerce and WooCommerce Blocks versions? Thank you!

WooCommerce Version: 6.3.1.
You can check [the link to the product](https://www.boslla.com/wp-json/wc/store/products/50533) by Store API. The images are in the object with numbers as keys.

**Comment by senadir** [comment] 2022-04-15 15:26
Hey, this doesn't seem to happen reliably, at least, I couldn't yet figure out the reproduction steps, can you help me narrow that down @whywilson ?

**Comment by tomasztunik** [comment] 2022-05-10 12:05
@whywilson we'll close this issue for now as this issue is not related to the repository - we've tried to reproduce it to if anything at least better direct you going forward but we had no "luck" there. 

If you still had issues around this please report with https://github.com/woocommerce/woocommerce - the team over there is responsible for the REST API service.

**Comment by senadir** [comment] 2023-02-21 13:10
This was closed by mistake, the issue is related to our repository, Store API is part of this repo.

**Closed as completed** 2023-02-22 13:12 UTC
Labels: type: bug

**Comment by whywilson** [comment] 2023-06-20 05:06
> This was closed by mistake, the issue is related to our repository, Store API is part of this repo.

The same issues happened on the **image** of `/wp-json/wc/store/products/categories` request. 
It should be null or object, but it's an array sometimes.

```
{
  "id": 233,
  "name": "Product Name",
  "slug": "product-name",
  "description": "Product description",
  "parent": 28,
  "count": 2,
  "image": [],   // not null or object, but array
  "review_count": 44,
  "permalink": ""
}
```
