### ISSUE TITLE
Store notices container always shows as an error

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gutenberg-products-block#11768] opened 2023-11-14 14:54 UTC
## Describe the bug

If a notice with `status: success` is created, it still shows the red, error state.

## To reproduce

1. Go to the Cart block.
2. In the JS console type: `wp.data.dispatch('core/notices').createSuccessNotice( 'This is a success message, it should show in green!', { context: 'wc/cart' } )`
3. See the "error" notice display even though it should be success.

## Expected behavior

The notices should show the correct type.

## Screenshots

<img width="987" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/5656702/f2ba98a1-5324-40cb-a75d-c1250fd6e5b0">

## Additional context

Removing this 'error' value and using the shorthand `status` instead will fix this - there is a TS error that should be fixed when doing that though.

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/packages/checkout/components/store-notices-container/store-notices.tsx#L130

**Comment by arsanyjoseph** [comment] 2023-11-22 22:58
@opr I would like to work on this 
If you don't mind, please assign me

**Comment by agung2001** [comment] 2023-11-24 02:15
Yes, can replicate this

## createNotice
the issue also happened in `createNotice` : 
```javascript
wp.data.dispatch('core/notices').createNotice('success', 'This is a success message, it should show in green!', { context: 'wc/cart' } )
```
![Screenshot 2023-11-24 at 09 15 27](https://github.com/woocommerce/woocommerce-blocks/assets/4479106/cddb89e8-36a2-4326-8953-88851f39973b)

## Snackbar
but the snackbar works just fine though : 
```javascript
wp.data.dispatch('core/notices').createNotice('success', 'This is a success message, it should show in green!', { type: 'snackbar', context: 'wc/cart' } )
```
![Screenshot 2023-11-24 at 09 13 30](https://github.com/woocommerce/woocommerce-blocks/assets/4479106/6681f126-c1db-474b-adb3-7d733fa13c67)

**Comment by agung2001** [comment] 2023-11-24 03:29
I think the issue is due to : 
- [noticeProps](https://github.com/woocommerce/woocommerce-blocks/blob/e4df7408dff52b244af70f86e991d60634af72a5/packages/components/store-notices-container/store-notices.tsx#L130) `status` is set to `error` instead of using `status` variable

## Solution
so to fix this we need to change the `noticeProps` to something like this : 
```javascript
const noticeProps: Omit<NoticeBannerProps, 'children'> & {
    key: string;
} = {
    key: `store-notice-${status}`,
    status,
    onRemove: () => {
        noticeGroup.forEach((notice) => {
            removeNotice(notice.id, notice.context);
        });
    },
};
```

## Solved
I've confirmed the fix by running : 
```javascript
wp.data.dispatch('core/notices').createSuccessNotice( 'This is a success message, it should show in green!', { context: 'wc/cart' } )
```

![Screenshot 2023-11-24 at 10 25 10](https://github.com/woocommerce/woocommerce-blocks/assets/4479106/ff9c2ee9-67d2-4cd1-8498-19793c148b72)

## Request
Hi @opr , can you assign this issue to me, so I can create PR for this?

**Comment by opr** [comment] 2023-11-24 10:38
Hey @agung2001 thanks for offering to work on this. I've assigned you to the issue.

Please feel free to tag me as a reviewer when your PR is open!

**Comment by agung2001** [comment] 2023-11-24 12:17
hi @opr thx for giving me an opportunity to fix the issue
I've opened the PR it's in here #11932 

but unfortunately, I don't have access to make you the reviewer
m not sure if I did it correctly.

just let me know if u got any feedback, cheers 👍

**Closed as completed** 2023-11-27 13:07 UTC
Labels: type: bug, type: good first issue, focus: blocks, block: cart, block: checkout
