### ISSUE TITLE
Mini Cart Block vs caching enabled

### ISSUE THREAD

**Issue by BicanMarianValeriu** [woocommerce/woocommerce-gutenberg-products-block#7530] opened 2022-10-30 01:49 UTC
## Describe the bug

If you enable any caching plugin (tested W3Total, WP Fastest Cache, WP-Optimize, Litespeed) the cart will not update on page load.

## To reproduce

1. Enable any caching plugin and turn on caching (including HTML)
2. Go to the shop and add a couple of products
3. Go to the homepage and load it once, it will cache the page initially with x products in the cart
4. Reload the page, it will show the products added to the cart
5. Go to the shop again and add another product
6. Go back to the homepage, showing the previously cached version without updating the cart until you hover it.

## Expected behavior

From point 6, if you go to homepage (used in our example, it can be any cached page) it should update the cart with the real value as soon as it loads.

## Screenshots

![image](https://user-images.githubusercontent.com/11237975/198858878-34b1a14c-dd9e-470e-b7e2-8dea0a73affa.png)
![image](https://user-images.githubusercontent.com/11237975/198858888-53959ea3-4b41-422b-ba44-260dd99b793d.png)
![image](https://user-images.githubusercontent.com/11237975/198858897-b7106711-8b98-4c55-a254-df6881d7f2ac.png)

### WordPress (please complete the following information):

-   WordPress version: [6.1 RC5]
-   Gutenberg version (if installed): [none]
-   WooCommerce version: [7.0.0]
-   WooCommerce Blocks version: [none]
-   Site language:
-   Any other plugins installed:
-   W3 Total Cache [2.2.6]

### Desktop (please complete the following information):

-   OS: [Windows]
-   Browser [Chrome]
-   Version [???]

## Additional context

I believe the problem is simple, refreshed fragments should run on page load instead of hovering the Mini Cart block.

**Comment by imanish003** [comment] 2022-11-01 04:47
Hi there @BicanMarianValeriu 👋 
Thank you so much for taking the time to create this issue – much appreciated. 🙏🏻

I tried to reproduce this issue with a fresh setup, but I cannot reproduce it. It might be possible that this issue could be due to the misconfiguration of `W3 Total Cache` plugin. I can reproduce it on [your store](https://bee.store.ro/).

Can you please try a fresh setup with the storefront theme & W3 Total Cache plugin? Please let me know if you can reproduce it with a new fresh setup too. That would be very helpful.

**Comment by BicanMarianValeriu** [comment] 2022-11-01 16:19
Testing with the Storefront theme is irrelevant - this issue happens on Blocks (Full Site Editor themes / Gutenberg Mini Cart block). Installed TT3 and the issue is still there. I don't think is a misconfiguration as the mini cart updates when hovered - It should update on page load instead on hover but I guess it delays the refreshed cart fragments javascript. You cannot show the user X products in the cart then if it hovers it, Y products.

**Comment by BicanMarianValeriu** [comment] 2022-11-01 16:20
That cart?locale=user api-fetch should be called once on load (instead hover) in my opinion.

**Comment by imanish003** [comment] 2022-11-03 05:54
Hi @BicanMarianValeriu, 
Thanks for sharing more info. I can reproduce this issue now 🙌🏻

The mini cart just servers HTML so that's what gets cached. 

> That cart?locale=user api-fetch should be called once on load (instead hover) in my opinion.

There are tradeoffs of always loading the JS on page load instead of only when cart is needed. We will definitely consider this approach while working on this issue. Thanks for your suggestion 🙏🏻

Adding this issue to our queue 🙏🏻

**Comment by dinhtungdu** [comment] 2022-11-11 14:08
Hi @BicanMarianValeriu,

We had a long and interesting conversation discussing this issue internally. I'm sharing the key takeaways:

- 'The Mini Cart does not update on page load' is expected behavior if full page caching is used.
- For commerce sites, page caching should always be approached carefully and if it is used, should implement fragment caching (which usually has to be done manually/custom).
- If fragment caching is not an option, our recommendation is to disable caching on all pages containing the Mini Cart block.
- The Mini Cart scripts are only loaded when visitors/customers interact with the Mini Cart, which explains the issue with full-page caching. It's possible to always load the Mini Cart scripts after the page load, it means that we're loading scripts even if the customer doesn't interact with the Mini Cart, we think it isn't an optimal solution.
- It's possible to force the Mini Cart to re-render by loading a custom script on page load (see below). But this isn't supported and developers should use it at their own risk:
```
const miniCartButton = document.querySelector( '.wc-block-mini-cart__button' );
if ( miniCartButton ) {
    miniCartButton.dispatchEvent( new Event( 'mouseover' ) ); 
}
```
_Thanks @imanish003, @nerrad, and @Aljullu for the convos!_

I'm closing this issue for now as it's a trade-off of using full-page caching with Mini Cart. But feel free to reopen it if needed. We can also continue the conversation even when this is closed.

**Closed as completed by dinhtungdu** 2022-11-11 14:08 UTC
Labels: type: bug

**Comment by BicanMarianValeriu** [comment] 2022-11-11 14:43
Ah, I understand.
It would be a nice improvement to include fragment cache by default for some of the major plugins: (Litespeed, W3Total, etc) but that's relative to whom should include that, WOO or the caching plugin itself.
I've got it resolved using this for Litespeed Cache (for others might be more complex for the average user). Anyway, many thanks.

```
// Fragment Cache
add_filter( 'render_block', function( $content, $data ) {
	if( get_prop( $data, [ 'blockName' ] ) === 'woocommerce/mini-cart' ) {
		do_action( 'litespeed_control_set_nocache' );
	}

	return $content;
}, 10, 2 );
```

**Comment by Aljullu** [comment] 2023-05-04 11:26
Heads-up that we are going to explore making the Mini Cart block work with this kind of cache plugins. In case somebody wants to follow the exploration, I created a new issue: https://github.com/woocommerce/woocommerce-blocks/issues/9353.
