### ISSUE TITLE
Integration Tracking (WC Subscriptions): `Something went wrong` while clicking the back button on browser in Checkout page

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gutenberg-products-block#4022] opened 2021-04-01 05:09 UTC
## Describe the bug

If you hit the back button on the browser (Tested in Chrome) while on the checkout page, you'll see the following error in Chrome:

## To reproduce

1. Add a product to the cart
2. Access the Checkout block page
3. Ensure you've set up a cart redirect option to the cart blocks page
4. See the error:
    ![https://d.pr/i/CfzPbc+](https://d.pr/i/CfzPbc+)
5. Notice that reloading the page fixes this issue.

## Expected behavior

Display the cart content, or remove the actual error and make it just request the user to reload the page.

### Desktop (please complete the following information):
* OS: macOS
* Browser: Latest version of Chrom

### Smartphone (please complete the following information):
* Device: iMac

**Comment by Aljullu** [comment] 2021-04-01 08:59
Thanks for filling this issue! This seems to be very similar, if not the same, as #4001 but with different testing steps. So I'm going to close it as a duplicate of that one since the solution is probably the same for both.

**Closed as completed by Aljullu** 2021-04-01 08:59 UTC
Labels: type: bug
