### ISSUE TITLE
Postal code: option required to not be optional (as per Covid situation)

### ISSUE THREAD

**Issue by rmichela13** [woocommerce/woocommerce-gutenberg-products-block#4578] opened 2021-08-14 09:02 UTC
## What do you think is missing from the Cart & Checkout blocks?
Hello!
I am testing the cart and the checking out blocks. I am working with Divi.
In terms of functionallity I am missing that the postal code is set as optional, and I would like to force my clients to introduce it, as per Covid restrictions, now there are zones we can't ship inside a same city, so the postal code is the only way I have to make precise locations. Thanks

**Comment by opr** [comment] 2021-08-18 14:28
Hi there @rmichela13 - thanks for taking the time to leave feedback about WooCommerce Blocks!

I was wondering if you could share a little more information about your store, specifically the country you're operating in.

The postal code is mandatory for me when trying to check out using a UK address.

<img src="https://user-images.githubusercontent.com/5656702/129916070-a571754d-6b35-4ccb-871f-049ba23b480e.png" width=350 />

You mention you're using divi, it's possible that some plugins are conflicting with the functionality here... Could you try disabling all plugins beside WooCommerce and WooCommerce Blocks and see if the postcode is mandatory then?

If this is the case, then please re-enable the plugins one-by-one until the postcode becomes optional. Then we'll know which plugin is causing the issue.

**Comment by ralucaStan** [comment] 2021-08-27 14:07
Hi @rmichela13  👋 ,
I'm going to close this because there still isn't anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we're able to reproduce we can re-open as necessary.

**Closed as completed by ralucaStan** 2021-08-27 14:07 UTC
Labels: block: checkout
