### ISSUE TITLE
Block "Products by Category" does not show all products in selected category, and there is no filter

### ISSUE THREAD

**Issue by land77** [woocommerce/woocommerce-gutenberg-products-block#3136] opened 2020-09-10 02:53 UTC
I was making a custom page, and added a block "Products by Category".
I have 80 proucts in the selceted category, but the block only show 12 of them. There is no pagination like page "privous 1 2 3 next"
I have read some articles. There is some way to add some code to increase the quantity of products in that page, But there is still no pagination. It is no good to load too many products on same page.
How could we slove this please?
Many thanks for your help.

**Comment by nerrad** [comment] 2020-09-17 15:12
Hi there @land77 👋 

Thanks for taking the time to leave your report. This is a duplicate of #2656 so I'm going to close this issue in favor of the other.

**Closed by nerrad** 2020-09-17 15:12 UTC
Labels: type: bug
