### ISSUE TITLE
Cart + Checkout Blocks > Random translation Cart "x left in stock" and Checkout GDPR Text

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#6662] opened 2022-07-06 18:20 UTC
### **Bug Description**

Translation not correctly loaded in some block areas. This is a random error 
(no additionnal plugins / TT2 theme confirmed)
(reproduced on wordpress.com hosting, but also dedicated ones)

### **How to reproduce ?**

- install WP and set it to French
- install Woo Block then Woo Commerce
- update / load all translations with updater check
- no other modules installed, default theme TT2
- Woo : define store location (address) and free shiping method
- Woo : no other default settings changed, default inventory value for "Stock display format selector" unchanged
- Woo : Add a product, set price and stock
- Cart page : edit it in Editor, to add the Cart Block + Save (replace the shortcode)

**1/ Add to cart**
- Go to Front to Add to Cart product
- Go to Cart page

![image](https://user-images.githubusercontent.com/919332/177617428-bcdd5061-7b00-4c56-b7e4-6e1caa20d71e.png)

**2/ Go to checkout**
We also have at checkout page one translated zone (GDPR) [shortcode version only, block version forgot to display this text see #6663 ]
The text is correctly set in FR in Woo account settings > should be displayed in French

![image](https://user-images.githubusercontent.com/919332/177617575-3389b094-85a1-4362-9e32-267e0da6558d.png)

![image](https://user-images.githubusercontent.com/919332/177613777-1acc77d9-6bd7-48d4-a25c-7fd34aed9164.png)

**3/ Checkout > shiping default text not translated**

"Shipping options will be displayed here after entering your full shipping address"

4/ Empty cart > empty cart message not translated

"Checkout is not available whilst your cart is empty—please take a look through our store and come back when you're ready to place an order."

NB :  no errors are detected with Browser debug tools

### **Environment info**
- WP 6.0
- Gutenberg plugin : no (only core)
- TT2 theme
- WooCommerce 6.6.1
- WooCommerce block 8.8.0
- No other modules
- Language set to FR in WP General Settings
- Bug reproduced with both Firefox and Chrome Browsers 

### Please confirm that you have searched existing issues in the repo.
Yes
seems not related to https://github.com/woocommerce/woocommerce-blocks/issues/6530

### Please confirm that you have tested with all plugins deactivated 
Yes
The issue occurs randomly (tested on several new instances with TT2 theme only), sometimes it is ok, sometimes it is still in english
It occurs also with other Themes, so it is not TT2 specific ;-)

**Comment by Marc-pi** [comment] 2022-07-08 14:08
seems translation issues are noticed on other part (in block settings) as well https://github.com/woocommerce/woocommerce-blocks/issues/6244, and https://github.com/woocommerce/woocommerce-blocks/issues/5866
and absolute/relative path https://github.com/woocommerce/woocommerce-blocks/issues/6186

**Comment by Marc-pi** [comment] 2022-07-12 13:01
@Aljullu **the red bug badge** is missing. For some reason, it was not automaticaly added when i submited this issue
can you add it ?

**Comment by opr** [comment] 2022-07-12 14:06
Hi there @Marc-pi! Thanks for taking the time to report this issue, while my site is set to French, I can also see that this string is not translated.

This is being caused by the string not being translated on https://translate.wordpress.org/ ([This is the string in question](https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/fr/default/?filters%5Bterm%5D=left+in+stock&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)) - we rely on volunteer contributors to help translate our plugin and it looks like nobody got round to this yet.

If you are interested in contributing translations, then the WordPress community as a whole would be super grateful for your help! You can [read more about translating WordPress on this page](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/).

I'll go ahead and close this issue now but if you need more help feel free to comment again, or open a new issue!

**Closed as completed by opr** 2022-07-12 14:06 UTC
Labels: focus: i18n, block: cart, block: checkout

**Comment by Marc-pi** [comment] 2022-09-09 18:11
@opr during those weeeks, i translated the whole extension plugin, thanks, it helped :-)
the point 4 is still present see the related linked issue
