### ISSUE TITLE
Products block: Selected product has additional spacing in the editor 

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#7866] opened 2022-12-07 09:12 UTC
## Describe the bug

Products Block (new Query Loop Product block)
Content is not aligned

## To reproduce

1. Create a set of products
2. Add the block
3. Observe the display

## Expected behavior

Strange, content is not well aligned, despite pictures/ contents are the same...
Missing "Align the last block to the bottom" (for the add to cart button), like we have in other blocks ?

## Screenshots
![image](https://user-images.githubusercontent.com/919332/206136553-3d043467-0313-4274-b06b-07474b5172fa.png)

## Environment

WP6.1.1
Woo Blocks 9.1
Gutenberg plugin 14.6.1
WC 7.1
TT2 Theme

**Comment by danieldudzic** [comment] 2022-12-23 14:46
Thank you for reporting this, @Marc-pi.

![Edit_Page_“All_Products”_‹_ratings_—_WordPress (1)](https://user-images.githubusercontent.com/905781/209354006-8cebc37b-dc78-41a4-9b62-753dad09e8fd.jpg)

This is caused by inline styling being added when a product is being selected (in the editor).

I'm not sure where this CSS is coming from, though:

![notify (1)](https://user-images.githubusercontent.com/905781/209353997-c1faebd0-3dff-422d-b4e7-361662d29843.gif)

**Comment by danieldudzic** [comment] 2023-01-12 13:10
There's a similar issue in Gutenberg core: https://github.com/WordPress/gutenberg/issues/45590

**Comment by imanish003** [comment] 2023-04-18 09:45
It appears that this issue has been addressed and resolved in the upstream Gutenberg repository. I will proceed to close this issue for now. However, if you encounter any further problems related to this issue, please do not hesitate to inform us. We would be more than happy to reopen the issue if necessary.

**Closed as completed by imanish003** 2023-04-18 09:45 UTC
Labels: type: bug, block-type: product-query
