### ISSUE TITLE
[Enhancement]: Opt-in option for new blocks

### ISSUE THREAD

**Issue by JoryHogeveen** [woocommerce/woocommerce-gutenberg-products-block#9567] opened 2023-05-17 13:34 UTC
### Describe the solution you'd like

Related: https://wordpress.org/support/topic/site-doesnt-include-support-for-the-woocommerce-product-tab-block/#post-16745323

Since the latest WooCommerce versions there are newer block types, probably Block Theme related.

For users that manually enabled the Block Editor for products this results in errors because the `woocommerce/product-tab` block doesn't exist.

What I suggest is that non-block themes should be able to opt-in on loading these custom blocks from WooCommerce.
Maybe through theme supports?

### Describe alternatives you've considered

Current workaround simply completely disables and overrides the WooCommerce block templates:

https://wordpress.org/support/topic/site-doesnt-include-support-for-the-woocommerce-product-tab-block/#post-16669859

**Comment by roykho** [comment] 2023-05-23 13:15
Hi @JoryHogeveen - Thanks for reporting. If you don't mind, could you please document the exact steps to reproduce this issue? This will help us to reliably replicate the issue on our end.

**Comment by JoryHogeveen** [comment] 2023-05-23 17:56
Hi @roykho 

This is not a report that is about reproducing an issue, it's an enhancement/feature request to opt-in for using the block theme related blocks.

Did you read the topic I linked to?

Context:
If you manually enable the block editor for products (I know this isn't a Woocommerce feature) you see an error when you try to add a new product.
It then tries to use the Woocommerce block theme related blocks that arent loaded at all since you aren't using a block theme.
The enhancement would be that you can manually opt-in to load these woocommerce blocks, like the product-tab block.

**Comment by Aljullu** [comment] 2023-06-23 09:05
Hi there, @JoryHogeveen, the Product Tab block is a block being created as part of modernizing the Edit product screen in the admin. In other words, it's different from the blocks which are part of this repo, which are intended to be used in the store frontend.

Would you mind testing again if you can reproduce the bug? Since you filled the issue there have been several WooCommerce releases that might have fixed that. Thanks in advance!

**Comment by JoryHogeveen** [comment] 2023-06-23 10:21
Hi @Aljullu 
I just tested this issue by removing the suggested compatibility code (removing the template param from the register array) and I don't see any errors when creating a new product. This gives me the impression that it could be fixed in one of the newer versions.
If this is the better solution then I'm ok with that!

**Comment by Aljullu** [comment] 2023-06-23 11:38
Cool, thanks for testing @JoryHogeveen! Based on your comment, I will go ahead and close this issue.

**Closed as not planned by Aljullu** 2023-06-23 11:38 UTC
Labels: type: enhancement, block: single product, type: community contribution
