### ISSUE TITLE
Product Category block returns with "No category" despite setting up Product Categories

### ISSUE THREAD

**Issue by namiokuzono** [woocommerce/woocommerce-gutenberg-products-block#8747] opened 2023-03-15 04:37 UTC
## Describe the bug

Product Category block returns with "No category" despite setting up Product Categories

## To reproduce

1. Make sure to have product categories set up on the site
2. Go to Page to edit
3. Add Product Category block

## Expected behavior

Product categories should be returned 

## Screenshots

https://user-images.githubusercontent.com/85893744/225207522-94cdcc69-26de-441a-bb28-1e8f2a7ee5f1.mp4

### WordPress (please complete the following information):

-   WP Version: 6.1.1
-   WC Version: 7.4.1
-   WC Blocks Version: ✔ 9.4.4
-   Site language: EN

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Vivalidi

**Comment by namiokuzono** [comment] 2023-03-15 04:40
There is also internal conversation here I encountered - p1675753912285509-slack-C3NCP7ZJ6 (not sure if bug report was filed at this time, but maybe I could not find it so reporting here)

I would want to say the priority would be high, since this would affect anyone who would want to use Product Category block... So I am going to change it to High for now, but please change it to low if appropriate.

**Comment by kmanijak** [comment] 2023-03-15 14:03
Hi!

Thanks a lot for raising this issue!

I checked the issue and indeed it behaves that way on the posts or pages, however, this is expected behavior. `Product Categories` block is dedicated for a Single Product template to display the categories related to the _specific product's_ categories, not _all_ categories. It may be not very clear by the block name though.

Here's the example how the block looks like in the Single Product Template:

| Editor | Frontend |
|-------|----------|
| <img width="677" alt="image" src="https://user-images.githubusercontent.com/20098064/225331510-75a2c3de-5981-493d-bc0e-2b46c53ef459.png"> | <img width="242" alt="image" src="https://user-images.githubusercontent.com/20098064/225331768-31ae882c-2b78-4d43-8757-f029c164ba67.png"> |

I hope that clarifies the issue!

But the experience can be improved and the real issue is that this block should not appear in inserter in posts or pages. There's already an issue raised in the Gutenberg, where progress can be tracked: https://github.com/WordPress/gutenberg/issues/45553.

I'm going to close this issue now, but keep in mind it can be still commented on! 🙌 

PS. I'll respond in the internal convo as well.

**Closed as completed by kmanijak** 2023-03-15 14:03 UTC
Labels: type: bug, priority: high

**Comment by kmanijak** [comment] 2023-03-16 15:16
I forgot to add yesterday that if a merchant wants to list all the categories, then `Product Categories List` block does that

<img width="478" alt="image" src="https://user-images.githubusercontent.com/20098064/225662639-dd1794b1-eecb-4fd9-afa1-34b2fabfa10e.png">
