### ISSUE TITLE
Checkout Block not updating Subscription billing/shipping information upon renewal order (when new billing/shipping information is entered)

### ISSUE THREAD

**Issue by namiokuzono** [woocommerce/woocommerce-gutenberg-products-block#5457] opened 2021-12-24 19:05 UTC
## Describe the bug

When you create a renewal subscription order, share the link "Create a pending renewal order" with the Subscriber, then Subcriber enters new billing address (and/or shipping address), this information is not updated in the Subscription order. (Which should be, because all the renewal orders honor the Subscription order)
  
## To reproduce

Make sure the Checkout page has a Checkout block. 
Make sure to have WC SUB and SUB product.
Make sure to have a Subscriber to assign. 

1. Create an order with a subscription product (WooCommerce > Order > Create an order) - Make sure to add at least Billing address
2. Create a subscription (WooCommerce > Subscriptions > Add Subscription)
3. Select the order created in step 1 as a Parent Order
4. Once the Subscription is created, create a renewal order "Create a pending renewal order"
5. Copy "Custoer payment page" link
6. Log in as the Subscriber or use plugin such as User Switching - https://wordpress.org/plugins/user-switching/
7. On the Checkout page, enter a completely different billing address.
8. You will see this new billing address in the renewal order, but you will not see the new address in Subscription order
9. Try "Create a pending renewal order" again from the Subscription order
10. You will see the original Billng address, and not the new one entered

## Expected behavior

Newly entered billing/shipping address should override the information in the Subscription order. Below is WC Core Checkout behavior, which should also be expected in Checkout Block. 

Subscription Order with original billing address
![https://d.pr/i/IT5k1P](https://d.pr/i/IT5k1P+)
Image link: https://d.pr/i/IT5k1P

Create a renewal order, enter completely different billing address at the Checkout (` [woocommerce_checkout] `)
![https://d.pr/i/OHjnpm](https://d.pr/i/OHjnpm+)
Image link: https://d.pr/i/OHjnpm

**Subscription Order is now updated with the new billing address.** 
![https://d.pr/i/NB8sfz](https://d.pr/i/NB8sfz+)
Image link: https://d.pr/i/NB8sfz

**Comment by namiokuzono** [comment] 2021-12-24 19:11
4633346-zen

**Comment by ralucaStan** [comment] 2021-12-28 15:54
Thank you @namiokuzono for taking the time and reporting this. 
I was able to reproduce this. WC Subscriptions is an extension supported by the C&C Blocks. Looks like the issue is coming from the block's side.
I am moving this to Needs Leads Triage in order to help with deciding the priority/next steps.

**Comment by Stella3** [comment] 2021-12-30 01:40
It's more than just subscription renewals. I am seeing it with ALL logged in users. 

Their contact and address info is not being populated. 

Users are also saying their CC trans are then failing because they are not noticing that it is all blank and they aren't filling it in.  

All of our users are wholesale with accounts and they have to log in to buy.

**Closed as completed** 2022-08-03 23:44 UTC
Labels: type: bug
