### ISSUE TITLE
Improving the performance of the address form + push changes

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#9444] opened 2023-05-11 14:16 UTC
We've been running various experiments with the address forms to find the optimal solution for checkout in terms of usability, and to work well from a technical standpoint. These include:

- [[Experimental] Checkout Block Stepped Address Forms](https://github.com/woocommerce/woocommerce-blocks/pull/8839)
- [[Experimental] Show condensed version of the billing and shipping address after input](https://github.com/woocommerce/woocommerce-blocks/pull/8559)
- [[Experimental] Checkout Block Modal Address Forms](https://github.com/woocommerce/woocommerce-blocks/pull/8513)

[The original issue/idea was here.](https://github.com/woocommerce/woocommerce-blocks/issues/8426)

After some user testing, it is suggested that the majority prefer the address being visible and editable inline like in the current experience, while #8559 has merits for returning shoppers. #8839 is not completely ruled out yet, but it looks like #8513 will not happen.

If sticking with the current address forms is the options we are taking, there are some technical issues we will need to solve:

1. When filling out the checkout forms we "push changes" during the `onBlur` event, and debounced as the shopper types into a field. This causes a visible slowdown in the UI after you type each letter due to the processing happening behind the scenes.
2. The shipping address section is not "current" until the full address is provided, so we need to make sure its refreshed late enough to show correct rates, but early enough so that something is shown there since the form step is visible at all times.
3. Knowing when the user is finished editing the address would be useful, but without a button its a guess.

cc @ralucaStan

**Comment by ralucaStan** [comment] 2023-05-18 12:48
> Knowing when the user is finished editing the address would be useful, but without a button its a guess.

We could think of going around this limitation by _blocking_ access to the other checkout sections while the shopper is editing the core address fields. 

cc @pmcpinto  @elizaan36

**Comment by pmcpinto** [comment] 2023-05-22 10:33
Regarding the shipping address, would it make sense to explore pushing changes only when the shopper fills the last required field? What are the biggest risks?

**Comment by mikejolley** [comment] 2023-05-22 11:30
If you're typing in a field (lets say for arguments sake it is required) and then click from that field into the shipping methods, that click is blocked because the update/push is triggered unless we push as the user types, which makes typing lag and can cause unnecessary pushes. That is the problem here.

**Comment by pmcpinto** [comment] 2023-05-25 16:46
Thanks for the clarification. I took a quick look to see if Baymard has some suggestions on dealing with live inline form validation. It looks like their recommendation is aligned with what we have:

> For most field types, the validity may be checked once the user leaves the field (by binding to the onblur event of the field). Why not sooner? Because the site has no way to tell if or when the user has finished typing and considers their input “done” or “fully entered”. It’s therefore only safe for the site to conclude that the user considers their input “done” when they leave the field / proceed to the next element in the form.

> Yet, a high performing inline validation implementation requires close attention to details, due to the opposing logic for invoking and removing the live error messages:
> On one hand, avoiding premature validation typically means that the validity of each field input can only be checked when the user leaves the field (something 10% of site implementations fail to do).
Yet, once an error has occurred, the displayed error message must live-update on a keystroke level and disappear the moment the user reaches a potentially valid input. Especially for interdependent fields, like e-mail and password confirmation fields. (Another 10% of site implementations fail to do this.)

[Usability Testing of Inline Form Validation](https://baymard.com/blog/inline-form-validation)

Are there other alternatives that we should consider?

Btw, I'm very curious to see how Shopify solves this in their [new checkout](https://twitter.com/AlexSto199/status/1658712258795692032). I'm assuming their address lookup makes their job a bit easier 😄

**Comment by elizaan36** [comment] 2023-05-26 20:04
> I'm very curious to see how Shopify solves this in their [new checkout](https://twitter.com/AlexSto199/status/1658712258795692032). I'm assuming their address lookup makes their job a bit easier

I'm super curious to see this as well! I don't have it on my test site yet.

> that click is blocked because the update/push is triggered unless we push as the user types

@mikejolley I'm not able to reproduce this. Not saying it's not a problem but just trying to understand how the user gets to this scenario.

**Comment by mikejolley** [comment] 2023-05-30 09:43
@elizaan36 
![2023-05-30 10 41 28](https://github.com/woocommerce/woocommerce-blocks/assets/90977/0be570c4-5388-4211-9bb4-8ce7a60d5db8)

How quick you need to be depends on the debounce, but you can see here when there are already shipping methods, if you click before its pushed to server or before you click out of the input field, clicking a shipping checkbox is blocked by the update.

**Comment by pmcpinto** [comment] 2023-05-31 18:00
Thanks for sharing the gif. It's very useful. I wonder whether most users will notice this, especially on mobile, where the transition between typing in a field and moving to the shipping options should take longer. The internet connection speed can also impact this area.

> When filling out the checkout forms we "push changes" during the onBlur event, and debounced as the shopper types into a field. This causes a visible slowdown in the UI after you type each letter due to the processing happening behind the scenes.

I forgot to ask this in my previous comment: what's the reasoning behind applying this approach to fields such as the first name?

**Comment by tomxygen** [comment] 2023-05-31 18:18
Why not adding a “save” button as described in issue #8839 ?
I think that it could turn the shoppers into the mood of “i’m saving the shipping address for future orders, it’s not just one time transaction and i’ll never see this store again”.
Just like you can save your credit card for faster checkout

**Comment by mikejolley** [comment] 2023-06-01 08:33
@tomxygen I believe it was found that the extra step was undesirable. I prefer the button solution from a technical perspective. 

> I forgot to ask this in my previous comment: what's the reasoning behind applying this approach to fields such as the first name?

@pmcpinto I think its mainly so if you leave and come back, or refresh, any information you typed is preserved. There was a need to push fields like email also for some extensions that require that data early on.

**Comment by elizaan36** [comment] 2023-06-01 19:58
> clicking a shipping checkbox is blocked by the update.

I don't see a huge problem here from a usability perspective. Users will expect the shipping methods to refresh based on the address. Shopify checkout has similar behavior, where the method/amount loads after completing the shipping form or changing the selection. 
![Screen Recording 2023-06-01 at 02 56 32 PM](https://github.com/woocommerce/woocommerce-blocks/assets/5121465/5bb4d9bf-014b-4540-80a4-08f79dc46068)

**Comment by mikejolley** [comment] 2023-06-02 09:54
@elizaan36 The refresh is not the main problem. The problem is if you click the shipping option slightly before, or during the refresh, your selection is discarded after the refresh. I know there was a bug ticket for this in the past but I cannot find it--@opr @senadir do you remember?

The example you provide mitigates the issue by only showing the shipping option selection interface on click—if we collapsed shipping methods in the same way we'd be able to solve it that way as well. But right now the actual radio buttons are always visible.

**Comment by opr** [comment] 2023-06-05 12:52
@mikejolley is it https://github.com/woocommerce/woocommerce-blocks/issues/8423? Seems related and does kind of illustrate the same point, but not exactly what you're thinking of.

**Comment by pmcpinto** [comment] 2023-06-09 16:03
@mikejolley do you think it would help if the radio buttons were disabled while the user is typing the shipping address?

**Comment by mikejolley** [comment] 2023-06-12 10:44
@opr not the one I was thinking of but similar yes.

@pmcpinto yes that would prevent the issue. The shipping rates shown their may be stale.

**Comment by pmcpinto** [comment] 2023-06-12 17:38
> @pmcpinto yes that would prevent the issue. The shipping rates shown their may be stale.

@mikejolley thanks for the feedback. Can you record a brief video showcasing this approach? Just to confirm the flow/transition looks seamless.

**Comment by mikejolley** [comment] 2023-06-13 15:43
@pmcpinto Not totally straightforward as I need to add some way to track (and share) when fields are in a dirty/edited state. Can we set aside some time for this in the next cycle?

**Comment by pmcpinto** [comment] 2023-06-14 09:25
> Can we set aside some time for this in the next cycle?

Yes, to keep the momentum going. Thanks
cc @ralucaStan

**Comment by mikejolley** [comment] 2023-07-21 15:48
I have implemented a bunch of refactors, ending with this one: https://github.com/woocommerce/woocommerce-blocks/pull/10315

It looks as though the onBlur prevents the click of the shipping radio button now, so its not so bad. The click doesn't select shipping, but it does immediately refresh so to the user it doens't feel like the click was ignored. We could also block UI as done in this closed PR:

https://github.com/woocommerce/woocommerce-blocks/pull/10279

But Ill await the above PRs to be reviewed first and then decide if we need to take further action or not.

**Closed as completed** 2023-08-09 17:24 UTC
Labels: type: enhancement
