### ISSUE TITLE
Translation Errors since 6.2.0

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#5106] opened 2021-11-09 11:00 UTC
## Describe the bug
When you configure the checkout page it is displayed correctly in the editor in german. If you now leave the editor, the page is only displayed in English.

## To reproduce
Update to 6.2.0 

## Expected behavior
Correct Translation in Editor and on the normal page

## Screenshots
In Editor:

![1](https://user-images.githubusercontent.com/17782319/140912015-42c2d2d6-5573-4a98-96ca-0f83b5565b7d.PNG)

Onpage:

![2](https://user-images.githubusercontent.com/17782319/140912711-0c718654-51c9-4c21-827f-945b0ff5b428.PNG)

### WordPress (please complete the following information):

* Core version: 5.8.1
* WooCommerce version: 5.9.0
* WooCommerce Blocks version: 6.2.0
* Site language: German

### Desktop (please complete the following information):
* OS: Windows and Mac 
* Browser Chrome, Edge, Safari

### Smartphone (please complete the following information):
* Device: iPhone, iPad
* OS: IOS 15.1
* Browser Safari

## Additional context

https://wordpress.org/support/topic/translation-errors-10/#new-topic-0

**Comment by nielslange** [comment] 2021-11-09 11:51
Hello @DarianDev 👋 Thanks for reporting this problem. I noticed that this issue is a duplicate of #5005. I already started working on the other issue and the problem that you're facing seems to be related that some translation files are not lazy loaded on the frontend.

Please keep an eye on #5005 for a fix of this problem. And again, thanks for reporting this! 🙌

**Closed as completed by nielslange** 2021-11-09 11:51 UTC
Labels: type: bug, focus: i18n, block: checkout, type: duplicate

**Comment by nielslange** [comment] 2021-11-29 10:54
Hello @DarianDev 👋 The translation problem you reported had been resolved in the last release. If you update to the latest version of the WooCommerce Blocks plugin, both the cart and the checkout pages should appear in German.
