### ISSUE TITLE
Filtering by attributes is not accurate 

### ISSUE THREAD

**Issue by viscosho** [woocommerce/woocommerce-gutenberg-products-block#1911] opened 2020-03-09 18:48 UTC
**Describe the bug**
I added the Filter by Attribute block to my store, my store has more than 20 articles, they all have all kinds of tags to be filter by. I'm seeing two types of errors with this block:

- It sometimes repeats the filter attribute.
- It sometimes show the same count for all attributes (even when I'm sure there are more)

**To Reproduce**

1. Make sure that you have a variety of products on your store with different tags.
2. Create a page and add a filter by attributes block and a products block. 
3. Set the filter by block to filter by a specific attribute.

**Expected behavior**
The filters should reflect the exact number of items and they should not repeat.

**Screenshots**
- It sometimes show the same count for all attributes (even when I'm sure there are more)
<img width="422" alt="Screen Shot 2020-03-09 at 3 37 51 PM" src="https://user-images.githubusercontent.com/3129483/76246508-9d8b9b80-621c-11ea-8db8-2e881f6edaff.png">

- It sometimes repeats the filter attribute.
<img width="310" alt="Screen Shot 2020-03-09 at 3 36 48 PM" src="https://user-images.githubusercontent.com/3129483/76246510-9ebcc880-621c-11ea-82c2-0a05037ec7b4.png">

**WordPress (please complete the following information):**

* Core version: 5.0.3
* WooCommerce version: 3.9.3
* WooCommerce Blocks version: 2.5.14
* Site language: En
* Any other plugins installed:
- WooCommerce Admin
- WooCommerce Advanced Product Labels
- WooCommerce Cart Add-Ons
- WooCommerce Cart Notices
- WooCommerce Checkout Field Editor
- WooCommerce Cost of Goods
- WooCommerce Dynamic Pricing
- WooCommerce Memberships
- WooCommerce Product Bundles

**Additional context**
I have disabled all plugins but woocommerce and woocommerce blocks and tested but it still not working, also I have tested with the default wordpress theme.

**Comment by nerrad** [comment] 2020-03-16 13:17
Hi Virginia,

Thanks for your report, The Attribute filter block and All Products block blocks should only be working in an environment with WordPress 5.3+ (the blocks should not even be available for use in older WP environments).  You're reporting WordPress core 5.0.3. Can you double-check on that version please?

**Comment by nerrad** [comment] 2020-04-04 11:45
I'm going to close this issue because there hasn't been a response for over two weeks. If you come across this and are still able to reproduce (and have answers to my questions), leave a comment and we can reopen this issue if necessary.

**Closed by nerrad** 2020-04-04 11:45 UTC
