### ISSUE TITLE
Cart & Checkout

### ISSUE THREAD

**Issue by ekogarden** [woocommerce/woocommerce-gutenberg-products-block#6484] opened 2022-05-30 11:04 UTC
Hi , I´m happy to have the oppurtunity to give feedback to you ;)

I´m having problem with filling out "Land/region" and "delstat/län""state/county". Sweden is available but dissapears when I´m pushing the button för ordering. I get a message that I have to fill in my land/ region. It´s a loop. The same with state, there´s no options there and I get the same message to make a choice? I can´t publish my webshop because of this :/ The customers can´t make an order.

Most of all I would like to choose my fields manually. I´d just pick name, email adress and phonenumber, that´s all we need so collect from our customers for the moment.

**Comment by senadir** [comment] 2022-05-31 16:54
@opr Could this be related to the recent bug you're working on for Combobox?

@ekogarden what version are you currently running and can you test with an older version (7.4.x?)

**Comment by opr** [comment] 2022-05-31 17:05
@senadir I doubt it, but it's not impossible. The bug I looked into related to `pushChanges` sending the wrong country/state because it pushed the country code to the server for a country you didn't select (yet) and only seemed to only manifest when `cartExtensionUpdate` was fired.

@ekogarden thanks for the report! Can you confirm you are entering and selecting your country from the dropdown list?

Could you try typing `Sw` into the country box, then manually click `Sweden` from the list and confirm if the issue still happens if you do this?

**Comment by ekogarden** [comment] 2022-06-02 12:32
@opr I can choose Sverige but when I continue it disappears and I get a warning that I have to choose country.
I can´t choose State either

**Comment by ekogarden** [comment] 2022-06-02 12:35
@senadir I have version 6.0

**Comment by ekogarden** [comment] 2022-06-02 12:42
@senadir   How can I find my version? I don´t know where to look? :/

**Comment by senadir** [comment] 2022-06-02 13:15
You can follow this guide and paste the result here
https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/

**Comment by tarunvijwani** [comment] 2022-07-08 12:53
@ekogarden  I’m going to close this because there still isn’t anything actionable for us on this issue. I'm able to select Sweden country and place an order.  If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2022-07-08 12:53 UTC
Labels: block: checkout
