### ISSUE TITLE
Minicart content not visible.

### ISSUE THREAD

**Issue by grogou** [woocommerce/woocommerce-gutenberg-products-block#5567] opened 2022-01-14 14:27 UTC
Minicart content not visible.

WooCommerce, WooCommerce Blocks and Gutenberg plugins versions are latest and the only active plugins.

![image](https://user-images.githubusercontent.com/10712881/149531051-e491a7c9-6202-446e-88ea-3e39151a7af5.png)

**Comment by Aljullu** [comment] 2022-01-14 15:59
@grogou thanks for reporting the issue. A couple of questions:

* Could you explicitly indicate the versions of WC, WC Blocks, WP and Gutenberg? I know you said they were the latest but given how fast the environment is moving I would like to make sure we test it on the correct ones (ie: are you using WC 6.1 which was released this week? WP 5.8.3 or 5.9 RC4? WC Blocks from .org or `trunk` from the repo?)
* Can you check if you get any errors in the console?
* It would also be helpful if you could share with us which theme you are using.

Thanks in advance!

**Comment by grogou** [comment] 2022-01-14 16:11
Yes sure.
The Wordpress version is 5.8.3, Gutenberg - 12.3.2 , Woocommerce - 6.1.0 and Woocommerce blocks - 6.8.0-dev ( from trunk ).
The theme is TT1 blocks - 0.4.8

Nothing in console or debug.log

**Comment by nielslange** [comment] 2022-01-17 05:45
Hello @grogou,

I'm unable to reproduce the problem you reported on my end when using a fresh Local WP installation using

- WordPress 5.8.3
- Gutenberg 12.3.2
- WooCommerce 6.1.0
- WooCommerce Blocks 6.8.0-dev
- TT1 Blocks 0.4.8

The following screen recording shows what I see on my end: https://d.pr/i/k34grI

Can you tell me how you set up your WordPress site, e.g. using Local WP, Docker, Vagrant, etc. and which browser you are using? And would you mind trying to create a fresh installation to see if you're still able to reproduce this problem?

**Comment by grogou** [comment] 2022-01-17 08:51
Hi @nielslange thank you for your feedback.

The screen record not working `Content length exceeded`.

I am using Docker with wordpress fresh install. 

The plugins list 
![image](https://user-images.githubusercontent.com/10712881/149736842-a23f5008-3f57-43b9-9159-5437eb2ab737.png)

and the theme.
![image](https://user-images.githubusercontent.com/10712881/149736898-7d7559a5-867a-42fd-8d51-3242f21c891f.png)


The browsers Chrome and Firefox, same issue on both.

The composer and node version when builded woocommerce blocks plugin is `Composer 2 with php8-cli`, `Node - 16.13.2` and `npm - 8.1.2`

The problem is same.
![image](https://user-images.githubusercontent.com/10712881/149737448-ddc5618e-cade-4eb6-87ed-83e84e12b389.png)

And the console output is
![image](https://user-images.githubusercontent.com/10712881/149737592-5f19d18b-91fd-423d-85ba-2055a993de28.png)

**Comment by grogou** [comment] 2022-01-17 08:52
After add to cart I get this console output `Cookie “woocommerce_cart_hash” has “SameSite” policy set to “Lax” because it is missing a “SameSite” attribute, and “SameSite=Lax” is the default value for this attribute.`

**Comment by grogou** [comment] 2022-01-17 09:14
And mini cart template part output in FSE editor
![image](https://user-images.githubusercontent.com/10712881/149741179-05e5bd76-c642-4bbf-bcfc-b448c13c97bf.png)

**Comment by nielslange** [comment] 2022-01-17 13:20
@grogou Thanks for the additional context.

@dinhtungdu Would you be able to look into this report?

**Comment by dinhtungdu** [comment] 2022-01-19 07:26
@grogou Thanks for the info! You got this error because your node environment is set to `production` instead of `development`. I guess your `blocks.ini` file at the root directory of this plugin would look like this:

```
woocommerce_blocks_phase = 3
woocommerce_blocks_env = production
```

To solve this you can:
- change the env in `blocks.ini` from `production` to `development`.
- Or add this constant to `wp-config.php`: `define( 'WC_BLOCKS_IS_FEATURE_PLUGIN', true );`

The `blocks.ini` is generated at the first time you run `npm start` or `npm run build`, the `woocommerce_blocks_env` is set using the value of `NODE_ENV`, which, in this case, was `production`.

**Comment by nielslange** [comment] 2022-01-19 10:11
Thanks for clarifying this, @dinhtungdu. 🙌

**Comment by grogou** [comment] 2022-01-19 10:30
@nielslange @dinhtungdu thank you very much, you best)

**Comment by dinhtungdu** [comment] 2022-01-19 13:36
@grogou I'm closing this issue. If you have other issues, feel free to reopen this or create new ones.

**Closed as completed by dinhtungdu** 2022-01-19 13:36 UTC
Labels: type: bug, block: mini-cart

**Comment by dinhtungdu** [comment] 2022-01-28 13:53
Correction:

The `woocommerce_block_env` will be set to production if we run `npm run build`. It's set to development again after running `npm start` or `npm run dev`.

**Comment by grogou** [comment] 2022-01-29 10:36
@dinhtungdu Yes I already check that from package,json. Thank you.
