### ISSUE TITLE
VAT number field

### ISSUE THREAD

**Issue by IsraPaya** [woocommerce/woocommerce-gutenberg-products-block#3499] opened 2020-12-02 16:34 UTC
It woudl be great that you add a VAT number field in the checkout form in WooCommerce Blocks.

**Comment by nerrad** [comment] 2020-12-02 20:40
Hi there @IsraPaya 

Thanks for taking the time to leave this request. This is a duplicate of #3096 so I'm going to close this in favor of the other issue.

**Closed as completed by nerrad** 2020-12-02 20:40 UTC
Labels: type: duplicate
