### ISSUE TITLE
Apple Pay missing phone number

### ISSUE THREAD

**Issue by raikkonen211** [woocommerce/woocommerce-gutenberg-products-block#7052] opened 2022-09-05 09:48 UTC
Thank you for an amazing plugin!
I have one little problem with Apple Pay integration. Everything works fine expect that it missing phone number to all orders.
Both of them (billing and shipping) address is require a phone number
Please check the screenshot :

https://prnt.sc/VF-ZyTgCkv4v

Kind Regards

**Comment by nielslange** [comment] 2022-09-06 05:51
Hello @raikkonen211,

Thanks for reaching out. Please note that the WooCommerce Blocks extension does not have an Apple Pay integration. May I ask how you have added Apple Pay to your site? Are you using the [WooCommerce Payments](https://wordpress.org/plugins/woocommerce-payments/) or the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) extension?

If so, I suggest that you contact the corresponding team directly. If you're unsure which extension you're using, I'm happy to assist you in finding that out. In that case, it will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment.

**Comment by tarunvijwani** [comment] 2022-09-30 11:41
@raikkonen211 I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue, and if we’re able to reproduce them, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2022-09-30 11:41 UTC
Labels: type: bug
