### ISSUE TITLE
Storefront child theme issue #3: Bugs/ glitches

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#3831] opened 2021-02-11 15:31 UTC
**I made a comprehensive analysis and tested all the themes listed in the [Storefront Themes ](https://woocommerce.com/product-category/themes/storefront-child-theme-themes/?categories=Themes&collections=theme&page=1&orderby=date) in WooCommerce website.**

You can check the [Issues map I've created in Figma](https://www.figma.com/file/vm7kZzr5uIFwacpKKZzMb5/Storefront-child-themes?node-id=1%3A142), where you will find all the issues divided by theme.

You will find in GitHub different issues where I grouped similar/ same problems and created different issues for each problem group.

__________________________________________________________________________________________________________

# Issue
There are some bugs when hovering over some elements.

# Arcade
(Child theme)
## 1. In the cart page, the cart preview on the header appears only when hovering over it.

![Arcade : Cart hover](https://user-images.githubusercontent.com/69914963/107657250-c35ac500-6c63-11eb-8de3-6f561947cc6e.gif)

# Artisan
## 1. There are some bugs in the checkout page when hovering over different elements.
![Artisan](https://user-images.githubusercontent.com/69914963/107657696-277d8900-6c64-11eb-8f2d-4265f2df60bb.gif)

# Boutique
(Child theme)
## 1. The cart preview of the header is not loading correctly.
![Frame 196](https://user-images.githubusercontent.com/69914963/107659101-8db6db80-6c65-11eb-8b30-b9c12eb654e4.png)

# Galleria
(Child theme)
## 1. There are some bugs in the cart page when hovering over different elements.

![Screen-Recording-2021-02-10-at-1](https://user-images.githubusercontent.com/69914963/107657632-1765a980-6c64-11eb-8b0e-8e5b3330513d.gif)

# Homestore
(Child theme)
## 1. Quantity input overflows the field.
![Frame 103](https://user-images.githubusercontent.com/69914963/107661440-0ae35000-6c68-11eb-8f19-4008dfa5dc68.png)

# Pharmacy
(Child theme)
## 1. There is a bug in the checkout page.

![Frame 128](https://user-images.githubusercontent.com/69914963/107658038-83481200-6c64-11eb-985e-b054cdb9dbd7.png)

# Block shop
(Child theme)
## 1. There is a bug in the payment method section.

![Frame 213](https://user-images.githubusercontent.com/69914963/107658330-c86c4400-6c64-11eb-8874-3a3aaf1ea459.png)

# Fifth avenue
## 1. There is a bug in the cart widget
![Frame 174](https://user-images.githubusercontent.com/69914963/107658419-dfab3180-6c64-11eb-92ff-1f2877cb773e.png)

**Comment by nerrad** [comment] 2021-02-12 19:25
@Aljullu I'm looking over all these reported issues and it looks to me like they all should be fixed in the respective theme repositories. Thoughts? Agree/disagree? If yes, I'll take care of checking I can reproduce and will create the issues in the respective repos (if needed).

**Comment by Aljullu** [comment] 2021-02-15 15:38
> @Aljullu I'm looking over all these reported issues and it looks to me like they all should be fixed in the respective theme repositories. Thoughts? Agree/disagree? If yes, I'll take care of checking I can reproduce and will create the issues in the respective repos (if needed).

Agree, all issues listed here are specific style conflicts on each theme and I think the best is to fix them individually in each theme code base.

**Comment by nerrad** [comment] 2021-02-22 17:03
I moved this report into individual issues (in progress):

### Artisan

This isn't a Storefront Child Theme. @Spacepol can you please file a report with the owner of Artisan?

### Galleria

- Fix styling issues for hover state on section container toggles in cart and checkout blocks. (105-gh-woocommerce/galleria)

### Homestore

- Fix overflow issues with quantity input in cart and checkout blocks. (90-gh-woocommerce/homestore)

### Pharmacy

This issue wouldn't be caused by the theme. It's unclear what the cause would be so I'm going to leave for now. 

### Block Shop

This is not a Storefront child theme. @Spacepol  can you please file a report with the owner of Block Shop.

### Fifth Avenue 

This is not a Storefront child theme. @Spacepol  can you please file a report with the owner of Fifth Avenue.

**Closed as completed** 2021-02-22 19:17 UTC
Labels: type: bug
