### ISSUE TITLE
I get this error when I want to pay by credit card. From where?

### ISSUE THREAD

**Issue by theironnn** [woocommerce/woocommerce-gutenberg-products-block#9805] opened 2023-06-13 09:35 UTC
The following extension is not compatible with block-based payment. Learn more(opens in new tab)
PayTR Sanal POS WooCommerce - iFrame API

I get this error when I want to pay by credit card. From where?
![blok hatası](https://github.com/woocommerce/woocommerce-blocks/assets/136445962/4af6a68e-9701-479a-b8f6-5dc1a82a8e05)

**Comment by kmanijak** [comment] 2023-06-13 10:06
Hi @theironnn,

Could you provide us with steps to reproduce that issue?

**Comment by ralucaStan** [comment] 2023-06-14 10:25
Thank you for reaching out.
@theironnn that is not an error, it's a warning that the PayTR Sanal POS WooCommerce - iFrame API extension is not compatible with the Cart and Checkout blocks. 
You can read more about it here https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-10

**Comment by tarunvijwani** [comment] 2023-07-07 12:48
@theironnn I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2023-07-07 12:48 UTC
Labels: block: cart, block: checkout, type: community contribution
