### ISSUE TITLE
Auto-filling checkout not work properly

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#6544] opened 2022-06-09 15:13 UTC
I lost another customer today because of this problem.

I use hotjar to capture visitors' screenshots when they come to the website and their behavior, to improve the website.

The user came with iOS 15.4.1, Phone (320 x 482)

The user clicked to fill in the form automatically and all the fields were filled in, but the postcode (ZIP) field throws out the error that it is empty. The user saw that the field was filled in and was confused and left the checkout.

When I checked WooCommerce > Orders > Drafts, I saw that all fields were recorded except the zip code field.

**Comment by msroky** [comment] 2022-06-09 18:31
Also, the user saw a standard message from WooCommerce, not from your plugin.

**Comment by alexflorisca** [comment] 2022-06-10 10:00
Hi @msroky, thanks for reporting this, we'll have a look into what's going wrong. It would help us tow know a few things first.

1. Do you know what the error message you got from WooCommerce was? 
2. Was the error inline (next to the input) or at the top of the page?
3. What is your website url?

Also just want to clarify that the zip code input was filled in correctly via autofill, but when clicking Place Order it gave an error?

**Comment by tarunvijwani** [comment] 2022-07-08 08:58
@msroky I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce them, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2022-07-08 08:58 UTC
Labels: type: bug, block: checkout
