### ISSUE TITLE
__experimentalRegisterCheckoutFilters  not firing during initial loading of the cart

### ISSUE THREAD

**Issue by rajeshsingh520** [woocommerce/woocommerce-gutenberg-products-block#4544] opened 2021-08-04 11:13 UTC
Filter function is not working when the cart is initially loaded from the inline json data

1) Add the below code in your site (say in theme footer.php)
2) Go to product page add the product to the cart 
3) Go to the cart page (block cart) you will not see the "Test data" added next to the product name 
4) Increase the quantity and now the product will make ajax call for item data and now the "Test data" will be added next to the item name 

(when ever you will refresh the cart page the filter function will not work)

See the test video https://youtu.be/hggKGImpkdw

```
<script>

const appendTextToPriceInCart = ( value, extensions, args ) => {
	if(extensions.pisol_edd != undefined && extensions.pisol_edd.estimate_date != null){
		return value+' '+'Test data';
	}
	return value;
};

const { __experimentalRegisterCheckoutFilters } = window.wc.blocksCheckout;
__experimentalRegisterCheckoutFilters( 'pisol_edd', {
  itemName: appendTextToPriceInCart
} );

</script>
```

**Comment by senadir** [comment] 2021-08-09 10:36
Hey there @rajeshsingh520 
I'm not able to reproduce this issue locally.
This is the code I used (since I don't have pisol_edd installed, I removed the check).
```
const appendTextToPriceInCart = ( value, extensions, args ) => {
	return value + ' ' + 'Test data';
};

const { __experimentalRegisterCheckoutFilters } = window.wc.blocksCheckout;
__experimentalRegisterCheckoutFilters( 'pisol_edd', {
	itemName: appendTextToPriceInCart,
} );
```

I added the JS code to a footer file and it worked, I also added in a JS file and enqueued that file properly and it worked as well.

https://user-images.githubusercontent.com/6165348/128693787-9f96e43c-6b2a-44a3-be29-b792079e1ac1.mov

There could be a possible conflict here or some other issue. Try disabling plugins one by one until it works.

Can you check for console errors? can you do a `console.log( extensions.pisol_edd )` before the `if` condition in `appendTextToPriceInCart`?

**Comment by rajeshsingh520** [comment] 2021-08-09 11:27
Hi,

Thanks for checking this out, but we still have the issue even with all the plugin inactive and we have removed the conditional tag as well still it do not work on refresh of the page,

here is the new test video with TwentyTwentyOne theme 

https://youtu.be/ECmxbcoXHow

**Comment by Aljullu** [comment] 2021-08-10 10:51
Hi @rajeshsingh520! You will need to make sure your code is run after the script with id `wc-blocks-checkout-js` but before the script with id `wc-cart-block-frontend-js`.

A small explanation:
* `wc-blocks-checkout-js` adds the `window.wc.blocksCheckout` constant that you can use to register the filters.
* `wc-cart-block-frontend-js` renders the Cart block.

Your script, where you register the filters, must run between both of them. In general, you should be able to accomplish this by registering your script with [`wp_register_script()`](https://developer.wordpress.org/reference/functions/wp_register_script/) and adding `wc-blocks-checkout` to the list of dependencies.

In order to test it with real code, you can use the snippet below:

```diff
- wp_register_script( 'test-script', '', array(), '1.0', true );
+ wp_register_script( 'test-script', '', array( 'wc-blocks-checkout' ), '1.0', true );
  wp_enqueue_script( 'test-script' );
  wp_add_inline_script(
	'test-script',
	"const { __experimentalRegisterCheckoutFilters } = window.wc.blocksCheckout;
	__experimentalRegisterCheckoutFilters( 'test_filter', {
		itemName: val => val + ' Test data'
	} );"
  );
```

When no dependencies are registered (`array()`) the filter is only applied in new re-renders. When the dependency is registered (`array( 'wc-blocks-checkout' )`), you will notice the filter is applied from the first render.

Also, make sure your script is not run on `window.load` or something similar. In that case, the block will have already been rendered before your filter is added.

Hope that helps!

**Comment by rajeshsingh520** [comment] 2021-08-10 10:56
thanks this worked

**Comment by rajeshsingh520** [comment] 2021-08-10 11:00
Hi @Aljullu 

I am having one more question I was looking for a similar filter function that can change the shipping method name 

but in the documentation I could not find the filter function for the shipping method name 

https://i.imgur.com/YIEarGz.png

**Comment by rajeshsingh520** [comment] 2021-08-10 11:01
![download (18)](https://user-images.githubusercontent.com/2164574/128855634-0a0602a8-5313-49a5-ae3a-7ead51bb70b4.png)

**Comment by rajeshsingh520** [comment] 2021-08-10 11:03
Hi @Aljullu

I am having one more question I was looking for a similar filter function that can change the shipping method name

but in the documentation I could not find the filter function for the shipping method name

![screenshot-localhost-2021 08 10-16_32_12](https://user-images.githubusercontent.com/2164574/128855894-aee7b1b0-f637-4925-9ebf-796a8c32eda4.png)

**Comment by Aljullu** [comment] 2021-08-10 13:09
In order to change shipping rate labels, you can use the existing PHP filters from WooCommerce. In this case, [`woocommerce_shipping_rate_label`](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-shipping-rate.html#source-view.200) would work. Ie:

```PHP
function change_shipping_labels( $name ) {
	return $name . ' Test';
}
add_filter( 'woocommerce_shipping_rate_label', 'change_shipping_labels' );
```

Hope that helps as well! I will proceed closing this issue now that the main question has been solved. If you have further questions, you can open a new issue or create a [thread in the Support Forum](https://wordpress.org/support/plugin/woo-gutenberg-products-block/). :slightly_smiling_face:

**Closed as completed by Aljullu** 2021-08-10 13:09 UTC
Labels: type: bug, category: extensibility
