### ISSUE TITLE
Create an account checkbox not working as expected in Checkout block

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gutenberg-products-block#6249] opened 2022-04-13 18:25 UTC
## Describe the bug

1. `Create an account` checkbox doesn't work on the Checkout block page. 
2. `Create an account` checkbox doesn't appear on the Checkout block page until the `Allow customers to place orders without an account` option is enabled in WooCommerce > Settings > Accounts & Privacy. 

## To reproduce

1. Go to WooCommerce > Settings > Accounts & Privacy. 
2. Disable the `Allow customers to place orders without an account` option. 
3. Enable `Allow customers to log into an existing account during checkout`. 
4. Go to checkout block page editor. 
5. Select the email inner block and enable `Allow shoppers to sign up for a user account during checkout`
6. Log out
7. Visit the store as a logged out user
8. Add a product to the cart
9. Go to checkout block page
10. Notice `Create an account` checkbox is not visible. 
11. Place an order with a random email. 
12. Notice the order is getting placed and a new user is created under wp-admin → Users with that random email address. 
13. Go to WooCommerce > Settings > Accounts & Privacy. 
14. Enable the `Allow customers to place orders without an account` option. 
15. Go to checkout block page again as a logged out user. 
16. Notice `Create an account` checkbox is now visible.
17. Place an order with a random email with `Create an account` checked. 
18. Notice the order is getting placed but a new user is not created under wp-admin → Users. 

## Expected behavior

1. `Create an account`  option should appear all the time irrespective of `Allow customers to place orders without an account` option is disabled or enabled. 
2. When the `Create an account` option is checked, it should create a new account when the order is placed.

### WordPress (please complete the following information):

-   Core version: 5.9
-   WooCommerce version:  6.3
-   WooCommerce Blocks version: 7.3
-   Site language: English

**Comment by senadir** [comment] 2022-04-15 14:40
Thank you Tarun for filling this issue.

> Create an account option should appear all the time irrespective of Allow customers to place orders without an account option is disabled or enabled.

The checkbox is only visible when you have the option to create or not. In the case you're describing, shopper must have an account to checkout, so they can't opt out of creating an account, hence why it's not shown. It's a frustrating experience indeed, but it's not a bug.

> When the Create an account option is checked, it should create a new account when the order is placed.

I'm not able to reproduce that, can you please check again?

**Comment by tarunvijwani** [comment] 2022-04-17 13:39
Thank you @senadir for checking it! 

>When the Create an account option is checked, it should create a new account when the order is placed.

I'm also couldn't reproduce this now. Maybe Niels and I got confused and missed any step when testing it or it might got fixed in the latest version. 


>The checkbox is only visible when you have the option to create or not. In the case you're describing, shopper must have an account to checkout, so they can't opt out of creating an account, hence why it's not shown. It's a frustrating experience indeed, but it's not a bug.

If shopper is not logged in and `Allow customers to place orders without an account` option is also `disabled` then it won't show the checkbox to create an account. 

Screen recording: 

https://user-images.githubusercontent.com/11503784/163716745-e1eeb252-10d0-48d6-b702-9b3d1d4f7b66.mov

**Comment by ralucaStan** [comment] 2022-11-14 13:47
@tarunvijwani I will close this ticket and split it into two other tickets. Thank you for taking the time to report this flow that definitely needs improvement

> Create an account option should appear all the time irrespective of Allow customers to place orders without an account option is disabled or enabled.
- woocommerce/woocommerce-blocks#7662 

> When the Create an account option is checked, it should create a new account when the order is placed.

- woocommerce/woocommerce#42529

**Closed as completed by ralucaStan** 2022-11-14 13:47 UTC
Labels: type: bug, focus: blocks, block: checkout
