### ISSUE TITLE
Checkout: Not clear what payment option this was in Express Payments section

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2309] opened 2020-04-27 11:50 UTC
**Describe the bug**
When I tried to checkout using an US shipping address I got an express payment option in the express payments section - it was not clear though what payment option it was, so I was hesistant to try it out. I did none the less. Ideally the button would be clearer as to what payment option you are using - i.e. Apple Pay, Google Pay etc.

**To Reproduce**
Use a US address for shipping - observe what payment options appear in the Express Payments section.

**Expected behavior**
The button would be clearer as to what payment option I was going to be using to create confidence and hence actually use it.

**Screenshots**
<img width="710" alt="Screenshot 2020-04-27 at 11 07 17" src="https://user-images.githubusercontent.com/10805911/80369065-93cdfe00-8885-11ea-92ef-46a38e3f2829.png">

**Comment by nerrad** [comment] 2020-04-28 17:48
This may be something to bring up with the payment method teams. We're just using what is provided by **Stripe** for the payment request button and this is apparently the specific style for the chrome browser payment request api:

<img width="1172" alt="Image 2020-04-28 at 1 38 28 PM" src="https://user-images.githubusercontent.com/1429108/80519250-ae6fa800-8955-11ea-8bab-0b877e2dd29f.png">

If you go to the [stripe documentation for the payment request button](https://stripe.com/docs/stripe-js/elements/payment-request-button) you'll see the same thing show up (as in my screenshot). Also if you go to the current cart shortcode page, you'll see the same button (except it is labelled as Buy now there by default):

<img width="631" alt="Image 2020-04-28 at 1 41 34 PM" src="https://user-images.githubusercontent.com/1429108/80519500-14f4c600-8956-11ea-8798-e39763ed2c67.png">

So I'm going to close this as a won't fix because it appears to me this is expected behaviour for this type of payment method that follows a standardized style for this kind of button (which I'm supposing creates buyer trust when they see that type of button?)

There are some _limited_ styling options provided via the stripe api for the button (the following screenshot is from the stripe settings in the woo admin):

<img width="798" alt="Image 2020-04-28 at 1 45 58 PM" src="https://user-images.githubusercontent.com/1429108/80519872-a6fcce80-8956-11ea-922a-aa041bb931f4.png">

And here's how the button looks with the above selection:

<img width="712" alt="Image 2020-04-28 at 1 45 20 PM" src="https://user-images.githubusercontent.com/1429108/80519898-b24ffa00-8956-11ea-9aef-c9a867dc61c4.png">

Again, this is all something [in the control of **Stripe**](https://stripe.com/docs/stripe-js/elements/payment-request-button#react-styling-the-element) and is pretty specific to guidelines they use for this button (which is specific to the browser).

I'm going to close this but feel free to reopen if you think it warrants more discussion (or maybe we should peg this as an issue the payment teams would take up)?

**Closed by nerrad** 2020-04-28 17:48 UTC
