### ISSUE TITLE
[Tracking issue] Implement Woo FSE specific commands in the Command Palette

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#11521] opened 2023-10-31 12:00 UTC
WordPress 6.4 improves the [Command Palette API](https://href.li/?https://make.wordpress.org/core/2023/07/17/introducing-the-wordpress-command-palette-api/), so it's time to start thinking how we can leverage that to implement some commands that would be useful to merchants.

We have brainstormed a bit during our Sevilla meetup: per0F9-18J-p2.

Obviously, many WooCommerce-specific commands, should probably go in Woo Core. Some others mentioned there, perhaps directly into Gutenberg core. This issue will serve as a tracking issue for those commands.

**Comment by Aljullu** [comment] 2023-11-09 12:19
Do we know who is going to make the decision of what commands to implement? Is it something that will be provided to us by design/product? Or we (engineers) should build the list? I read the P2 post, but it looks like there isn't a "final" list yet.

**Comment by sunyatasattva** [comment] 2023-11-13 09:58
@Aljullu Yes, definitely there is no list currently. As for the decision, I think we can come up with a list as engineers and propose it to design/product, what do you think?

**Comment by Aljullu** [comment] 2023-11-13 13:29
Sounds good, thanks! I will assign this issue to me, then. I will first investigate how to add at least one basic command so we have the infrastructure in place, and after that we can work out what are the best commands to create. The good thing is that we can iterate on this without the risk of breaking backwards compatibility.

**Comment by Aljullu** [comment] 2023-11-13 14:42
> I will first investigate how to add at least one basic command so we have the infrastructure in place,

Oh, never mind. I see @nerrad already did that some time ago: https://github.com/woocommerce/woocommerce/pull/39268. :slightly_smiling_face:

**Comment by Aljullu** [comment] 2023-11-13 14:46
> we can work out what are the best commands to create

I have been taking a look at commands included in Gutenberg and some commands proposed for WooCommerce and here it goes my proposal (disclaimer: many items have been copied from per0F9-18J-p2):

### Static commands

* _Add new product_
* _Products_: same as the one in [Darren's PR](https://github.com/woocommerce/woocommerce/pull/39268/files#diff-fd7985999b0863cc13353fec5b938de0fbf6ffe07d34b0a7b7046fedfd128109R12), but renaming it to _Products_ to match _Pages_ and _Single Posts_ commands.
  * We could consider making this contribution upstream in Gutenberg, so any Custom Post Types appear automatically in the command line.
* [settings_title]: searching for a Settings tab name or section name, should redirect to that page/section. Ie: Store Address, Shipping, Payments, etc.
* [analytics_title]: searching for an Analytics page name, should redirect to it. Maybe in the command label we should suffix "Analytics" or "Stats". Ie: Revenue Analytics, Order Analytics, etc.

### Dynamic commands

* [product]: searching for a product name should redirect to the product edit page. Ie: Hoodie.
* [product] Analytics: searching for a product should also offer seeing its analytics page. Ie: Hoodie Analytics.
* [product_variation] + [product_variation] Analytics: same as before but with product variation names.
* [product_cat] + [product_cat] Analytics: same as before but with product categories.
* [product_tag]: same as before but with product tags.
* [product_attribute]: same as before but with product attributes.
* [order_id]: searching for an order ID should redirect to the order page.
* [coupon_code]: searching for a coupon code should redirect to the coupon edit page.
* [coupon_code] Analytics: searching for a coupon code should also offer seeing its analytics page.

Some commands I didn't include (and the reason why):

* _Link to WooCommerce System status (potentially including copying SSR to clipboard)_: I'm not sure about this one, but I see that WordPress doesn't include any commands related to the Site Health report.
* _Documentation shortcuts_: similarly, I think Gutenberg isn't currently doing that, so I would mimic them on that field.
* _View Store_/_Cart_/_Checkout_: same here. WP doesn't have commands redirecting to the frontend (ie: Homepage), so probably WooCommerce shouldn't add them either.
* _Share feedback links_: I think this item is not used that much to deserve a command entry.
* _Save edit_, _Create Synced Pattern_, _Clear template customizations_ and _Open Stylebook_: IMO these features belongs to Gutenberg, not WooCommerce.

Note: I missed some in-person discussions about this, so I'm possibly lacking some context. Feel free to disregard any suggestion if it has already been discussed. :slightly_smiling_face: 

Btw, I intentionally skipped any commands related to the new Product Editor for now.

**Comment by sunyatasattva** [comment] 2023-11-15 07:06
My question here is that it seems most of those should live in Core. Of course, with the merging to the monorepo, this distinction is blurred. So, as the next steps, I wonder:

1. Maybe let's open a GitHub discussion with your proposal on the monorepo?
2. Can we find any “block-specific” commands that would make sense?

**Comment by Aljullu** [comment] 2023-11-15 14:50
> Maybe let's open a GitHub discussion with your proposal on the monorepo?

Good idea. I started the discussion here: https://github.com/woocommerce/woocommerce/discussions/41472.

> Can we find any “block-specific” commands that would make sense?

From what I saw, Gutenberg doesn't have block-specific commands. There are some commands which are only available when a block is selected (transforms, group/ungroup, etc.), but they don't seem to be block-dependent. For now, I would not add any WC block-specific commands if Gutenberg hasn't done it yet, so we stay aligned with them. What do you think?

**Comment by sunyatasattva** [comment] 2023-11-16 07:07
Sorry, I meant “Blocks-specific” commands, as in: specific to WooCommerce Blocks or the FSE flow, more than WooCommerce Core.

**Comment by Aljullu** [comment] 2023-11-16 14:52
> Sorry, I meant “Blocks-specific” commands, as in: specific to WooCommerce Blocks or the FSE flow, more than WooCommerce Core.

Oh, it makes sense! Honestly, I couldn't think of any specific command related to WooCommerce Blocks which is not included in https://github.com/woocommerce/woocommerce/discussions/41472.

**Closed as completed** 2023-11-28 11:26 UTC
Labels: type: enhancement, focus: FSE
