### ISSUE TITLE
Products blocks display hidden products

### ISSUE THREAD

**Issue by Magganpice** [woocommerce/woocommerce-gutenberg-products-block#2823] opened 2020-07-07 12:56 UTC
The product blocks also show hidden products. Any product can be set to "hidden from shop" and/or "hidden from search". These products shouldn't be shown in any "product block".

1. set product to "hidden"
2. it still shows up in the block

**Expected behavior**
Hidden products should be hidden.

**WordPress:**

* Core version: 5.4.2
* WooCommerce version: 4.2.2
* WooCommerce Blocks version: 2.9.0
* Site language: German

**Comment by nerrad** [comment] 2020-07-07 13:26
Hi there 👋,

Thanks for taking the time to report this bug, we really appreciate your help. This is clearly an issue that needs resolved and we'll likely start working on it soon.

**Comment by Magganpice** [comment] 2020-07-31 09:06
Noticed that this bug is still there and it makes those product blocks not very usable since they display wrong products.

Is a fix planned? Probably isn't a big thing to fix.

**Comment by Magganpice** [comment] 2020-10-01 14:36
Anyone looking into this? Makes the products blocks unusable because they are full of out of stock products.

**Comment by Magganpice** [comment] 2021-03-21 16:44
This issue is still there.

**Comment by nerrad** [comment] 2021-05-26 18:39
This is still in our backlog as something for our team to eventually pick up and look at. We haven't done any work on this yet because of other prioritized work. 

While the proposed solution _does_ make sense, there is potential here for this to be a block level setting that _defaults_ to what is set at the global settings level. There is still some thought we have to give to the relationship between global store level settings as they apply to existing archive pages in WooCommerce and how they apply to product grid blocks where some merchants might want to override the global settings per block instance. The actual technical implementation might be fairly trivial once the UX considerations and decisions are made but that's something we're not able to devote the time to resolving for now.

**Comment by Magganpice** [comment] 2021-07-27 10:47
I give up. Seems not to be understood that the blocks display wrong products.

**Comment by tomasztunik** [comment] 2022-02-02 11:05
Investigating this issue and can confirm it must have been fixed sometime along the way.

Steps I'm taking to reproduce:
- using latest Woo (6.2) and WordPress (5.9), having Twenty Twenty-Two theme.
- In product catalog visibility settings I've set product visibility to hidden
- In product catalog visibility settings I've set another product inventory to out of stock
- I've set to hide out of stock items in the settings

Block | Catalog visibility hidden | hidden out of stock
-- | -- | --
**core**
WooCommerce Product Grid Block | ✔️  | ✔️ 
WooCommerce Product Taxonomy Block | ✔️  | ✔️ 
**products blocks**
All Products | ✔️  | ✔️ 
Products by Category | ✔️  | ✔️ 
Products by Attribute | ✔️  | ✔️ 
Best Selling Products | ✔️  | ✔️ 
Top Rated Products | ✔️  | ✔️ 
On-sale Products | ✔️  | ✔️ 
Product Search | ✔️  | ✔️ 


Related issue but unrelated to blocks: 
- [wocommerce/28693](https://github.com/woocommerce/woocommerce/issues/28693) Hidden products are not hidden from native WordPress search, but they are hidden from product search.

**Closed by tomasztunik** 2022-02-02 11:05 UTC
Labels: type: bug, 🔹 block-type: product
