### ISSUE TITLE
[WC 3.9 beta.2]: Filter by Attribute Block: The attributes filter checkboxes don’t show a focus outline in Firefox

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#1429] opened 2019-12-20 18:52 UTC
**Describe the bug**

When using `Filter by Attribute Block`, the attributes filter checkboxes don’t show a focus outline in Firefox. 

**To Reproduce**

0. Use Firefox to test this as well as Chrome for comparison where the bug is not present;
1. Create a page or post where you can add blocks;
2. Add the `Columns` block and select the number of columns. For example, 2;
3. Add `All Products` block in the first column;
4. Add `Filter by Attributes` block in the 2nd column (I also added `Filter by Price` and `Active filters` blocks but they are not necessary)
5. Publish the page/post and view this page/post at the front end;
6. Filter the products by one of the attributes;
7. Note that the attributes filter checkboxes don’t show a focus outline in Firefox:

Storefront theme:

![outline3](https://user-images.githubusercontent.com/19143190/71283719-e4be6a80-2358-11ea-9120-19ed24f2433a.jpg)

Twenty Twenty theme:

![outline4](https://user-images.githubusercontent.com/19143190/71283724-ea1bb500-2358-11ea-99d3-357650d6240a.jpg)

**Expected behavior**

I expected the attributes filter checkboxes to show a focus outline in Firefox as it is shown in Chrome:

Storefront theme:

![outline1](https://user-images.githubusercontent.com/19143190/71283792-17686300-2359-11ea-92cb-599b0d15a909.jpg)

Twenty Twenty theme:

![outline2](https://user-images.githubusercontent.com/19143190/71283798-1f280780-2359-11ea-8fa9-263e4149b03c.jpg)

**Screenshots**

See the screenshots above. 

**WordPress:**

* Core version: 5.3.1
* Gutenberg version (if installed): not installed
* WooCommerce version: 3.9 beta.2
* WooCommerce Blocks version: not installed
* Site language: English
* Any other plugins installed: No

**Desktop:**

Chrome where there is no issue:

* OS: macOS Catalina
* Browser: Chrome
* Version: 78.0.3904.108 (Official Build) (64-bit)

Firefox where there is an issue:

* OS: macOS Catalina
* Browser: Firefox
* Version: 70.0.1

**Additional context**

Thanks to @brandonpayton for spotting this issue during his testing.

**Comment by senadir** [comment] 2019-12-23 11:38
I can see an outline when I tab select them, not when clicking
![image](https://user-images.githubusercontent.com/6165348/71355411-419b6a00-257f-11ea-9059-c4decf4add41.png)
Woo Core only assign styles to focused elements, Chrome focuses element when they are active (clicked) while Firefox consider active and focus different states, I consider this default behavior and therefor not should if I should fix or not

**Comment by Aljullu** [comment] 2019-12-27 12:13
I'm unable to reproduce this issue in Linux, but heuristics whether the focus state must be displayed to the user depend on the browser and I don't think we want to overwrite them if they don't represent an accessibility issue.

When selecting attributes with the mouse, I think both showing and not showing the focus outline is ok. When selecting attributes with the keyboard I agree we must always show the focus outline, but according to @senadir this is already happening?

@juliaamosova can you confirm that? Should we close this bug or is there anything we are missing?

**Comment by nerrad** [comment] 2020-01-07 12:06
Based on the assessment by @senadir and @Aljullu , this doesn't appear to be a bug to me as both browsers are behaving as intended.  What _would_ be a bug is if using keyboard to select attributes does not show the focus.  Further, you can test this variance between browsers for native WordPress inputs (for instance the "Pending Review" checkbox in the "Status & Visibility" panel in the block editor) and see the same behaviour.

I'm going to close this issue, but if you have additional reasons why you think this should be addressed @juliaamosova please do re-open.

**Closed by nerrad** 2020-01-07 12:06 UTC
Labels: type: bug
