### ISSUE TITLE
Product Search block broken on WooCommerce-generated Shop page

### ISSUE THREAD

**Issue by tijosh** [woocommerce/woocommerce-gutenberg-products-block#4470] opened 2021-07-15 19:49 UTC
## Describe the bug

When using the `Product Search` block on the Shop page generated by WooCommerce, the search bar is non-functional.

## To reproduce

1. Make sure a shop page is set at **WooCommerce > Settings > Advanced**
2. Head to that page editor at **WP Admin > Pages**
3. Add the `Product Search` block (from core WooCommerce or the feature plugin)
4. See missing input DIVs on the page's HTML

## Expected behavior

The search bar works.

## Screenshots

![image](https://user-images.githubusercontent.com/35117248/125842286-a91a7b02-0674-4cb2-be05-a4684f13f403.png)

![image](https://user-images.githubusercontent.com/35117248/125842341-74db42f1-5ebe-4dc0-a02a-16646a82aeb5.png)

## Environment

<details>
`
### WordPress Environment ###

WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.77.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.30-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.2.2
Jetpack: by Automattic – 9.9
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.1
WooCommerce Payments: by Automattic – 2.7.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.57
WooCommerce: by Automattic – 5.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 278
Oldest: 2021-07-14 11:23:40 -0400
Newest: 2021-07-15 15:04:46 -0400

Pending: 4
Oldest: 2021-07-15 15:05:44 -0400
Newest: 2022-02-15 14:21:49 -0500

### Status report information ###

Generated at: 2021-07-15 15:05:25 -04:00
`
</details>

**Comment by ralucaStan** [comment] 2021-07-16 12:50
Hello @tijosh, 
thank you for taking the time to report this bug.
The problem is actually on WooCommerce’s side, as it does some escaping on the shop page that affects the Product search block. There is an already [opened issue](https://github.com/woocommerce/woocommerce/issues/29723) on WooCommerce’s repo.

If you don't mind I am gonna close this issue. To get updates on the topic I recommend that you subscribe to the issue mentioned above ( right sidebar, under Notifications).

**Closed as completed** 2021-07-16 12:51 UTC
Labels: type: bug, block: product search
