### ISSUE TITLE
Facebook tracking does not work with Checkout block

### ISSUE THREAD

**Issue by grogou** [woocommerce/woocommerce-gutenberg-products-block#5008] opened 2021-10-27 07:54 UTC
## Describe the bug
Tracking with 'Facebook for WooCommerce' plugin does not work with the Checkout Block despite the compatibility notice here: https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/#section-6
the Server side 'purchase event' not triggered because the current supported action name is woocommerce_checkout_update_order_meta, while
in case of block based checkout the order is created/updated using rest endpoint, where triggered action name is __experimental_woocommerce_blocks_checkout_update_order_meta
Hence, you can't use Facebook for WooCommerce and checkout block together properly.

## To reproduce
Set up Facebook partner integration with WooCommerce and its basic event.
Make a purchase.

## Expected behavior
'Purchase event' should fire by default from the server side if the action names are correct

## Additional context
Initially we wrote to woocommerce.com/Facebook for WooCommerce support, but they directed me here. Please, see the screenshot of their response. 
![image](https://user-images.githubusercontent.com/10712881/139025065-96d6aebc-08ca-49ce-bbec-1b4c43930b81.png)

**Comment by nerrad** [comment] 2021-10-27 19:48
Thanks for the report @grogou.

@mikejolley do you have any suggestions here? I think we explicitly added new actions because there's a slight variation of how things are handled via the StoreAPI checkout flow over the default Core flow (as well as introducing the client side events). I'm guessing firing existing hooks is likely not something we want to do here?

**Comment by mikejolley** [comment] 2021-10-28 07:00
@nerrad That is correct. The core hook `woocommerce_checkout_update_order_meta` passes POST data from the checkout. This is not something we can easily replicate--the `__experimental_woocommerce_blocks_checkout_update_order_meta` only passes the order object. 

Whilst we could trigger the action without POST data, this could break existing integrations that rely on it.

**Comment by budzanowski** [comment] 2021-10-28 10:13
In Facebook For WooCommerce the `woocommerce_checkout_update_order_meta` event just adds the meta: https://github.com/woocommerce/facebook-for-woocommerce/blob/9b1a1dcb696fe4e1926b9f196b0375705fad4c41/facebook-commerce-events-tracker.php#L874-L878 and then it returns. Only with `woocommerce_thankyou` the [inject_purchase_event ](https://github.com/woocommerce/facebook-for-woocommerce/blob/9b1a1dcb696fe4e1926b9f196b0375705fad4c41/facebook-commerce-events-tracker.php#L853) proceeds to the sending of the event to the API. 

Just adding the metadata can be easily fixed by doing this in: `__experimental_woocommerce_blocks_checkout_update_order_meta`.

If later `woocommerce_thankyou` is triggered with the Checkout Blocks everything should work fine.

Quick PR in FB repo for verifying and probably fixing the issue: https://github.com/woocommerce/facebook-for-woocommerce/pull/2107

**Comment by nerrad** [comment] 2021-10-28 10:25
Thanks Bartek! I'm going to go ahead and close this issue because it's being addressed in the FB repo. Thanks for reporting this @grogou and we'll hopefully see a fix released for FB in the nearish future.

**Closed as completed by nerrad** 2021-10-28 10:25 UTC
Labels: type: bug, category: extensibility

**Comment by grogou** [comment] 2021-10-28 11:23
@nerrad thank you too.

**Comment by grogou** [comment] 2021-11-16 07:54
@nerrad sorry but we need to open this ticket again.

Previously it was `__experimental_woocommerce_blocks_checkout_update_order_meta` which was renamed with 
`woocommerce_blocks_checkout_update_order_meta`.

The problem is that the purchase event is hooked into `woocommerce_checkout_update_order_meta` which does not fire during block based checkout and the event is not logged to facebook dashboard.

**Comment by budzanowski** [comment] 2021-11-16 08:21
@grogou Hi!

I gave it a quick look and I believe that nothing has changed really. Yes, the deprecation notice is there bc the filter was graduated to not `__experimental` version, but the code still calls the old action here https://github.com/woocommerce/woocommerce-gutenberg-products-block/commit/3ebee9ae889d393c388a1a3ac1514337a88ec744#diff-af2c90fa556cc086b780c8fad99b68373d87fd6007e6e2ff1b4c68ebe9ccb551R427 . Please check if in your scenario the `woocommerce_thankyou` is called. This is the second part of the flow inside the Facebook Plugin. During the `__experimental_woocommerce_blocks_checkout_update_order_meta` order meta gets added and during the `woocommerce_thankyou` it is used to send the tracking event.

**Comment by rufus87** [comment] 2021-11-16 10:15
@budzanowski many thanks for you response. 

Actually, here is the code line from `Facebook for Woocommerce` plugin:
`add_action( 'woocommerce_checkout_update_order_meta', array( $this, 'inject_purchase_event' ) );`

As you can see, the `inject_purchase_event` method is called during `woocommerce_checkout_update_order_meta` action only, which is not triggered during block based checkout order creating, but the new `woocommerce_blocks_checkout_update_order_meta` action does.

So, what I suggest is to add another line of code, what will hook to new action `woocommerce_blocks_checkout_update_order_meta` and will make plugin to support block based checkout like this:

`add_action( 'woocommerce_blocks_checkout_update_order_meta', array( $this, 'inject_purchase_event' ) );`

This is a simple, correct and quick solution to reported issue.

**Comment by budzanowski** [comment] 2021-11-16 11:30
Hi @rufus87

Whenever `inject_purchase_event` is called during `woocommerce_checkout_update_order_meta` the only thing that happens is storring of the fb order placed meta with the order, the function returns right after that. This is covered by the lines highlighted here:  
https://github.com/woocommerce/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L863-L888
This is the most important bit:
```PHP
 		if ( 'woocommerce_checkout_update_order_meta' === current_action() ) {
				$order->update_meta_data( $order_placed_meta, 'yes' );
				$order->save_meta_data();
				return;
			}
```

For the purpose of compatibility with the Checkout block flow another function was added:
```PHP
		/**
		 * Inject order meta gor WooCommerce Checkout Blocks flow.
		 * The blocks flow does not trigger the woocommerce_checkout_update_order_meta so we can't rely on it.
		 * The Checkout Block has its own ( so far ) experimental hook that allows us to inject the meta at
		 * the appropriate moment: __experimental_woocommerce_blocks_checkout_update_order_meta.
		 *
		 *  @since 2.6.6
		 *
		 *  @param WC_Order $order Order object.
		 */
		public function inject_order_meta_event_for_checkout_block_flow( $order ) {

			$event_name = 'Purchase';

			if ( ! $this->is_pixel_enabled() || $this->pixel->is_last_event( $event_name ) ) {
				return;
			}

			$order_placed_meta = '_wc_' . facebook_for_woocommerce()->get_id() . '_order_placed';
			$order->update_meta_data( $order_placed_meta, 'yes' );
			$order->save_meta_data();
		}
```
from [lines 950-971](https://github.com/woocommerce/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L950-L971).

Which is hooked into:

```PHP
			add_action( '__experimental_woocommerce_blocks_checkout_update_order_meta', array( $this, 'inject_order_meta_event_for_checkout_block_flow' ) );
```
from [line 130](https://github.com/woocommerce/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L134).

This does what you want to achieve with the code you are proposing. In your solution it would be also necessary to modify the action check logic at [line 884](https://github.com/woocommerce/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L884) because we would miss that we need to update during the new `woocommerce_blocks_checkout_update_order_meta` .

So as long as the `__experimental_woocommerce_blocks_checkout_update_order_meta` is still triggered ( this time as deprecation ) then: nothing changes we just need to update the name of the action to avoid deprecation notices.

This is why I was wondering if `woocommerce_thankyou` action is called at the right moment:
If you take a look at the Facebook Plugin code you can find that this action is alos conneted to the `inject_purchase_event`:
```PHP
			add_action( 'woocommerce_checkout_update_order_meta', array( $this, 'inject_purchase_event' ) );
			add_action( 'woocommerce_thankyou', array( $this, 'inject_purchase_event' ), 40 );
```

This time the check from [line 884](https://github.com/woocommerce/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L884) is not applied and the `inject_purchase_event` method continues further up to the point where it sends the tracking event.

The new code was added in Facebook For WooCommerce 2.6.6 that was released 3.11.2021.

**Comment by budzanowski** [comment] 2021-11-16 15:09
Just to make the message clear. I am not saying that you are not experiencing issues, or the problem is not there :) I am merely explaining why I think the explanation you have provided does not describe the source of the problem. I don't exclude the possibility that I am not seeing things correctly and the problem is obviously there. I will be happy to provide fixes for the Facebook plugin; if it will be needed; when we will understand where the problem lies.

**Comment by rufus87** [comment] 2021-11-17 05:47
@budzanowski thank you so much for clarification. Actually, I've missed `add_action( '__experimental_woocommerce_blocks_checkout_update_order_meta', array( $this, 'inject_order_meta_event_for_checkout_block_flow' ) );` line which does all the required job. The only thing that may require you attention is `__experimental_woocommerce_blocks_checkout_update_order_meta` action name, which is currently deprecated but one day it can be removed. 

Thank you again. Ticket can be closed.

**Comment by budzanowski** [comment] 2021-11-17 09:24
I have created an FB Issue to track the deprecation https://github.com/woocommerce/facebook-for-woocommerce/issues/2123
