### ISSUE TITLE
WooCommerce Box Office product type ticket with wrong Ticket Detail button behaviour inside empty cart block

### ISSUE THREAD

**Issue by pluginslab** [woocommerce/woocommerce-gutenberg-products-block#5185] opened 2021-11-18 16:24 UTC
## Describe the bug
When visiting a cart page with an empty cart, the "New in Store" is presented with 3 products. If one of those products is a ticket product from WooCommerce Box Office, the button that says Ticket Detail will add it to cart, instead of redirect to product page detail.

## To reproduce

1. Install WooCommerce Box Office
2. Create a ticket product
3. Go to the cart page with an empty cart
4. Identify the ticket product and click on the Ticket Details button, it will add the ticket to the cart instead of redirect it to the cart page. 

## Expected behavior
It should open the page for the product (inside the <a> tag, there's an `ajax_add_to_cart` class added to it, that other buttons, like the Read More button does not have).

## Screenshots
![CleanShot 2021-11-18 at 16 19 07@2x](https://user-images.githubusercontent.com/57633278/142454351-76814996-e676-4f3e-9aca-8d1ff271da7a.png)
![CleanShot 2021-11-18 at 16 23 31@2x](https://user-images.githubusercontent.com/57633278/142455028-0d6a095c-4091-41f5-ae2f-98aa4612f8b8.png)

### WordPress (please complete the following information):
* Core version: 5.8.2
* WooCommerce version: 5.8.0
* WooCommerce Blocks version: 6.2
* Any other plugins installed: WooCommerce Box Office

**Comment by Aljullu** [comment] 2021-11-19 07:53
Thanks for creating this issue @pluginslab!

It looks like WooCommerce Box Office is returning true on `$product->supports( 'ajax_add_to_cart' )` when I think it should return `false`. That seems to be the cause that is making those products to be added directly without introducing extra details.

I created an issue in the Box Office repo so I will close this one here.

**Closed as completed by Aljullu** 2021-11-19 07:53 UTC
Labels: type: bug, block-type: product-grid, type: compatibility
