### ISSUE TITLE
Method "get_tax_location" in Order doesn't return the correct Local PickUp Address

### ISSUE THREAD

**Issue by rahulv-dev** [woocommerce/woocommerce-gutenberg-products-block#10014] opened 2023-06-27 22:48 UTC
## Description
For Avatax plugin, we are in the process of using the right local pickup address for tax calculation. However, when we try to fetch the local pickup address using the method $order->get_tax_location(), it always returns the store address.

Here are the steps I followed:

- Go to WooCommerce - > Settings - >Shipping
- Click on Local Pickup
- Add 2 local locations (local to store) with different zip codes.
- Make sure store address and local addresses are different.
- Create an order from cart (select a local pick up address here) - > checkout - > successful order.
- Go to Orders and choose this order, click on order actions and choose an action such that you have access to $order object.
- In this flow, log "$order->get_tax_location()" and you will see that it returns store address instead of local pickup address.

**Other Information:**
I observed that during checkout process, if we log $cart->get_customer()->get_taxable_address() then this returns the correct local pickup address.

## Expected behavior
- When $order->get_tax_location() is invoked during the flow stated above, it should return the correct local pickup address instead of store address.
- Currently it seems like the method only returns "country", "state", "postcode" and "city". It would be great if this could return "Address_line1" and "Address_line2" as well so that the caller has complete address for further usage. 

### WordPress (please complete the following information):

-   WordPress version: 6.2.2
-   WooCommerce version: 7.7.2
-   WooCommerce Blocks version: 10.0.6
-   Site language: en_US
-   Any other plugins installed: AvaTax

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrome
-   Version: 114.0.5735.133

**Comment by wavvves** [comment] 2023-06-29 21:52
Hi @rahulv-dev, thank you for reporting this.

I'm finding it a bit strange that different results are being observed for `$order->get_tax_location()` and `$customer->get_taxable_address()`, by looking at [OrderController.php#L63](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/Utilities/OrderController.php#L63) I see that we actually rely on `$customer->get_taxable_address()` to output ` $order->get_tax_location()`. Are you sure you are var_dumping the data after the filter gets applied?

Also, looking at the code, I see that probably the best path for adding "Address_line1" and "Address_line2" to that data could be tapping into that `woocommerce_order_get_tax_location` filter and modifying it to include those fields. We don't have any use case for that and would prefer not to output a different data shape that comes from core. No further action would be needed outside Avatax plugin code, unblocking your work.

**Comment by rahulv-dev** [comment] 2023-07-05 22:39
Hi @wavvves , thanks for your response.
I looked at the code you referenced above, however when we are inside an order(edit order) then the following code `wc()->customer` returns null and therefore `$taxable_address = wc()->customer->get_taxable_address();` is never set because of line 67 with if condition. That's probably the reason it's doesn't set the right location to be returned. 

Please let me know if there is something I am missing here or any other information I can provide to help reproducing the issue at your end, but I am pretty sure if you follow the steps mentioned in the description, you'll be able to repro it at your end too.

**Comment by tarhi-saad** [comment] 2023-07-13 16:05
Hi, @rahulv-dev! 👋 Thank you for reaching out! 🙌 I was trying to follow the testing steps you mentioned in this ticket's description:

> Here are the steps I followed:
>- Go to WooCommerce - > Settings - >Shipping
>- Click on Local Pickup
>- Add 2 local locations (local to store) with different zip codes.
>- Make sure store address and local addresses are different.
>- Create an order from cart (select a local pick up address here) - > checkout - > successful order.
>- Go to Orders and choose this order, click on order actions and choose an action such that you have access to $order object.
>- In this flow, log "$order->get_tax_location()" and you will see that it returns store address instead of local pickup address.

In the last step, I logged `$order->get_tax_location()` from the `plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php` file inside the `save` function. But I got an error. The `get_tax_location` doesn't exist.

But we can access the correct pickup address using the following code:

```PHP
$line_items_shipping = $order->get_items( 'shipping' );

foreach ( $line_items_shipping as $item_id => $item ) {
  $data = $item->get_data();
}
```

Please, let me know if this works for you!

@wavvves, could you confirm that `get_tax_location` doesn't exist in the `$order` object?

**Comment by rahulv-dev** [comment] 2023-07-18 15:00
Hello @tarhi-saad, thank you for the response.
I tried to use the code you suggested, however it looks like it would return address in a String format with comma delimited values instead of Address Object. I think it would be error prone if we happen to use this String Address Object because there is no uniformity like for e.g. there is no comma between state and zip code.
Similarly if tomorrow something changes in that string w.r.t delimiter, the logic at our end would break. Let me know your thoughts on this.

**Comment by mikejolley** [comment] 2023-07-24 11:46
The custom pickup address handling that utilises `woocommerce_order_get_tax_location` is only ran during Store API calls (`update_order_from_cart` method). So if you were to try to get the address from an order on any other request, it will ignore this and use the store base address because of this logic in woo core:

```
if ( $apply_base_tax && count( array_intersect( $shipping_method_ids, $local_pickup_methods ) ) > 0 ) {
	$tax_based_on = 'base';
}
```

The pickup location address is not stored to the order as the customer billing/shipping address, so a lookup would be difficult. Blocks does not need this because once the order is placed it no longer interacts with orders or recalculates taxes.

From our side, we could filter at all times but this could create some issues in other places. Alternatively, the order method called `get_tax_location` could be updated to handle pickup locations somehow. But both would need a lookup similar to the code @tarhi-saad posted above.

**Comment by nielslange** [comment] 2023-08-11 10:54
I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by nielslange** 2023-08-11 10:54 UTC
Labels: type: bug, type: community contribution
