### ISSUE TITLE
[GlobalStep - Integration Tracking (WC Subscriptions)] On Cart page, the "Due today" amount fails to update after applying the coupon.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#4002] opened 2021-03-26 16:17 UTC
## Bug Description:
On Cart page, the "Due today" amount fails to update after applying the coupon.

## Test Instructions:
https://gist.github.com/senadir/895e901e7189d9546d8200eac2fbbd90#subscription-coupons

## Environment:
Woocommerce Version : WooCommerce 5.1
WordPress version: (v5.7)

PC:
Windows 10
Chrome(Version 89.0.4389.90) 
Firefox(Version 86.0)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard 
1. Install and activate the WooCommerce blocks plugin.
1. Edit "Cart" page and insert Cart block instead of Shortcode, save.
1. Edit "Checkout" page and insert Checkout block instead of Shortcode, save.
1. Add some products.
1. Go to Shop page on frontend.
1. Add any product to the cart.
1. Go to Cart page.
1. Remove the product from the cart.
1. Now try to Add new product to cart from "New in store" section.
1. Observe that  "Something went wrong" error message is displayed.

## Actual Result:
"Something went wrong" error message is displayed on cart page upon removing the product from the cart and adding the new product from the "New in Store" section.

## Expected Result:
Product should get add to the cart upon removing the product from the cart and adding the new product from the "New in Store" section.

## Screenshot:
![#4002](https://user-images.githubusercontent.com/41110392/112662024-35d2dd80-8e7d-11eb-81e5-2e1d492447cd.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://sunny-guanaco.jurassic.ninja
Site address (URL): https://sunny-guanaco.jurassic.ninja
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.8.0-dev
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 4.09MB
Database Data Size: 2.53MB
Database Index Size: 1.56MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.44MB + Index: 0.09MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 5
page: 6
post: 2
product: 12
product_variation: 2
revision: 3
shop_coupon: 9
shop_order: 6
shop_subscription: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Query Monitor: by John Blackbourn – 3.6.7
Code Snippets: by Code Snippets Pro – 2.14.1
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.5
Facebook for WooCommerce: by Facebook – 2.3.3
Jetpack by WordPress.com: by Automattic – 9.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce Blocks: by Automattic – 4.8.0-dev
WooCommerce Payments: by Automattic – 2.1.1
WooCommerce Subscriptions: by WooCommerce – 3.0.13
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://sunny-guanaco.jurassic.ninja
Subscription Statuses: auto-draft: 3
wc-active: 2
wc-pending-cancel: 1
wc-on-hold: 1

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 2
wc-on-hold: 1
wc-pending-cancel: 1


### Payment Gateway Support ###

WooCommerce Payments: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Check payments: products
Cash on delivery: products

### Action Scheduler ###

Complete: 66
Oldest: 2021-03-26 07:59:01 +0000
Newest: 2021-03-26 15:51:44 +0000

Pending: 4
Oldest: 2021-03-27 08:02:15 +0000
Newest: 2022-03-26 12:59:39 +0000


### Status report information ###

Generated at: 2021-03-26 15:56:09 +00:00
`
```
</details>

**Comment by Aljullu** [comment] 2021-03-29 18:45
I'm unable to reproduce this, @gglobalstep it looks like the Steps to reproduce are not from this issue? Given the screenshot, I assumed you tested with a `Recurring Product % Discount` coupon, like [this one](https://d.pr/i/wUz7QS), is that correct?

**Comment by opr** [comment] 2021-03-30 09:08
@Aljullu This was discussed here p1616760741108600/1616759988.103600-slack-C011ENB20Q1

**Comment by Aljullu** [comment] 2021-03-30 09:25
Ah, thanks @opr! Assigning this one to @senadir based on that discussion.

**Comment by senadir** [comment] 2021-04-04 12:19
This seems to be an issue with the testing instructions actually, the results above are correct, the item should now show the coupon value. I'm going to close this.

See this PR https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3905

**Closed as completed by senadir** 2021-04-04 12:19 UTC
Labels: type: bug
