### ISSUE TITLE
It shouldn't be possible to add siblings to the Filled/Empty Mini Cart Contents blocks

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5907] opened 2022-02-21 12:34 UTC
## To reproduce

1. Go to Apperance > Site Editor > Template Parts > Mini Cart.
2. Select the Mini Cart Contents block.
3. Press <kbd>Enter</kbd>.
4. Notice you are allowed to add a block right inside the Mini Cart Contents block and as a sibling of the Filled and Empty Mini Cart Contents blocks.

## Expected behavior

It shouldn't be possible to add inner blocks as direct children of the Mini Cart Contents blocks.

## Screenshots

https://user-images.githubusercontent.com/3616980/154955982-4fdad000-2006-4712-b09a-6cb38869f420.mp4

Please, @dinhtungdu @gigitux correct me if that's intentional. I might be missing something.

**Comment by gigitux** [comment] 2022-02-21 13:24
> Please, @dinhtungdu @gigitux correct me if that's intentional. I might be missing something.

Yes, this is intentional. We want that the user adds blocks only to the `Mini Cart items` block and `Empty Mini Cart Contents`. More details [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5883#issuecomment-1046875456).

**Comment by Aljullu** [comment] 2022-02-21 13:58
Thanks. So this issue would be a duplicate of woocommerce/woocommerce#42659?

**Comment by gigitux** [comment] 2022-02-21 16:36
> Thanks. So this issue would be a duplicate of woocommerce/woocommerce#42659?

Yes!

**Comment by dinhtungdu** [comment] 2022-02-22 02:12
I can confirm this is a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5387. @Aljullu Is it okay if we close this issue and add your reproduce step and screencast to the https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5387?

**Comment by Aljullu** [comment] 2022-02-22 08:18
Sure, go ahead @dinhtungdu!

**Comment by dinhtungdu** [comment] 2022-02-22 08:24
Closing in favor of woocommerce/woocommerce#42659.

@Aljullu please note that I edit the reproduce steps a bit to correct the last step.

> Notice you are allowed to add a block right inside the Mini Cart Contents block and as a sibling of the Filled and Empty Mini Cart Contents blocks.

The new block is actually added under the Mini Cart Contents block and doesn't belong to Mini Cart Contents block. It's a top-level block:

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/5423135/155091928-19fa1739-9264-44dc-a00d-f6e81abf8305.png">

**Closed as completed by dinhtungdu** 2022-02-22 08:24 UTC
Labels: type: bug, block: mini-cart
