### ISSUE TITLE
Layout options & themes that don't support wide widths 

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#207] opened 2018-12-04 17:31 UTC
Currently, we display a single layout option in themes that don't support the wide layout options. Clicking that option doesn't do anything either.

![layout](https://cldup.com/mBqqh5-0AI-3000x3000.png)

Suggest we just remove the layout option for themes that don't support wide layouts. This would be inline with how the cover image block behaves.

**Comment by ryelle** [comment] 2018-12-04 22:22
This looks like a duplicate of #208, so I'm going to close it. Feel free to reopen & elaborate if I'm wrong, @jameskoster

**Closed by ryelle** 2018-12-04 22:22 UTC
