### ISSUE TITLE
Add term classes

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce-gutenberg-products-block#1189] opened 2019-11-17 21:57 UTC
**Is your feature request related to a problem? Please describe.**
There are classes missing for blocks like the category list.

**Describe the solution you'd like**
Add classes for term slug/ID to each category list item.

**Describe alternatives you've considered**
There aren't really any alternatives, there aren't dedicated filters either.

**Comment by ralucaStan** [comment] 2021-01-26 16:06
Hi @strarsis to move this forward we need additional information from your side.
- which blocks are you referring to specifically?
- by category list block, do you mean the Product Categories List Block?
- which class names would you like to see on the list items

Thank you!

**Comment by strarsis** [comment] 2021-08-03 13:58
Finally I arrive answering the questions:
Product Categories List Block.
class should be the slug of the category term, as with the traditional shortcode markup.

**Comment by nielslange** [comment] 2021-08-24 14:47
> class should be the slug of the category term, as with the traditional shortcode markup.

@strarsis By _"traditional shortcode markup"_, are you referring to the `[product_categories]` shortcode? I'm asking as when applying this shortcode and using the Storefront theme, I do not see the category terms used as term classes:

```
<ul class="products columns-4">
	<li class="product-category product first">
		<a href="https://store.local/product-category/clothing/">
			<img src="https://store.local/wp-content/uploads/woocommerce-placeholder-324x324.png" alt="Clothing" width="324" height="324">
			<h2 class="woocommerce-loop-category__title">Clothing <mark class="count">(14)</mark> </h2>
		</a>
	</li>
	<li class="product-category product">
		<a href="https://store.local/product-category/decor/">
			<img src="https://store.local/wp-content/uploads/woocommerce-placeholder-324x324.png" alt="Decor" width="324" height="324">
			<h2 class="woocommerce-loop-category__title">Decor <mark class="count">(1)</mark></h2>
		</a>
	</li>
	<li class="product-category product">
		<a href="https://store.local/product-category/music/">
			<img src="https://store.local/wp-content/uploads/woocommerce-placeholder-324x324.png" alt="Music" width="324" height="324">
			<h2 class="woocommerce-loop-category__title">Music <mark class="count">(2)</mark> </h2>
		</a>
	</li>
</ul>
```

**Comment by nielslange** [comment] 2021-09-09 11:04
@strarsis I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed by nielslange** 2021-09-09 11:04 UTC
Labels: type: enhancement, good first issue, needs feedback, priority: low
