### ISSUE TITLE
Featured Product Block change product does not change product URL

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce-gutenberg-products-block#1889] opened 2020-03-06 12:26 UTC
I have used in past two weeks on few sites first time the Featured Product Block and I like it. After using it, I liked to feature another product in a before setup Block. For this, I used the pencil icon for editing Featured Product Block and selected a different product. Product image changend as expected, but URL to product did not change. I expected URL to change to new selected product. This can be overseen by admins.

**Comment by nerrad** [comment] 2020-03-07 22:40
Hi there,

I appreciate the report, but we need details about your environment so we can make sure we're verifying this bug report in the same setup.

I'm going to close this issue and if you can go through the bug report template [found here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/new/choose) that will include the questions we need answered to help troubleshoot your report.

Thanks!

**Comment by nerrad** [comment] 2020-03-07 22:49
I can reproduce this on master so I'm re-opening. However it'd still be nice to know what environment you saw this on @ajgw so it can help us decide where we'll land the fix.

Also, I do appreciate if in the future for bug reports (which are very valuable to us!) you could use the templates I linked to in my previous comment because that saves going back and forth.  Thanks!

**Comment by ajgw** [comment] 2020-03-08 08:49
Well @nerrad I’ve copied environment questions into this and will fill them out:

**WordPress (please complete the following information):**

* Core version: 5.3.2
* Gutenberg version (if installed): no
* WooCommerce version: 3.9.3
* WooCommerce Blocks version: 1 site only WC, another site 2.5.14
* Site language: DE
* Any other plugins installed: Storefront Powerpack 1.5.0

**Desktop (please complete the following information):**

* OS: macOS 10.15.3
* Browser Safari
* Version 13.0.5

**Comment by nerrad** [comment] 2020-03-08 13:08
Thanks Adrian 👍

**Closed** 2020-05-12 09:08 UTC
Labels: scope: blocks, type: bug
