### ISSUE TITLE
[Site Editor] Incorrect redirection to a different template than the one selected to edit 

### ISSUE THREAD

**Issue by jimjasson** [woocommerce/woocommerce-gutenberg-products-block#10236] opened 2023-07-17 11:19 UTC
## Describe the bug

When selecting a template to edit in the Site Editor, I am always redirected to the "Page" template, regardless of the template I selected.

https://github.com/woocommerce/woocommerce-blocks/assets/25955483/bc257ed6-052a-452c-96fe-3e050fcf4714

## To reproduce

1. Go to Appearance > Editor.
2. Click on the Single Product template while the Editor is seemingly still loading.
3. Click to edit the template.
4. When the Editor finishes loading, you will be redirected to a different template than the one you selected.

## Expected behavior

When I select a template to edit, I expect that this is the template that opens in the Editor and I am not redirected to a different template.

## Environment

Fresh WordPress installation with the latest WooCommerce and Blocks plugin active.

**Comment by nefeline** [comment] 2023-07-19 07:36
Hey @jimjasson ! I did a few tests here and couldn't reproduce the problem so far: the template is loaded as expected in all scenarios while having the latest version of Woo Blocks enabled. Out of curiosity, on which version of WordPress did you test this?

**Comment by jimjasson** [comment] 2023-07-24 09:54
Hey @nefeline, 

Thanks for looking into this!

I am using WordPress 6.2.2 and Blocks 10.7.0.  

I think that an important step to replicate this is to click to edit a template, while the editor is still loading -- if you have a look at my video, there is a spinning wheel visible when I select the single product template. 

If your editor runs really fast and you don't have time to click on a template while it is still loading, then could you please add some network delay/latency in your browser? 

Finally, it would be really helpful to share a video of what you see in case I can spot any differences compared to what I try.

**Comment by roykho** [comment] 2023-07-28 13:51
Hi @jimjasson - I've tested this and was able to reproduce maybe once or twice and it was quite difficult to reproduce even with throttling. I tested with Fast 3G, Slow 3G..etc.

Do you mind testing Blocks trunk and see if this still occurs?

**Comment by jimjasson** [comment] 2023-07-31 09:11
Hey @roykho, 

Thanks for testing this! 

I did another test with the latest `nightly` release and I can still replicate this issue. 

What could contribute to the slow loading times I see in my editor? Is it that I have many pages (currently 17)? The rest of the WP/WC pages seem to load fast enough.

**Comment by gigitux** [comment] 2023-08-01 15:24
Hey @jimjasson,
It seems that this is a bug of the Gutenberg. I replicated the same issue with a WordPress template:

https://github.com/woocommerce/woocommerce-blocks/assets/4463174/88aadf4a-796e-464b-871c-cc2287829287

**Comment by jimjasson** [comment] 2023-08-02 06:16
Hey @gigitux, 

Thanks for testing! 

I had a look at the Gutenberg repo: https://github.com/WordPress/gutenberg and I wasn't able to find a similar issue there. Can you take a look too and if there isn't an open issue for this there, then let's go ahead and report it.

**Comment by gigitux** [comment] 2023-08-02 15:00
I didn't find any issue. I created one! https://github.com/WordPress/gutenberg/issues/53271

I will close this issue!

**Closed as completed by gigitux** 2023-08-02 15:00 UTC
Labels: type: bug

**Comment by jimjasson** [comment] 2023-08-03 06:35
Thanks Luigi!
