### ISSUE TITLE
Create account on checkout page does not work

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#3431] opened 2020-11-19 11:44 UTC
## Describe the bug
On the "checkout" page, when I check the "create an account" box, the password field is not displayed, therefore an account cannot be created. I think several days ago, it did work.

## To reproduce
2. Click on 'Create an account' on checkout page.

## Expected behavior
The password field must be displayed.

## Screenshots
<img width="1112" alt="Captura de pantalla 2020-11-19 a las 12 32 48" src="https://user-images.githubusercontent.com/74713739/99661308-f1b17580-2a63-11eb-80af-7a0264bf1119.png">

### WordPress (please complete the following information):
* Core version: [5.5.3]
* WooCommerce version: [4.7.0]
* WooCommerce Blocks version: [3.8.0]

### Desktop (please complete the following information):
* OS: [macOS]
* Browser [all]

**Comment by senadir** [comment] 2020-11-19 13:48
Hi there @gaolbu 

The create account behaviour in the Checkout block is different from the one present in the old checkout; **There's no password field.** When a customer checks the "create an account" box and submits the order, an account will be created for him with that email, he will also receive an email with a link to set up his password.

This is intentional because adding more friction to the account creation process negatively impacts conversions.

So, if you're checking out with a new email with that checkbox on, you should receive that email and a new customer would be created.

I'm going to close this issue for now because this is the expected behaviour, but if you followed the steps above and an account is still not created, open this issue back or comment here, and I will receive a notification.

**Closed as completed by senadir** 2020-11-19 13:48 UTC
Labels: type: bug
