### ISSUE TITLE
Block Checkout + Apple Pay: wrong region input for hong kong address

### ISSUE THREAD

**Issue by beeruschan33** [woocommerce/woocommerce-gutenberg-products-block#8978] opened 2023-04-06 12:46 UTC
It sounds as though Apple Pay cannot be used with the Hong Kong address because the region field is not being mapped correctly i.e. the region field we present on the block checkout does not map to the correct regions that Apple Pay expects.

> This case is from Hong Kong,
This case can't test it now. I use WooCommerce Cart & Checkout blocks, but after finding a problem, I have temporarily returned to the original checkout. This problem was discovered after a customer from Hong Kong discovered that Apple Pay could not be used for payment. The error message of Apple Pay is: wrong region input.

**Comment by beeruschan33** [comment] 2023-04-06 12:47
How to fix it issue? thanks

**Comment by senadir** [comment] 2023-04-06 20:31
Can you provide with an error log from the console? or a screenshot at least?

**Comment by ralucaStan** [comment] 2023-04-10 08:26
Possibly related https://github.com/woocommerce/woocommerce-blocks/issues/8983

We have a fix for this and it would be released with WC Blocks version 10.0.0

**Comment by ralucaStan** [comment] 2023-04-10 08:26
@beeruschan33 could you confirm that the error appears for you when trying to add the postcode for a country? Many thanks

**Comment by beeruschan33** [comment] 2023-04-10 13:40
> 

Postcode is 0000
But when I go to the checkout page, the relevant error message has been displayed

**Comment by ralucaStan** [comment] 2023-04-11 11:07
Hey @beeruschan33,
Could you please walk us through your case by providing some testing steps?

What country do you introduce? What state? etc...

**Comment by beeruschan33** [comment] 2023-04-11 11:19
> Hey @beeruschan33, Could you please walk us through your case by providing some testing steps?
> 
> What country do you introduce? What state? etc...

This case is from Hong Kong,
This case can't test it now. I use WooCommerce Cart & Checkout blocks, but after finding a problem, I have temporarily returned to the original checkout.  This problem was discovered after a customer from Hong Kong discovered that Apple Pay could not be used for payment. The error message of Apple Pay is: wrong region input.

**Comment by wavvves** [comment] 2023-04-13 13:52
Hi @beeruschan33 

Can you update the issue description with this [template](https://github.com/woocommerce/woocommerce-blocks/issues/new?assignees=&labels=type%3A+bug&template=---bug-report.md) providing as much info as  possible? A good minimal example of that would enable us to try and replicate the bug would be:
- Installed plugins and versions
- Steps to replicate the error, including extension configuration

You can try replicating it in a local installation if it is not reproducible anymore in production.

**Comment by mikejolley** [comment] 2023-04-24 13:30
Whilst this issue does lack some details we can probably piece together enough information to test. It sounds as though Apple Pay cannot be used with the Hong Kong address because the region field is not being mapped correctly i.e. the region field we present on the block checkout does not map to the correct regions that Apple Pay expects.

It's not clear to me however if this is a Stripe issue, or something else. @beeruschan33 can you confirm which payment gateway you are using to add Apple Pay support?

Similar issues have appeared before. For reference:

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1477
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1508
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2569

**Comment by wavvves** [comment] 2023-05-19 16:21
Closing this due to inactivity.

**Comment by beeruschan33** [comment] 2023-08-09 03:22
Hi Mike,

I just reported this Stripe issue also exist,
Can you find the problems and resolve that?
Thanks & regards

在 2023年4月24日週一 下午9:30，Mike Jolley ***@***.***> 寫道：

**Comment by ralucaStan** [comment] 2023-08-09 09:21
@beeruschan33 Thank you for your input. Are you using Apple Pay via [the Stripe extension](https://woocommerce.com/products/stripe/)? If so, what version of the extension are you using. Could you provide some testing steps?

**Comment by tarunvijwani** [comment] 2023-08-23 20:18
@beeruschan33 I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue, and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2023-08-23 20:18 UTC
