### ISSUE TITLE
FIltering Variation Products

### ISSUE THREAD

**Issue by TatjanaDjurdjevic** [woocommerce/woocommerce-gutenberg-products-block#6777] opened 2022-07-27 14:42 UTC
Variation products can be filtered, and fetched by IDs via API if you add parameter type=variable to every query. 
It is not mentioned anywhere in the documentation.

1. When trying to fetch list of products by id's and that products are all variations  eg. 
`/wp-json/wc/store/products?include=ID1,ID2,ID3` returns empty array
 `/wp-json/wc/store/products?type=variation&include=ID1,ID2,ID3` the response returns variation products with selected IDs

2. When trying to fetch all products that are variation of some product with ID:
`/wp-json/wc/store/products?parent_id=ID`return empty array
`/wp-json/wc/store/products?type=variation&parent_id=ID` return all variations of product

Also I am not sure how to filter all products at once.

**Comment by senadir** [comment] 2022-07-28 10:28
This seems like a bug more than a feature, if you pass ID, you should get the item, the product type (especially a core type) shouldn't matter here.

**Comment by nielslange** [comment] 2022-07-28 10:33
Hello @TatjanaDjurdjevic 👋

In addition to what @senadir mentioned, it seems that you're using `parent_id`, which indicates that you are using the WooCommerce REST API. The attribute `parent_id` can be seen on https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties. In comparison, the attribute for the parent ID when using the WooCommerce Blocks Store API is called `parent` as described on https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/docs/products.md#list-products.

> Also I am not sure how to filter all products at once.

I created a new local WordPress site and imported the WooCommerce sample products. The sample import contains the following products with it's variations:

- ID: 13 | V-Neck T-Shirt
  - ID: 27 | Color: Red
  - ID: 28 | Color: Green
  - ID: 29 | Color: Blue
- ID: 14 | Product title: Hoodie
  - ID: 30 | Color: Red | Logo: No
  - ID: 31 | Color: Green | Logo: No
  - ID: 32 | Color: Blue | Logo: No
  - ID: 37 | Color: Blue | Logo: Yes

Fetching all variable products can be accomplished using the following query:

```sh
http://store.local/wp-json/wc/store/v1/products?type=variation
```

<img width="1512" alt="Screenshot 2022-07-28 at 12 33 01" src="https://user-images.githubusercontent.com/3323310/181485112-6e08722a-0860-4d8e-8f9b-17e8dc3fc096.png">

**Comment by senadir** [comment] 2022-08-01 08:53
Hello again @TatjanaDjurdjevic, I after testing this one more time, it looks like this isn't a bug, but a feature (and a but confusing one). When you pass `type= variation` (not to be confused with `type=variable`, which is what happened to me first), you actually get child variations, variable products are still returned on the top level request, which is the correct order.
Not returned the full variation data by default also makes sense since you rarely need that level of detail. Another good API might be to use `store/products/variations/` and have that act the same as `store/products?type=variation` but that's something I don't see much value in doing right now.

**Comment by TatjanaDjurdjevic** [comment] 2022-08-01 11:27
Hello @senadir, sorry for my slow replay.
My confusion is that if I pass ID's in `include` (e.g `store/products?include=ID1,ID2,ID3`), if some products ID are `type=variation` and some are `type=variable`, I will not get all the products requested in response. 

So there is no possibility to fetch products by their id no matter what their type is ?

What do you mean by variable products are still returned by the top level request? You mean the one without `type=variation`?

**Comment by TatjanaDjurdjevic** [comment] 2022-08-01 11:35
Hello @nielslange 👋 
We want to stay on client only domain, and not to use woo-commerce rest api. 
My confusion was this difference in response that is not mentioned in documentation. 
Sorry I made a mistake while typing, I was refering to parent, not parent_id.

<img width="571" alt="Screenshot 2022-08-01 at 13 31 31" src="https://user-images.githubusercontent.com/62244139/182138997-6f042b40-d6b6-49e0-a733-58b97ec322af.png">

And when we add type=variation, the response is no longer empty. 
<img width="1201" alt="Screenshot 2022-08-01 at 13 32 22" src="https://user-images.githubusercontent.com/62244139/182139128-ac981a15-bbac-4c7f-8716-1f4e70a08e09.png">

I was asking about filtering all products at once eg with all types possible. 
Not only variations or variable products. 

Thank you for your quick responses.

**Comment by senadir** [comment] 2022-08-01 11:46
> My confusion is that if I pass ID's in include (e.g store/products?include=ID1,ID2,ID3), if some products ID are type=variation and some are type=variable, I will not get all the products requested in response.

That's by design so far, variation products are excluded by default and you need to be explicit there. I understand that you want to query both variable and variation products at the same request?

**Comment by TatjanaDjurdjevic** [comment] 2022-08-01 13:06
If there is a possibility to query both variable and variation products at the same request that would be awesome 😄 

If not, I would only suggest to update the documentation. 
It didn't saw it mentioned anywhere in store api documentation, and it took me a long time to figure out how to get variation products 😄

**Comment by ralucaStan** [comment] 2022-08-10 13:33
Thank you so much for sharing your experience @TatjanaDjurdjevic. We are going to update the documentation to prevent confusion around this topic (see https://github.com/woocommerce/woocommerce-blocks/issues/6873).

As there is no action we can do on this ticket I am going to close it.

**Closed as completed by ralucaStan** 2022-08-10 13:33 UTC
Labels: focus: documentation
