### ISSUE TITLE
Checkbox Privacy Policy

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#3583] opened 2020-12-22 00:02 UTC
The woocommerce blocks checkout form does not show the acceptance box for the privacy policy or terms and conditions.

**Comment by senadir** [comment] 2020-12-31 11:03
Hi @gaolbu ,

Thanks for taking the time to leave the feedback.

This report is a duplicate of #3258.

**Closed as completed by senadir** 2020-12-31 11:03 UTC
Labels: type: bug
