### ISSUE TITLE
wc-featured-product-editor style gets enqueued in frontend

### ISSUE THREAD

**Issue by traed** [woocommerce/woocommerce-gutenberg-products-block#509] opened 2019-03-28 08:50 UTC
**Describe the bug**
When the `woocommerce/featured-product` block gets registered it includes `wc-featured-product-editor` in the `style`-option instead of the `editor_style`. The style then gets included in frontend which may cause problems when you're not using WooCommerce styles.

**To Reproduce**

1. Place the Featured Product block on a page.
2. Load page and inspect. `wc-featured-product-editor-css` and `wc-vendors-css` styles are included in `<head>`

**Expected behavior**
No WC styles should be included when using `add_filter('woocommerce_enqueue_styles', '__return_empty_array');`

**WordPress (please complete the following information):**
* Core version: 5.1.1
* WooCommerce version: 3.5.7
* WooCommerce Blocks version: 1.4.0

**Desktop (please complete the following information):**
* OS: MacOS 10.14.4
* Browser: Chrome
* Version: 73

**Comment by ryelle** [comment] 2019-03-28 14:57
As of WooCommerce 3.6 (currently beta), we've changed the CSS a bit so we're not loading all of `vendors.css` on the frontend. Would it be possible for you to try using [the WooCommerce 3.6 beta?](https://woocommerce.wordpress.com/2019/03/15/woocommerce-3-6-beta/) That will get you the latest blocks code, with the updated css files.

The styles are needed for the blocks to work, structurally, so we're not likely to unhook it - but if you're still seeing issues with your custom CSS, let us know and we can troubleshoot from there.

**Comment by mikejolley** [comment] 2019-05-09 12:44
I've confirmed this is no longer the case. The only style enqueued on the frontend with the current version is `wc-block-style-css`. 

The filter `woocommerce_enqueue_styles` allows the core WooCommerce catalog styles to be modified or removed. I don't think blocks fit in that bucket since they are self-contained. The styles are also not registered by WooCommerce directly, they are enqueued by WordPress via the `register_block_type` function so it's not possible to use that filter.

That leaves theme authors a choice of either extending the block styles, or dequeuing them (https://codex.wordpress.org/Function_Reference/wp_dequeue_style). 

Since these blocks should ideally match the styling in the editor (editor styles which are also added by `register_block_type`), and since these blocks are not technically part of the product catalog (blocks are shown on posts/pages for example) _extending_ simply by adding additional CSS in the theme is probably preferable--that way users of the theme will not see broken styles if blocks are modified or new blocks are added.

Closing this as the original issue is resolved.

**Closed by mikejolley** 2019-05-09 12:44 UTC
Labels: [Status] Needs Reply, [Type] Question
