### ISSUE TITLE
Zaino: Inconsistent button styling.

### ISSUE THREAD

**Issue by alaczek** [woocommerce/woocommerce-gutenberg-products-block#7972] opened 2022-12-19 00:20 UTC
## Describe the bug
Zaino is a premium WooCommerce theme based on TT3 (and in fact, it's using a modified version of one of TT3 style variations). 
Overall it works well with WC without needing any extra styling, except for buttons. 

The default theme buttons should be styled like this:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/4550351/208326710-2da1da3d-8d35-4af6-a04c-87b2eadbd732.png">

This is how buttons are styled in various places:

Shop page:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/4550351/208326816-0c249d1a-583f-4447-bf53-996b3a05b041.png">

Product page:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/4550351/208326836-56c3ab09-047f-44cd-bd58-432cd90c5ad6.png">

Minicart:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/4550351/208326863-604c17dc-b555-42d8-a159-32cc6c8f6e5c.png">

Cart (using the new checkout block):
<img width="747" alt="image" src="https://user-images.githubusercontent.com/4550351/208326882-15ebd292-0235-4818-9b4b-fad5b36c8fef.png">

Checkout:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/4550351/208326910-746fbe04-dbab-4656-8286-13558e45861d.png">

## To reproduce

1. Activate Zaino theme on an Atomic test site and a test product.
2. Go to the Shop page and view the button appearance.
3. Go to the single product page and view the button appearance.
4. Add product to the cart and check the button appearance in the Mini Cart slide-out panel.
5. Go to the Cart and view the Proceed to Checkout button.
6. Go to checkout and view the Place order button.

[You can also see these on the Zaino demo page.](https://zainodemo.wpcomstaging.com/)

## Expected behavior

I expected all the buttons to look the same and ideally inherit the theme styles.

## Environment

This is happening both on Atomic sites and when testing locally.

## Additional context

Related to #7388

**Comment by Aljullu** [comment] 2022-12-19 12:48
Thanks for opening this issue, @alaczek, this is very valuable! The good news is that in most blocks (except Mini Cart/Cart/Checkout, which I will mention below), the correct styles are applied. So, in general, as we blockify more parts of WooCommerce, less issues like this we will face and more correctly we will follow theme styles. Unfortunately, we are not there yet and WC still has some parts of the UI which are rendered by PHP templates.

I divided the issues you reported in two:

## Shop and product page

These buttons are added by WC core PHP templates and they use their own set of class names and CSS styles.

Recently, we added the `wp-element-button` class name to those buttons so they could inherit some styles from the Elements API (https://github.com/woocommerce/woocommerce/pull/35306/). However, the WC core styles are still more specific in most cases so they override the styles from the Elements API.

Possible solutions:
* Investigate if we can reduce the specificity of WC core styles so they don't always win styles from the Elements API: I'm not sure if that's feasible and definitely not something trivial because it can impact classic themes.
* Programmatically load those styles only in classic themes and not in block themes: I think that would be the best, similar to the way we have a stylesheet for block themes, we could have one for classic themes so all these styles that we don't want in block themes won't be there. However, this requires significant changes in WC core. We should also investigate what happens with block themes which don't set button styles using the Elements API.

## Mini Cart, Cart and Checkout blocks

When those blocks were created, the Elements API didn't exist. And instead of inhering the styles themes usually added via the `.button` class name, we decided to define opinionated styles to the buttons in order to apply best practices for better conversion. At the same time, however, this has some drawbacks like the buttons looking off and not having enough contrast in dark themes.

We could reconsider the decision of having opinionated styles for those buttons. However, we have some blockers:

* We can't use normal _Button_ blocks because we want the links to be dynamic, and that's something not yet supported in Gutenberg.
* We can't use the Elements API because, AFAIK, there is no way to style "outlined" buttons, so we can't achieve the [design of the Mini Cart block](https://user-images.githubusercontent.com/3616980/208428970-5b59559c-5174-4d1b-82ba-c7b251c55ac8.png) where one button is filled and the other outlined.
* At the same time, removing these opinionated styles from the buttons might work great for block themes that define button styles using the Elements API, but will be tricky for other themes because buttons would end up having no style at all.

Some possible solutions:
* Like suggested for the other problem, create a classic theme stylesheet to include the "opinionated styles" for Mini Cart/Cart/Checkout buttons, so they are only applied to classic themes and block themes inherit the styles from the Elements API.
* Accept that _Button_ links won't be dynamic and generate their `href` on insertion. This would allow us to use the _Button_ block from Gutenberg and solve the styling issues.

cc @nerrad @danielwrobert for your thoughts on this.

cc'ing also @ralucaStan given that this impacts the Cart and Checkout blocks as well.

**Comment by Aljullu** [comment] 2022-12-19 14:39
I didn't mention it, but an interim solution would be to add CSS styles to the theme (or to WC targeting TT3 and variants). It's more a work-around than a real fix, but probably the fastest solution.

**Comment by nerrad** [comment] 2022-12-19 17:05
> or to WC targeting TT3 and variants

Let's at least do this first. There was some work done for TT3 support prior to its release but it looks like these button styles were missed.

**Comment by Aljullu** [comment] 2022-12-20 15:02
I merged #7992 which should allow the Mini Cart, Cart and Checkout blocks button to inherit the styles from the themes. This is more a work-around than a real fix because it requires us to update the CSS for every theme we want to support. However, it seems like the only option we have right now given [what I raised before](https://github.com/woocommerce/woocommerce-blocks/issues/7972#issuecomment-1357616866).

I will try to work on Shop and product page buttons next week.

**Comment by Aljullu** [comment] 2022-12-29 09:52
I opened a PR in WC core which should solve the _Shop and product page_ part: https://github.com/woocommerce/woocommerce/pull/36225.

**Comment by ralucaStan** [comment] 2023-01-03 16:50
@Aljullu could you provide more details about what dynamic means in this context:

> We can't use normal Button blocks because we want the links to be dynamic, and that's something not yet supported in Gutenberg.

I love that the buttons work on TT3, but I agree it's not viable to apply workarounds for TT2, and other block themes, as well. So we should get agreement on a decision, as a lot of people have complained about this issue. (mostly using classic themes)

> Like suggested for the other problem, create a classic theme stylesheet to include the "opinionated styles" for Mini Cart/Cart/Checkout buttons, so they are only applied to classic themes and block themes inherit the styles from the Elements API.

What are the pros and cons of this approach? From what I understand:
- pro: buttons work on block themes; we only need to add a custom style for the classic theme as opposed to for every block theme
- cons: the buttons will still not inherit the style from the classic theme

**Comment by Aljullu** [comment] 2023-01-03 17:12
> @Aljullu could you provide more details about what dynamic means in this context:

Sure! What I meant is that buttons are "intelligent" to link to the Cart or to the Checkout page. So if the user changes these pages in the settings, or changes the slug of the page, or something similar, the links will continue working. If we used the Buttons block, the link would be "static" and wouldn't update in those circumstances.

> I love that the buttons work on TT3, but I agree it's not viable to apply workarounds for TT2, and other block themes, as well. So we should get agreement on a decision, as a lot of people have complained about this issue. (mostly using classic themes)

With the approach I'm taking in https://github.com/woocommerce/woocommerce/pull/36225, we would have a `.woocommerce-block-theme-has-button-styles` class name we can use to know if the block theme has customized the button styles or not. So we wouldn't need to target themes individually.

However, that only applies to block themes. For classic themes, we could look into removing some of our CSS resets (ie: colors, border-radius, etc. could be inherited from the theme IMO, instead of hardcoding ours).

> What are the pros and cons of this approach? From what I understand:

Yup, heads-up that this approach is similar to the one I mentioned above about having the `.woocommerce-block-theme-has-button-styles` class in the `<body>`. The difference is that instead of having the styles in two files, they are in the same and we use a `:not()` selector to exclude them in some circumstances.

The pros and cons you describe are exactly that. But as I mentioned above, if we are ok changing the styles in classic themes, I think we could remove some of our CSS resets. When doing so, we should make sure to do cross-theme testing to ensure we don't introduce regressions.

**Comment by ralucaStan** [comment] 2023-01-03 17:23
@Aljullu just to confirm, with the approach in https://github.com/woocommerce/woocommerce/pull/36225, the buttons would work out of the box on TT2, so long it applies its own styles to those buttons?

**Comment by Aljullu** [comment] 2023-01-04 12:28
In theory, no. That PR checks if the theme sets button styles using the Elements API, and TT2 doesn't ([see code](https://github.com/WordPress/twentytwentytwo/blob/trunk/theme.json#L268)), the first WP core theme that does it is TT3 ([see code](https://github.com/WordPress/twentytwentythree/blob/trunk/theme.json#L597-L628)).

So in that PR, the distinction is not between classic and block themes, but between block themes that use the Elements API to style buttons and all other themes.

**Comment by ralucaStan** [comment] 2023-01-04 13:39
Thank you for clarifying, I wasn't aware that TT2 wasn't adding custom styles.

Going back to this point below, I think it is the best solution. Can't we use the Button block  and wrap that in some parent component that sends down to the button the actual dynamic link? I'm thinking high level, I am not aware of the technical limitations.

> We can't use normal Button blocks because we want the links to be dynamic, and that's something not yet supported in Gutenberg.

**Comment by Aljullu** [comment] 2023-01-09 12:35
> Going back to this point below, I think it is the best solution. Can't we use the Button block and wrap that in some parent component that sends down to the button the actual dynamic link? I'm thinking high level, I am not aware of the technical limitations.

That's a good idea. I don't know how feasible it is, but it might be worth an exploration.

**Closed as completed** 2023-01-18 16:36 UTC
Labels: type: bug, focus: global styles
