### ISSUE TITLE
"Products by Category" Block Isn't Finding All Products in Category

### ISSUE THREAD

**Issue by ercousin** [woocommerce/woocommerce-gutenberg-products-block#383] opened 2019-01-31 04:52 UTC
**Describe the bug**
Products by Category block isn't finding all the products I have added into my category. I've added 7 products into a category and it isn't displaying in the Preview.

I can see them:
- In the WooCommerce Product Categories page
- In the Editor after adding the category to the block

I can't see them:
- In the category select list of block settings
- In the Preview of the post

**To Reproduce**

Add 7 products, assign to a category, create new post, add "Products by Category" block

**Expected behavior**
I expect this block to find all products in my category, even if they are marked as hidden from the catalog. I only expect products with non-Public visibility to not show up.

**Screenshots**

**WooCommerce Product Categories page**

![image](https://user-images.githubusercontent.com/1551339/52031198-598e7900-24e9-11e9-82e1-720547b4195a.png)

**In the Editor after adding the category to the block**

![image](https://user-images.githubusercontent.com/1551339/52031264-a4a88c00-24e9-11e9-9e7a-66acb2e351eb.png)

**In the category select list of block settings**

![image](https://user-images.githubusercontent.com/1551339/52031279-b12ce480-24e9-11e9-99bd-2c2dcbb1b206.png)

**In the Preview of the post**

![image](https://user-images.githubusercontent.com/1551339/52031285-bbe77980-24e9-11e9-8b05-b2940fa804e2.png)

**WordPress (please complete the following information):**

* Core version: 5.0.3
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: 3.5.4
* WooCommerce Blocks version: 1.3.1
* Site language: EN
* Any other plugins installed:

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Chrome
* Version: 71.0.3578.98

**Comment by ryelle** [comment] 2019-01-31 17:12
@ercousin It sounds like this is a duplicate of #252 , but you're suggesting that we _should_ show hidden products in the block. I'm going to close this issue, and we can have that discussion over on the other issue.

**Closed by ryelle** 2019-01-31 17:12 UTC
