### ISSUE TITLE
Nothing is showing on my cart page

### ISSUE THREAD

**Issue by neonnightsnz** [woocommerce/woocommerce-gutenberg-products-block#3725] opened 2021-01-23 19:18 UTC
Hi there I have added the cart and checkout blocks to both pages on my website and I'm seeing nothing when navigating to the page except the rath math page score.

What have I done wrong any tips to overcome the issue?

https://neonnights.co.nz/shop/cart/

Thanks
Isaac

**Comment by senadir** [comment] 2021-01-24 20:28
Hey there, it seems you have a cache plugin that is minfying and concating JS files, can you disable all cache plugins and try again?

**Comment by budzanowski** [comment] 2021-01-26 11:20
Closing for now as we know that this problem is caused by caching issues. If after disabling cashing the problem persist please reopen the issue.

**Closed as completed by budzanowski** 2021-01-26 11:20 UTC
Labels: type: bug
