### ISSUE TITLE
JS update woocommerce/filter-wrapper

### ISSUE THREAD

**Issue by dan-zakirov** [woocommerce/woocommerce-gutenberg-products-block#8725] opened 2023-03-14 07:52 UTC
I mean [this block](http://img.alexodlw.beget.tech/2023-03-08_185140.png)

The block is called “Filter by Stock”.

### Let’s break down step by step how it is loaded

1. The page is loaded
2. When the page loads, this file /wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/stock-filter-wrapper-frontend.js is called (or a file from your plugin)
3. After processing the file [this block appears ](http://img.alexodlw.beget.tech/2023-03-08_185140.png)

### What does it look like visually?

1. When the page loads, the [block is loaded](http://img.alexodlw.beget.tech/2023-03-08_190129.png) and something from the stock-filter-wrapper-frontend.js file is called
2. After the stock-filter-wrapper-frontend.js file runs, [the block appears as](http://img.alexodlw.beget.tech/2023-03-08_185140.png
)

### What is my problem?

I have other filters on my site, and when they work an ajax request occurs, which for some reason erases the HTML structure “Filter by Stock”. [It goes like this](http://img.alexodlw.beget.tech/bag.gif) 

That is, the block [goes to the state](http://img.alexodlw.beget.tech/2023-03-08_190129.png) and further does not load

### How I temporarily solved the problem?

I decided to call this block after AJAX request was loaded:

```
jQuery(document).ajaxStop(function() {
// here I call the code from your plugin
// woo-gutenberg-products-block/build/filter-wrapper-frontend.js
});
```

And magic… Everything works fine, but it looks terrible [in the code]( http://img.alexodlw.beget.tech/2023-03-08_193517.png)

### What do I want to end up with?

Either way there should be a “Filter by Stock” initialization call or some kind of trigger or JS event that re-builds the HTML, it also works if I call all the code from the file

For example, on woocommerce [there are such triggers](http://img.alexodlw.beget.tech/2023-03-08_194047.png) 

In any case there should be some event on initialization of “Filter by Stock” so I can call it here:

```
jQuery(document).ajaxStop(function() {
// I want to trigger an event here that will display the block
});
```

??

**Comment by kmanijak** [comment] 2023-03-16 14:42
Hi @dan-zakirov, thanks a lot for raising the issue and the whole explanation!

Would you be able to provide us with testing steps, so we could reproduce it on our side? 

> I have other filters on my site, and when they work an ajax request occurs, which for some reason erases the HTML structure “Filter by Stock”.

Is it one of WooCommerce Blocks filters or do you use another plugin that we could test it with?

I'd like us to try to find a root cause and a fix, before thinking about extending the block API. 🙌

**Comment by dan-zakirov** [comment] 2023-03-16 14:46
@kmanijak Hi 

Template woodmart and fillers that uses this template. But, that's not what I asked. I need an initialization event “Filter by Stock”

**Comment by roykho** [comment] 2023-03-31 13:52
Hi @dan-zakirov - I understand you looking for a trigger to use to initialize the block however it seems the issue and/or question is why is the `Filter by Stock` block disappearing? Is that not the main culprit?

**Comment by Aljullu** [comment] 2023-04-21 12:45
Hey there @dan-zakirov! As we didn't hear back from you for over two weeks, I will proceed closing this issue. But if you want to continue the discussion, feel free to leave a comment and we will reopen it. :slightly_smiling_face:

**Closed as not planned by Aljullu** 2023-04-21 12:45 UTC
Labels: type: bug, block: filter by stock
