### ISSUE TITLE
Align height of Add coupon form and Apply button

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-gutenberg-products-block#10890] opened 2023-09-12 03:33 UTC
## Describe the bug

Currently, the Add coupon form height is different to the height of the Apply button. These should be consistent to increase trust, reduce noise, and for overall visual alignment.

## To reproduce

On any theme, go to the Cart or Checkout blocks and choose "Add a coupon". The form and Apply button misalignment will appear. There's also the same issue mentioned in #10889 where the input and helper text padding needs to be reduced.

## Expected behavior

In the designs the height of the form field is aligned with the button at 48px. @mikejolley Is there any way to create this alignment between the two regardless of theme?

## Screenshots

Current
<img width="476" alt="Screen Shot 2023-09-11 at 10 31 20 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/cb04d833-ff37-4a12-bc8a-3d14644ebdd7">

Expected
<img width="399" alt="Screen Shot 2023-09-11 at 10 25 16 PM" src="https://github.com/woocommerce/woocommerce-blocks/assets/5121465/cbd87659-87ae-406f-a03c-884cb6caa4e0">

cc @pmcpinto

**Comment by anshulsoni4** [comment] 2023-09-20 05:22
hey @mikejolley can you assign this to me

**Comment by mikejolley** [comment] 2023-09-20 11:30
Hi @anshulsoni4. This issue is due to be tackled in a few weeks, but yeah if you want to give it a shot before then by all means 👍🏻 Let us know if you need anything.

**Comment by tarunvijwani** [comment] 2023-10-19 16:49
@elizaan36 I'm unable to reproduce the issue. I tried multiple themes, and button seems to be aligned with the coupon field. Below are the screenshots:

## Storefront:

| Cart | Checkout |
|---|---|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/9c9d1887-d9c8-411b-a7c8-b0f36517891f)|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/85edc9e1-c881-49c7-8e22-0ca775f97ef1)|


## Twenty-Twenty Three
| Cart | Checkout |
|---|---|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/522e1512-9499-4335-90dd-3bbed4dc35d4)| ![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/d18bb97c-7bf8-43c2-b523-a12279ccfcfc)|


## Twenty-Twenty Two
| Cart | Checkout |
|---|---|
|![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/b3bdc6aa-d84f-4a22-a16f-3b1ccae02594)| ![image](https://github.com/woocommerce/woocommerce-blocks/assets/11503784/f1672d36-23e3-4a88-ad1a-4a281ee9af0b)|


Is this happening with any specific theme? Please correct me if I'm missing anything. Looking forward to hearing back from you.

**Comment by elizaan36** [comment] 2023-10-26 17:32
Thanks @tarunvijwani , This looks fixed! Next is to get the CTA corder radius to match but that's for another time.

**Comment by tarunvijwani** [comment] 2023-10-27 13:22
Thank you for confirming! I'll close the issue. 👍

**Closed as completed by tarunvijwani** 2023-10-27 13:22 UTC
Labels: type: bug, type: good first issue, block: cart, block: checkout, focus: global styles
