### ISSUE TITLE
2 issues relating to cart and checkout page

### ISSUE THREAD

**Issue by hamza81952** [woocommerce/woocommerce-gutenberg-products-block#3045] opened 2020-08-24 18:28 UTC
very impressive work but i noticed 2 issues. kindly consider resolving them.
1-cart page issue= everything is working perfectly on desktop version but when we go on mobile version discounted price is not showing overlined, for example if we add a sale product of 599 original price and 500 discounted price, it should be overlined 599 (line cutting 599 from middle) which is perfectly working on desktop but when we see mobile view both prices visible without line cutting original price so it is a confusing situtaion for our customer why i am seeing two prices of single product 599 and 500?
2-checkout page issue= product thumbnail is showing only on desktop version but not showing on mobile view.
![Screenshot_2020-08-24 Cart – fastaan](https://user-images.githubusercontent.com/70037890/91082041-7d805500-e661-11ea-8824-a9a4faf43eda.png)
![Screenshot_2020-08-24 Cart – fastaan(1)](https://user-images.githubusercontent.com/70037890/91082050-807b4580-e661-11ea-8e1c-971a741a33e9.png)

**Comment by nerrad** [comment] 2020-08-25 13:11
Hi there, thanks for your report!

Regarding issue one: That is a duplicate of #2991 (we're already aware of it).
Regarding issue two: I'm still seeing the product thumbnail in mobile view. One thing you might not be aware of is that by default when the mobile view loads for checkout, the order summary container is _collapsed_ by default to remove extraneous information from the purchase process. More details can be seen by clicking the arrow next to the Order Summary header.

I'm going to close this because there's nothing to be addressed specifically from this report. Please do add additional comments if you think there's something else we need to know or you feel there's something I have missed.

**Closed by nerrad** 2020-08-25 13:11 UTC
