### ISSUE TITLE
Backward Compatibility Issues with WooCommerce Cart and Checkout Templates after Update

### ISSUE THREAD

**Issue by chvillanuevap** [woocommerce/woocommerce-gutenberg-products-block#10927] opened 2023-09-13 06:17 UTC
After updating to the latest version of WooCommerce Blocks, I've observed several backward compatibility issues:

1. The URLs to edit the Cart and Checkout pages have changed to use the FSE:

- Previous: `https://www.mysite.com/wp-admin/post.php?post=XXXX&action=edit`
- Current: `https://www.mysite.com/wp-admin/site-editor.php?postType=wp_template&postId=woocommerce%2Fwoocommerce%2F%2Fcart`
2. Two `wp_template` posts have been added to the database.
3. There's a notable change in the appearance of my Cart and Checkout pages. Specifically, the Checkout page now lacks the header consistent with the rest of my website.

<img width="1512" alt="Screen Shot 2023-09-13 at 12 14 11 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/3827771/f53d584c-b5cc-4db6-a889-aaba4546055d">
<img width="1512" alt="Screen Shot 2023-09-13 at 12 14 17 AM" src="https://github.com/woocommerce/woocommerce-blocks/assets/3827771/9129acd6-dff4-43b4-a555-0303407767bb">

These changes were unexpected and happened automatically after the plugin update. This breaks backward compatibility as the site design and layout were modified without any prior notice.

I've previously customized my Cart and Checkout templates using a mix of blocks and shortcodes.

**Question:** Is there a filter to disable the new Site Editor templates and revert to the previous block and shortcode setup (besides deactivating the plugin)?

**Comment by webmandesign** [comment] 2023-09-13 11:34
Hi @chvillanuevap,

I've reported similar issues at #10595 and [others](https://github.com/woocommerce/woocommerce-blocks/issues?q=is%3Aissue+author%3Awebmandesign), but [I was advised](https://github.com/woocommerce/woocommerce-blocks/issues/10595#issuecomment-1683869402) to log this to discussion board.

Can you please chime in and report your findings there so the WC team can start reconsidering/resolving this new approach? You can find the discussion board issue at https://github.com/woocommerce/woocommerce-blocks/discussions/10703

Thanks.

**Comment by mikejolley** [comment] 2023-09-14 14:00
These changes only impact stores using block based themes. We're working on a solution for the next release to keep pages around for content (see https://github.com/woocommerce/woocommerce-blocks/pull/10773) which is a large part of the problem.

> Is there a filter to disable the new Site Editor templates and revert to the previous block and shortcode setup (besides deactivating the plugin)?

No, for block themes the site editor is needed. It wouldn't be feasible to maintain both approaches for block themes as it would further complicate usage.

You will however be able to edit pages again once #10773 is merged.

> Two wp_template posts have been added to the database.

The creation of `wp_template` is not a bug. These are customised templates which were based on the content of your pages and they override the defaults.

> There's a notable change in the appearance of my Cart and Checkout pages. Specifically, the Checkout page now lacks the header consistent with the rest of my website.

This is an unfortunate side effect of the new templates/default distraction free header. You can customise this via the site editor under Appearance > Templates > Checkout and then click the header area. From there you can customise it in place or edit the header template part.

cc @pmcpinto @wavvves

**Comment by ralucaStan** [comment] 2023-09-27 13:41
https://github.com/woocommerce/woocommerce-blocks/pull/10773 was merged and will be released this week in WooCommerce Blocks 11.2.0.

closing this issue as there is nothing actionable on our end

**Closed as completed by ralucaStan** 2023-09-27 13:41 UTC
Labels: focus: documentation, block: cart, block: checkout, focus: template
