### ISSUE TITLE
Remove checkout-draft from the status dropdown

### ISSUE THREAD

**Issue by GRSM78** [woocommerce/woocommerce-gutenberg-products-block#7582] opened 2022-11-04 16:32 UTC
Is there any way to remove the checkout-draft from the status dropdown in the admin dashboard? For some reason `unset( $order_statuses['wc-checkout-draft'] );` doesn't work here while working for any other status

**Comment by GRSM78** [comment] 2022-11-04 16:37
Just in case here's a whole code I'm using to remove those:

`// Admin order edit page: order status dropdown
function filter_wc_order_statuses( $order_statuses ) {  
    global $post, $pagenow;

    // Target edit pages
    if( $pagenow === 'post.php' && isset($_GET['post']) && $_GET['action'] == 'edit' && get_post_type($_GET['post']) === 'shop_order' ) {
        // Get ID
        $order_id = $post->ID;

        // Get an instance of the WC_Order object
        $order = wc_get_order( $order_id );

        // Is a WC order
        if ( is_a( $order, 'WC_Order' ) ) {
            // Get current order status
            $order_status = $order->get_status();

            // Compare
            if ( $order_status == 'approved' ) {
                                unset( $order_statuses['wc-completed'] );
				unset( $order_statuses['wc-pending'] );
				unset( $order_statuses['wc-on-hold'] );
				unset( $order_statuses['wc-failed'] );
				unset( $order_statuses['wc-cancelled'] );
				unset( $order_statuses['wc-checkout-draft'] );
				unset( $order_statuses['wc-refunded'] );
			
			} elseif ( $order_status == 'processing' ) {
                                unset( $order_statuses['wc-completed'] );
				unset( $order_statuses['wc-pending'] );
				unset( $order_statuses['wc-on-hold'] );
				unset( $order_statuses['wc-failed'] );
				unset( $order_statuses['wc-rejected'] );
				unset( $order_statuses['wc-checkout-draft'] );
				unset( $order_statuses['wc-refunded'] );
				unset( $order_statuses['wc-cancelled'] );
          } 
        }
    }
    
    return $order_statuses;
} add_filter( 'wc_order_statuses', 'filter_wc_order_statuses', 10, 1 );`

**Comment by wavvves** [comment] 2022-11-08 17:52
Hi @GRSM78, thank you for reaching out.

Judging by the provided snippet provided, you want to remove some status from being added to _approved_ and _in process_ orders, eg rolling them back, correct?

'wc-checkout-draft' is added by the DraftOrders class, and may not have been available at the time your filter runs, have you tried to decrease the priority (eg increasing '10' to '100')?

I would also add you'd want this to be the absolute last order status manipulation running and only on the shop_order edit page.
Draft order status is used before payment is attempted, during checkout, when a cart is converted to an order. Removing this may have unwanted effects.

**Comment by tarunvijwani** [comment] 2022-11-25 08:23
@GRSM78 I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2022-11-25 08:23 UTC
