### ISSUE TITLE
Checkout Block: Order not getting created and order notifications not sent after completing purchase.

### ISSUE THREAD

**Issue by abstractionltd** [woocommerce/woocommerce-gutenberg-products-block#2657] opened 2020-06-06 12:19 UTC
**Describe the bug**
Replaced woocommerce standard checkout with blocks
proceeded to checkout, all is fine and the order confirmation screen is shown but processed almost instantly where classic checkout would take a couple of seconds before showing confirmation

* Problem 1: no order email sent to customer or store admin
* Problem 2: no actual order created in the admin

**Expected behavior**
Order should be created in admin and all relevant notifications sent

**Screenshots**
NA since no error was present

**WordPress (please complete the following information):**

* Core version: 5.4.1
* Gutenberg version (if installed): NA
* WooCommerce version: 4.2.0
* WooCommerce Blocks version: 2.6.1
* Site language: en-nz
* Any other plugins installed: google analytics, divi, flycart, automate woo, application passwords, woo coupons, woo subscriptions, woo stripe, wp mail log, wp smtp, wordfence

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Chrome
* Version: 83.0.4103.97 64-bit

**Comment by nerrad** [comment] 2020-06-07 10:37
HI there,

Thanks for creating the bug report here! Would you mind answering a few more questions please?

- What payment method are you using to complete the order?
- What type of product(s) are you testing the purchase with?
- Are there any customizations on your (non-block) shortcode based checkout/order-received pages?
- Do you have access to the PHP Error logs on the server you are doing the testing? Are there any error notices/warnings recorded in the logs around the time of your testing?
- Are you able to consistently reproduce this for every purchase through the new Checkout block or does it happen inconsistently for you?
- Is the purchase made while the user is logged in or is it a guest checkout?

**Comment by abstractionltd** [comment] 2020-06-08 23:55
Sure, answers below:

* Stripe
* Simple products 
* Nope - just the blocks shortcode
* no errors I could find
* 100% error rate when using the checkout block
* both guest and logged in

**Comment by nerrad** [comment] 2020-06-09 14:46
Hmm, I'm not able to reproduce and we haven't had any other reports of this. With Stripe, are you using [this extension](https://woocommerce.com/products/stripe/)? And what payment method from Stripe are you using? The blocks only support Stripe Credit Card payment method (along with the payment request methods powering express payments, which are Apple Pay, Chrome Pay etc).

Would you be able to share a screenshot of what the payment method area looks like for the checkout block? It should be something like this (except in your case you might not have cheque or paypal standard active):

<img width="800" alt="Image 2020-06-09 at 10 45 13 AM" src="https://user-images.githubusercontent.com/1429108/84162387-52ad3a00-aa3e-11ea-96f8-63c00019de5d.png">

The screenshot is from using the Storefront theme.

I also just noticed in your original report that you mentioned you're using the Divi theme. If you are able to test with a different theme (such as Storefront), do things work okay? If so, then that narrows it down to a conflict with Divi.

**Comment by nerrad** [comment] 2020-06-09 14:57
I downloaded and activated the Divi theme and I'm still not able to reproduce the issue. It might still be worthwhile if you're able to try a different theme to see if things work for you. It's possible it may be a specific configuration you have with Divi that is causing the errors.

You may also want to try temporarily deactivating some of the plugins you have active (flycart might be one to start with) to see if things work without it active.

We're keen to help, but until we find out what is causing this issue for your environment, there's not much we can do. Thanks for hanging in there so far!

**Comment by abstractionltd** [comment] 2020-06-09 20:24
Hey there,

Thanks for the reply. I cloned the site to stating this morning and disabled everything excluding woo, woo services and woo blocks. I started turning on the plugins 1 by 1 and found the offending plugin to be [WooCommerce Order Status Manager](https://woocommerce.com/products/woocommerce-order-status-manager/). The site is running the latest 1.11.8 version of the plugin. There is nothing in the PHP error log that matches this plugin, and we do need it since it forms part of my client's integration with their 3PL.

I am happy to email you access details to the staging site if you want to jump on.
H

**Comment by nerrad** [comment] 2020-06-11 14:59
Thanks for sharing the plugin. I'm not having issues with orders being created with that plugin active, but I am seeing that emails aren't sent. 

The new Checkout block introduces a _new_ order status of "Draft" (slug is `checkout-draft`) that was introduced to the flow to support creating orders as soon as the checkout flow is started. Among other things, this allows for tracking any changes to the order during checkout and secure order attachment to specific customers through new REST endpoints.

Because it's possible customers might abandon the checkout flow, there is a scheduled task that will automatically delete draft orders on a rolling daily basis to prevent store databases from getting clogged with any of those orders.

How does this affect your situation?

The Order Status Manager plugin is an extension that allows customizing the order status flow including what emails are triggered at points in that flow. Since it sounds like you've used this to customize a number of statuses, I'm guessing that the issue is that the new draft status order is not included in whatever flow you have configured. So it would be a matter of [following the instructions for the extension](https://docs.woocommerce.com/document/woocommerce-order-status-manager/) to configure your flow to include the new draft status.

I hope that helps! I'm going to close this issue because it's not really a bug, but rather a configuration issue around an extension. If you still have issues configuring things, you can get in touch [with our support team](https://docs.woocommerce.com/document/how-to-get-help/) for additional assistance.

I _really appreciate you creating this issue_, I'm notifying our support team about this being a potential thing folks can experience as they try the new blocks.

**Closed by nerrad** 2020-06-11 14:59 UTC
Labels: ◼️ block: checkout

**Comment by nerrad** [comment] 2020-06-11 15:16
I should add, one reason why you may not be seeing the order in your backend is because by default, draft orders are not shown in the main order list:

<img width="1755" alt="Image 2020-06-11 at 11 15 14 AM" src="https://user-images.githubusercontent.com/1429108/84404508-ea449100-abd4-11ea-8253-f2211ff06527.png">
_Notice that I'm in the "Draft" view for the Order list table_

**Comment by abstractionltd** [comment] 2020-06-12 00:34
Right, I get that but what's happening is that I can try and create several orders with the plugin active and each time the order number shown on the confirmation remains the same. So the order is literally not being created at all, not as draft or otherwise.

add to cart > checkout test mode using stripe > order confirmed with order number 123
then
new incognito window > add to cart > checkout test mode > order confirmed with order number 123 again

And the loop continues...

**Comment by nerrad** [comment] 2020-06-14 13:33
> So the order is literally not being created at all, not as draft or otherwise.

For me, with the Order Status Manager plugin freshly activated with zero configuration, I'm not getting this behaviour. New orders are created and show up in the order list table (and db) for each test transaction. I followed these steps:

- Activate Order Status  Manager plugin.
- While logged in, purchase products (using Stripe test mode) and take note of order number.
- In incognito mode, purchase products (using Stripe test mode) - I also purchased same products in my test. The order number is different than the original.
- I tried multiple variations including starting orders in different browsers, leaving one order incomplete etc and in all cases new orders are getting created as expected.

I'm definitely interested in helping resolve this but at this point it does look like it might have something to do with how your site is configured with the Order Status Manager plugin. It could be something to do with a custom flow setup maybe?

**Comment by madeincosmos** [comment] 2020-07-06 15:12
I found one more user with the same problem in 3120554-zen, Order Status Manager isn't used on this site, problem still happens when I switch away from Divi to TwentyTwenty. 

Can't reproduce the same behavior on my test sites, I'm wondering if this might be related to server setup rather than some other plugins or themes active.

I'll keep you updated if further tests show anything.

**Comment by madeincosmos** [comment] 2020-07-10 14:11
Updating to WooCommerce 4.3 and Blocks 2.9.0 solved the problem in 3120554-zen.

**Comment by nerrad** [comment] 2020-07-10 17:43
> Updating to WooCommerce 4.3 and Blocks 2.9.0 solved the problem in 3120554-zen.

Great! Thanks for the update 👍
