### ISSUE TITLE
Z-indexing on mini cart toolbar 

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7194] opened 2022-09-21 16:04 UTC
I noticed an issue with the toolbar being slightly behind the content layer. 

<img width="615" alt="Screenshot 2022-09-21 at 17 02 20" src="https://user-images.githubusercontent.com/9888201/191554408-f009b5bf-af9f-4895-afab-8b4631ab80d7.png">

**Comment by albarin** [comment] 2023-03-01 10:40
@vivialice I haven't been able to reproduce this, this is what I see. Are you still seeing this problem? Which theme are you using? Thanks!
<img width="656" alt="Screenshot 2023-03-01 at 11 38 50" src="https://user-images.githubusercontent.com/186112/222116082-7789e477-9808-4c43-8beb-2f22ea15539f.png">

**Comment by Aljullu** [comment] 2023-03-01 13:39
I'm not able to reproduce it either. Let's close it for now, we can always reopen if somebody can reproduce again.

**Closed as not planned by Aljullu** 2023-03-01 13:39 UTC
Labels: type: bug, focus: global styles, block: mini-cart
