### ISSUE TITLE
product page image not visible (styling/single product regression?)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2646] opened 2020-06-05 01:18 UTC
**Describe the bug**
With WooCommerce Blocks installed and active (current master - 6b1eea33056071c28bb796514d7c1972ea0fdd47), the main product image is not showing on product pages. 

<img width="1005" alt="Screen Shot 2020-06-05 at 1 10 09 PM" src="https://user-images.githubusercontent.com/4167300/83825740-55eab200-a72e-11ea-8d8a-bc31dd20171f.png">

With WooCommerce Blocks deactivated, the image shows up. This affects all browsers I tried - Chrome, Safari, Firefox.

Looking at the CSS I don't immediately see why it's not showing - 🤷🏻‍♂️

I spotted this when testing Storefront (https://github.com/woocommerce/storefront/pull/1368). (Confirmed the storefront PR branch is not relevant to this - issue reproducible on Storefront master.)

Apologies if this is already known/reported or in progress on another branch - I couldn't find an issue so logging one.

**To Reproduce**
1. Ensure your store has products with images.
2. View a product page, e.g. `/product/sunglasses/`

With WooCommerce Blocks active on master, you should not see a product image.

If you deactivate WooCommerce Blocks, the image is visible.

**Comment by haszari** [comment] 2020-06-05 01:23
Looks like this affects other themes - tested Twenty Seventeen:

<img width="1637" alt="Screen Shot 2020-06-05 at 1 22 55 PM" src="https://user-images.githubusercontent.com/4167300/83826323-bb8b6e00-a72f-11ea-8991-d565534dbd0a.png">

**Comment by Aljullu** [comment] 2020-06-05 06:11
I can reproduce it too, it looks like `.woocommerce-product-gallery` doesn't get `opacity: 1` for some reason. Marking this as blocker for now.

**Closed** 2020-06-05 12:19 UTC
Labels: type: blocker, type: bug
