### ISSUE TITLE
7.7.0 Issue with Cart & Checkout Page Editing

### ISSUE THREAD

**Issue by Stella3** [woocommerce/woocommerce-gutenberg-products-block#9710] opened 2023-05-11 15:17 UTC
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

With Twenty Twenty Three theme and no plugins at all except for WooCommerce, 7.7.0 removes the ability to see or edit previously added content on the Cart and Checkout pages.

### Expected behavior

Should be able to edit Cart & Checkout pages and see previously added blocks.

### Actual behavior

Update to 7.7.0 and all previously added blocks from on the Cart and Checkout pages are gone from the editor. They still show up on the front end. 

### Steps to reproduce

Before update:
![Screenshot 2023-05-11 at 11-00-24 Edit Page “Cart” ‹ Frame   Thread — WordPress](https://github.com/woocommerce/woocommerce/assets/19824054/88b8c19e-9668-4ed7-8a30-a2bf9e8df4f4)

Here goes:
![Screenshot 2023-05-11 at 11-02-03 Plugins ‹ Frame   Thread — WordPress](https://github.com/woocommerce/woocommerce/assets/19824054/c2d81787-27dd-430a-a025-a9d9e6b7b446)

After update:
![Screenshot 2023-05-11 at 11-05-31 Edit Page “Cart” ‹ Frame   Thread — WordPress](https://github.com/woocommerce/woocommerce/assets/19824054/6323073e-a518-4e5f-9b4d-c53a95856be1)

Note, this is from a Local site but the behavior is exactly the same on our live site. 

### WordPress Environment

`
### WordPress Environment ###

WordPress address (URL): https://frame-thread.local
Site address (URL): https://frame-thread.local
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.2.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.77.0
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_fo40na56ca_
Total Database Size: 210.94MB
Database Data Size: 129.03MB
Database Index Size: 81.91MB
wp_fo40na56ca_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_woocommerce_order_items: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_fo40na56ca_woocommerce_order_itemmeta: Data: 10.52MB + Index: 12.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_woocommerce_payment_tokens: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_woocommerce_payment_tokenmeta: Data: 0.25MB + Index: 0.30MB + Engine InnoDB
wp_fo40na56ca_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_actions: Data: 1.42MB + Index: 1.44MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_actionscheduler_logs: Data: 1.44MB + Index: 1.72MB + Engine InnoDB
wp_fo40na56ca_aryo_activity_log: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_atum_export_templates: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_atum_order_itemmeta: Data: 0.30MB + Index: 0.31MB + Engine InnoDB
wp_fo40na56ca_atum_order_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_atum_product_data: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_commentmeta: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_fo40na56ca_comments: Data: 7.52MB + Index: 9.09MB + Engine InnoDB
wp_fo40na56ca_eg_grids: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_eg_item_elements: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_eg_item_skins: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_eg_navigation_skins: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_elfsight_instagram_feed_ig_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_elfsight_instagram_feed_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_elfsight_instagram_feed_widgets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_hurrytimer_evergreen: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_mailster_action_bounces: Data: 0.42MB + Index: 0.17MB + Engine InnoDB
wp_fo40na56ca_mailster_action_clicks: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_fo40na56ca_mailster_action_errors: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_mailster_action_opens: Data: 1.52MB + Index: 2.20MB + Engine InnoDB
wp_fo40na56ca_mailster_action_sent: Data: 1.52MB + Index: 3.47MB + Engine InnoDB
wp_fo40na56ca_mailster_action_unsubs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_mailster_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_mailster_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_mailster_forms_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_mailster_forms_tags: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_mailster_links: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_mailster_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_mailster_lists_subscribers: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_fo40na56ca_mailster_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_mailster_queue: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_fo40na56ca_mailster_subscriber_fields: Data: 0.13MB + Index: 0.25MB + Engine InnoDB
wp_fo40na56ca_mailster_subscriber_meta: Data: 1.52MB + Index: 5.06MB + Engine InnoDB
wp_fo40na56ca_mailster_subscribers: Data: 0.16MB + Index: 0.22MB + Engine InnoDB
wp_fo40na56ca_mailster_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_mailster_tags_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_mwai_chats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_options: Data: 16.30MB + Index: 0.25MB + Engine InnoDB
wp_fo40na56ca_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_post_smtp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_postmeta: Data: 42.56MB + Index: 29.11MB + Engine InnoDB
wp_fo40na56ca_posts: Data: 10.52MB + Index: 1.25MB + Engine InnoDB
wp_fo40na56ca_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_usermeta: Data: 6.52MB + Index: 10.03MB + Engine InnoDB
wp_fo40na56ca_users: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_fo40na56ca_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wc_customer_lookup: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_fo40na56ca_wc_order_product_lookup: Data: 1.52MB + Index: 1.23MB + Engine InnoDB
wp_fo40na56ca_wc_order_stats: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
wp_fo40na56ca_wc_order_tax_lookup: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_fo40na56ca_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_fo40na56ca_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_reserved_stock: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wcpdf_packing_slip_number: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_wfconfig: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wffilemods: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfhits: Data: 1.47MB + Index: 0.30MB + Engine InnoDB
wp_fo40na56ca_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wfissues: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_wfknownfilelist: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wflogins: Data: 0.50MB + Index: 0.16MB + Engine InnoDB
wp_fo40na56ca_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fo40na56ca_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfnotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_fo40na56ca_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_fo40na56ca_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_fo40na56ca_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fo40na56ca_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Blocks: by Automattic – 10.2.0
WooCommerce: by Automattic – 7.7.0

### Inactive Plugins (32) ###

Activity Log: by Activity Log Team – 2.8.6
AI Engine: ChatGPT Chatbot, Content Generator, GPT 3 & 4, Ultra-Customizable: by Jordy Meow – 1.6.75
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.29.1
B2BKing Core: by WebWizards – 4.2.50
B2BKing Pro: by WebWizards – 4.1.82
Code Snippets: by Code Snippets Pro – 3.3.0
Contact Form 7: by Takayuki Miyoshi – 5.7.6
Elfsight Instagram Feed CC: by Elfsight – 4.0.3
Essential Grid: by ThemePunch – 3.0.17.1
Essential Grid Google Fonts Addon: by ThemePunch – 1.1.1
GA Google Analytics: by Jeff Starr – 20230306
Heartbeat Control by WP Rocket: by WP Rocket – 2.0
HurryTimer PRO: by Nabil Lemsieh – 2.10.0
Jetpack: by Automattic – 12.1
Mailster - Email Newsletter Plugin for WordPress (Premium): by EverPress – 3.3.3
Mailster SendGrid Integration: by EverPress – 2.1
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.40

PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.2
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.14.1
Post SMTP: by Post SMTP – 2.5.1
Query Monitor: by John Blackbourn – 3.12.2
SEOPress: by The SEO Guys at SEOPress – 6.6.3
Superfly Menu: by Looks Awesome – 5.0.14
User Switching: by John Blackbourn & contributors – 1.7.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.7
WooCommerce Email Customizer with Drag and Drop Email Builder: by Flycart Technologies LLP – 1.5.16
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce Stripe Gateway: by WooCommerce – 7.4.0
Wordfence Security: by Wordfence – 7.9.2
WP File Manager: by mndpsingh287 – 7.1.9
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.8

XforWooCommerce: by XforWooCommerce – 1.7.0

### Dropin Plugins (1) ###

db-error.php: db-error.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: woocommerce/woocommerce#109 - /shop/
Cart: woocommerce/woocommerce#110 - /cart/
Checkout: woocommerce/woocommerce#111 - /checkout/
My account: woocommerce/woocommerce#112 - /my-account/
Terms and conditions: woocommerce/woocommerce#132 - /terms-conditions/

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-12 00:07:34 -04:00
Options: ✔
Notes: 150
Onboarding: completed

### Action Scheduler ###

Complete: 3,808
Oldest: 2023-03-28 19:27:32 -0400
Newest: 2023-05-11 11:08:34 -0400

Failed: 36
Oldest: 2023-02-19 17:06:11 -0500
Newest: 2023-05-11 11:03:15 -0400

Pending: 5
Oldest: 2023-05-12 10:51:53 -0400
Newest: 2023-05-18 10:51:56 -0400

### Status report information ###

Generated at: 2023-05-11 11:15:38 -04:00
`

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment] 2023-05-15 08:37
Hi @Stella3,

I'm not able to reproduce this in a test install. The test install has PHP 8.1.18. Try deactivating the WooCommerce Blocks plugin in your test install to see if that resolves the issue.

**Comment by Stella3** [comment] 2023-05-16 13:13
I'm really at a loss here because this is now a stripped down 4 page site with 1 theme installed - Storefront and only 1 plugin - WooCommerce. PHP 8.1.18.

7.7.0 has the problem and rolling back to 7.6.1 fixes it. 

I also noticed 7.7.0 adds back cross-sells in the editor (a block I had removed) so it looks like it is attempting to default the page in the editor but the live page is my original setup. 

The only thing that solves this is rolling back to 7.6.1 and then removing all added blocks - setting it to default. Then update to 7.7.0 and rebuild the page from scratch. I'm sure I'm not the only one out there so hopefully this helps someone.

**Comment by coreymckrill** [comment] 2023-06-02 21:23
Moved this to the woocommerce-blocks repo because it appears to be related to cart blocks and store editing.

**Comment by tarhi-saad** [comment] 2023-06-09 23:24
Hello, @Stella3! 👋 Thank you for reporting this bug! I followed the following steps but couldn't reproduce the bug:

1. In a fresh WordPress site, I installed the WooCommerce plugin and rolled back to version 7.6.1
2. In the Cart editor page, I removed the cross-sells block and added some custom blocks/paragraphs
3. I updated the WooCommerce plugin to version 7.7.0. And I can see all the changes made in step 2 in the Cart Block editor and front-end pages

Am I missing something in my tests? And is this issue persisting in version 7.8.0 of the Woocommerce plugin?

**Comment by nielslange** [comment] 2023-06-23 07:39
Hello @Stella3, I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by nielslange** 2023-06-23 07:39 UTC
Labels: type: community contribution
