### ISSUE TITLE
Store Editing Templates: Preview feature in Site Editor doesnt work

### ISSUE THREAD

**Issue by tjcafferkey** [woocommerce/woocommerce-gutenberg-products-block#5733] opened 2022-02-07 12:20 UTC
The "Preview" feature does not work for WooCommerce templates in the Site Editor.

![Screenshot 2022-02-07 at 12 19 34](https://user-images.githubusercontent.com/8639742/152786916-7c5d7a89-f851-4c01-942f-0d3bde91d777.png)

**Comment by tjcafferkey** [comment] 2022-02-07 12:21
Depending on how much time/effort is required to fix this do we:

* Commit to fixing the issue right away
* Remove the Preview option until we've fixed it

I suppose we will need to understand how much work is involved before deciding.

cc: @Aljullu

**Comment by frontdevde** [comment] 2022-03-02 10:25
After investigating this issue, we've come to the conclusion that the Preview does work as intended. 
When selecting the Tablet and Mobile view, it does show the correct result i.e. reflect what the user would see in the editor when visiting on a tablet/mobile device. The result might just not be what a user would necessarily expect.

To clarify, on mobile viewports we show a small grey box instead of the template placeholder SVG. This was an intentional decision to reduce the amount of screen space that an SVG placeholder image representing the mobile view would take up. We favored the usability of a lower height block over the visual fidelity of a more accurate representation in this case. This way a user can move blocks around easily without having to scroll past a long (anyway inaccurate) placeholder. For more details see [the decision and related Slack discussion here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4949#issuecomment-953931002).

I will thus close this issue given that the Preview works as intended as per the above decision.

CC'ing @ifinoi as an FYI.

**Closed as completed by frontdevde** 2022-03-02 10:25 UTC
Labels: type: bug, focus: FSE, focus: template
