### ISSUE TITLE
Filter by Tag block error: Invalid parameter(s): attributes

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gutenberg-products-block#1234] opened 2019-11-21 03:25 UTC
**Describe the bug**
When trying to use the Filter by Tag block, after selecting a tag, I get an error shown within the block.

Error loading block: Invalid parameter(s): attributes

**To Reproduce**

1. Add Filter by Tag block a page.
2. Select a tag to display
3. See error

**Expected behavior**
I expected to be able to see my tagged products. :)
**Screenshots**
![https://cld.wthms.co/siTTkj](https://cld.wthms.co/siTTkj+)
Image link: https://cld.wthms.co/siTTkj

![https://cld.wthms.co/zJP6Eg](https://cld.wthms.co/zJP6Eg+)
Image link: https://cld.wthms.co/zJP6Eg

**WordPress (please complete the following information):**

* Core version: 5.3
* Gutenberg version (if installed): 6.9.0
* WooCommerce version: 3.8.0
* WooCommerce Blocks version: 2.5.0
* Site language: English
* Any other plugins installed:

```
### Active Plugins (24) ###

Query Monitor: by John Blackbourn – 3.4.0
Animated Blocks: by Virgiliu Diaconu – 1.0.5
Atomic Blocks - Gutenberg Blocks Collection: by atomicblocks – 2.2.0
AutomateWoo: by WooCommerce – 4.7.3
Block Gallery: by GoDaddy – 1.1.6
CoBlocks: by GoDaddy – 1.17.2
Code Snippets: by Shea Bunge – 2.13.3
Email Log: by Sudar – 2.3.1
Gutenberg: by Gutenberg Team – 6.9.0
Jetpack by WordPress.com: by Automattic – 7.9.1
Posts List Block: by Automattic – 1.1
User Switching: by John Blackbourn & contributors – 1.5.3
WooCommerce Blocks: by Automattic – 2.5.0
WooCommerce Admin: by WooCommerce – 0.22.0
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.6 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17 – Not tested with the active version of WooCommerce
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.17 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.25
WooCommerce Product Bundles: by SomewhereWarm – 5.14.0
WooCommerce FedEx Shipping: by WooCommerce – 3.4.24
WooCommerce USPS Shipping: by WooCommerce – 4.4.35
WooCommerce Square: by WooCommerce – 2.0.7
WooCommerce: by Automattic – 3.8.0
```

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by haszari** [comment] 2019-11-24 23:59
I saw this same symptom for the `Hand-picked products` block in the editor (using Woo sample product data). Note the block renders fine on the front end.

- WordPress 5.3, WooCommerce 3.8
- Add `Hand-picked products` block
- Select some products (I chose all the hats)
- See error in editor block preview

<img width="844" alt="Screen Shot 2019-11-25 at 12 55 06 PM" src="https://user-images.githubusercontent.com/4167300/69503840-d318bb80-0f82-11ea-876f-ae6e6686751a.png">

This request failed, with error:

`http://localhost:8222/wp-json/wp/v2/block-renderer/woocommerce/handpicked-products?context=edit&attributes%5Bcolumns%5D=4&attributes%5BeditMode%5D=false&attributes%5BcontentVisibility%5D%5Btitle%5D=true&attributes%5BcontentVisibility%5D%5Bprice%5D=true&attributes%5BcontentVisibility%5D%5Brating%5D=true&attributes%5BcontentVisibility%5D%5Bbutton%5D=true&attributes%5Borderby%5D=date&attributes%5Bproducts%5D%5B0%5D=20&attributes%5Bproducts%5D%5B1%5D=37&attributes%5Bproducts%5D%5B2%5D=22&attributes%5BalignButtons%5D=false&attributes%5BisPreview%5D=false&post_id=63&_locale=user`

```js
{
    "code": "rest_invalid_param",
    "message": "Invalid parameter(s): attributes",
    "data": {
        "status": 400,
        "params": {
            "attributes": "isPreview is not a valid property of Object."
        }
    }
}
```

**Comment by haszari** [comment] 2019-11-26 00:46
Closing as a duplicate of #1253 – @ryanr14 feel free to reopen if this is a separate issue.

**Closed by haszari** 2019-11-26 00:46 UTC
Labels: type: bug
