### ISSUE TITLE
Infinite loading with 4.9.0

### ISSUE THREAD

**Issue by Suriteka** [woocommerce/woocommerce-gutenberg-products-block#4346] opened 2021-06-14 09:39 UTC
## Describe the bug
Hello, since I've updated WooCommerce Blocks (4.9.0), when I visit a webpage or edit a page which contains a WooCommerce Block I have an infinite loading and then an error 500. Every webpages that contains a block don't load.

## To reproduce

1. Install WooCommerce Blocks 4.9.0

2. Either 
- Edit a page that contains a WooCommerce Gutenberg Block
- Go to a page in the front end that contains a WooCommerce Block

## Expected behavior
I should have my pages working without errors 500

### WordPress (please complete the following information):
* Core version: 5.7.2
* WooCommerce version: 5.3.0
* WooCommerce Blocks version: 4.9.0
* Site language: EN
* Any other plugins installed: EAN for WooCommerce, bbPress and YOAST

### Desktop (please complete the following information):
* OS: macOS, Windows and Linux
* Browser : Chrome, Safari and Firefox

## Additional context
I've already investigated, and it seems like the problem appeared when the **deprecated parts** were removed from the blocks. Since then, I can't update to the last version of WooCommerce (which embeds WooCommerce Blocks) or update to WooCommerce Block 2.9.0 (it's breaking with this version).

**Comment by nerrad** [comment] 2021-06-14 12:48
@Suriteka thanks for taking the time to leave a report. However, can you please clarify I few details.

You've reported you updated to WooCommerce blocks 4.9.0 however the latest version of the feature plugin developed in this repository is 5.3.0.  Are you referencing the same plugin?

Further, in the WordPress environment section, you list that you are using WooCommerce core 4.3.0 (the latest released version of Woo Core is **5.4.1**), and you are using WooCommerce Blocks version **2.9.0** (which is not what you reported in the main content of this issue).

It's unclear from your current report what your environment setup is but I do recommend that you make sure you are on the latest of all reported products.

**Comment by Suriteka** [comment] 2021-06-14 12:55
> @Suriteka thanks for taking the time to leave a report. However, can you please clarify I few details.
> 
> You've reported you updated to WooCommerce blocks 4.9.0 however the latest version of the feature plugin developed in this repository is 5.3.0. Are you referencing the same plugin?
> 
> Further, in the WordPress environment section, you list that you are using WooCommerce core 4.3.0 (the latest released version of Woo Core is **5.4.1**), and you are using WooCommerce Blocks version **2.9.0** (which is not what you reported in the main content of this issue).
> 
> It's unclear from your current report what your environment setup is but I do recommend that you make sure you are on the latest of all reported products.

Ah yes, I've updated my issue sorry. I'm using WooCommerce Blocks 4.9.0 actually. I would like to update, but I'm stuck at the latest versions, WooCommerce blocks is creating an infinite loop during the loading of the webpages. I tried to install WooCommerce Blocks 5.3.0 and WooCommerce Core 5.4.1 but then I have my error 500.

**Comment by nerrad** [comment] 2021-06-14 18:10
Thanks for the reply @Suriteka and for editing your original comment, however, it's still not clear to me.

> I've already investigated, and it seems like the problem appeared when the deprecated parts were removed from the blocks. Since then, I can't update to the last version of WooCommerce (which embeds WooCommerce Blocks) or update to WooCommerce Block 2.9.0 (it's breaking with this version).

What deprecated parts are you referring to? And from the last sentence where does the WooCommerce Blocks 2.9.0 come from? Is that a typo and do you mean when you update _from_ WooCommerce Blocks 4.9.0 to the latest version?

In the interest of moving things forward, I _think_ what you're reporting here is that you are seeing an error when you try updating to the latest version of WooCommerce Blocks and WooCommerce Core 5.4.1 and when you go back to your current versions (WooCommerce Blocks 4.9.0 and WooCommerce Core 4.3.0) you don't have the issue? 

If so, this does sound like something that may be specific to your website as this isn't something I've seen reported yet. Do you have access to your site's error logs? Ideally, if you're able to share with us what PHP error is reported that results in the fatal error on your website that will be helpful.

**Comment by nerrad** [comment] 2021-06-24 13:58
@Suriteka I'm going to close this because there still isn't anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we're able to reproduce we can re-open as necessary.

**Closed as completed by nerrad** 2021-06-24 13:58 UTC
Labels: type: bug
