### ISSUE TITLE
Deprecated: Function WP_Scripts::print_inline_script is deprecated since version 6.3.0! Use WP_Scripts::get_inline_script_data() or WP_Scripts::get_inline_script_tag() instead.

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce-gutenberg-products-block#10121] opened 2023-07-06 12:14 UTC
## Describe the bug

I get this message when woocommerce is active in wp 6.3

Deprecated: Function WP_Scripts::print_inline_script is deprecated since version 6.3.0! Use WP_Scripts::get_inline_script_data() or WP_Scripts::get_inline_script_tag() instead. in /var/docs/server.tst/public/wp-includes/functions.php on line 5452

When i turn off woocommerce it is gone

It is coming from woocommerce blocks minicart.php line 357 and 358

Please fix.

## To reproduce

install a clean wp 63. latest trunk build

install woocommerce

make sure debug mode is on.

activate the plugin and run through the install process.

logout and loginin. you will see the messages at the login screen already,

## Expected behavior

Please use the correct new function call as suggested by wp

### WordPress (please complete the following information):

wp 6.3 trunk latest build
latest woocommerce beta

### Desktop (please complete the following information):

any browser

### Smartphone (please complete the following information):

any mobile device

## Additional context

Thank you for your time and effords to fix this.

**Comment by webdados** [comment] 2023-07-11 10:01
This is a duplicate of #10004

**Comment by danieldudzic** [comment] 2023-07-11 11:10
Thank you for reporting. I'm closing this in favor of the existing issue: https://github.com/woocommerce/woocommerce-blocks/issues/10004

**Closed as completed by danieldudzic** 2023-07-11 11:10 UTC
Labels: type: bug, type: community contribution
