### ISSUE TITLE
Local Pickup UX may lead to unintentional selection by shoppers

### ISSUE THREAD

**Issue by dennisjonda** [woocommerce/woocommerce-gutenberg-products-block#9387] opened 2023-05-08 13:44 UTC
> When I enter an address, the "Shipping" and "Local Pickup" buttons appear above the shipping address. This disrupts the natural flow and makes it confusing for users. I think it would be better if the email field came first, followed by the shipping or billing address, then the two buttons, and finally, depending on the user's choice, either the shipping conditions or no further steps in the case of local pickup.

> This happens when a delivery address is entered. Users then receive the fields to fill out. I believe that customers are more likely to scroll down and enter the additional information rather than scrolling back up during checkout.

> Over the weekend (a busy sales weekend every year), I noticed that many people accidentally choose "Pickup in-store" because it's free. I think this usually happens when paying through PayPal Express, as the residential address is always displayed there. The residential address is often outside Zone 1, and since our website advertises free shipping for orders over €20 for only one city, everyone clicks on "Pickup in-store" instead of delivery, as delivery outside Zone 1 costs €12.95. However, it is necessary for customers on this website to always have their orders delivered to a different shipping address.

![grafik](https://user-images.githubusercontent.com/74372535/236837802-ae7f8675-f5f9-4320-b322-3899c54f1e59.png)

<details><summary>Original Report</summary>
## Describe the bug 
Hello,

I'd like to report some issues with the "Hide shipping costs until an address is entered" feature:

1. Address Entry: There seems to be an ongoing issue with entering addresses. Sometimes the page reloads, which requires re-entering the address, or the next steps don't always show up.
2. Incorrect Display of Shipping Methods: Despite selecting the option to hide shipping costs until an address is entered, all shipping methods are still displayed when I have three different shipping methods available (Everything in Germany: 1. PLZ from one City, 2. 14 Regions, 3. Everything else). Additionally, only the most expensive shipping method is always displayed.
3. User Experience: When I enter an address, the "Shipping" and "Local Pickup" buttons appear above the shipping address. This disrupts the natural flow and makes it confusing for users. I think it would be better if the email field came first, followed by the shipping or billing address, then the two buttons, and finally, depending on the user's choice, either the shipping conditions or no further steps in the case of local pickup.

## Screenshots
1. 
![grafik](https://user-images.githubusercontent.com/74372535/236837757-bb83a3ab-2afa-45ee-bf67-c7128a37bfdf.png)

2.
![grafik](https://user-images.githubusercontent.com/74372535/236838407-b73b70a9-4104-488d-99e7-6eecaec963f5.png)
![grafik](https://user-images.githubusercontent.com/74372535/236838472-871745c1-d437-412f-82e3-f2b89e53b0b5.png)

3.
![grafik](https://user-images.githubusercontent.com/74372535/236837802-ae7f8675-f5f9-4320-b322-3899c54f1e59.png)

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   WooCommerce version: 7.6.1
-   WooCommerce Blocks version: 10.1.0
-   Site language: German, English
-   Any other plugins installed: Reproduced this Bug with only WooCommerce and Elementor

### Desktop (please complete the following information):

-   OS: Windows
-   Browser: chrome, firefox
-   Version 11

### Smartphone (please complete the following information):

-   Device: iPhone 14 Pro
-   OS: iOS
-   Browser chrome, firefox 
-   Version 16.4.1 (a)
</details>

**Comment by dennisjonda** [comment] 2023-05-11 22:53
I'm not sure why, but for some reason, the feature to hide shipping costs is working exceptionally well in Version 9.8.4.

**Comment by nielslange** [comment] 2023-05-12 05:32
Hello @dennisjonda,

Thanks for bringing this to our attention. Can you tell me how to reproduce this issue?

**Comment by dennisjonda** [comment] 2023-05-16 18:48
Hey @nielslange,
I apologize for the delay. :/ 

1. Address Entry: This happens sometimes, when I renter a ZIP code and a city. What I also saw that the city input tends to shift left and right after entering a ZIP Code.

2. Incorrect Display of Shipping Methods: This occurs when I have three different shipping zones:

Zone 1: Germany and 61440 (Delivery €7, free delivery for orders over €20)
Zone 2: Germany and 60*, 61*, 658*, 657*, 658* (Delivery €7, free delivery only with a voucher)
Zone 3: Germany (Delivery €12.95) <- In this case, the most expensive shipping method is always displayed
("Pickup in-store" from WooCommerce Blocks is also active, but it's free)

I would like to remove the view in the shopping cart because I want visitors to see the total cost only at the checkout. This issue is not present in version 9.8.4 (which I currently have to use because this problem still exists in version 10.2.0 :/), but only for non-logged-in users. Unfortunately, it still persists for logged-in and cached users.

![grafik](https://github.com/woocommerce/woocommerce-blocks/assets/74372535/698fc8b9-c503-4a5f-83da-8ffe21e5ab94)
![grafik](https://github.com/woocommerce/woocommerce-blocks/assets/74372535/cdd65ea7-ba3a-4a9e-88fd-e274128e2cee)



3. User Experience: This happens when a delivery address is entered. Users then receive the fields to fill out. I believe that customers are more likely to scroll down and enter the additional information rather than scrolling back up during checkout.

Over the weekend (a busy sales weekend every year), I noticed that many people accidentally choose "Pickup in-store" because it's free. I think this usually happens when paying through PayPal Express, as the residential address is always displayed there. The residential address is often outside Zone 1, and since our website advertises free shipping for orders over €20 for only one city, everyone clicks on "Pickup in-store" instead of delivery, as delivery outside Zone 1 costs €12.95. However, it is necessary for customers on this website to always have their orders delivered to a different shipping address.

**Comment by nielslange** [comment] 2023-05-22 10:49
Hello @dennisjonda, I think I found the problem. In `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=options`, there's an option called `Hide shipping costs until an address is entered`. However, this option can only be activated, when `Local Pickup` is not enabled via `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location`.

<table>
<tr>
<td valign="top">

Deactivate `Local Pickup` …

<img width="1279" alt="Screen Shot 2023-05-22 at 17 46 26" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/50d9d419-c90a-45f0-8645-f42e7b404a68">
</td>
<td valign="top">

… allows enabling `Hide shipping costs …` 

<img width="1280" alt="Screen Shot 2023-05-22 at 17 46 13" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/4515d2d1-ac8d-4705-af97-f08bf5cdd335">

</td>
</tr>
</table>

Could you double-check if deactivating `Local Pickup` leads to the expected result in terms of displaying the shipping costs?

**Comment by dennisjonda** [comment] 2023-05-22 15:28
Hey @nielslange, yes, it's working great after deactivating `Local Pickup`.  But then I need to use the old method and create in the shipping zone the shipping method "Local Pickup". :/ 

I was wondering if there's any way to incorporate this change into the new version of WooCommerce Blocks, so that it's compatible with the improved `Local Pickup` method. The design of the new version is much better, and it would be great to have that functionality. :) 

Thank you very much for your help!

**Comment by nielslange** [comment] 2023-05-23 04:22
Hello @dennisjonda, I'm glad to hear that deactivating `Local Pickup` lead to the expected result. Of course, that's not what you were looking for, and I can understand that. My primary intention of asking you to try this, was to narrow down the problem. I'll reach out to our team and discuss why the option `Hide shipping costs until an address is entered` cannot be enabled when `Local Pickup` is activated. I'll let you know once I have further information on this case.

**Comment by dennisjonda** [comment] 2023-05-23 12:30
Hey @nielslange, I'm sorry I misunderstood you. 
Thank you so much for your help again!

**Comment by nielslange** [comment] 2023-05-23 12:48
> Hey @nielslange, I'm sorry I misunderstood you.
> Thank you so much for your help again!

Don't worry, @dennisjonda. I should have communicated better that by asking you to run the extra test, that it was not my intension to find a solution, but to narrow down the issue. I failed to communicate this better.

Meanwhile, I reached out to a colleague and understood that the issue you're facing is because internally the `Local Pickup` is treated similar to the regular shipping options. Addressing this issue will require a bigger effort than initially expected. In https://github.com/woocommerce/woocommerce-blocks/issues/9387#issuecomment-1550188203, you mentioned:
> Over the weekend (a busy sales weekend every year), I noticed that many people accidentally choose "Pickup in-store" because it's free.
If only a few people had accidentally selected `Local Pickup`, we could argue that the problem was a result of not reading the shipping options carefully. Given that you mentioned _"many people"_, there appears to be a bigger issue around this section.

While we're internally discussing how to proceed best in this case, would it be an option for you to apply the following steps:
1. Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=pickup_location` and deactivate `Local Pickup`.
2. Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section` and add the core shipping method `Local Pickup`
<table>
<tr>
<td>

<img width="1434" alt="Screen Shot 2023-05-23 at 19 46 51" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/bdf0cdcd-ddeb-4412-950b-de38f3f9cfb5">

</td>
<td>

<img width="1436" alt="Screen Shot 2023-05-23 at 19 47 04" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/db0cd170-6d6c-4c64-a3d8-25343d7cf20c">

</td>
</tr>
</table>

3. Go to `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=options` and activate the option `Hide shipping costs until an address is entered`

I'm very well aware that this is not the solution you were hoping for. But I wonder if this could work for you as an interim solution, until we have more clarity on how to proceed in this case.

**Comment by nielslange** [comment] 2023-05-29 06:17
Internal discussion: https://wp.me/pca54o-5MZ

**Comment by dennisjonda** [comment] 2023-08-14 01:54
Hey @nielslange,
I hope this message finds you well. :)

Have you perhaps found a solution yet?

Kind regards (oder auch liebe grüße!)
Dennis

**Comment by mikejolley** [comment] 2023-09-05 12:25
Hi Dennis

This issue also contains several different problems so I think it might be easier to track if split up.

> Address Entry: There seems to be an ongoing issue with entering addresses. Sometimes the page reloads, which requires re-entering the address, or the next steps don't always show up.

If you can still replicate this please open a new issue with details—so far I don't think anyone has been able to replicate this our side. 

> Incorrect Display of Shipping Methods: Despite selecting the option to hide shipping costs until an address is entered, all shipping methods are still displayed when I have three different shipping methods available (Everything in Germany: 1. PLZ from one City, 2. 14 Regions, 3. Everything else). Additionally, only the most expensive shipping method is always displayed.

As stated above, the option to hide shipping costs is not available when using Local Pickup (new). If you have suggestions on why this would still be desirable, or what exactly needs to be hidden in your store, create a new issue with the details for consideration. 

> User Experience: When I enter an address, the "Shipping" and "Local Pickup" buttons appear above the shipping address. This disrupts the natural flow and makes it confusing for users. I think it would be better if the email field came first, followed by the shipping or billing address, then the two buttons, and finally, depending on the user's choice, either the shipping conditions or no further steps in the case of local pickup.

This seems to be the main focus of the issue. I am going to edit the original post and summarise what we have so far, then I'll comment back here afterwards.

**Comment by mikejolley** [comment] 2023-09-05 12:32
I've summarised the points in the issue description. As an update, no we don't yet have a plan for tackling this one. The main sticking point is working out why Local Pickup was chosen.

I don't believe this is due to how and where shipping address is rendered. The big advantage of the local pickup method now is that shipping address does not need to be collected when its chosen. If you choose Local Pickup, the fields are hidden. 

This was the main alarm for me:

> I think this usually happens when paying through PayPal Express, as the residential address is always displayed there.

Is there anyway you could confirm if this was the case by looking at past orders? That might be the problem here, because I think that express methods are just going to list all shipping methods bunched up, so if its not clear that its not really "shipping", it could be chosen accidentally. And being free, its likely selected by default. 

If it turns out to be a problem with express; what would be the desired outcome? Hiding local pickup? Prefixing it? Ensuring it appears last in the list?

**Comment by tarunvijwani** [comment] 2023-10-20 14:45
@dennisjonda  I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2023-10-20 14:45 UTC
Labels: type: bug, block-type: local pickup
