### ISSUE TITLE
500 Error using the Store API checkout endpoint

### ISSUE THREAD

**Issue by webdev-lee** [woocommerce/woocommerce-gutenberg-products-block#11748] opened 2023-11-11 16:25 UTC
I am able to use the GET /wc/store/v1/checkout on my local development machine running XAMPP as soon as I deploy this to a production server using Laravel forge I get a 500 error returned. When I open the status log in Woocommerce I get the following error:

> 2023-11-10T15:31:50+00:00 CRITICAL Uncaught Error: Failed opening required '/home/forge/<mysite.com>/public/wp-content/plugins/woocommerce/src/Caching/WPCacheEngine.php' (include_path='.:/usr/share/php') in /home/forge/<mysite.com>/public/wp-content/plugins/woocommerce/vendor/jetpack-autoloader/class-php-autoloader.php:90
> Stack trace:
> #0 [internal function]: Automattic\Jetpack\Autoloader\jp1bbfdf541239455249e667ffd1774863\PHP_Autoloader::load_class()

I can clear all the logs and refresh the status page, without any interaction with the API and get the error regenerated.
I'm not using Jetpack on my site so I'm not sure why Jetpack is trying to autoload anything.

**Comment by wavvves** [comment] 2023-11-14 17:07
Hello @webdev-lee, by looking at the logs this seems like a problem spawning from a cache plugin you might have enabled in production, can you te-test after disabling any cache plugins? or adding an exception to that URL? (usually all GET requests get cached).

Also if you can submit the report from WooCommerce > Status here, I can assist you better.

**Comment by mikejolley** [comment] 2023-12-11 16:02
> I'm not using Jetpack on my site so I'm not sure why Jetpack is trying to autoload anything.

This is a package we're using to autoload files, its not from Jetpack the plugin. It sounds like a build error/composer was not installed.

Since this hasn't received any updates I'm going to close it, but feel free to reply back or create a new issue if the issue persists with additional information to help us reproduce the bug.

Thanks!

**Closed as completed by mikejolley** 2023-12-11 16:02 UTC
Labels: type: bug, focus: rest api, type: community contribution, team: Rubik
