### ISSUE TITLE
Uncaught Error: Class "Automattic\WooCommerce\Blocks\Patterns\PatternsHelper" not found

### ISSUE THREAD

**Issue by EjayhanFernandes** [woocommerce/woocommerce-gutenberg-products-block#11928] opened 2023-11-24 08:07 UTC
I'm seeing multiple reports of this PHP error:

```
An error of type E_ERROR occurred in line 9 of the file /nas/content/live/websitename/wp-content/plugins/woocommerce/packages/woocommerce-blocks/patterns/featured-category-cover-image.php. 

The error message is as follows: Uncaught Error: Class 'Automattic\WooCommerce\Blocks\Patterns\PatternsHelper' not found in /nas/content/live/websitename/wp-content/plugins/woocommerce/packages/woocommerce-blocks/patterns/featured-category-cover-image.php:9
Stack trace:
#0 /nas/content/live/websitename/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockPatterns.php(180): include()
#1 /nas/content/live/websitename/wp-includes/class-wp-hook.php(324): Automattic\WooCommerce\Blocks\BlockPatterns->register_block_patterns('')
#2 /nas/content/live/websitename/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /nas/content/live/websitename/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /nas/content/live/websitename/wp-settings.php(643): do_action('init')
#5 /nas/content/live/websitename/wp-config.php(121): require_once('/nas/content/li...')
#6 /nas/content/live/websitename/wp-load.php(50): require_once('/nas/content/li...')
#7 /nas/content/live/websitename/wp-admin/admin-
```

It's referring to this specific part of the code:

https://github.com/woocommerce/woocommerce-blocks/blob/90d9e2faa805a100b4b1116bc68dac2e2d705454/patterns/featured-category-cover-image.php#L9

Reported in:
- 7331148-zd-a8c: Error occurred when updating WooCommerce. Rolled back to a previous version because of this issue. 
- 7329281-zd-a8c: Error occurred when updating WooCommerce
- 7337803-zd-a8c: Error occurred but didn't specify if this happened after updating WooCommerce
- 7328031-zd-a8c: Error occurred when updating WooCommerc
- 7354270-zd-a8c: Multiple sites crashed. The error occurred when updating WooCommerce
- 7323607-zd-a8c: Error occurred when updating WooCommerce
- 7325533-zd-a8c: Error occurred when updating WooCommerce
- 7326810-zd-a8c: Error occurred when updating WooCommerce
- 7241809-zd-a8c: Error occurred when updating WooCommerce

I haven't been able to replicate this issue, but I'm placing it here so it's monitored.

**Comment by gigitux** [comment] 2023-11-24 12:46
We attempted to reproduce the problem but were unsuccessful in doing so.

For fellow users encountering similar issues, it might be beneficial to consider the following points and communicate them to help us debug this issue:

- Have you successfully run version 8.3.1 without encountering any problems?
- When updating WooCommerce, does reactivating the plugin after disabling it resolve any issues?
- If fatal errors persist, it would be helpful to know the method employed for updating WooCommerce (e.g., FTP, via a multi-site management panel, through the 'Update' button on the plugins page, or by uploading the zip file using the plugin updater tool)?

Thanks! 

cc @nerrad @albarin @kmanijak

**Comment by albarin** [comment] 2023-12-13 11:48
Closing because with haven't had any new reports for weeks.

**Closed as completed** 2023-12-13 11:48 UTC
Labels: type: bug, team: Kirigami & Origami
