### ISSUE TITLE
Problem with checkout page: automatic form filling

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#4372] opened 2021-06-20 10:32 UTC
The customer came to the checkout page, had personal information stored in their browser and automatically filled in all the fields, but when he clicked on the button to complete the purchase he got the error that the fields are empty.

The customer had to manually enter their personal details for each field that was required.

Please fix this in the next version.

**Comment by mikejolley** [comment] 2021-06-21 15:00
I just tested this in an Incognito window in Edge browser. I used autocomplete then immediately placed an order successfully. If autocomplete had missed a field, I would have had an error for said field.

- Did you reproduce this problem for yourself?
- If yes, what browser was affected?
- What theme is being used? 
- What was the exact error message text?

**Comment by msroky** [comment] 2021-06-26 13:56
All fields are filled in automatically, but when the user clicks on the checkout button it says that the field is not filled even though it is filled. I have noticed this happening since I installed this plugin.

I noticed depends on how the user saved the password. I have a screenshot of a user who came to my web shop via mobile phone and when he came to the checkout page he automatically filled in all the fields of the form and got the error that the fields are empty.

**Comment by senadir** [comment] 2021-07-02 16:53
Hey @msroky, without reliable testing steps, we can't really fix this issue.
Can you tell us what browsers and devices are affected so we can test them?

**Comment by nerrad** [comment] 2021-07-12 13:03
Since there is currently nothing actionable we can do with this issue I'm going to close it. However, please feel free to update with any additional info (including reproducible steps) so we can investigate further and potentially reopen the issue. Thanks!

**Closed as completed by nerrad** 2021-07-12 13:03 UTC
Labels: type: bug
