### ISSUE TITLE
`Cart` does not show "Change address" if TRS is active.

### ISSUE THREAD

**Issue by sverleis** [woocommerce/woocommerce-gutenberg-products-block#9025] opened 2023-04-12 19:48 UTC
## Describe the bug

When Table Rate Shipping is active, the "Change address" element is removed from the cart, when using WooCommerce Blocks. Having Blocks disabled and using the WooCommerce version does not produce this issue.

## To reproduce

1. Install [Table Rate Shipping](https://woocommerce.com/products/table-rate-shipping/?aff=10486&cid=1131038)
2. Install [WooCommerce Blocks](https://woocommerce.com/products/woocommerce-gutenberg-products-block/?aff=10486&cid=1131038)
3. Set up a cart page, using the `cart` block.
4. Shipping options will not allow for an address change.

## Expected behavior
As per the core WooCommerce block, address change should be possible.

## Screenshots
![Z4TvGr.gif](https://user-images.githubusercontent.com/16252298/231567074-30a6f71c-1c75-460d-b135-134ed178943c.gif)

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   Gutenberg version (if installed): n/a
-   WooCommerce version: 7.5.1
-   WooCommerce Blocks version: 10.0.0
-   Site language: en_US
-   Any other plugins installed: 

Jetpack: by Automattic – 12.0
MailPoet: by MailPoet – 4.11.0
Sensei LMS: by Automattic – 4.13.0
WooCommerce Deposits: by WooCommerce – 2.1.5
WooCommerce Payments: by Automattic – 5.7.0

### Desktop (please complete the following information):

-   OS: macOS
-   Browser Chrome
-   Version: 111.0.5563.110

## Additional context

Internal ticket: #6194752-zen

**Comment by wavvves** [comment] 2023-04-13 13:40
Hi @sverleis. Thanks for reaching out with this.

Can you share your settings for shipping and Table Rate config?
Also does this occur with another theme (eg Storefront)

I tried to replicate the bug without success:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/17236129/231776734-a10baad8-a3a9-4435-8182-7ca09d00b8dc.png">

**Comment by K13NN13** [comment] 2023-04-16 02:18
> 

Can you try this in a private browser as I can reproduce this also, sometimes on an admin account it does display the change address, but most of the time it doesnt display with the table rate plugin enabled. As soon as i enable the table rate plugin it doesn't display the change address button

**Comment by mikejolley** [comment] 2023-04-24 15:17
I tested this both logged in and out with only a single Table Rate active and could not replicate the issue. 

Table Rates itself has no dedicated blocks integration so I cannot see what would prevent the button appearing unless its some other setting.

Could you share screenshots of your Table Rate Settings, Zones, and WooCommerce > Settings > Shipping > Shipping options?

**Comment by K13NN13** [comment] 2023-05-11 17:19
> Hi @sverleis. Thanks for reaching out with this.
> 
> Can you share your settings for shipping and Table Rate config? Also does this occur with another theme (eg Storefront)
> 
> I tried to replicate the bug without success: <img alt="image" width="384" src="https://user-images.githubusercontent.com/17236129/231776734-a10baad8-a3a9-4435-8182-7ca09d00b8dc.png">

I am having the same issue, I cannot change the address in the cart page at all, and defaults to the shop default address. I have attatched a few images, hopefully this helps. I do have a staging site i can share if needed in private

![Table_Rate_2](https://github.com/woocommerce/woocommerce-blocks/assets/41597316/e0867adc-4b68-40b2-a42c-451fa34d74a4)
![Table_Rate](https://github.com/woocommerce/woocommerce-blocks/assets/41597316/0140ca78-8e25-4f35-8e2d-e7439ead6db8)
![Shipping_Options](https://github.com/woocommerce/woocommerce-blocks/assets/41597316/f0635027-ba79-485f-a2b7-07b82a1eb73a)

**Comment by K13NN13** [comment] 2023-05-19 17:31
So this issue seems to be due to the option "Enable the shipping calculator on the cart page" missing within WooCommerce > Settings > Shipping >Shipping Options. I see the option within the WooCommerce cart block editor page and its enabled there, but this doesnt allow the "change address to be shown" you have to have the option "Enable the shipping calculator on the cart page"  ticked and as this option is missing for me the change address isn't showing.

Picture from a support chat, the rep had the option whereas thats omitted for me
<img width="954" alt="Markup 2023-05-19 at 12 13 56" src="https://github.com/woocommerce/woocommerce-blocks/assets/41597316/e4e2827c-66c8-4a63-b776-1d2c3b739e0a">

**Comment by K13NN13** [comment] 2023-05-20 04:37
An update to this after testing further. If i use any WooCommerce version after 7.5.0 the "Change address" option does not appear, neither does the "Enable the shipping calculator on the cart page" option within WooCommerce > Settings > Shipping >Shipping Options.

As a temporary solution i will have to downgrade, but hopefully this can be resolved

![Enable_Shipping_Setting](https://github.com/woocommerce/woocommerce-blocks/assets/41597316/07fd4c8c-b11a-4b50-99c1-74928783f1d9)
![Change_Address_V7 5 0](https://github.com/woocommerce/woocommerce-blocks/assets/41597316/953b9fee-c0a8-4844-8c61-1693f92bb9ee)

**Comment by K13NN13** [comment] 2023-05-20 20:18
Another update to this, after testing the latest woocommerce 7.7.0 with version 9.8.2 woocommerce blocks installed the "Enable the shipping calculator on the basket page" option is still shown within WooCommerce > Settings > Shipping >Shipping Options. Within the woocommerce blocks update 9.9.0 there was a change that was to remove certain shipping settings within the above directory. That is not a problem but the 9.9.0 upodate does cause the "Change address" button to not show on the cart page even if it is enabled within the cart block instead

**Comment by tarunvijwani** [comment] 2023-05-22 09:54
@kromeninja I tested it with the Table Rate Shipping plugin, and it works as expected. 

If you have any default shipping method, it won't display the change shipping address link. This change was introduced in woocommerce/woocommerce-blocks#8141 PR.

**Comment by K13NN13** [comment] 2023-05-22 16:58
> @kromeninja I tested it with the Table Rate Shipping plugin, and it works as expected.
> 
> If you have any default shipping method, it won't display the change shipping address link. This change was introduced in woocommerce/woocommerce-blocks#8141 PR.

Hey thank you for the reply. I see that is a shame, I would like to have the geo location enabled or even the shop / country region setting enabled, but still have the change address incase the customer does not live in the same country as the store. The other reason for this is due to the way prices are displayed depending on the address due to VAT, the customer would have to go to the checkout page to change their address to see the correct prices on the store

**Comment by tarunvijwani** [comment] 2023-05-23 10:40
@kromeninja If that's the case, you might want to remove the default shipping method. In that way, it will display the change address link.

**Comment by K13NN13** [comment] 2023-05-24 03:28
> 

Hey when i set it to "No location by default it doesn't show the change address option on the checkout page for the customer, instead it just seems to display a table rate zone instead.

Within the cart block also there is the following option, is this supposed to show the change address as this doesn't show the change address button on the cart page.

From a customer user experience it makes more sense to have it on geolocation so it is showing the correct shipping prices for that customer, and the change address can be used if they want to ship it to another country. Currently it’s quite confusing for customers as they think i do not ship to their country as it doesn’t show any way to change the address on the cart page, the customer won’t always go to the checkout page to try and change the address if it doesn’t show this within the cart page.
![Shipping Calculator](https://github.com/woocommerce/woocommerce-blocks/assets/41597316/d71ba139-3abf-4fbc-b421-f0ca8797bd97)

**Comment by mikejolley** [comment] 2023-06-13 14:37
> If you have any default shipping method, it won't display the change shipping address link. This change was introduced in https://github.com/woocommerce/woocommerce-blocks/pull/8141 PR.

@tarunvijwani what did you mean by this? It is my understanding that the only factor that affects the change address link is the block level toggle, and the main setting under WC > Settings > Shipping.

**Comment by tarunvijwani** [comment] 2023-07-07 13:06
@mikejolley No, if there is any shipping method that is applicable for all the shipping locations then it will not display the shipping calculator at all. This was discussed in the https://github.com/woocommerce/woocommerce-blocks/pull/8141#issuecomment-1397239622

Customers can change the shipping address from the checkout page and the shipping cost will be recalculated accordingly.

**Comment by tarunvijwani** [comment] 2023-07-07 13:09
@kromeninja Could you please reproduce the same on any test site like [instaWP](https://instawp.com/) and share the site details with us?

It will help us to check the settings of the site and guide you through further steps to display the calculator. If required, we will log the issue for you.

**Comment by mikejolley** [comment] 2023-07-11 09:32
> @mikejolley No, if there is any shipping method that is applicable for all the shipping locations then it will not display the shipping calculator at all. This was discussed in the https://github.com/woocommerce/woocommerce-blocks/pull/8141#issuecomment-1397239622

This is flawed @tarunvijwani unless you mean the shipping method is the same, as well as the price? Otherwise you could have several different flat rates and not be able to change the rates.

**Comment by mikejolley** [comment] 2023-07-24 11:24
We'll need to do further investigation into this. Closing in favour of https://github.com/woocommerce/woocommerce/issues/42280

**Closed as completed by mikejolley** 2023-07-24 11:24 UTC
Labels: type: bug, block: cart
