### ISSUE TITLE
Products block not available in gutenberg block selection "No blocks found"

### ISSUE THREAD

**Issue by BrunoBoehm** [woocommerce/woocommerce-gutenberg-products-block#157] opened 2018-11-27 09:25 UTC
**Describe the bug**
When using latest Gutenberg version (Version 1.1.2) on a custom child theme of Genesis, with latest stable wordpress (4.9.8). When looking for the products block int the gutenberg blocks window when editing my page, can't find a trace of the "Products Block".

**To Reproduce**
1. Create a new wordpress page
2. Click the (+) to add a new Gutenberg block into the page
3. Look into the "widgets" section for the "Products" block... it is nowhere to be found!

**Expected behavior**
Should let us create a product block since plugin is activated.

**Screenshots**
Here's what the console has to say:
`VM1933 products-block.js:1470 Uncaught TypeError: Cannot read property 'Toolbar' of undefined
    at Object.<anonymous> (VM1933 products-block.js:1470)
    at __webpack_require__ (VM1933 products-block.js:20)
    at Object.<anonymous> (VM1933 products-block.js:79)
    at __webpack_require__ (VM1933 products-block.js:20)
    at VM1933 products-block.js:63
    at VM1933 products-block.js:66`

**Desktop (please complete the following information):**

* OS: MacOS High Sierra
* Browser: Chrome Version 70.0.3538.102 (Build officiel) (64 bits)

**Comment by ryelle** [comment] 2018-11-27 15:17
Thanks for the report – this is a duplicate of #120, which will be fixed in the next release.

**Closed by ryelle** 2018-11-27 15:17 UTC
