### ISSUE TITLE
ERROR in /style.scss 1:0

### ISSUE THREAD

**Issue by vondam** [woocommerce/woocommerce-gutenberg-products-block#2822] opened 2020-07-07 08:49 UTC
When I try to install this plugin and run npm start I get the following error;

```
ERROR in ./node_modules/wordpress-components/src/custom-select-control/style.scss 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    > .components-custom-select-control {
    |   color: $dark-gray-500;
    |   position: relative;
```

It seems the stylesheets are not build correctly and I need some additional loaders to handle scss? Does anyone else have a similar issue?

**Comment by nerrad** [comment] 2020-07-07 09:46
There haven't been any reports of this and I was able to build the main branch without issue.

What branch are you trying to run `npm start` on?  Did you run `npm install` first?

**Comment by vondam** [comment] 2020-07-07 09:57
Dear nerrad, I just updated the WooCommerce plugin and cloned the main branch for the blocks, I ran the following commands;

- npm install
- composer install
- npm start

It fails compiling the stylesheets..

**Comment by nerrad** [comment] 2020-07-07 10:08
I'm sorry but I don't know why you're having issues.

If you just want to use the plugin in your WordPress install and aren't planning on developing with it, you can just download the zip from the tag release (or checkout the tag) and install that in your WordPress site. The tags are built versions of the plugin.

What operating system are you using locally? If Windows, that _might_ be why none of us can reproduce (none of our development team uses windows).

**Comment by nerrad** [comment] 2020-07-07 10:13
So if you _are_ using Windows, then we use `node-sass` in this project and there's some additional setup steps you'll have to take for `node-sass` to work in your environment. 

- node-sass requires node-gyp https://github.com/sass/node-sass#install
- node-gyp requires windows-build-tools https://github.com/nodejs/node-gyp#on-windows

This _might_ be the reason you are having difficulties?

**Comment by nerrad** [comment] 2020-07-15 18:07
I'm going to close this issue because it hasn't had any feedback in over a week. However, if you have additional information please do update and we can consider re-opening if that exposes something we can do to fix.

**Closed by nerrad** 2020-07-15 18:07 UTC
Labels: action: needs feedback, type: support

**Comment by dd10-e** [comment] 2020-08-04 20:55
Hello @vondam, have you resolved this issue ?

I currently facing to this issue on my Windows 10 machine and i don't understand why. 

`node-gyp@7.0.0` and `node-sass` are installed, so everything should be good on my installation requirement.

If you have any advice for moving forward to resolve this. I keeping trying to resolve this...

**Comment by dd10-e** [comment] 2020-08-10 22:27
I've finally be able to build it using Ubuntu with WSL.

So yeah it doesn"t build on Windows, i'm pretty sure it's a webpack configuration issue. 
Anyway, I'll keep you informed if i'm able to build it on Windows!
