### ISSUE TITLE
[GlobalStep - WooCommerce Blocks 2.7] “Something went wrong…” error is displayed on Preview and Publish upon adding “All Product” block with “Cart” block on same page.  

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2697] opened 2020-06-11 14:38 UTC
**Environment:**
Windows 10: Chrome(v83.0.4103.61)(64-bit), Firefox(v77.0.1)(64-bit)

**Steps to Reproduce:**
1. Open a test site.
2. Login with valid credentials.
3. From dashboard go to Pages.
4. Add new page.
5. Add "All Products" block
6. Add "Cart" block.
7. Note that no error message is displayed on editor.
8. Now Preview the page or Publish the page.
9. Observe that "Something went wrong..." error message is displayed.

**Note:** The error message fails clear unless and until we remove any one block from the page.

**Actual Result:**
“Something went wrong…” error is displayed on Preview and Publish upon adding “All Product” block with “Cart” block on same page.

**Expected Result:**
Valid error message should be displayed if we add "All Product” block with “Cart” block on the same page. 

**Refer Artifact:**
[#2697.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4765509/2697.zip)

**Comment by nerrad** [comment] 2020-06-11 20:04
Thanks for the report!

While this is definitely not good, there's really not a use-case for folks to add both blocks to the same page. So while I'll still keep this as a bug report, it's low impact imo because the solution is just to not use both blocks on the same page :)

**Comment by Aljullu** [comment] 2020-09-17 08:14
I'm unable to reproduce this issue with the latest version of `main`: I could add the `All Products` + `Cart` blocks in the same page and preview & publish it without issues and it was looking alright in the frontend. I will close this issue for now, feel free to reopen if you think I missed something.

**Closed by Aljullu** 2020-09-17 08:14 UTC
Labels: type: bug
