### ISSUE TITLE
Single Product template. Being able to adjust the Product Details block

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce-gutenberg-products-block#11884] opened 2023-11-22 12:58 UTC
## Is your feature request related to a problem? Please describe.
Single Product template. Being able to adjust the Product Details block. For instance removing the tabs to only keep the Description or having a Description block separate. 

## Describe the solution you'd like
Adjust the Product Details block to only keep Description.

## Describe alternatives you've considered
None yet.

## Additional context
-

**Comment by Marc-pi** [comment] 2023-11-23 17:19
duplicate of https://github.com/woocommerce/woocommerce/issues/42277

**Comment by paaljoachim** [comment] 2023-11-23 19:22
Thank you @Marc-pi . I am happy I made a duplicate of your issue! As it shows the importance of this block.

**Comment by gigitux** [comment] 2023-11-27 09:42
Thank you for opening this issue! As mentioned by @Marc-pi, I will close the issue because it is a duplicate of woocommerce/woocommerce#42277.

**Closed as completed by gigitux** 2023-11-27 09:42 UTC
Labels: type: enhancement, type: community contribution
