### ISSUE TITLE
Allow shoppers to sign up for a user account should automatically update the admin setting for Account creation

### ISSUE THREAD

**Issue by ralucaStan** [woocommerce/woocommerce-gutenberg-products-block#7662] opened 2022-11-11 12:14 UTC
Currrently, if you add the Checkout Block and choose the `Contact Information` inner block, you'll see the option `Allow shoppers to sign up for a user account during checkout` under `Account options` in the sidebar.
This option will add a checkbox for the user to create an account.

 However, this won’t be shown until the `Allow customers to place orders without an account` option in `WooCommerce > Settings > Accounts & Privacy` is turned on. 
 
 There’s also a visual bug where the toggle is overlapping with the label text.
![contant-info](https://user-images.githubusercontent.com/1628454/201338218-9ff1484b-e750-4485-b98b-47be05fed198.png)

## Expected behavior

The checkbox `Allow shoppers to sign up for a user account during checkout` should automatically update the admin setting for Account creation. There’s currently no way for the merchant to know that they need to do this.

The text for `Allow shoppers to sign up for a user account during checkout` in the block settings bar should not overlap with the input.

Improvement suggested by @elizaan36

**Comment by ralucaStan** [comment] 2022-12-05 17:36
Related "Guest checkout" and "Account creation" settings between core settings and checkout block not synced #5716

**Comment by nielslange** [comment] 2022-12-08 11:54
Instead of syncing the account creation options between the WooCommerce core settings on `/wp-admin/admin.php?page=wc-settings&tab=account`, I wonder if it isn't a better approach to remove the account creation option from the Checkout block, and inform merchants to adjust this setting within the WooCommerce core settings. As mentioned in #5716, we're already applying this pattern both for the shipping and payment options:

<table>
<tr>
<td valign="top">Shipping options:
<br><br>

<img width="273" alt="Screen Shot 2022-02-04 at 12 41 04" src="https://user-images.githubusercontent.com/3323310/152478420-4cbede21-4a4b-4d24-ab2a-f2da258619af.png">
</td>
<td valign="top">Payment options:
<br><br>

<img width="271" alt="Screen Shot 2022-02-04 at 12 41 15" src="https://user-images.githubusercontent.com/3323310/152478428-c0193d89-348e-40cd-bfb5-988effc60192.png">
</td>
</tr>
</table>

### Benefits of removing these setting from the block

- We're following a consistent pattern together with the shipping and payment options.
- We're reducing complexity within the code, which increases the maintainability and decreases the risk of regressions/bugs.
- We're having a better performance by not having to check if both settings are in sync and respectively sync them, in case they are out of sync.

### Benefits of syncing the settings

- The merchant stays in the block and doesn't have to jump to other sections.

Personally, I cannot imagine that merchants adjust the account creation settings on a frequent base. I believe that it's a one-time adjustment similar to the shipping and payment options. As a result of that, I would treat all three settings similar from an UX perspective.

**Comment by tarunvijwani** [comment] 2022-12-08 12:32
@opr and I spent some time during the pair programming, and below are our findings:
1. We would need to develop either a StoreApi endpoint (this does not seem like the intended use of StoreApi), or an AJAX endpoint to update this setting. (seems more reasonable). This would need to update the WooCommerce option whenever the toggle control changes value. It doesn't look like there's any @wordpress/data mechanism for updating options via the core store.
2. We could hook into the `save_post` hook, parse the blocks in the post content, and check for the Checkout block. If present, we could then check this attribute and update the setting accordingly. This would come with a performance tradeoff since we'd need to check every single post when it gets saved to know if the Checkout block was present.
3. We like the idea suggested by @nielslange  in [#5716](https://github.com/woocommerce/woocommerce-blocks/issues/5716). It would be more efficient to add the link to the admin page to change the settings and avoid confusion.

**Comment by nielslange** [comment] 2022-12-14 08:26
Closing this issue in benefit of https://github.com/woocommerce/woocommerce-blocks/issues/5716.

**Closed as completed by nielslange** 2022-12-14 08:26 UTC
Labels: block: checkout

**Comment by nielslange** [comment] 2022-12-14 08:37
@elizaan36 Just wanted to let you know that we'll remove the `Allow customers to place orders without an account` setting from the Checkout block and refer merchants directly to the corresponding settings page within WooCommerce core. For the shipping and payment options, we're following the same pattern.

**Comment by elizaan36** [comment] 2022-12-14 18:02
hey @nielslange, I think it makes sense to remove this from blocks settings since it's more of a functionality change. I don't think a link to the admin is necessary in this case, since as you mentioned the merchant will likely not be in need of changing this setting very often. It's likely something they take care of during store setup, then leave it.

**Comment by nielslange** [comment] 2022-12-15 06:16
> I don't think a link to the admin is necessary in this case, since as you mentioned the merchant will likely not be in need of changing this setting very often.

Even though the merchant will not change this setting often, I do believe that showing a link is helpful. That way, the merchant does not have to look around where the corresponding setting is located. This is also something we're doing with the shipping and payment options.

<table>
<tr>
<td valign="top">Shipping options:
<br><br>

<img width="273" alt="Screen Shot 2022-02-04 at 12 41 04" src="https://user-images.githubusercontent.com/3323310/152478420-4cbede21-4a4b-4d24-ab2a-f2da258619af.png">
</td>
<td valign="top">Payment options:
<br><br>

<img width="271" alt="Screen Shot 2022-02-04 at 12 41 15" src="https://user-images.githubusercontent.com/3323310/152478428-c0193d89-348e-40cd-bfb5-988effc60192.png">
</td>
<td valign="top">Account options:
<br><br>

<img width="278" alt="Screenshot 2022-12-15 at 13 15 35" src="https://user-images.githubusercontent.com/3323310/207786627-1adbdd64-a235-4b7e-9266-d46394a10dc4.png">
</td>
</tr>
</table>
