### ISSUE TITLE
experimental__woocommerce_blocks-product-list-render, If a large number of products are configured, this will result in the output of a large number of js scripts, resulting in the response message body being too large

### ISSUE THREAD

**Issue by namm163** [woocommerce/woocommerce-gutenberg-products-block#8708] opened 2023-03-13 02:23 UTC
https://github.com/woocommerce/woocommerce-blocks/blob/b1e07428a8858f7c76c41bc15c87d23f39cb01d5/src/BlockTypes/AbstractProductGrid.php#L108

**Comment by kmanijak** [comment] 2023-03-16 13:58
Hi @namm163!

Thanks a lot for raising the issue.

Could I ask you to provide steps to reproduce the issue? It will help us reproduce and debug the issue. Please include answers to the following questions:

> resulting in the response message body being too large

Could you explain in more detail what happens and what's the impact? Does it affect store usage or any specific feature?

> If a large number of products are configured

What do you mean by "large number"? Order of magnitude will help us to reproduce it.

Thanks!

**Comment by gigitux** [comment] 2023-04-05 08:16
@namm163 I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by gigitux** 2023-04-05 08:16 UTC
Labels: type: bug
