### ISSUE TITLE
[StoreApi] Support default shipping rates

### ISSUE THREAD

**Issue by mpskovvang** [woocommerce/woocommerce-gutenberg-products-block#10963] opened 2023-09-15 06:16 UTC
## Is your feature request related to a problem? Please describe.
WooCommerce supports default shipping rates when using a theme-based storefront. You don't necessarily have to choose a shipping method in either cart or checkout. Out-of-the-box the first rate per package is always chosen by the system.

However, this is not the case when using the Store API. You must call the `cart/select-shipping-rate` endpoint.

The theme-based behavior happens when calling `WC()->cart->calculate_shipping()`. The magic happens in the `get_chosen_shipping_methods` method.

This behavior is especially useful if you only have one rate per shipping package or want to have more control from the backend. Support will also reduce HTTP requests from the storefront.

## Describe the solution you'd like
The Store API should support the same behavior as the theme-based either by default or by opting in. I'm unsure if there are any drawbacks to the chosen default shipping rates (except probably a breaking change related to default cart totals).

I believe implementation is pretty straightforward. If the `get_shipping_packages` method in the `CartController` calls `$cart->get_chosen_shipping_methods($packages);` after calculating shipping, the session should be updated accordingly.

## Describe alternatives you've considered
The developer must send an HTTP request from the storefront to select the rates or consider extending the behavior by using hooks like `woocommerce_shipping_packages`.

**Comment by opr** [comment] 2023-09-15 22:33
Hi there, thanks for posting your issue. I was under the impression that a rate _is_ selected by default. I just added an item to my cart via the API and in the response I see the list of shipping rates and one of them is selected. (Search for `"selected": true,` to find it).

```json
"shipping_rates": [
		{
			"package_id": 0,
			"name": "Shipment 1",
			"destination": {
				"address_1": "",
				"address_2": "",
				"city": "",
				"state": "CA",
				"postcode": "",
				"country": "US"
			},
			"items": [
				{
					"key": "db458a8d3b97188a9990608c0b611526",
					"name": "Hoodie - Blue, Yes",
					"quantity": 1
				}
			],
			"shipping_rates": [
				{
					"rate_id": "free_shipping:1",
					"name": "Free shipping",
					"description": "",
					"delivery_time": "",
					"price": "0",
					"taxes": "0",
					"instance_id": 1,
					"method_id": "free_shipping",
					"meta_data": [
						{
							"key": "Items",
							"value": "Hoodie - Blue, Yes &times; 1"
						}
					],
					"selected": true,
					"currency_code": "GBP",
					"currency_symbol": "£",
					"currency_minor_unit": 2,
					"currency_decimal_separator": ".",
					"currency_thousand_separator": ",",
					"currency_prefix": "£",
					"currency_suffix": ""
				},
				{
					"rate_id": "flat_rate:2",
					"name": "Flat rate",
					"description": "",
					"delivery_time": "",
					"price": "700",
					"taxes": "0",
					"instance_id": 2,
					"method_id": "flat_rate",
					"meta_data": [
						{
							"key": "Items",
							"value": "Hoodie - Blue, Yes &times; 1"
						}
					],
					"selected": false,
					"currency_code": "GBP",
					"currency_symbol": "£",
					"currency_minor_unit": 2,
					"currency_decimal_separator": ".",
					"currency_thousand_separator": ",",
					"currency_prefix": "£",
					"currency_suffix": ""
				},
				{
					"rate_id": "flat_rate:4",
					"name": "Next day",
					"description": "",
					"delivery_time": "",
					"price": "1000",
					"taxes": "0",
					"instance_id": 4,
					"method_id": "flat_rate",
					"meta_data": [
						{
							"key": "Items",
							"value": "Hoodie - Blue, Yes &times; 1"
						}
					],
					"selected": false,
					"currency_code": "GBP",
					"currency_symbol": "£",
					"currency_minor_unit": 2,
					"currency_decimal_separator": ".",
					"currency_thousand_separator": ",",
					"currency_prefix": "£",
					"currency_suffix": ""
				},
				{
					"rate_id": "pickup_location:0",
					"name": "Local Pickup (US Location)",
					"description": "",
					"delivery_time": "",
					"price": "200",
					"taxes": "0",
					"instance_id": 0,
					"method_id": "pickup_location",
					"meta_data": [
						{
							"key": "pickup_location",
							"value": "US Location"
						},
						{
							"key": "pickup_address",
							"value": "1234 Hollywood Boulevard, Los Angeles, CA 90028"
						},
						{
							"key": "pickup_details",
							"value": "Go past the Shrek star and enter the store. Bring your order confirmation!"
						},
						{
							"key": "Items",
							"value": "Hoodie - Blue, Yes &times; 1"
						}
					],
					"selected": false,
					"currency_code": "GBP",
					"currency_symbol": "£",
					"currency_minor_unit": 2,
					"currency_decimal_separator": ".",
					"currency_thousand_separator": ",",
					"currency_prefix": "£",
					"currency_suffix": ""
				}
			]
		}
	],
```

Do you see something different when adding an item to your cart? 

@tarunvijwani since you've been looking at the chosen shipping methods would you mind taking a look at this too to make sure I didn't misunderstand something?

Thanks!

**Comment by mpskovvang** [comment] 2023-09-16 10:16
Indeed, you're right. However, when sending a `checkout` request, I receives a `woocommerce_rest_invalid_shipping_option` error code. I guess the `cart/select-shipping-rate` is still required for checkout to complete?

**Comment by senadir** [comment] 2023-09-16 12:08
No it shouldn't be required, @nielslange can you confirm in your testing of this issue if selecting a shipping rate is required for checking out? When checking out, you don't send any cart data, and the store uses whatever is set in Cart.

**Comment by nielslange** [comment] 2023-09-18 05:41
> No it shouldn't be required, @nielslange can you confirm in your testing of this issue if selecting a shipping rate is required for checking out? When checking out, you don't send any cart data, and the store uses whatever is set in Cart.

@senadir I just tested this, and on my end, I'm seeing the same result as @opr in https://github.com/woocommerce/woocommerce-blocks/issues/10963#issuecomment-1721964703. After placing the order, I looked up the order in WP Admin, and saw that the first shipping option, the one that had been selected by default, was also listed as expected.

<details>
<summary>Screenshot of the order</summary>
<img width="1278" alt="Screenshot 2023-09-18 at 12 14 06" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/611426c8-0b1e-4e20-84b4-dac65ee9bd93">
</details>


@mpskovvang Can you provide detailed steps on to reproduce what you are seeing?

**Comment by mpskovvang** [comment] 2023-09-18 18:42
Thank you both for confirming the expected behavior. I'll have to troubleshoot further.

In the session value, the `chosen_shipping_methods` is for some reason `false`.


```a:12:{s:4:"cart";s:419:"a:1:{s:32:"3eef284e80280be9aff8a80800dae3f3";a:11:{s:3:"key";s:32:"3eef284e80280be9aff8a80800dae3f3";s:10:"product_id";i:61249;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:2;s:9:"data_hash";s:32:"b5c1d5ca8bae6d4896cf1807cdf763f0";s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:13:"line_subtotal";d:203.2;s:17:"line_subtotal_tax";d:0;s:10:"line_total";d:203.2;s:8:"line_tax";d:0;}}";s:11:"cart_totals";s:400:"a:15:{s:8:"subtotal";s:5:"203.2";s:12:"subtotal_tax";d:0;s:14:"shipping_total";s:1:"0";s:12:"shipping_tax";d:0;s:14:"shipping_taxes";a:0:{}s:14:"discount_total";d:0;s:12:"discount_tax";d:0;s:19:"cart_contents_total";s:5:"203.2";s:17:"cart_contents_tax";i:0;s:19:"cart_contents_taxes";a:0:{}s:9:"fee_total";s:1:"0";s:7:"fee_tax";d:0;s:9:"fee_taxes";a:0:{}s:5:"total";s:6:"203.20";s:9:"total_tax";d:0;}";s:15:"applied_coupons";s:6:"a:0:{}";s:22:"coupon_discount_totals";s:6:"a:0:{}";s:26:"coupon_discount_tax_totals";s:6:"a:0:{}";s:21:"removed_cart_contents";s:6:"a:0:{}";s:8:"customer";s:777:"a:27:{s:2:"id";s:1:"0";s:13:"date_modified";s:0:"";s:8:"postcode";s:4:"1000";s:4:"city";s:4:"Test";s:9:"address_1";s:4:"Test";s:7:"address";s:4:"Test";s:9:"address_2";s:0:"";s:5:"state";s:0:"";s:7:"country";s:0:"";s:17:"shipping_postcode";s:0:"";s:13:"shipping_city";s:0:"";s:18:"shipping_address_1";s:0:"";s:16:"shipping_address";s:0:"";s:18:"shipping_address_2";s:0:"";s:14:"shipping_state";s:0:"";s:16:"shipping_country";s:0:"";s:13:"is_vat_exempt";s:0:"";s:19:"calculated_shipping";s:0:"";s:10:"first_name";s:15:"Martin Skovvang";s:9:"last_name";s:8:"Petersen";s:7:"company";s:0:"";s:5:"phone";s:8:"10101010";s:5:"email";s:16:"test@example.org";s:19:"shipping_first_name";s:0:"";s:18:"shipping_last_name";s:0:"";s:16:"shipping_company";s:0:"";s:14:"shipping_phone";s:0:"";}";s:22:"shipping_for_package_0";s:92:"a:2:{s:12:"package_hash";s:40:"wc_ship_ae23f9b5f8ceb728df6b305c0e933f14";s:5:"rates";a:0:{}}";s:25:"previous_shipping_methods";s:16:"a:1:{i:0;a:0:{}}";s:23:"chosen_shipping_methods";s:14:"a:1:{i:0;b:0;}";s:22:"shipping_method_counts";s:14:"a:1:{i:0;i:0;}";s:21:"store_api_draft_order";i:218761;}```

**Comment by mpskovvang** [comment] 2023-09-18 18:54
Apparently, after sending the `cart/add-item` request, the `chosen_shipping_methods` does indeed have the expected rate ID: `a:1:{i:0;s:9:"custom:4";}`

However, when calling the `checkout` endpoint, the rate in the session value is changed to `false`.

**Comment by nielslange** [comment] 2023-09-19 03:39
> However, when calling the `checkout` endpoint, the rate in the session value is changed to `false`.

On my end, I was using the REST client [Insomnia](https://insomnia.rest/). As soon as I call the `checkout` endpoint, the order gets submitted to the server and I only see this response in my REST client:

```json
{
	"order_id": 312,
	"status": "on-hold",
	"order_key": "wc_order_5IRr7bmODVy4j",
	"order_number": "312",
	"customer_note": "",
	"customer_id": 0,
	"billing_address": {
		"first_name": "Peter",
		"last_name": "Venkman",
		"company": "",
		"address_1": "550 Central Park West",
		"address_2": "Corner Penthouse Spook Central",
		"city": "New York",
		"state": "NY",
		"postcode": "10023",
		"country": "US",
		"email": "admin@example.com",
		"phone": "555-2368"
	},
	"shipping_address": {
		"first_name": "Peter",
		"last_name": "Venkman",
		"company": "",
		"address_1": "550 Central Park West",
		"address_2": "Corner Penthouse Spook Central",
		"city": "New York",
		"state": "NY",
		"postcode": "10023",
		"country": "US",
		"phone": "555-2368"
	},
	"payment_method": "cheque",
	"payment_result": {
		"payment_status": "success",
		"payment_details": [
			{
				"key": "result",
				"value": "success"
			},
			{
				"key": "redirect",
				"value": "https:\/\/store.test\/checkout\/order-received\/312\/?key=wc_order_5IRr7bmODVy4j"
			}
		],
		"redirect_url": "https:\/\/store.test\/checkout\/order-received\/312\/?key=wc_order_5IRr7bmODVy4j"
	},
	"extensions": {}
}
```

Can you post detailed steps on how to reproduce what you are seeing, @mpskovvang? Where do you see the default shipping rate value?

**Comment by mpskovvang** [comment] 2023-09-19 06:12
I've found the reason. I noticed, that the expected shipping lines actually was created in the database before the `woocommerce_rest_invalid_shipping_option` error was returned.

My initial `checkout` request:

```json
{"billing_address":{"first_name":"Martin Skovvang","last_name":"Petersen","company":"","address_1":"Test","address_2":"","postcode":"1000","city":"Test","phone":"10101010","email":"test@example.org"},"shipping_address":{"first_name":null,"last_name":null,"company":null,"address_1":null,"address_2":null,"postcode":null,"city":null},"customer_note":null,"payment_method":"bacs","extensions":{"northlands":{"accepts_marketing":false}}}
```

I did two things wrong:

1. I omitted the `country` field because the shop is limited to one selling country and the `woocommerce_checkout_fields` hook sets the default value to `DK`.
2. I used `NULL` values in the shipping address as I then expected it would default to the billing address.

The checkout succeeds when using `country` in the `billing_address` and omitting the `shipping_address` field instead of using `NULL` values.

I really appreciate your help!

**Comment by nielslange** [comment] 2023-09-19 08:02
I'm glad to hear that you found out what went wrong. I'll go ahead and close this for now. If you have any more questions or suggestions, feel free to [open a new issue](https://github.com/woocommerce/woocommerce-blocks/issues/new/choose). 😀

**Closed as completed by nielslange** 2023-09-19 08:02 UTC
Labels: type: enhancement, focus: rest api, type: community contribution
