### ISSUE TITLE
Cart items without "key" can't be removed from block cart and quantity does not function

### ISSUE THREAD

**Issue by ethanclevenger91** [woocommerce/woocommerce-gutenberg-products-block#9969] opened 2023-06-22 18:26 UTC
## Describe the bug

If an item winds up in the cart without a `key` value, it:
1. Can't be removed
2. Its quantity does not initialize properly
3. Its quantity cannot be adjusted

This is true only of the cart block, and does not impact the cart shortcode.

## Reproduce

1. Use the below serialized data for a user's persisted cart in the `usermeta` table. Swap out the product ID for one that actually exists in your test environment.
2. Log in as that user
3. View cart via shortcode
4. May need to update cart to get prices to reflect data for the item you injected? Untested.
5. See correct quantity (2)
6. See correct price
7. See incrementing/decrementing quantity works, can be saved
8. Click "X" to remove item from cart
9. See it is removed
10. Restore cart data in database
11. View block cart
12. See new warnings in your debug log: `PHP Warning:  Undefined array key "key" in .../plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/CartItemSchema.php on line 350
PHP Warning:  Undefined array key "key" in .../plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Schemas/V1/CartItemSchema.php on line 353`
13. See quantity shows "1"
14. See incrementing/decrementing quantity does not actually persist changes to the cart
15. See clicking "Remove item" does not, in fact, remove the item

On the site this is an issue, I've only had it turn up with logged-in users, meaning their cart data is coming from the database and not browser session storage (which I'm only assuming happens for logged-out users)

I'm not sure how the data came to be in the database in such a state, but it may be specific to items that were added to carts before we switched to block-based checkout. If I add a new product to the cart, I'm able to remove that one, but still not the existing one. I don't know enough about the history of the `key` value to know when it was added or how an item may end up in a cart without it.

`_woocommerce_persistent_cart_1` usermeta value that can be used for testing:

```
a:1:{s:4:"cart";a:1:{s:32:"7bccfde7714a1ebadf06c5f4cea752c1";a:11:{s:10:"product_id";i:1236;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:2;s:10:"line_total";d:4;s:13:"line_subtotal";d:4;s:8:"line_tax";d:0;s:17:"line_subtotal_tax";d:0;s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:18:"available_quantity";i:2;s:18:"has_special_offers";b:0;}}}
```

## Screenshots

Shortcode cart - note quantity 2 and price reflected:

<img width="1320" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/2623646/567ebdb0-59c2-4040-97ab-c98e893ccc46">

Block cart for same cart - note quantity 1, but correct price:

<img width="1320" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/2623646/72ad9d05-264c-4b5d-b041-85bb7781abb2">

### WordPress (please complete the following information):

-   WordPress version: 6.2.2
-   Gutenberg version (if installed): Not active
-   WooCommerce version: 7.8.0
-   WooCommerce Blocks version: Not installed independently
-   Site language: English
-   Any other plugins installed: ACF Pro

### Desktop (please complete the following information):

-   OS: MacOS
-   Browser Firefox
-   Version 113.0.2

### Additional notes/context
Obviously one solution is to wipe all saved carts.

**Comment by nielslange** [comment] 2023-06-23 09:29
Hello @ethanclevenger91 👋 Thanks for reaching out. Can you tell me how to reproduce this issue, without manually overwriting the `_woocommerce_persistent_cart_1` meta value? I'm asking, as on my end, I always see the key being part of `_woocommerce_persistent_cart_1`. 

Here's what I did:
- Go to the frontend of the site.
- Verify tat the cart is empty.
- Open the database and navigate to `wp_usermeta`.
- Search for meta key `_woocommerce_persistent_cart_1`.
- Keep an eye on the entry with the highest `umeta_id`.
- My entry for `_woocommerce_persistent_cart_1` looks like this:
```
a:1:{s:4:"cart";a:0:{}}
```
- Add a product to the cart.
- My entry for `_woocommerce_persistent_cart_1` now looks like this:
```
a:1:{s:4:"cart";a:1:{s:32:"34173cb38f07f89ddbebc2ac9128303f";a:6:{s:3:"key";s:32:"34173cb38f07f89ddbebc2ac9128303f";s:10:"product_id";i:30;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:1;s:9:"data_hash";s:32:"b5c1d5ca8bae6d4896cf1807cdf763f0";}}}
```

I also ran a test in which I added four products to the cart. The following screenshot shows that each product has its own `key`:

<img width="999" alt="Screenshot 2023-06-23 at 11 28 10" src="https://github.com/woocommerce/woocommerce-blocks/assets/3323310/96f21e3c-ddce-4a70-92f6-2bc80af029ab">

So far, I haven't been able to add a product to the cart in a way that `_woocommerce_persistent_cart_1`  would not have a key for the corresponding product(s). I would appreciate it if you could provide further steps so that I can reproduce this case on my end.

**Comment by ethanclevenger91** [comment] 2023-06-23 17:04
@nielslange you request is pretty much my conundrum. All I know is I, personally, had a cart reflecting this, and that at least one user reported the same issue.

I don't know enough about `key` and its history to say how we might have gotten here. One thought was that at one point it wasn't part of the cart data, and these are both really old carts. But there's no `@since` in the docblock for the function that generates the `key`, so I don't know how long that this value has been in cart item data.

How long has `key` been around?

**Comment by wavvves** [comment] 2023-06-30 15:04
@ethanclevenger91 unfortunately 'key' is a required unique identifier for the item in the cart, and I believe it is present since WC 1.0. This is part of WooCommerce itself, we do enforce it by schema and check for it on tests, no reason not to expect it on cart.
That being said, it would be awesome if we could find the steps to reproduce it without injecting the malformed data in the db, I believe what should be the focus here is finding out how that data is generated.

**Comment by mikejolley** [comment] 2023-07-24 11:15
Since this hasn't had any feedback in a while and there have been no other reports, I'm going to go ahead a close this. But if anyone does find steps to reproduce the issue, please comment back or create a new issue with the details.

Thanks

**Closed as completed by mikejolley** 2023-07-24 11:15 UTC
Labels: type: bug, type: community contribution
