### ISSUE TITLE
remove CartCoupon endpoints that have been moved to Cart controller

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1849] opened 2020-03-02 21:49 UTC
**Describe the bug**
Some API endpoints in CartCoupon controller actually affect the whole cart. For example  `CartCoupons.create_item()`  `POST /cart/coupons` applies a coupon to the cart, which affects cart totals, and potentially shipping (I think coupons can be used for free shipping?). 

Because this endpoint affects the cart entity, we added `POST /cart/apply-coupon`to `Cart` controller.

This means we are no longer using `CartCoupons.create_item()` endpoint. I'd argue it's dangerous to leave this in place for two reasons:

- We aren't using it, so if bugs creep in we may not catch them (principle: don't ship code that you're not actively using).
- It's tricky to use well - the client may need to know to update related data, i.e. perform a full cart request.

The crux of the issue for me is that applying coupon is not independent of the cart, it's an operation on the cart, so IMO the cart controller is the right fit.

We may have similar issues with some other endpoints which affect the cart entity - selecting shipping rates (see in progress PR #1794), changing / removing items. Might be worth reviewing `CartItems` controller to see if it is useful on its own, or if it is coupled to the cart entity.

**Expected behavior**
All API endpoints that affect the cart entity are defined on the `Cart` controller and return a full cart.

If there are controllers for slices of the cart, these are safe to use independently from the full cart controller, or are completely independent. E.g. `GET coupons` is independent of the cart, so makes sense to be a separate controller.

**Comment by mikejolley** [comment] 2020-03-03 09:52
> We aren't using it, so if bugs creep in we may not catch them (principle: don't ship code that you're not actively using).

We do however have unit tests covering this functionality.

**Comment by mikejolley** [comment] 2020-05-06 15:48
I think I'm going to close this issue since we've now gone over these endpoints and got the Store API to a more or less stable point (documentation for the endpoints up here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/master/src/StoreApi/Routes).

To comment on specific points:

> I'd argue it's dangerous to leave this in place for two reasons:
> We aren't using it, so if bugs creep in we may not catch them (principle: don't ship code that you're not actively using).

We should accept that some APIs are not always created for our own usage. We may be providing APIs for example, for 3rd parties. The good thing about APIs is that we can test them in isolation, and they are fairly easy to create unit tests for since you only need to test the request and expected response. Due to that, I don't think this is dangerous at all. 

The endpoints themselves (e.g. POST cart/coupons and cart/apply-coupon) have test coverage and share controller class logic, so if there was a bug in that, the fix would apply to all endpoints consuming it.

> It's tricky to use well - the client may need to know to update related data, i.e. perform a full cart request.

I think so long as the docs are clear this is a non-issue. Each endpoint has clear schema for the request and response, so if a client does need to get a full cart, we have an endpoint for that. If the client only wants to deal with coupons, and check that it applied and what applied, there is an endpoint for that also.

> We may have similar issues with some other endpoints which affect the cart entity - selecting shipping rates (see in progress PR #1794), changing / removing items. Might be worth reviewing CartItems controller to see if it is useful on its own, or if it is coupled to the cart entity.

The dedicated shipping quote endpoint has been removed and replaced with one under /cart/ only. So this part of the issue is resolved.

> All API endpoints that affect the cart entity are defined on the Cart controller and return a full cart.

I believe this is now the case.

**Closed by mikejolley** 2020-05-06 15:48 UTC
Labels: type: cooldown

**Comment by haszari** [comment] 2020-05-06 19:50
Sounds good to me – thanks @mikejolley for wrapping this up and the explanation :)
