### ISSUE TITLE
Review WooCommerce Blocks and ensure they work with the new Block Based widget area coming to WordPress 5.7

### ISSUE THREAD

**Issue by nerrad** [woocommerce/woocommerce-gutenberg-products-block#3228] opened 2020-10-01 15:58 UTC
~WordPress 5.6~ WordPress 5.7 is scheduled to introduce the new block based widget areas in WordPress. For this issue, we will need to test all the WooCommerce blocks in this new UI and ensure they work as expected.

We also need to review all WooCommerce widgets that are not converted to blocks yet and ensure they work with the new legacy widget wrapper/mechanism the block widget interface is adding.

(note block widget areas were [punted to WordPress 5.7](https://core.trac.wordpress.org/ticket/51506#comment:13))

To expand this issue a bit (feel free to open a separate issue in Storefront if desired, I added here because I figured we'd be testing this issue in storefront anyways), let's see how WordPress core blocks work in Storefront with widget areas as well. Related, is this issue in the GB repo: https://github.com/WordPress/gutenberg/issues/27458

**Comment by Aljullu** [comment] 2020-12-11 15:28
Posting this comment that will serve as a summary of my in-progress work.

### Set up
* You need to install Gutenberg, ideally the latest version in `master`.
* The widgets editor can be accessed from Appearance > Widgets.
* There is an alternative view from Appearance > Customize > Widgets, but according to [this post](https://make.wordpress.org/core/2020/11/18/hallway-hangout-summary-managing-blocks-in-the-customizer/), it will change dramatically.

### Known issues
Currently, the widgets editor has some known issues that affect our widgets/blocks as well:

  * https://github.com/WordPress/gutenberg/issues/27173
  * https://github.com/WordPress/gutenberg/issues/26468

So when testing it's important to distinguish what's a Gutenberg bug and what's something specific to WooCommerce.

### Testing WooCommerce Core widgets in the new widgets editor

| Widget name | Works in editor? | Works in frontend? |
| --- | :---: | :---: |
| Product Search | 🗸 | 🗸 |
| Product Tag Cloud | 🗸 | 🗸 |
| Product Categories | 🗸 | 🗸 |
| Products | ❌<sup>1</sup> | 🗸 |
| Products by Rating | ❌<sup>1</sup> | 🗸 |
| Recent Viewed Products | 🗸 | 🗸 |
| Products by Rating | 🗸 | 🗸 |
| Recent Product Reviews | 🗸 | 🗸 |
| Active Product Filters | ❌<sup>2</sup> | 🗸 |
| Filter Products by Attribute | ❌<sup>2</sup> | 🗸 |
| Filter Products by Price | ❌<sup>2</sup> | 🗸 |
| Filter Products by Rating | ❌<sup>2</sup> | 🗸 |
| Cart | ❌<sup>3</sup> | 🗸 |

#### Issues found
<sup>1</sup> Products and Products by Rating have the initial value of _Number of products to show_ set to 5, but after pressing Update, that value is replaced by 1. This change is only visible when looking at the frontend or by reloading the widgets editor screen.
<sup>2</sup> WC Core filter widgets are invisible when previewed in the widgets editor. That's because they are only visible in the shop page, but it looks quite confusing for users.
![imatge](https://user-images.githubusercontent.com/3616980/102120334-b0ce3600-3e42-11eb-847d-4b56761275fb.png)
<sup>3</sup> In WC Core Cart widget, only title is visible when previewed.
![imatge](https://user-images.githubusercontent.com/3616980/102202330-7ce92400-3ec7-11eb-9ab1-2d78558cdba7.png)

### Testing WooCommerce Blocks in the new widgets editor

| Widget name | Works in editor? | Works in frontend? |
| --- | :---: | :---: |
| Featured Product | ❌<sup>1</sup> | 🗸 |
| Featured Category | ❌<sup>1</sup> | 🗸 |
| Hand-Picked Products | ❌<sup>1, 2</sup> | 🗸 |
| Best Selling Products | ❌<sup>2</sup> | 🗸 |
| Top Rated Products | ❌<sup>2</sup> | 🗸 |
| Newest Products | ❌<sup>2</sup> | 🗸 |
| On Sale Products | ❌<sup>2</sup> | 🗸 |
| Products by Category | ❌<sup>1, 2</sup> | 🗸 |
| Products by Tag | ❌<sup>1, 2</sup> | 🗸 |
| Products by Attribute | ❌<sup>1, 2</sup> | 🗸 |
| Product Categories List | 🗸 | 🗸 |
| Reviews by Product | ❌<sup>1</sup> | 🗸 |
| Reviews by Category | ❌<sup>1</sup> | 🗸 |
| All Reviews | 🗸 | 🗸 |
| Product Search | 🗸 | 🗸 |
| All Products | ❌<sup>1, 3, 6</sup> | 🗸 |
| Filter Products by Price | ❌<sup>1, 6</sup> | 🗸 |
| Filter Products by Attribute | ❌<sup>1</sup> | 🗸 |
| Active Product Filters | ❌<sup>1, 6</sup> | 🗸 |
| Cart | 🗸 | ❌<sup>4</sup> |
| Checkout | 🗸 | ❌<sup>4, 5</sup> |

#### Issues found
<sup>1</sup> `SearchlistControl` has some style conflicts (https://github.com/woocommerce/woocommerce-admin/pull/5901):

| Widget editor | Post/page editor |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/102195288-abaecc80-3ebe-11eb-844a-4f6409f32d63.png) | ![imatge](https://user-images.githubusercontent.com/3616980/102195322-b8332500-3ebe-11eb-881c-8a264b088923.png) |

<sup>2</sup> Product grid images are skewed (#3553).

![imatge](https://user-images.githubusercontent.com/3616980/102196113-bd44a400-3ebf-11eb-8659-1953cd3b5d34.png)

<sup>3</sup> Having an All Products block in the sidebar and another one in the post can cause unexpected behavior. For example, if you change the pagination in the All Products block in the post content  from `1` to `2`, the grid of the All Products block in the sidebar gets updated too, but the pagination components is still marking `1` as the current page. A similar issue happens when interacting with the sort select: product grid is updated in both components but the select is not synced.

<sup>4</sup> Coupon code input and button have different heights (#3575):
![imatge](https://user-images.githubusercontent.com/3616980/102199297-c0da2a00-3ec3-11eb-9d16-620ecca20884.png)

<sup>5</sup> After completing an order, the shortcode is shown (https://github.com/WordPress/gutenberg/issues/27793):
![imatge](https://user-images.githubusercontent.com/3616980/102199729-3d6d0880-3ec4-11eb-903f-ffaf7ed9b38c.png)

<sup>6</sup> It can only be added in one widget area.

### Testing WordPress Core blocks in Storefront

| Widget areas | Works in editor? | Works in frontend? |
| --- | :---: | :---: |
| Sidebar | ❌<sup>1</sup> | 🗸 |
| Below Header | 🗸 | 🗸 |
| Footer Column 1 | 🗸 | 🗸 |
| Footer Column 2 | 🗸 | 🗸 |
| Footer Column 3 | 🗸 | 🗸 |
| Footer Column 4 | 🗸 | 🗸 |

#### Issues found
<sup>1</sup> Cart button styles make it look disabled:
![imatge](https://user-images.githubusercontent.com/3616980/102199024-63de7400-3ec3-11eb-8757-f7a3a666fcb8.png)

### Other issues
* Several core widgets have their block equivalent. As a user, it's not clear what's the difference between them. In some cases, they are almost the same (Product Search), but in some others, they work completely different (ie filters: the widgets work in the Shop page and the blocks work with the All Products block).

**Comment by nerrad** [comment] 2020-12-15 12:23
I'm sure you are already planning this Albert, but make sure you surface the WooCommerce core widget issues to Proton. I think that's something we can safely handoff to them to work on and we'll focus on the extensions we own along with Storefront and blocks compatibility with the new feature.

**Comment by nerrad** [comment] 2021-01-03 19:58
@Aljullu it looks like most (if not all) of the things you found either have a tracking issue or are already have a fix merged. Can you confirm that? Do we need to keep this issue open or are there other things that should be considered as a part of doing work for Cycle 1?

I'm moving this issue to the backlog for now but will pull back into the cycle anything that needs addressed depending on your answer.

**Comment by Aljullu** [comment] 2021-01-04 13:40
@nerrad yes, it's ok to close this issue. Everything that could be fixed on our end has been fixed and follow-up discussions are taking place in pca54o-KL-p2.

**Closed by Aljullu** 2021-01-04 13:40 UTC
Labels: category: blocks, priority: high, type: cooldown, type: wp dependency
