### ISSUE TITLE
Cart - no error messages with coupons

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce-gutenberg-products-block#2301] opened 2020-04-27 11:26 UTC
**Describe the bug**
When testing the various coupon types I expected to see an error if I used one that was not valid etc. I did not get any error messages - all that happened was that the `Apply` button on the coupon compoment stayed in a persistent spinning state and nothing changed on the screen - I had to refresh the page to continue.

**To Reproduce**
Try use a coupon that should return an error and see if you get an error messages

**Expected behavior**
Using a coupon that should result in an error message should return that message on screen so that the user is aware what is happening.

**Screenshots**

<img width="386" alt="Screenshot 2020-04-27 at 12 25 54" src="https://user-images.githubusercontent.com/10805911/80367054-4ac87a80-8882-11ea-91ee-044b25ee876a.png">

**Comment by nerrad** [comment] 2020-04-28 17:21
Hmm I'm unable to reproduce this in either a latest build of master or in the beta release:

![Screen Recording 2020-04-28 at 01 19 PM](https://user-images.githubusercontent.com/1429108/80517394-00fb9500-8953-11ea-8e69-dfa57b2ef568.gif)

Can you give some more info on your browser setup Gary? Also if you have this happen again, can you open your browser console and report any errors you see in it?

**Comment by nerrad** [comment] 2020-04-28 17:23
Also, is `oldcoupon` an actual coupon that exists in your system that should result in an error for the conditions in the cart? If so, can you please include the details of that coupon and why you expected an error message so we can setup those same conditions for replicating? Thanks!

**Comment by nerrad** [comment] 2020-04-28 18:27
Gary I think you may be experiencing the same issue as what is reported by @pedro in 2323, I realize yours was created earlier but there's more info in the other issue so I'm going to close this in favor of that issue (the coupon logic in both cart and checkout is the same).

**Closed by nerrad** 2020-04-28 18:27 UTC
Labels: action: needs feedback
