### ISSUE TITLE
Woo Checkout Block > GDPR config not displayed (gap with the shortcode version)

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#6663] opened 2022-07-06 19:42 UTC
## Describe the bug

The checkout Woo Block does not display the GDPR config values (see Woo config > user account)

"Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our" is not displayed !!

it s only in use with the checkout short code version !!!

## To reproduce

just install Woo and edit Checkout Page in Editor to make use of Woo Checkout Block.

## Expected behavior

Align Checkout block with shortcode version !!

## Screenshots

N/A

## Environment

- WP 6.0
- Gutenberg plugin : no (only core)
- TT2 theme
- WooCommerce 6.6.1
- WooCommerce block 8.8.0

**Comment by ralucaStan** [comment] 2022-07-12 13:24
Hi @Marc-pi,
thank you for taking the time to report this. 

The Checkout Block displays a different structure and text for the Privacy policy and Terms and Conditions section, as seen in the image below.

<img width="791" alt="Screenshot 2022-07-12 at 16 17 13" src="https://user-images.githubusercontent.com/1628454/178499222-5f40e673-a065-4f6a-b925-4e42d29b1bd4.png">

If you don't see the `By proceeding with your purchase you agree to our Terms and Conditions and Privacy Policy` text you need to make sure that the pages you have selected are published.

If you would still like to have that text you can add it in the Editor by selecting the corresponding section, as seen below:
<img width="515" alt="Screenshot 2022-07-12 at 16 23 18" src="https://user-images.githubusercontent.com/1628454/178500388-822cee52-9e17-4c1d-bf24-1e59aad92bf8.png">

I am going to close this ticket as there is no actionable item on our side.

**Comment by Marc-pi** [comment] 2022-07-12 13:32
@ralucaStan 
there are dedicated settings for that purpose on wp-admin/admin.php?page=wc-settings&tab=account
why not using them ?????
it is a regression
![image](https://user-images.githubusercontent.com/919332/178501894-399d7334-0c29-4c8d-b384-b545b12324b8.png)

**Comment by ralucaStan** [comment] 2022-07-13 09:44
@Marc-pi thank you for explaining this further, now I understand better the reason behind your ticket.

With the Checkout Block we wanted to offer an in place editing experience. I've reopened this issue and we will reconsider in the future how we handle that settings in the Checkout Block.

**Comment by senadir** [comment] 2022-08-15 11:19
Hello @Marc-pi ! After digging into this issue more, I will mark it as a not a bug.

Currently, the Checkout block is going to be the future main Checkout, one of things we're working on is moving all of those visual settings to the actual block. For Checkout block, you can actually go an an edit the text with whatever you want.

In the future, that setting will be irrelevant to the Checkout flow.

https://user-images.githubusercontent.com/6165348/184626201-ca06912c-9783-424a-9c13-3e07fc36ef9b.mov

**Closed as completed by senadir** 2022-08-15 11:19 UTC
Labels: block: checkout, focus: settings

**Comment by Marc-pi** [comment] 2022-08-15 11:28
@senadir in that case, please adjust WC settings wording to tell that this setting does *NOT* apply to FSE Cart/Checkout blocks
since those FSE blocks are not experimental anymore (see https://github.com/woocommerce/woocommerce-blocks/pull/6805)
