### ISSUE TITLE
Error with saved credit cards Blocks 6.7.0

### ISSUE THREAD

**Issue by Stella3** [woocommerce/woocommerce-gutenberg-products-block#5522] opened 2022-01-06 01:54 UTC
Since update to Blocks 6.7.0 I have had 5 users report the same credit card issue while using saved cards. They are getting error "payment_data[0] [value] is not of type string.boolean."

## To reproduce
1. Check out as a logged-in user using a saved card 
2.  ![cc](https://user-images.githubusercontent.com/19824054/148314350-f99c6a87-b515-452f-afc6-f7aaa765e640.jpg) this error and there is no record of an attempted charge with Stripe.
3. When I log in to the user account using the using the User Switching app (Windows with Firefox), I am able to run their cards through their accounts. 
4. May be a coincidence but all saved cards have had a 2023 expiration date. 

## Expected behavior
completed charge

## Screenshots
attached

### WordPress (please complete the following information):
* Core version: 5.8.2
* WooCommerce version: 6.0.0
* WooCommerce Blocks version: 6.7.0
* Site language: English
* Any other plugins installed: WooCommerce Stripe Gateway 6.0.0 & Payment Plugins for Stripe WooCommerce 3.3.15 (alternating between the 2 to test and both have the same issue.

### Desktop (please complete the following information):
* OS: Windows, Android
* Browser: Firefox
* Version various 95.0.2 64 bit

### Smartphone (please complete the following information):
* Device: iPhone various
* OS: iOS various
* Browser : Safari 
* Version: various

**Comment by nicdwilson** [comment] 2022-01-06 02:31
Reported in zen-4643869, and replicated

It should be noted that the payment_data token is being put through as an integer.

This is a regression - see here: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3618

![image](https://user-images.githubusercontent.com/3624025/148318365-f9d50842-a80c-42a3-93ab-eefd8115085a.png)

**Comment by tobinfekkes** [comment] 2022-01-06 21:01
We ran into this as well with our Authorize.net payment gateway extension block. It is fixed by supporting the 'integer' type in the `src/StoreApi/Routes/Checkout.php` class.

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Routes/Checkout.php#L77

I would love to have this updated in core so we can resume our plugin updates 😉

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/6226162/148451312-e5a24a24-97b6-4880-9137-c6c92d9c36e3.png">

**Closed as completed** 2022-01-07 13:41 UTC
Labels: type: bug, priority: high

**Comment by ralucaStan** [comment] 2022-01-07 17:40
The fix for this is available in the new WooCommerce Blocks v6.7.1. Please update.

**Comment by tobinfekkes** [comment] 2022-01-08 01:53
Excellent, thank you for getting that fixed so quickly! This is wonderful. 

Just for my own curiosity, can you share the reason why it was cast to a string, rather than support integers?

**Comment by ralucaStan** [comment] 2022-01-12 09:45
@tobinfekkes Supporting integers would have been a change in the API that could have had other implications outside of the fix of this bug. Sticking to the functioning API was the way to go.

**Comment by Stella3** [comment] 2022-03-16 16:30
This was fixed but we're running into a very similar error with saved cards again in 7.1.0 Blocks. As before, this never makes it to Stripe but it does result in a failed order. The error we see on our end is this:

![image](https://user-images.githubusercontent.com/19824054/158638675-bdbd27ef-6623-4573-b22a-9b130a93a05c.png)

**Comment by Stella3** [comment] 2022-03-16 17:16
As a follow-up to that, it may be a new issue where updates to saved cards in WooCommerce are not reflected in the Stripe dashboard. 

We just had one where they had 2 cards in Stripe (call them card A & card B) but, in their My Account page, they showed 2 cards that did not match (card B & card C). I manually cleared out card A from Stripe & Card C from WooCommerce. 

Looks to be the same issue another user had but I'm still trying to isolate it.

**Comment by tobinfekkes** [comment] 2022-03-16 17:41
Sorry to hear this is giving you troubles again! Our saved card issue was that the radio button for the particular card was visually set, but not in the params that React sends back to the server. So it looked selected when rendered, but wasn't actually set under the hood. If a customer actively "selected" a payment profile, it would update and process correctly. But if someone landed on the checkout and saw their payment profile selected and submitted, the payment_method would be empty in the transaction request.

Does it work if you choose a different saved card on checkout? Seems like an issue where the cards weren't synced from Stripe, so card A still existed in Woo, but didn't exist in Stripe anymore.

Unfortunately, I can't test Stripe specifically, we don't use it. But we extend the checkout block payment gateway for Authorize.net the same as Stripe, so there's that similarity. I haven't had issues resurface like the above ticket. I've tested on both v7.1.0 and now v7.2.0.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/6226162/158652534-59f552a4-7862-4100-8120-04e4b50988b5.png">

**Comment by senadir** [comment] 2022-03-17 10:04
Hey @Stella3, could this be a Stripe Plugin issue? did you confirm the bug isn't happening on 7.0.0? We don't really touch cards beyond rendering them on the checkout.

**Comment by Stella3** [comment] 2022-03-17 12:27
@senadir, yes, I should have been more clear with that update I posted. I am now assuming it is definitely a Stripe issue. 

Seems to be many with them lately where approvals take so long that buyers are refreshing the page and creating duplicate orders (we've had 7 in the last week). Of course we end up refunding the duplicate but Stripe still takes the full fee on a refunded order. 

I mention that because it seems as if there may be a connection issue where card updates are also involved.
