### ISSUE TITLE
All Products Block not cropping product images at 1:1

### ISSUE THREAD

**Issue by wyter** [woocommerce/woocommerce-gutenberg-products-block#5398] opened 2021-12-16 06:42 UTC
## Description
When displaying products on a page with the WooCommerce All Products block, portrait images are not getting cropped to the 1:1 setting. This leads to some products being displayed with varying heights wherever the block is used. 

## To reproduce
1. Switch to Storefront
2. In Appearance → Customize → WooCommerce → Product Images, set cropping to 1:1
3. Create a product with a product image that’s has a portrait aspect ratio, I used 304 by 529px
4. Create a page and add the All Products WooCommerce Block
5. For comparison: Make a normal WooCommerce Shop page

## Expected behavior
The All Products block would crop the vertical product image into a square to respect the 1:1 cropping setting in the Customizer → WooCommerce → Product Images

## Screenshots
How it displays on the normal Shop page:
![Normal Shop page](https://user-images.githubusercontent.com/11092629/146319767-2618d728-df1f-4d21-8168-c90c75bf8ea3.png)

How it displays on the All Products Block page
![All Products Block](https://user-images.githubusercontent.com/11092629/146319818-c5b14358-110b-4445-9835-497594343ac8.png)

![Irregular sized images](https://user-images.githubusercontent.com/11092629/146321109-f407f4e5-7f31-41c9-b5cf-79cc5af95963.png)

## Additional context
Reported here : 17746163-hc
Discussion here: p1639563285125700-slack-C3NCP7ZJ6

Related issue : [#2728](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2728)

**Comment by nielslange** [comment] 2021-12-16 09:27
Hello @wyter 👋

Thanks for reporting this problem. I took a brief look and this problem seems to affect all cropping options and all themes. I'll look closer into this case now.

**Comment by nielslange** [comment] 2021-12-20 09:55
Hello @wyter 👋

After investigating this problem, I noticed that it's not trivial to fix. Therefore, I have added this issue to our backlog. I cannot tell you when it will be fixed, but I'll ping you when it will be picked up.

**Comment by alexflorisca** [comment] 2022-01-10 10:01
Hi @wyter Just wanted to let you know I'm currently working on this. The problem is down to the image size setting for the image of the All Products block. This is set to "Full Size" by default, which displays the original product image and does not respect cropping settings. But you can also set this to "Cropped" and it will respect the cropping settings. Here's a step by step:

1. In the editor, open the page with your All Products block. 
2. Click the "Edit inner product layout" button 
<img width="250" alt="Screenshot 2022-01-10 at 11 55 08" src="https://user-images.githubusercontent.com/3966773/148747082-800be92e-dd1b-442f-ab57-69c83070bd61.png">

3. Click on the product image.
4. In the right hand sidebar, click "Block", then you should see 2 options for the image sizing. Select "Cropped".
<img width="317" alt="Screenshot 2022-01-10 at 11 57 18" src="https://user-images.githubusercontent.com/3966773/148747302-380bf1be-379b-4135-9fed-738b196dd20e.png">

5. Click "Done" and "Update" and you should see the product images render as thumbnails, respecting the cropping size.

We are currently discussing making a change so that the images will render with this "Cropped" size by default. However this will not impact existing blocks, only newly created blocks. 

I hope this is helpful and I will update this issue with the decision of changing the default image size.

**Closed as completed** 2022-01-12 17:50 UTC
Labels: type: bug, block: all products
