### ISSUE TITLE
Script Dependencies Report marks all assets as newly added

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#7781] opened 2022-11-29 13:52 UTC
The Script Dependencies Report is supposed to monitor dependencies which are being added in a particular PR. Currently, it marks everything as if it was new.

**Comment by sunyatasattva** [comment] 2022-11-29 14:10
@Aljullu I have investigated this issue and it seems so far it was a fluke which somehow happened [here](https://github.com/woocommerce/woocommerce-blocks/pull/7755#issuecomment-1327641944). Otherwise, new PRs don't seem to have this problem, and I have debugged the action locally, and it seems fine.

I'll keep the issue open for as long as I'm porter this week and I'll keep monitoring new PRs to see if they exhibit this strange behaviour. What do you think?

**Comment by Aljullu** [comment] 2022-11-29 16:23
That's weird, there were several PRs last week where it wasn't working fine. But it's true now it seems to be back to normal. :confused: 

> I'll keep the issue open for as long as I'm porter this week and I'll keep monitoring new PRs to see if they exhibit this strange behaviour. What do you think?

Works for me. Thanks!

**Comment by Aljullu** [comment] 2022-12-02 11:38
Heads-up that the issue seems to be still present in some PRs: https://github.com/woocommerce/woocommerce-blocks/pull/7790#issuecomment-1335085727.  :confused:

**Comment by sunyatasattva** [comment] 2022-12-03 18:17
Somehow the linked comment seems to have been fixed…

**Comment by dinhtungdu** [comment] 2022-12-06 04:10
Sometimes, the `assets.json` file is generated differently between runs, which causes this issue. I have no idea why it happens though. The logs of `build-trunk` actions are identical between the two runs.

Look at these links, they're action logs for the `Check Modified Assets` action of the same PR:

- https://github.com/woocommerce/woocommerce-blocks/actions/runs/3625527020
- https://github.com/woocommerce/woocommerce-blocks/actions/runs/3625638002

<img width="1771" alt="Screen Shot 2022-12-06 at 10 56 56" src="https://user-images.githubusercontent.com/5423135/205811098-72860fe9-b84c-4104-8429-aabd2a92ce8e.png">

**Comment by dinhtungdu** [comment] 2022-12-06 04:11
It's possible that the node modules cache plays a role here, and skipping the cache may fix the issue, but I think it's not the right way to solve this problem.

**Comment by sunyatasattva** [comment] 2022-12-30 15:53
I haven't seen this happen anymore. Shall we close? @Aljullu

**Comment by Aljullu** [comment] 2022-12-30 15:57
I will let @dinhtungdu make the decision, he did some research about this so he will know better. But yes, I can't find any PRs affected by this anymore.

**Comment by dinhtungdu** [comment] 2023-01-01 13:11
I agree, let's close this one.

**Comment by Aljullu** [comment] 2023-02-16 08:07
This seems to be reproducible again, so reopening:

https://github.com/woocommerce/woocommerce-blocks/pull/8445#issuecomment-1431663157

**Comment by mikejolley** [comment] 2023-11-20 15:18
Closing due to pca54o-6Dz-p2

**Closed as completed by mikejolley** 2023-11-20 15:18 UTC
Labels: type: bug, type: cooldown, type: task
