### ISSUE TITLE
Product Query [3]: [Filters] When multiple filter conditions are selected, only the topmost is applied in the Product Query Block

### ISSUE THREAD

**Issue by sunyatasattva** [woocommerce/woocommerce-gutenberg-products-block#7608] opened 2022-11-08 01:16 UTC
> **Warning**
> In order to reproduce this bug, woocommerce/woocommerce-blocks#7382 is required

## Describe the bug

When selecting multiple conditions in a filter paired with a Product Query block inside an FSE template, only the topmost filter is applied.

## To reproduce

Steps to reproduce the behavior with WooCommerce default sample data:

1. Add a “Filter by Attribute” block and a “Product Query” block set to “Inherit query from template” inside the “Product Catalog” template.
2. Filter by “Blue” and “Yellow”.
3. Notice that only blue products are shown, not yellow.

## Expected behavior

Adding multiple filters should behave as in `OR` condition and show all products that match any of the conditions.

## Screenshots

![Screenshot 2022-11-08 at 02 09 38](https://user-images.githubusercontent.com/1847066/200449261-b25cae0f-d14b-43a1-94dd-af45c169844f.png)

## Additional context

Apparently, this works correctly inside a normal post/page without inheriting the query from the template.

**Comment by imanish003** [comment] 2023-04-18 10:57
I just checked, and it appears that this issue is no longer reproducible. I believe the issue was fixed while working on other tasks.
@kmanijak, would you mind trying to reproduce it as well? If you're unable to reproduce it then I think we can close this issue. 🙂

**Comment by gigitux** [comment] 2023-04-18 12:58
This issue is replicable only with the custom implementation of the "inherit query from template" setting.

![image](https://user-images.githubusercontent.com/4463174/232784718-30fb67aa-5563-4813-9a17-20600e769499.png)

**Comment by imanish003** [comment] 2023-04-19 09:24
Hi @gigitux, Thanks for the clarification 🙏  I'll be closing this issue for the time being. Should we decide to implement a custom "inherit query from template" feature in the future, we can always reopen it. Related issues can be found under Epic woocommerce/woocommerce#42616. 🔍👀
Internal discussion: p1681812585287949-slack-C02UBB1EPEF

<img width="781" alt="image" src="https://user-images.githubusercontent.com/16707866/233030866-8a102f98-179f-4e1f-84cb-15129b4f3e1b.png">

**Closed as completed by imanish003** 2023-04-19 09:24 UTC
Labels: type: bug, block-type: product-query

**Comment by kmanijak** [comment] 2023-04-19 09:44
> @kmanijak, would you mind trying to reproduce it as well? If you're unable to reproduce it then I think we can close this issue. 🙂

For visibility - I wasn't able to follow the steps to reproduce, due to the issue encountered. But I'm glad there's decision anyway 🙏
