### ISSUE TITLE
Installed latest Plugin and product images are not displaying

### ISSUE THREAD

**Issue by amdclarke31** [woocommerce/woocommerce-gutenberg-products-block#3416] opened 2020-11-17 21:57 UTC
## Describe the bug

My Woocommerce site has been updated to 4.7, Wordpress version is 5.5.3.  I installed the latest Woocommerce Blocks pluggin which has caused he following issue

## To reproduce

1. Go to https://wearfreedom.ie/product-category/dancewear-ireland/leotard/
2. Click on Any product image
3. Product detail page open
4. The image is not displaying.

## Expected behavior
When the product details page opens there should be an image of the product
## Screenshots

https://wearfreedom.ie/product-category/dancewear-ireland/leotard/

<img width="1023" alt="Screenshot 2020-11-17 at 21 56 33" src="https://user-images.githubusercontent.com/74627637/99455545-e6553180-291f-11eb-989a-393df68ca415.png">

### WordPress (please complete the following information):
* Core version: [e.g. 5.0.3]
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: [e.g. 3.5.3]
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by senadir** [comment] 2020-11-18 12:14
Hi there,

I can't seem to reproduce this issue, I can see images clearly on your website so it could be a cache issue from your side.

![image](https://user-images.githubusercontent.com/6165348/99529477-28be5300-29a0-11eb-9ca6-ac30f80a4142.png)


Nevertheless, this issue is not related to WooCommerce Blocks because we don't touch the product page at all, so we couldn't possibly influence this.

I'm going to close this issue because there's nothing to address here, but you manage to pinpoint the reason WooCommerce Blocks is causing this issue for you, feel free to comment it here and open this back.

**Closed as completed by senadir** 2020-11-18 12:14 UTC
Labels: type: bug
