### ISSUE TITLE
Product Category link takes you back to shop base page

### ISSUE THREAD

**Issue by leahwo** [woocommerce/woocommerce-gutenberg-products-block#3133] opened 2020-09-05 18:20 UTC
I'm not sure why but when I use a product categories block the actual link should take you to that particular category but instead every category link takes me back to the shop base page.
http://foliaevents.com/newsite/add-ons/

**Comment by nerrad** [comment] 2020-09-15 14:49
Hi @leahwo 👋 

Thanks for your bug report. I'm unable to reproduce the bug you reported with the category links generated by the Product Categories block not going to the category archive page. I also went to the link you shared for your site and it doesn't appear that you are using the block on the page at this url: http://foliaevents.com/newsite/add-ons/.

If you're interested in troubleshooting this further, we'll need a few more details:

- What WooCommerce core version are you using on your site?
- If you're using the WooCommerce Blocks feature plugin, what version of it?
- What theme are you using (and version)?
- Have you tried [these troubleshooting steps](https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4)?

**Comment by nerrad** [comment] 2020-09-17 15:10
I'm going to close this issue for now since it's not reproducible on our end. Please feel free to leave a comment with any additional details and we'll be happy to retry reproducing and reopening the issue if needed.

**Closed by nerrad** 2020-09-17 15:10 UTC
Labels: action: needs feedback, type: bug, ◼️ block: product categories list
