### ISSUE TITLE
Unable to change address for shipping calculations in basket.

### ISSUE THREAD

**Issue by emcgal** [woocommerce/woocommerce-gutenberg-products-block#9785] opened 2023-06-12 09:37 UTC
Hi, 
A client got stung last week on shipping and I am looking at it more closely now. The option to change the address isn't showing in the basket but is switched on. I tried to pop a note here because particularly on mobile, the shipping defaults to the shop location, ie Ireland because that is the majority of her customers come from plus shop collect is still really popular for her. I tried switching to geolocation and wasn't calculating at all. 

https://connemarablue.com/basket/

1) The change address is no showing in basket.

2) This is a knock on effect: The shipping in the checkout stays at the default on checkout and not giving the correct amount. The shipping address is down further but the customer sees the total from the basket. 

This was working, isn't now. This website is in maintenance for quite a while. 

Can someone please shed some light? For now I have had to put shipping to Ireland on the shipping options plus some text until it gets resolved why the user cannot update the address in the basket when the setting is on.

Also it was displaying off line on mobile. This could be a caching issue which I need to looking into as well.

Thanks,
Emer

**Comment by mikejolley** [comment] 2023-06-13 12:42
Hi,

Hard to say whats happening just by looking at it, but for point 1, there are two settings that can prevent the calculator being shown:

1. WooCommerce > Settings > Shipping > "Enable the shipping calculator on the cart page"
2. Edit the cart page select the shipping section in the block and there is this setting in the sidebar:

![Screenshot 2023-06-13 at 13 38 40](https://github.com/woocommerce/woocommerce-blocks/assets/90977/4f336af2-96c1-4166-863e-65a6c49c254e)

There is also a case whereby if a local pickup/collection rate is selected, the calculate button disappears. I consider this a bug so I'll patch this shortly. 

> This is a knock on effect: The shipping in the checkout stays at the default on checkout and not giving the correct amount. The shipping address is down further but the customer sees the total from the basket.

Can you explain the steps to replicate this one please? The rates should update (depending on your shipping sections) when the shopper completes the address fields. Is this not happening?

**Comment by tarunvijwani** [comment] 2023-07-07 12:47
@emcgal I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Comment by emcgal** [comment] 2023-07-07 14:45
Hi, 
Would you please mind reopening this. For some reason I only received this last notification not the previous one.  I checked several times after I posted but I was travelling a lot then. I expected an email notification (especially when the last one did come in) but no sign.

What exactly do you need from me?
I have a copy of the issue on this staging copy so I can play with it and try to debug it.
https://staging14.connemarablue.com/
* Under Shipping > Shipping Options: Hide shipping costs until an address is entered is unchecked. Is there another one you are referring to?
* We are using Flexible shipping for weights to define the shipping zones. 
* On the basket page, that setting is on for the Shipping Calculator. 

As I mentioned, this was working fine and not it isn't so I am really baffled where to even begin. I will check back in on Monday.

**Comment by mikejolley** [comment] 2023-07-11 10:53
> Under Shipping > Shipping Options: Hide shipping costs until an address is entered is unchecked. Is there another one you are referring to?

yeah, its labelled "Enable the shipping calculator on the cart page". This is under WooCommerce > Settings > Shipping. I realise its slightly confusing to have 2 settings that do the same thing, but one is global and one is at block level. Ensure both are toggled on.

> This is a knock on effect: The shipping in the checkout stays at the default on checkout and not giving the correct amount. The shipping address is down further but the customer sees the total from the basket.

We'd need the steps you took to replicate this one. It should be that as the user inputs their address during checkout, rates are updated to reflect this. I'm not sure if perhaps the shipping plugin you're using would break this or if its compatible with blocks. If it uses the standard shipping zones in WooCommerce, it should be fine.

**Comment by mikejolley** [comment] 2023-07-24 11:24
We'll need to do further investigation into this. Closing in favour of https://github.com/woocommerce/woocommerce/issues/42280

**Closed as completed by mikejolley** 2023-07-24 11:24 UTC
Labels: block: cart, block: checkout, type: community contribution

**Comment by emcgal** [comment] 2023-07-24 12:35
Thanks a mil @mikejolley and again so sorry, I am not getting notifications unless the status of the ticket changes. I will pop this on woocommerce/woocommerce#42280 as well but the option to even enter the address in the basket is no longer there. Just shows the shipping options which are set to Ireland by default as most customers are coming from Ireland. In the past we were able to change it and it is still available on another client website I still have full access too that used the postcode in Dublin. It is showing on theirs and I can't see any difference in the settings so I am starting to wonder has something become corrupt?

Most of my clients don't bother with shipping abroad anymore with the costs so I'm limited in what I can compare to.
