### ISSUE TITLE
[GlobalStep]User is able to use email limited coupon on every mail id.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2640] opened 2020-06-04 15:21 UTC
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. On dashboard create a email limited coupon(use email: "*@automattic.com").
3. Go to site.
4. Add a product to cart.
5. Procced to checkout.
6. Enter any email id other than we used while creating a coupon for example "priyanka.zanwar@globalstep.com".
9. Observe that no error message is displayed and user is able to apply email limited coupon on every mail id

**Actual Result:**
User is able to use email limited coupon on every mail id.

**Expected Result:**
User should not be able to use email limited coupon on every mail id.

[#2640.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4731005/2640.zip)

**Comment by nerrad** [comment] 2020-06-05 00:02
This is a valid issue in that there is no immediate feedback that the coupon is not valid. However, if the checkout is submitted with that coupon, then the submission will fail.

@mikejolley, I seem to remember this was something we knew about and weren’t able to address right away for some reason, do you recall as well?

**Comment by mikejolley** [comment] 2020-06-05 08:08
@nerrad the check happens later because earlier on in checkout or cart we may have no email to compare against. 

We could consider blocking the coupon until an email is provided but then that would require yet more checks if email is modified after that.

**Comment by nerrad** [comment] 2020-06-05 11:02
Ahh right, I thought it was something like that. Okay I've confirmed that the email restriction _does_ work when the checkout is submitted so I'm going to go ahead and close this.

**Closed by nerrad** 2020-06-05 11:02 UTC
Labels: scope: rest-api, type: bug
