### ISSUE TITLE
Checkout Block fields are not pre-filled via Customer payment page link for Subscription Renewal Orders

### ISSUE THREAD

**Issue by namiokuzono** [woocommerce/woocommerce-gutenberg-products-block#5456] opened 2021-12-24 18:40 UTC
## Describe the bug
WC Block's Checkout block does not pre-fill the Checkout Block fields upon sharing the "Customer payment page" link. 

## To reproduce

Make sure the Checkout page has a Checkout block. 
Make sure to have WC SUB and SUB product.
Make sure to have a Subscriber to assign. 

1. Create an order with a subscription product (WooCommerce > Order > Create an order)
2. Create a subscription (WooCommerce > Subscriptions > Add Subscription)
3. Select the order created in step 1 as a Parent Order
4. Once the Subscription is created, create a renewal order "Create a pending renewal order"
5. Copy "Custoer payment page" link
6. Log in as the Subscriber or use plugin such as User Switching - https://wordpress.org/plugins/user-switching/
7. When pasting the link you copied, you will not see any pre-filled fields

## Expected behavior

The Checkout fields should be pre-filled for all the information such as First Last, Address, and Email (and Phone)

## Screenshots

Comparison of Checkout page via shortcode vs. Checkout Block

**WC Core Checkout page ` [woocommerce_checkout] `**
![https://d.pr/i/VinEr5](https://d.pr/i/VinEr5+)
Image link: https://d.pr/i/VinEr5

**WC Block Checkout block**
![https://d.pr/i/ducYmU](https://d.pr/i/ducYmU+)
Image link: https://d.pr/i/ducYmU

**Comment by namiokuzono** [comment] 2021-12-24 19:11
4633346-zen

**Comment by ralucaStan** [comment] 2021-12-28 15:53
Thank you @namiokuzono for taking the time and reporting this. 
I was able to reproduce this. WC Subscriptions is an extension supported by the C&C Blocks. Looks like the issue is coming from the block's side.
I am moving this to Needs Leads Triage in order to help with deciding the priority/next steps.

**Comment by Stella3** [comment] 2021-12-30 00:34
This appears to be more widespread than just subscriptions!

I am seeing this behavior with ALL signed in users. Our site is wholesale only and all users have saved contact info/addresses. 

Today all are reporting that the checkout page is not populated at all except for their saved CC info. 

This is causing CC processing failures because the users are accustomed to skipping the contact/shipping info. 

https://frameandthread.com/checkout/

Blocks 6.6.0
Stripe Gateway 5.9.0
WooCommerce 6.0.0

**Closed as completed** 2021-12-31 15:10 UTC
Labels: type: bug, block: checkout

**Comment by ralucaStan** [comment] 2022-01-04 13:21
The fix is now part of the new release. Please update to WooCommerce Blocks 6.7.0.
