### ISSUE TITLE
Mollie payment options not appearing on live site

### ISSUE THREAD

**Issue by kcswong** [woocommerce/woocommerce-gutenberg-products-block#11508] opened 2023-10-31 02:08 UTC
## Describe the bug

Reported in 7225959-zen, this is a WordPress.com site. The user has [Mollie Payments for WooCommerce](https://woocommerce.com/products/mollie-payments-for-woocommerce/) activated, but none of the enabled options appear in the live site's checkout, only in the editor within the Checkout block. It's a bit difficult to test as I wasn't able to use a live API key (there's a verification process a business has to go through to enable access; the user's site is using a live API key), but using a test API key had the same results.

## To reproduce

1. Install and activate the [Mollie Payments for WooCommerce](https://woocommerce.com/products/mollie-payments-for-woocommerce/) plugin
2. Sign up for an account to get a test API key, and add it in WooCommerce > Settings > Mollie Settings > General
3. Enable the Mollie - Vouchers payment method in WooCommerce > Settings > Payments

## Expected behavior

The new Vouchers option should appear on the live site's checkout.

### WordPress (please complete the following information):

-   WordPress version: 6.3.2
-   Gutenberg version (if installed): 16.9
-   WooCommerce version: 8.2.1

**Comment by opr** [comment] 2023-11-02 12:55
Hi, I was able to reproduce but I'm not sure if this is an issue for us to fix in WC Blocks, I'd expect Mollie to look into it first and for them to let us know if there's something going wrong with payment method registration.

If it were a problem in WC Blocks I'd expect other gateways to be broken as well.

Would it be possible for you to raise this with Mollie, and let them know about this issue so they can comment on it if necessary?

Thanks!

**Comment by kcswong** [comment] 2023-11-02 20:51
Thanks @opr! I've reached out to the user to let them know, as they'd previously been in contact with Mollie related to this issue.

**Comment by opr** [comment] 2023-11-03 17:38
Thanks @kcswong I'll close this issue until they come back with something actionable. Thanks a lot!

**Comment by kathrynwp** [comment] 2023-11-09 21:32
@opr Hi - user came back and said 

> I reached out to Mollie again, they checked everything they could but there are no errors on their end. It really has to do with the Tazza theme.

**Comment by opr** [comment] 2023-11-09 21:34
> @opr Hi - user came back and said 
> 
> > I reached out to Mollie again, they checked everything they could but there are no errors on their end. It really has to do with the Tazza theme. 

Hi @kathrynwp that doesn't sound right, it was not showing for me on Twenty twenty three either. If they change theme does it show up for them?

**Comment by kathrynwp** [comment] 2023-11-09 21:37
@opr I'll ask them!

**Comment by kathrynwp** [comment] 2023-11-09 21:46
@opr I see in the ticket that on Nov. 2 they did mention that it was working with TT3. I've asked them to re-test since it now appears broken for you in TT3.

**Comment by ghost** [comment] 2023-11-11 10:52
Hi @opr @kathrynwp @kcswong, I'm the user with said problem. I just answered the email Kathryn sent me, but maybe we can come to a quicker solution if I react here too: 
I tested every other Automattic theme in store format: Attar, Winkel, Tsubaki, Zaino, Amulet; none of them work. 
So far I found a few themes that do work: Twenty Sixteen, Twenty Seventeen, Twenty Nineteen, Twenty Twenty and Twenty Twenty One. But: those are blog themes. Not shop themes. 
Twenty Twenty Two and Twenty Twenty Three aren't working.  

I can't wrap my head around the fact that it's a Mollie problem when there are themes that show no error. 

Hope you can help!

**Comment by ccwalburn** [comment] 2023-11-13 16:08
Just noting that the themes it does not work with are all Block (FSE) themes so I have suggested reaching out to Mollie again to see if they have examples of any Block themes that their plugin works with.

**Comment by wavvves** [comment] 2023-11-14 17:45
@opr when you succesfully reproduced this problem, did you check against the classic checkout?
I am not getting the payment option there too, so I wonder if anything's broke at plugin level, and we're being induced in error by something else like caching for example.

Blocks

<img width="782" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/17236129/cb56e8d5-1fe9-4519-952b-194c3793695a">

Classic Checkout

<img width="610" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/17236129/37258b07-ce4e-4305-a5bd-5c58726547ef">

**Comment by InpsydeNiklas** [comment] 2023-11-15 12:26
Hi team, the Mollie plugin has yet to be optimized for the new Checkout templates while using a Block theme. Consequently, the Mollie payment methods may not appear when creating a Block Checkout via the Checkout template with the Site Editor.
With a regular shortcode Checkout in the template, it seems to be working correctly, though (I tried `Twenty Twenty-Three` and `Twenty Twenty-Four`. Please note, the Voucher gateway in particular also requires the product to have a [Voucher category assigned](https://github.com/mollie/WooCommerce/wiki/Setting-up-Voucher-gateway) to load.

One way to work around the limitation with the Block Checkout template would be to create a new page with the Checkout Block.
Attached is an example of how the _template_ Block Checkout doesn't show the payment methods in the frontend while a newly created _page_ with the Checkout Block does load the methods (please excuse the misplaced cursor):
https://github.com/woocommerce/woocommerce-blocks/assets/70433191/4e69b725-b8e2-42de-bbf5-f7083ab783d7
This will be addressed within the scope of the Mollie plugin in a future update.

**Comment by ghost** [comment] 2023-11-15 12:46
Hi everyone, 
I just found a solution for this problem. Mollie asked me to update the Woocommerce Blocks plugin because according to them it was running on the 11.5.2 version when it needed to be 11.5.4. I checked but the Woocommerce plugin wasn't even installed, so when I installed the plugin, the problem was solved. 
Mollies payment options appear now and they work properly.

**Comment by wavvves** [comment] 2023-11-15 17:47
>Please note, the Voucher gateway in particular also requires the product to have a [Voucher category assigned](https://github.com/mollie/WooCommerce/wiki/Setting-up-Voucher-gateway) to load.

Thanks for clarifying this @InpsydeNiklas 🙇🏼 

I'm closing this issue as a solution was found.

**Closed as completed by wavvves** 2023-11-15 17:47 UTC
Labels: type: bug, block: checkout, focus: data-store, type: community contribution
