### ISSUE TITLE
Coinbase payment gateway doesn't work with Cart and Checkout Blocks

### ISSUE THREAD

**Issue by VDiamond78** [woocommerce/woocommerce-gutenberg-products-block#10318] opened 2023-07-22 12:14 UTC
Nowdays, the cryptocurrencies gains more and more importance and they become a way of payment more and more common.
In this path, I would like to add this payement option to my website but she's doesn't compatible with the blocks.

So, I hope you will made that compatible between them as quickly as possible.

Thanks for your listening and hoping you can take care of it !

**Comment by mikejolley** [comment] 2023-07-24 10:26
Closing as duplicate of https://github.com/woocommerce/woocommerce-blocks/issues/10317

**Closed as completed by mikejolley** 2023-07-24 10:26 UTC
Labels: type: community contribution
