### ISSUE TITLE
Cart/Checkout Blocks: Free shipping coupon should automatically select free shipping option

### ISSUE THREAD

**Issue by chickenn00dle** [woocommerce/woocommerce-gutenberg-products-block#2345] opened 2020-04-29 04:47 UTC
**Describe the bug**
After successfully adding a coupon for free shipping, the previously selected shipping radio button remains selected.

**To Reproduce**

1. Create a free shipping coupon
2. Set up Shipping zones/rates
3. Add an item to your cart and select a shipping option
4. Add the free shipping coupon
5. You will then have to manually select the free shipping option

**Expected behavior**
I would expect adding a free shipping coupon to automatically select the free shipping radio button for me 

**Screenshots**
![Screen Capture on 2020-04-29 at 13-39-01](https://user-images.githubusercontent.com/17905991/80561526-bc89fb00-8a1f-11ea-82e6-c11563f5bbcd.gif)

**WordPress (please complete the following information):**

* Core version: 5.4
* WooCommerce version: 4.1
* WooCommerce Blocks version: 2.6.0-beta.1
* Site language: English

**Desktop (please complete the following information):**

* OS: iOS
* Browser FireFox
* Version 75.0

**Comment by nerrad** [comment] 2020-04-29 21:04
Hmm ya that's a good idea, this is a good companion to #2302.

**Comment by mikejolley** [comment] 2020-04-30 11:51
I'm pretty certain WooCommerce core handles this for us; in testing I wasn't able to reproduce the issue as shown in this gif:

![2020-04-30 12 44 25](https://user-images.githubusercontent.com/90977/80707005-2ae2c200-8ae1-11ea-8d2f-36bfd03329b9.gif)

**Comment by Aljullu** [comment] 2020-04-30 12:35
I couldn't reproduce it either: I tested with `master` and beta 1, tried with logged/unlogged users and whether the number of shipping rates made any difference, but in all cases the `free shipping` option was selected when introducing the coupon.

@chickenn00dle do you think there might be a step to reproduce that we are missing? :confused: 

I will proceed closing this issue, but we can reopen it if we get more details or somebody else can reproduce.

**Closed by Aljullu** 2020-04-30 12:35 UTC
Labels: type: enhancement
