### ISSUE TITLE
Individual product scope: Entire search result row should be clickable

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce-gutenberg-products-block#82] opened 2018-03-23 15:58 UTC
![result](https://cldup.com/zuGGRHvRLj-2000x2000.png)

Currently you have to click the `Add` link. It should be possible to click the entire row. We can then remove the superfluous Add link.

**Comment by claudiulodro** [comment] 2018-04-03 16:29
lol. You made a duplicate of your own issue #70. :P

**Closed by claudiulodro** 2018-04-03 16:29 UTC
Labels: Enhancement
