### ISSUE TITLE
Aggregated Notices shown on Checkout instead of Cart when Redirect to cart is set.

### ISSUE THREAD

**Issue by jimbardim** [woocommerce/woocommerce-gutenberg-products-block#3132] opened 2020-09-08 22:16 UTC
Edited by @senadir
Note: Couldn't reproduce on a local website, only on `sentralshop.com`
"X has been added to your cart" notice is shown on Checkout, this happens because that notice should be shown on Shop page, but that page is skipped when you have "Redirect to cart" option set to true, and is not shown on Cart because it seems to be generated after showing the page.

## Steps to reproduce
1. Enable "Settings -> Products -> Add to cart Behavior -> Redirect to cart and Use Ajax"
2. Add a product to your cart, you will be redirected to Cart block with no notice.
3. Continue to Checkout or any other page, you will see the notice.

## Expected Behavior
The notice should be shown on cart page.

**Comment by jimbardim** [comment] 2020-09-09 18:22
sure @juliaamosova 
step 1) someone goes into sentralshop.com
step 2) he adds a product in the cart
step 3) he go into checkout
on the top of checkout he see this
[https://ibb.co/gyBqWQW](url)
when normally this should exist in the cart page but none the less we don't need this to appear at all

now step 4) as soon as someone visit that page (the checkout page) woo record it as a sale
doesn't matter if i have add any payments inside my woo account or not, so essentially if someone visit my checkout page he is recorded as a sale
here an example [https://ibb.co/wdJZC5m](url)
those are just me visiting the checkout page. and this is a huge issue

if you need me to shoot a video to show to you let me know

**Comment by jimbardim** [comment] 2020-09-12 00:53
@juliaamosova any news regarding the issue?
https://ibb.co/wdJZC5m

**Comment by senadir** [comment] 2020-09-13 19:55
@jimbardim for the second issue (the one about orders showing in sales), this happens because Checkout block will capture any order and save it as a draft order, that order will be cleared after 24h if the customer didn't finish it.

**Comment by senadir** [comment] 2020-09-13 20:01
For the first issue, this seems to happen on your website because you have this option set to true
![image](https://user-images.githubusercontent.com/6165348/93027281-bf1e7300-f603-11ea-901a-c88c6230bc93.png)
cc @Aljullu when that option is shown, the notice should be shown on Cart block, seems related to https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2854

**Comment by jimbardim** [comment] 2020-09-13 20:28
@senadir  i want the use to go in the cart page after the addition, but that message is NOT showing on the cart page but on the checkout page that has nothing to do with the cart...

in addition i build another store for a client
dealsfromheaven.com
and when someone add a product to the cart and go in the checkout he doesn't see this message on the checkout

**Comment by senadir** [comment] 2020-09-13 20:35
> in addition i build another store for a client
dealsfromheaven.com
and when someone add a product to the cart and go in the checkout he doesn't see this message on the checkout

Yes, I'm aware of that, that's because you don't have that option set to true on that website, **this is a bug** and should be fixed in a future release.

**Comment by jimbardim** [comment] 2020-09-13 20:41
@senadir  hopefully this bug along with paypal express checkout and woo payments will be rolled out soon coz we can't use it to actually receive payments as it is right now.... i have high hopes for this...
can also have the option when a product is on the cart or checkout to exclude the first sentence from product details? we add alot of times images there and in the cart and checkout it doesn't look good. i would open the issue but the truth is few days i found about github and i am not very good at opening requests etc, and i don't know if this is mentioned from someone else.

thanks for your help btway.

**Comment by senadir** [comment] 2020-09-13 20:54
> can also have the option when a product is on the cart or checkout to exclude the first sentence from product details? we add alot of times images there and in the cart and checkout it doesn't look good. i would open the issue but the truth is few days i found about github and i am not very good at opening requests etc, and i don't know if this is mentioned from someone else.

I agree that having images on the product description is not desirable, [I've filled an issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3142) but I will this up to the design team to decide.

**Comment by senadir** [comment] 2020-09-15 16:45
@jimbardim I've updated the issue title and content to better reflect the current issue, but I'm unable to reproduce the issue on a local website, this means that I'm missing something from the testing instructions, or that your website has something affecting the behavior, can you disable all extra plugins and switch to storefront and test again?
![image](https://user-images.githubusercontent.com/6165348/93239724-15fa8880-f77b-11ea-98cc-5e82c12f8a34.png)

**Comment by jimbardim** [comment] 2020-09-16 00:25
the problem is it takes few lines from product description

https://ibb.co/jfqbTxR

i switch to storefront

now as far as plugins i can't think any to conflict
i use woo obviously
really simple ssl
Better Search Replace
Self-Hosted Google Fonts
WooCommerce PayPal Checkout Gateway

**Comment by nerrad** [comment] 2020-09-17 15:08
@jimbardim it appears your latest comment is referencing the issue with the product summaries in the cart as noted in the new issue @senadir created. Let's keep the conversation related to that in the new issue so it's easier for us to follow the conversation and address your feedback.

@senadir's question [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3132#issuecomment-692837771) is specific to the issue around Notices and he's having trouble reproducing this. Do you have anything to add regarding that?

**Comment by jimbardim** [comment] 2020-09-17 21:35
@nerrad i don't know my way here, this issue appears on checkout as well, obviously we can't advertise and show our products like this.

**Comment by nerrad** [comment] 2020-09-18 12:32
> @nerrad i don't know my way here, this issue appears on checkout as well, obviously we can't advertise and show our products like this.

Are you talking about the issue with product summaries in the cart (which has been split out to #3142). If yes, let's please move the conversation to that issue. Thanks.

We can keep this issue here specific to the report around aggregated notices (which so far is not reproducible by our team).

**Comment by jimbardim** [comment] 2020-09-18 14:28
@nerrad i am talking about the issue
1) images on the cart that the plugin take from product description (it actually take the first few lines from description so if in the description we have image it pull the image) same thing happens on checkout as well.

2) it doesn't work with paypal express checkout which should be standard

3) doesn't work with woo payments which is stripe essentially

4) when someone visit the checkout page it record it as a sale i have shown this at least 2-3 times
doesn't matter if the user add his info or not (on top someone mention that after few hours this draft order dissapear which is not happening)

i know that i wrote about many issues guys here but my frustration is on the roof right now it seems nothing work correct at the moment.

**Comment by nerrad** [comment] 2020-09-18 17:53
I understand you are frustrated but let's keep in mind a few things:

- The Cart and Checkout blocks are in preview. We still are iterating on improving them, which takes time. That does mean we have to prioritize what we work on and that priority may not always line up with every store's needs. Even so, we still welcome feedback and reports of folks needs so we can use that to help guide our future work.
- Given the above, it's completely understandable that some stores might not be able to use the Cart and Checkout blocks for now. Which is why going back to the shortcode flows is an option for those stores.
- The repository here is not an avenue for support. We're pretty focused here on continuing to work on the priority list we have. That does require that we draw a line on any help we can give specific stores here. 

Regarding the itemized list you left above.

> 1. images on the cart that the plugin take from product description (it actually take the first few lines from description so if in the description we have image it pull the image) same thing happens on checkout as well.

An issue on this has been created and it has gone into our list of things to do. I can't give you an ETA when it will be addressed but it is something we will address in some way.

> 2. it doesn't work with paypal express checkout which should be standard

Correct, not all payment methods are integrated with the new blocks yet. That is something that will change over time as payment method extensions integrate with the new blocks.

> 3. doesn't work with woo payments which is stripe essentially

Correct, WooCommerce Payments is currently working on an integration and you should see it in a future release of that extension.

> 4. when someone visit the checkout page it record it as a sale i have shown this at least 2-3 times
doesn't matter if the user add his info or not (on top someone mention that after few hours this draft order dissapear which is not happening)

@senadir's has already given a good answer around the purpose of the draft order and how it works (along with linking to the issue created in the WooCommerce Admin repository for improving the reporting of draft orders so they are not included with sale reports by default. 

At this point, given your frustration and the issues you are facing I do suggest you may want to restore the shortcodes for cart and checkout block flows until the blocks have support for the extensions you use and some of the issues you have raised have been addressed. You can also [keep an eye on this document](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) which we will be updating as we build support for additional extensions. You can also [subscribe to the issues that have been created](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications#notifications-and-subscriptions) and watch for [updates to the Blocks plugin](https://developer.woocommerce.com/category/blocks/) which should help with discovery around any fixes that interest you for your needs.

I realize the above may not be what you are looking for, but that's the best we can do at the moment.

**Closed** 2020-11-10 16:10 UTC
Labels: type: bug, ◼️ block: cart
