### ISSUE TITLE
Correctly handle store tax options in Cart and Checkout blocks

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#1798] opened 2020-02-23 20:08 UTC
In WooCommerce there are 3 settings for whether prices are inclusive or exclusive of tax:

- `Prices entered with tax`
- `Display prices in the shop` incl/excl tax
- `Display prices during cart and checkout` incl/excl tax

Of these, I think `Display prices during cart and checkout` is the one that the cart & checkout blocks should respect. From my testing, it looks like the cart block is using the `Display prices in the shop` setting, so if they are set differently, there might be a bug. (This is a little complicated, perhaps this is into edge case territory!)

With these set as follows, the cart block doesn't show the same pricing as existing cart.

- `Display prices in the shop: Excluding tax`
- `Display prices during cart and checkout: including tax`

<img width="668" alt="Screen Shot 2020-02-27 at 1 23 33 PM" src="https://user-images.githubusercontent.com/4167300/75400514-5cfe6900-5964-11ea-8c33-def744ef4739.png">

<img width="814" alt="Screen Shot 2020-02-27 at 1 28 59 PM" src="https://user-images.githubusercontent.com/4167300/75400786-1eb57980-5965-11ea-8c05-aa7fef5adef3.png">

<img width="821" alt="Screen Shot 2020-02-27 at 1 29 24 PM" src="https://user-images.githubusercontent.com/4167300/75400808-2e34c280-5965-11ea-9d16-e989354ee479.png">

Differences/issues I'm seeing:

- Cart block should show line item prices incl tax based on `Display prices during cart and checkout` option.
- Consider adding `(incl tax)` to prices that include tax.
- Consider adding the tax name – not sure how relevant/important this is, but it is shown on existing cart.

**Comment by haszari** [comment] 2020-02-23 20:13
Spun off new issue noticed when testing #1784

**Comment by nerrad** [comment] 2020-02-24 17:18
Since this will need to be done for both cart and checkout (and will likely involve the same components) I modified the title.

**Comment by mikejolley** [comment] 2020-02-25 15:25
Upon checking this, it seems to be working in master now. Whether that's down to changes we've made since logged this issue or a different setting is not certain :)

![Screenshot 2020-02-25 at 15 22 26](https://user-images.githubusercontent.com/90977/75261412-e8e88780-57e2-11ea-986f-14e1f94a0fa7.png)

This option affects display also it should be noted.

For me, inclusive options did not show a tax row and prices were shown correctly inclusive of tax.

Closing this for now but let me know if I missed something reproducing this.

**Comment by haszari** [comment] 2020-02-27 00:34
Did some more testing :) Reopening this, I think there's an issue (or inconsistent behaviour with old checkout). 

There are 3 settings:

- `Prices entered with tax`
- `Display prices in the shop` incl/excl tax
- `Display prices during cart and checkout` incl/excl tax

Of these, I think `Display prices during cart and checkout` is the one that the cart & checkout blocks should respect. From my testing, it looks like the cart block is using the `Display prices in the shop` setting, so if they are set differently, there might be a bug. (This is a little complicated, perhaps this is into edge case territory!)

With these set as follows, the cart block doesn't show the same pricing as existing cart.

- `Display prices in the shop: Excluding tax`
- `Display prices during cart and checkout: including tax`

<img width="668" alt="Screen Shot 2020-02-27 at 1 23 33 PM" src="https://user-images.githubusercontent.com/4167300/75400514-5cfe6900-5964-11ea-8c33-def744ef4739.png">

<img width="814" alt="Screen Shot 2020-02-27 at 1 28 59 PM" src="https://user-images.githubusercontent.com/4167300/75400786-1eb57980-5965-11ea-8c05-aa7fef5adef3.png">

<img width="821" alt="Screen Shot 2020-02-27 at 1 29 24 PM" src="https://user-images.githubusercontent.com/4167300/75400808-2e34c280-5965-11ea-9d16-e989354ee479.png">

Differences/issues I'm seeing:

- Cart block should show line item prices incl tax based on `Display prices during cart and checkout` option.
- Consider adding `(incl tax)` to prices that include tax.
- Consider adding the tax name – not sure how relevant/important this is, but it is shown on existing cart.

I've generalised the issue title & description to cover this.

FYI @garymurray - design may already account for tax options, and/or we might be deliberately streamlining how tax is displayed.

**Comment by garymurray** [comment] 2020-02-27 13:53
I feel those settings in core should have the same impact on how we show the taxes in the block based cart and checkout as per the current cart/checkout for now.

**Closed** 2020-03-03 10:12 UTC
Labels: scope: rest-api
