### ISSUE TITLE
The design of the form changed after the upgrade

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#6160] opened 2022-03-29 17:22 UTC
Here's what happened to the checkout form after the last upgrade screenshot - 
<img width="522" alt="Capture4" src="https://user-images.githubusercontent.com/12650820/160669531-fb50ead6-947d-4cc5-816e-50d6afebd53f.PNG">

**Comment by alexflorisca** [comment] 2022-03-30 09:24
Hi @msroky, thanks a lot for reporting this! 

I've just tested on a local version of WP and I can't replicate it. Could you first try disabling all plugins apart from `WooCommerce` and `WooCommerce Blocks` and see if the issue still happens? Could you also try this in an incognito browser as there may be leftover assets from the previous install left in your browser cache that could be conflicting.

If this still doesn't solve it, it would be useful to know a bit more about the problem.
1) Does this only happen at certain screen widths?
2) What settings do you have enabled in the Checkout block and its' sub blocks
3) Could you post your WooCommerce system report here (WooCommerce > Status > Get System Report) and paste it here

Thanks!

**Comment by nielslange** [comment] 2022-04-19 10:21
@msroky I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by nielslange** 2022-04-19 10:21 UTC
Labels: type: bug, block: cart
