### ISSUE TITLE
Automatically remove the `status: ready to merge` label from merged PRs

### ISSUE THREAD

**Issue by tarhi-saad** [woocommerce/woocommerce-gutenberg-products-block#7002] opened 2022-08-29 13:59 UTC
## Describe the bug

In each PR, the label `status: ready to merge` is automatically added when it's approved by a reviewer. But, when it's merged the label in question isn't removed (see `Screenshots` section below)).

## To reproduce

Instead of creating a random PR and merge it, you can check the already merged ones and check if we still have the `status: ready to merge` label attached (see `Screenshots` section below)).

## Expected behavior

We need to set up a GitHub action that removes the `status: ready to merge` label when a PR is merged!

## Screenshots

<img width="700" alt="image" src="https://user-images.githubusercontent.com/14235870/187215259-3689afcf-32ef-4346-ab4a-c14253e7ded4.png">

### WordPress (please complete the following information):

N/A

### Desktop (please complete the following information):

N/A

### Smartphone (please complete the following information):

N/A

## Additional context

N/A

**Comment by nielslange** [comment] 2022-10-20 05:33
Whoever is working on this issue, the [approved-with-labels.yml](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/workflows/approved-with-labels.yml) workflow is currently adding the label `status: ready to merge` in this section:

https://github.com/woocommerce/woocommerce-blocks/blob/b05961310f28830071338728a7957814c0b7790c/.github/workflows/approved-with-labels.yml#L4-L14

We could introduce a new workflow called `merged-with-labels.yml` which removes the `status: ready to merge` label.

**Comment by roykho** [comment] 2023-02-02 15:00
I believe this is already done seen [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/workflows/merged-with-labels.yml). If someone can confirm, we can close this issue. cc @nielslange

**Comment by nielslange** [comment] 2023-02-02 16:08
> I believe this is already done seen [here](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/.github/workflows/merged-with-labels.yml). If someone can confirm, we can close this issue. cc @nielslange

@roykho You're right, this issue had been addressed in #7456. I just noticed that in the other PR I referred to #7022 instead of to #7002. That's why this issue hasn't been closed. Given that the issue is done, I'll close this issue for now.

**Closed as completed by nielslange** 2023-02-02 16:08 UTC
Labels: type: bug, tools, type: cooldown
