### ISSUE TITLE
Checkout: Invalid coupon not returning an error

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce-gutenberg-products-block#2323] opened 2020-04-27 16:20 UTC
**Describe the bug**
When I add an invalid coupon the "apply" button doesn't stop loading and it doesn't display an error message informing that the coupon is invalid.

**To Reproduce**
1. Add the checkout block in a page
2. Got to the checkout page on the frontend and add an invalid coupon
3. See that the coupon button doesn't stop loading
4. See the following error in the console: 
POST https://ecommerce.mystagingwebsite.com/wp-json/wc/store/cart/apply-coupon?_locale=user 403
(index):1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

**Expected behavior**
Displaying an error message saying that the coupon is invalid.

**Screenshots**
https://d.pr/i/BW847P

**Comment by senadir** [comment] 2020-04-27 16:51
Hey Pedro, thank you for filling in this issue, I cannot reproduce this issue on my install.
Usually `Unexpected token < in JSON at position 0` means that the server has returned HTML instead of JSON, which could be an error trace that will help us identify this bug.
In your console, in the network tab, you will see all the request that has been made, search for one that starts with `?apply-coupon` it will be in red if it failed, clicking on it should open a tab, can you tell us what you see in the Preview or Respond tab?
![image](https://user-images.githubusercontent.com/6165348/80398551-b412b280-88af-11ea-8455-3567ed77ece5.png)

**Comment by nerrad** [comment] 2020-04-28 18:16
Looks like this happened for @garymurray as well in #2301 .  I also was unable to reproduce. I think what you are suggesting here is correct @senadir but it also means we might want to see if there's some way we can protect against this happening (i.e. let's catch this unexpected token error and handle it).

**Comment by senadir** [comment] 2020-04-28 18:19
Without fully knowing what the error could be, we can't know for sure, REST API will catch all errors and return them correctly, but sometimes error might happen way before the API runs, meaning an internal error, however it seems this issue exists for more than 1 person so it's probably related to our code somehow.

**Comment by nerrad** [comment] 2020-04-28 18:19
I was able to visit the testing site @pmcpinto was using and it looks like wherever this site is setup, it returns a html 403 page: 

<img width="827" alt="Image 2020-04-28 at 2 18 17 PM" src="https://user-images.githubusercontent.com/1429108/80522868-34422200-895b-11ea-838d-5cba165c570c.png">

@pmcpinto can you give us some more details about the host you have this site on?

**Comment by nerrad** [comment] 2020-04-28 18:21
We _might_ need to use a different error code :\ @mikejolley any ideas here?

**Comment by senadir** [comment] 2020-04-28 18:28
I remember I discussed this before with Mike, I still think all possible UX behaviors should be a `200` response no matter the outcome, 403 could be left for requests without a nonce (which will only happen if someone is using the API directly, in which case they can handle errors by themselves).

**Comment by nerrad** [comment] 2020-04-28 18:37
> but sometimes error might happen way before the API runs, meaning an internal error, however it seems this issue exists for more than 1 person so it's probably related to our code somehow.

ApiFetch is throwing an error because of this logic: 

https://github.com/WordPress/gutenberg/blob/33a821ff00755e7a535e30b69bb0588941c3b908/packages/api-fetch/src/utils/response.js#L26-L39

We're not catching the `invalidJsonError` and we should. It _may_ be a bug in redux-routine not passing the uncaught error up too, but I'm pretty sure [we could handle it](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/869741051e4d52d9f05ff63f5f0b62e6fea09f33/assets/js/base/hooks/cart/use-store-cart-coupons.js#L61-L70)

**Comment by haszari** [comment] 2020-04-29 03:20
Maybe related, I know that with Woo / WP rest api you can sometimes break the json of the response by returning HTML error responses, often by accident/misconfiguration. So that might be relevant here.

Specific example, if [`WP_DEBUG_DISPLAY`](https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug_display) is true, then the JSON API responses can be corrupted when any debug/error messages are rendered for "display" (as html), resulting in `Unexpected token < in JSON at position 0` errors.

**Comment by pmcpinto** [comment] 2020-04-29 09:09
Sorry for the late reply on this

> it will be in red if it failed, clicking on it should open a tab, can you tell us what you see in the Preview or Respond tab?

I'm getting the 403 Forbidden error that Darren mentioned in the previous comment

> can you give us some more details about the host you have this site on? 

I'm using Pressable.
WooCommerce version: 4.0.1
WP version: 5.4
php version: 7.4.5

Let me know if you need more info or an additional test

**Comment by mikejolley** [comment] 2020-04-29 10:57
> I know I've seen this behaviour with some hosts where they customize certain error code responses (most common ones like 500, 403 etc) so I'm thinking we'll have to use an alternative error code for invalid coupons (or anything else we use 403 with)?

> I remember I discussed this before with Mike, I still think all possible UX behaviors should be a 200 response no matter the outcome

I think we should try to avoid using non-standard codes in this API. I'd like to investigate further before making a decision because it may be a notice or error causing the invalid response, rather than the response itself. It may also be solvable by setting certain headers.

**Closed** 2020-04-29 14:47 UTC
Labels: action: needs feedback, type: bug
