### ISSUE TITLE
[GlobalStep] Fix “Product Category List” displaying error on changing alignment setting.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2696] opened 2020-06-11 14:35 UTC
**Environment:**
Windows 10: Chrome(v83.0.4103.61)(64-bit), Firefox(v77.0.1)(64-bit)

**Steps to Reproduce:**
1. Open a test site.
2. Login with valid credentials.
3. From dashboard go to Pages.
4. Add new page.
5. Add Product Category List block.
6. Now in editor change alignment from Wide Width to Full Width and vice versa.
7. Observe that randomly “Error loading block invalid parameter attribute…” is displayed on Editor.

**Actual Result:**
On “Product Category List” block upon changing block alignment error stating “Error loading block invalid parameter attribute…” is displayed on Editor.

**Expected Result:**
Content inside the block should align according to the settings i.e., Wide Width or Full width and no error message should be displayed.

**Refer Artifact:**
[#2696.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4765478/2696.zip)

**Comment by nerrad** [comment] 2020-06-11 19:59
Thanks for the report!

This wasn't happening randomly for me. It happened as soon as I changed the alignment.

<img width="1148" alt="Image 2020-06-11 at 3 58 26 PM" src="https://user-images.githubusercontent.com/1429108/84433575-80d87880-abfc-11ea-8a8c-9c53ab9e475b.png">

@Aljullu would you mind checking to see if this happens in the 2.5 branch. If it doesn't, then this is a regression I think we'll want to fix for a 2.7.1 release (to get landed in wc core).

**Comment by Aljullu** [comment] 2020-06-12 09:43
> @Aljullu would you mind checking to see if this happens in the 2.5 branch. If it doesn't, then this is a regression I think we'll want to fix for a 2.7.1 release (to get landed in wc core).

I tested with WooCommerce Core (without Blocks enabled) and I could reproduce the issue, so it doesn't seem to be a regression. Anyway, it seems to be an easy fix, so I will get a PR ready today. We can decide whether we do a point release or wait for 2.8.0.

**Closed** 2020-06-16 11:18 UTC
Labels: type: bug, ◼️ block: product categories list
