### ISSUE TITLE
Apply filter woocommerce_loop_add_to_cart_link is called with 2 params instead of 3

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/woocommerce-gutenberg-products-block#8020] opened 2022-12-22 14:32 UTC
## Describe the bug

While we were testing Google Listings & Ads and the Products Block (Beta) a fatal error was displayed, the issue is caused because the filter `woocommerce_loop_add_to_cart_link` is applied with two parameters instead of three.

See how WooCommerce applies the filter: https://github.com/woocommerce/woocommerce/blob/7.2.2/plugins/woocommerce/templates/loop/add-to-cart.php#L35

See WooCommerce Blocks: 
https://github.com/woocommerce/woocommerce-blocks/blob/ffe341c2b77b9d55dddc5908a6d8317f0ba03244/src/BlockTypes/ProductButton.php#L111

See how GL&A use the filter: https://github.com/woocommerce/google-listings-and-ads/blob/d4b2dfd8751ebadb096f2a974de0202d08c048d0/src/Google/GlobalSiteTag.php#L153

Fatal error:

`Uncaught ArgumentCountError: Too few arguments to function Automattic\WooCommerce\GoogleListingsAndAds\Google\GlobalSiteTag::Automattic\WooCommerce\GoogleListingsAndAds\Google\{closure}(), 2 passed in /var/www/html/wp-includes/class-wp-hook.php on line 308 and exactly 3 expected`

The filter should be aligned with how WooCommerce applies the filter. 

## To reproduce

1. Install Google Listings & Ads plugin.
2. Create a page with the Products Block (Beta)

![image](https://user-images.githubusercontent.com/2488994/209155950-ee083757-c1ed-4667-8b0d-2344a88aa9e9.png)

5. See error: `Uncaught ArgumentCountError: Too few arguments to function Automattic\WooCommerce\GoogleListingsAndAds\Google\GlobalSiteTag::Automattic\WooCommerce\GoogleListingsAndAds\Google\{closure}(), 2 passed in /var/www/html/wp-includes/class-wp-hook.php on line 308 and exactly 3 expected`

## Expected behavior

Not fatal errors.

**Comment by kmanijak** [comment] 2023-01-09 15:29
Thanks @jorgemd24 for raising this issue.

I followed the steps you provided, but I can't seem to reproduce the issue. On the other hand, from the links you provided, it looks like there is some inconsistency in the number of parameters provided to the filter.

@sunyatasattva, could you take a look at the issue as it's related to Products block, please?

**Comment by sunyatasattva** [comment] 2023-01-09 18:09
Thank you @kmanijak for tagging me. This sounds related to the Products block. If you and @jorgemd24 could provide reliable reproduction steps, then it'd be great if you'd add it to the woocommerce/woocommerce#42616 Epic 🙏

**Comment by kmanijak** [comment] 2023-01-10 11:42
Sounds good @sunyatasattva! 

@jorgemd24, could I ask you for more details around testing steps? I followed those steps:
> 1. Install Google Listings & Ads plugin.
> 2. Create a page with the Products Block (Beta)

but that didn't trigger the error you mentioned:
> 5. See error: Uncaught ArgumentCountError: Too few arguments to function Automattic\WooCommerce\GoogleListingsAndAds\Google\GlobalSiteTag::Automattic\WooCommerce\GoogleListingsAndAds\Google\{closure}(), 2 passed in /var/www/html/wp-includes/class-wp-hook.php on line 308 and exactly 3 expected

This may be just formatting issue, but I spotted the testing steps are missing steps 3. and 4. Maybe they misplaced while raising an issue :)

**Comment by sunyatasattva** [comment] 2023-02-03 23:00
Hello @jorgemd24 , we tried to reproduce this issue but with no luck. Could you guide us further on reproducing it? Otherwise I'm going to need to close the issue.

**Comment by Aljullu** [comment] 2023-02-14 14:28
I wasn't able to reproduce the fatal either, but I think it makes sense to align the number of parameters of the `woocommerce_loop_add_to_cart_link` filter with WC core. Besides that, we could easily add support to the `woocommerce_loop_add_to_cart_args` filter as well. I opened a PR that would fix this: https://github.com/woocommerce/woocommerce-blocks/pull/8422.

> See how GL&A use the filter: https://github.com/woocommerce/google-listings-and-ads/blob/d4b2dfd8751ebadb096f2a974de0202d08c048d0/src/Google/GlobalSiteTag.php#L153

As a sidenote, GL&A is declaring the `$args` param but not using this. I think that could be simplified as well, I opened a PR in GL&A repo too: https://github.com/woocommerce/google-listings-and-ads/pull/1886.

**Comment by jorgemd24** [comment] 2023-02-14 14:58
Sorry, not sure why I missed these comments! Here it is a video reproducing the error:


https://user-images.githubusercontent.com/2488994/218773900-0347ae98-964c-488f-aa8a-e6ed6a8d1871.mp4






And then in the logs, I see:

```
Uncaught ArgumentCountError: Too few arguments to function Automattic\WooCommerce\GoogleListingsAndAds\Google\GlobalSiteTag::Automattic\WooCommerce\GoogleListingsAndAds\Google\{closure}(), 2 passed in /var/www/html/wp-includes/class-wp-hook.php on line 308 and exactly 3 expected

```

Plugins:

WooCommerce 7.3.0
Google Listings and Ads 2.3.8

Thanks for fixing this!

**Closed as completed** 2023-02-15 14:37 UTC
Labels: type: bug, block-type: product-query
