### ISSUE TITLE
Fatal error with Blocks plugin if Core is called before Blocks

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gutenberg-products-block#533] opened 2019-04-18 13:49 UTC
**Describe the bug**
If the [Blocks plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/) is active and for some reason WooCommerce core is called before it, it results in a fatal error:

```
PHP Fatal error:  Cannot declare class WC_Block_Featured_Product, because the name is already in use in .../wp-content/plugins/woo-gutenberg-products-block/includes/blocks/class-wc-block-featured-product.php on line 15
```

**To Reproduce**

1. Rename the plugin folder to `/zwoocommerce-gutenberg-products-block/` (just for testing)
2. Reload any page, and you should get a fatal.

**Comment by mikejolley** [comment] 2019-04-18 13:53
This can be mitigated by moving the check on `WGPB_VERSION` later than the constructor, e.g. to init hook.

For example (confirmed this works in core, I didn't edit this repo because I'm unsure how the constants work and why there are some remove_actions for these in one of the files):

```php
	/**
	 * Constructor.
	 */
	public function __construct() {
		if ( function_exists( 'register_block_type' ) ) {
			add_action( 'init', array( 'WC_Block_Library', 'init' ) );
		}
	}

	/**
	 * Init Block Library during WordPress Init.
	 */
	public static function init() {
		// Shortcut out if we see the feature plugin, v1.4 or below.
		// note: `WGPB_VERSION` is transformed to `WC_VERSION` in the grunt copy task.
		if ( defined( 'WGPB_VERSION' ) && version_compare( WGPB_VERSION, '1.4.0', '<=' ) ) {
			return;
		}
		self::register_blocks();
		self::register_assets();
		add_filter( 'block_categories', array( 'WC_Block_Library', 'add_block_category' ) );
		add_action( 'admin_print_footer_scripts', array( 'WC_Block_Library', 'print_script_settings' ), 1 );
	}
```

Alternatively the ```if ( defined( 'WGPB_VERSION' ) ``` block could be defined in each of the callbacks (register_blocks and register_assets) and this would also prevent the error occuring.

**Comment by ryelle** [comment] 2019-04-18 13:56
@mikejolley This should be fixed in 2.0 regardless since we've changed that class name – can you check if this is still an issue with [this version?](https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v2.0.0)

**Comment by mikejolley** [comment] 2019-04-18 14:12
@ryelle Not quite. There is no fatal, but it seems to have an infinite loop somewhere because I get infinity 'woocommerce' groups in Gutenberg when I rename the directory to `zwoocommerce-gutenberg-products-block`

**Comment by mikejolley** [comment] 2019-04-18 14:15
O maybe I tested that wrong @ryelle... How do I pull that version in as the 'core' version to run alongside 1.4.0?

**Comment by ryelle** [comment] 2019-04-18 14:18
Yeah, I can't replicate that. The easiest way to test would be to download the .tgz from that link, and install it like a normal plugin: https://github.com/woocommerce/woocommerce-gutenberg-products-block/releases/tag/v2.0.0

**Comment by ajgw** [comment] 2019-04-24 11:17
I have updated plugin from 1.4 to 2.0 with wc 3.6.1 and edited few posts with wc-blocks in there saved with 1.4 like products per category. But at opening related post I saw a error on product block which could not be resolved by wp. I had to delete the block and set up new. Is this what you are talking about? Will it be fixed?

**Comment by ryelle** [comment] 2019-04-24 14:45
@ajgw No, that sounds like a different problem– can you open a [new issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/new?template=---bug-report.md) and fill out the information there?

**Comment by ryelle** [comment] 2019-04-24 14:46
This is fixed as of https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/534, and was merged into WooCommerce core here: https://github.com/woocommerce/woocommerce/pull/23399

**Closed by ryelle** 2019-04-24 14:46 UTC
