### ISSUE TITLE
Version 10.5.0 causes all woocommerce blocks to disappear

### ISSUE THREAD

**Issue by winnersmedia** [woocommerce/woocommerce-gutenberg-products-block#9980] opened 2023-06-23 12:55 UTC
## Describe the bug

All the woocommerce blocks disappeared when upgrading to 10.5.0 they were no longer available in the editor. It also caused all the existing blocks to stop working.

I tried uninstalling all related editor plugins and this problem still continued.  Downgrading to 10.4.2 fixed the problem.

## To reproduce

Upgrade to 10.5.0.  

## Expected behavior

The woocommerce blocks to be visible and in the editor after upgrading

## Environment
`
### wp-core ###

version: 6.2.2
site_language: en_GB
user_language: en_GB
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-dropins (1) ###

maintenance.php: true

### wp-active-theme ###

name: GeneratePress (generatepress)
version: 3.3.0
author: Tom Usborne
author_website: https://tomusborne.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, post-formats, woocommerce, title-tag, html5, customize-selective-refresh-widgets, align-wide, responsive-embeds, editor-color-palette, custom-logo, menus, editor-styles, editor-style, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
auto_update: Enabled

### wp-themes-inactive (5) ###

Twenty Nineteen: version: 2.5, author: WordPress Team, Auto-updates enabled
Twenty Twenty: version: 2.2, author: the WordPress team, Auto-updates enabled
Twenty Twenty-One: version: 1.8, author: the WordPress team, Auto-updates enabled
Twenty Twenty-Three: version: 1.1, author: the WordPress team, Auto-updates enabled
Twenty Twenty-Two: version: 1.4, author: the WordPress team, Auto-updates enabled

### wp-plugins-active (17) ###

Code Snippets: version: 3.4.0, author: Code Snippets Pro, Auto-updates enabled
Easy WP SMTP: version: 2.1.0, author: Easy WP SMTP, Auto-updates enabled
FAQ Schema For Pages And Posts: version: 2.3.0, author: Krystian Szastok (SEO Consultant), Auto-updates enabled
Flexible SSL for CloudFlare: version: 1.3.1, author: One Dollar Plugin, Auto-updates enabled
GenerateBlocks: version: 1.7.3, author: Tom Usborne, Auto-updates enabled
GenerateBlocks Pro: version: 1.5.2, author: Tom Usborne, Auto-updates enabled
GP Premium: version: 2.3.1, author: Tom Usborne, Auto-updates enabled
Happyforms (free): version: 1.25.5, author: Happyforms, Auto-updates enabled
Health Check & Troubleshooting: version: 1.6.0, author: The WordPress.org community, Auto-updates disabled
MC4WP: Mailchimp for WordPress: version: 4.9.5, author: ibericode, Auto-updates enabled
Site Kit by Google: version: 1.103.0, author: Google, Auto-updates enabled
Smash Balloon Instagram Feed: version: 6.1.5, author: Smash Balloon, Auto-updates enabled
WooCommerce: version: 7.8.0, author: Automattic, Auto-updates enabled
WooCommerce Blocks: version: 10.4.2, author: Automattic (latest version: 10.5.0), Auto-updates disabled
WooCommerce PayPal Payments: version: 2.1.0, author: WooCommerce, Auto-updates enabled
WooCommerce Stripe Gateway: version: 7.4.1, author: WooCommerce, Auto-updates enabled
Yoast SEO: version: 20.9, author: Team Yoast, Auto-updates enabled

### wp-plugins-inactive (4) ###

Classic Editor: version: 1.6.3, author: WordPress Contributors, Auto-updates enabled
Contact Form 7: version: 5.7.7, author: Takayuki Miyoshi, Auto-updates enabled
Gutenberg: version: 16.0.0, author: Gutenberg Team, Auto-updates disabled
WP Show Posts: version: 1.1.4, author: Tom Usborne, Auto-updates enabled

### code-snippets (1) ###

snippet-5: name: Number Of Products Per Page, scope: front-end, modified: 2023-06-03 11:03:58

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2021-10-14 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 16M
upload_max_filesize: 16M
max_effective_size: 16 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 126 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 126 GB
	imagick::RESOURCETYPE_MEMORY: 63 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 3.10.0-1160.59.1.el7.x86_64 x86_64
httpd_software: nginx/1.24.0
php_version: 8.1.20 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 3600
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 3600
upload_max_filesize: 16M
php_post_max_size: 16M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.5.68-MariaDB
client_version: mysqlnd 8.1.20
max_allowed_packet: 33554432
max_connections: 151

### wp-constants ###

WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### google-site-kit ###

version: 1.103.0
php_version: 8.1.20
wp_version: 6.2.2
amp_mode: no
site_status: connected-site
user_status: authenticated
verification_status: verified-file
connected_user_count: 1
active_modules: site-verification, search-console, analytics, analytics-4, pagespeed-insights
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_update_plugins: ✅
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ✅
	googlesitekit_view_wp_dashboard_widget: ✅
	googlesitekit_view_admin_bar_menu: ✅
	googlesitekit_view_shared_dashboard: ⭕
	googlesitekit_read_shared_module_data::["search-console"]: ⭕
	googlesitekit_read_shared_module_data::["analytics"]: ⭕
	googlesitekit_read_shared_module_data::["analytics-4"]: ⭕
	googlesitekit_read_shared_module_data::["pagespeed-insights"]: ⭕
	googlesitekit_manage_module_sharing_options::["search-console"]: ✅
	googlesitekit_manage_module_sharing_options::["analytics"]: ✅
	googlesitekit_manage_module_sharing_options::["analytics-4"]: ✅
	googlesitekit_manage_module_sharing_options::["pagespeed-insights"]: ✅
	googlesitekit_delegate_module_sharing_management::["search-console"]: ✅
	googlesitekit_delegate_module_sharing_management::["analytics"]: ✅
	googlesitekit_delegate_module_sharing_management::["analytics-4"]: ✅
	googlesitekit_delegate_module_sharing_management::["pagespeed-insights"]: ⭕
enabled_features: 
	adBlockerDetection: ⭕
	adsenseSetupV2: ✅
	dashboardSharing: ✅
	ga4ActivationBanner: ⭕
	ga4Reporting: ✅
	gm3Components: ⭕
	gteSupport: ✅
	userInput: ⭕
search-console_shared_roles: none
search-console_management: owner
analytics_shared_roles: none
analytics_management: owner
analytics-4_shared_roles: none
analytics-4_management: owner
pagespeed-insights_shared_roles: none
pagespeed-insights_management: all_admins
search_console_property: https://www.proteinpopcorn.co.uk/
analytics_account_id: 2495•••••
analytics_property_id: UA-2495•••••••
analytics_profile_id: 2914•••••
analytics_use_snippet: yes
analytics_4_property_id: 3810638••
analytics_4_web_data_stream_id: 5337••••••
analytics_4_measurement_id: G-PP••••••••
analytics_4_use_snippet: yes

### easy_wp_smtp ###

version: 2.1.0
license_key_type: lite
debug: No debug notices found.

### Desktop:

-   OS: [macOS]
-   Browser [chrome]
-   Version 113.0.5672.126

**Comment by nielslange** [comment] 2023-06-23 13:19
Hello @winnersmedia 👋 Thanks for reaching out. 

When you upgraded to WooCommerce Blocks 10.5.0 did you see any error message where the blocks should appear? Apart from that, could you try to deinstall and reinstall WooCommerce Blocks, to see if this brings the blocks back?

**Comment by winnersmedia** [comment] 2023-06-25 13:10
No error apart from the block editor asking if I wanted to convert it into HTML. I tried deleting the plugin and then adding again but it was the same result.

**Comment by tarunvijwani** [comment] 2023-07-07 12:15
Could you please share the list of blocks that are affected? If possible, could you also share link to your site? We'll try to reproduce the behaviour at our end.

**Comment by opr** [comment] 2023-07-21 11:03
Hi @winnersmedia thanks for your patience on this issue, I experienced a similar issue to this one recently and it could also be the cause of your issue.

If you have database access, please delete the `_transient_woocommerce_blocks_asset_api_script_data` from the `wp_options` table. This should refresh the script data cache and the blocks should load correctly again.

I expect it will have started working again anyway given the TTL of the transient being shorter than this ticket has been open, but if not please try the above.

I'll close this ticket because I believe the issue will be solved by my suggestions. Thanks again for your patience!

**Closed as completed by opr** 2023-07-21 11:03 UTC
Labels: type: bug, type: community contribution

**Comment by opr** [comment] 2023-07-26 13:57
Could be fixed by #10278
