### ISSUE TITLE
Woo block 

### ISSUE THREAD

**Issue by 321-Soleil** [woocommerce/woocommerce-gutenberg-products-block#3682] opened 2021-01-13 22:28 UTC
Hello I saw a little problem on woo blocks when i used the other plug in advanced dynamic pricing : 
Wiht the dynamic pricing plug in I made a gratis product for each order. Suppose that a guy buy a 15 dollar t-shirt on my website, he gets a gratis key ring that usually costs 3 dollars. The two plug ins work perfectly with each other BUT the problem is that AFTER proceeding to the checkout, my clients are debited for 18 Dollars !!!! And not 15 as it say because it is a gratis product.
Hope you understood me.
Best Regards
Tim

**Comment by nerrad** [comment] 2021-01-14 12:20
Closing because this is a duplicate of #3681

**Closed as completed by nerrad** 2021-01-14 12:20 UTC
Labels: type: duplicate
