### ISSUE TITLE
Evaluate if we can move away from Notice component

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce-gutenberg-products-block#2280] opened 2020-04-23 10:51 UTC
**Describe the bug**
Investigating the increased bundle size in `All Product` it seems it was caused by us pulling in `Notice` component, that pulled in other dependencies like Dashicon, this could be fixed by https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2140 or by building our custom component.

Notice in itself also pulls dashicons and some other dependencies.

**Comment by senadir** [comment] 2020-05-04 15:51
@nerrad I would love if you can help me evaluate this and reach a decision here, notices is hitting us hard now (the bulk of the weight introduced in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2399 is by notices) all products is the same, we can assume that notices will be added to every interactive block we will develop (all products, Cart and Checkout, single product and any future product).

We should evaluate if we should move it to an independent bundle or build something our own, the notice implementation is simple and straightforward, the snackbar is slightly more complicated but still very doable.

**Comment by nerrad** [comment] 2020-05-04 18:30
With the bulk of the weight coming from Dashicons, I'd prefer to do what's needed to eliminate that instead of building our own replacement for what we're using from GB core.

**Comment by nerrad** [comment] 2020-06-02 15:46
I just realized that I hadn't prioritized this. I think we need to consider this a blocker to releasing 2.7.0 because that's the tag that will be merged to WC Core and thus introduce the significant weight increases in the bundle-sizes for various existing built files (All products, and filter blocks).

I'd like to avoid duplicating work in creating our own notice components in lieue of the WordPress package. @senadir , I think you were working on a way to address this?

**Closed** 2020-06-08 15:27 UTC
Labels: type: blocker, type: performance

**Comment by Aljullu** [comment] 2020-06-09 10:53
Even after the improvements from #2664, the size of `all-products-frontend.js` still increased from 14,85KB (WC Core 5.2) to 38,41KB (WC Blocks 2.7). Should we reopen this issue to investigate if we can improve this further?

**Comment by senadir** [comment] 2020-06-09 11:20
Removing notice will potentially remove other dependencies, but if we ever found ourself doing animations we can reuse some of those things, you can create an issue, but I'm certain the extra weight is from the effect-ful imports in `@wordpress/components` that we can’t get rid of unless we remove `@wordpress/components` (or try something similar to #2664).

**Comment by nerrad** [comment] 2020-06-09 11:50
Keep in mind we use the snackbar notices which in turn uses react-spring. I think at some point we're going to have to look investigate using lazy loading more. That way some of the extra package dependencies could be pulled in only when needed.

So while I'm 💯 on continuing to look at where we can reduce bundlesizes, I'm not convinced removing our usage of WordPress notices is the way to go because it means we just have to reproduce all of that code for what I imagine will likely be marginal gain.
