### ISSUE TITLE
Mini cart does not show on the front on cart and checkout pages

### ISSUE THREAD

**Issue by carolinan** [woocommerce/woocommerce-gutenberg-products-block#6303] opened 2022-04-24 05:18 UTC
## Describe the bug

The Mini Cart does not show on the front on the cart and checkout templates.
It is problematic because if add a mini cart that visually is a part of a menu, then the design will vary from page to page. This leads to an inconsistent user experience.

If I use a block theme and add the mini cart to a site wide header template part, the mini cart shows correctly on the home/index, posts and the shop, but if I go to `example.com/cart/` then the mini cart does not show.

(If the reasoning is that the mini cart does not need to show on these two pages because they already show all the goods in the cart, please see that Storefront shows the mini cart on all pages in the demo, but it doesn't use the block. https://themes.woocommerce.com/storefront/cart/ )

## To reproduce

1. Add a cart.html template to any block theme, for example Twenty Twenty-Two, inside the templates folder, using a file editor.
2. Activate the theme, WooCommerce, and WooCommerce blocks. Optionally activate Gutenberg.
3. In the site editor, add a mini cart block directly to the cart template or for example to a template part that is used in the template.
4. See that the mini cart displays the placeholder correctly in the editor.
5.  Save and view the front. See that the mini cart does not show on the cart page.

- Test with products in the cart and without products.

## Expected behavior
I expect the mini cart to be visible on all pages where it is present in the editor and where I have placed it.

### WordPress (please complete the following information):

-   Core version: 5.9.3
-   Gutenberg version (if installed): 13.0, tried both with and without. 
-   WooCommerce version: 6.4.1
-   WooCommerce Blocks version: Tried from 7.4.0 to 7.4.2.
-   Site language: English
-   Any other plugins installed: -

### Desktop (please complete the following information):

-   OS: Windows 10
-   Browser: Chrome  100.0.4896.127

### Smartphone (please complete the following information):
Untested

**Comment by tjcafferkey** [comment] 2022-04-26 13:29
Thanks for raising this! It looks like this is intentional and expected behaviour. I've linked below the related issue, pull request and internal discussion around this specific change:

**Issue**: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5931
**PR**: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5996
**Internal discussion**: 2c473-pb/

For now, I will close this issue but feel free to reopen this.

**Closed as completed by tjcafferkey** 2022-04-26 13:29 UTC
Labels: type: bug
