### ISSUE TITLE
"Updating failed. The response is not a valid JSON response." message appears with cart and checkout blocks.

### ISSUE THREAD

**Issue by apeksha10** [woocommerce/woocommerce-gutenberg-products-block#2596] opened 2020-06-01 10:10 UTC
**Describe the bug**
"Updating failed. The response is not a valid JSON response." message appears with cart and checkout blocks.

**To Reproduce**

1. Try to create cart block
2. After clicking on Update button "Updating failed. The response is not a valid JSON response" appears with console error.
https://www.screencast.com/t/RYkQiVmd
3. Permalink set up screenshot: https://www.screencast.com/t/gw7rMidltB

Note: If I try to select "Day and name" selector on the permalink tab then it is working fine
https://www.screencast.com/t/W2F9wQA1x

**Expected behavior**
Cart and Checkout blocks should work with all permalink settings.

**WordPress (please complete the following information):**

* Core version: 5.4.1
* WooCommerce version: 4.1.1
* WooCommerce Blocks version: 2.6.0
* Site language: English US
* Any other plugins installed: https://www.screencast.com/t/Lw03TDDMWErK

**Comment by mikejolley** [comment] 2020-06-01 10:47
I wasn't able to replicate this issue. In the console I saw all rest requests going to the correct `index.php?rest_route=%2Fwp%2Fv2%2Fposts%2F170&_locale=user` routes when using plain permalinks. 

Noting the API request in your console error isn't one from blocks either; it's an endpoint the editor itself uses.

Were the permalink settings changes whilst the editor was open? If they were made "plain" while the editor is open without refresh it wouldn't use the correct structure.

**Comment by nerrad** [comment] 2020-06-02 13:01
As Mike noted, the endpoint Mike pointed out is not a blocks REST api route but an editor route. I suspect what he pointed out is the cause here.

@apeksha10 I'm going to close this issue for now, if you are still able to reproduce (even accounting for Mike's suggestions), this is likely an issue with your testing environment. If you encounter any additional information that can help us troubleshoot this (or narrows it down to something specific to Woo blocks) then feel free to add that to this issue and we can reopen if necessary.

**Closed by nerrad** 2020-06-02 13:01 UTC
