### ISSUE TITLE
Checkout block: Wrong payment method used (e.g. BACS) when shopper selects saved payment method (e.g. saved Stripe CC) 

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#3120] opened 2020-09-08 04:46 UTC
## Describe the bug
When submitting an order using a previously-saved payment method, the order is completed using a different payment method. For example, user selects `Visa ending in 4242` (saved Stripe CC), but the order is processed using BACS.

Apologies if this is tricky to reproduce – I've seen it a few times today, on different stores (ephemeral / production build, local dev), so I'm confident there's a real issue. But it may require specific setup of payment methods (or other config).

## To reproduce
1. Set up checkout page using block.
2. Enable BACS and Stripe payment methods (only, though may reproduce with other combinations).
3. Complete a purchase using a new payment method, Stripe CC, check `Save payment information to my account for future purchases`.
4. Add something to cart, proceed to checkout.
5. **Leave the default selected payment method - i.e. the first saved payment method**. Submit checkout.

Expected: Stripe CC used for order.

Actual: BACS used for order.

### Screenshots
Here's a gif of this happening (this was on ephemeral with production versions of everything):

![Screen Capture on 2020-09-08 at 16-34-21](https://user-images.githubusercontent.com/4167300/92433950-99076600-f1f2-11ea-8057-7f1cef7acad8.gif)

Here's a pic of my setup in case something's relevant - the order may be important.

<img width="1096" alt="Screen Shot 2020-09-08 at 4 46 01 PM" src="https://user-images.githubusercontent.com/4167300/92434045-d9ff7a80-f1f2-11ea-9701-75c95569b143.png">

### Environment
WooCommerce Blocks plugin version: 3.2 (release), 3.3.0 (release), 3.4.0-dev

**Comment by Aljullu** [comment] 2020-09-08 09:41
I'm able to reproduce. If Stripe is the first payment method in the list or the only one enabled, I get instead an error message:

![imatge](https://user-images.githubusercontent.com/3616980/92460336-27b2bd80-f1c8-11ea-98c1-8267015457b8.png)

For some reason it looks like the previously saved payment method is not correctly selected and Checkout is trying to do the purchase with new one.

**Comment by nerrad** [comment] 2020-09-08 18:40
When doing a report like this (which _could_ be critical for live stores) could the report please include what version of the plugin this is happening in. If it's only on the main branch (non-deployed) code that has less severity and priority than if it's something in the wild and potentially encountered by stores right now.

For now I'm adding this to the 3.4.0 milestone as a blocker because at a minimum it should be fixed before the next blocks release. However if this is happening in 3.3.0 we may want to consider a 3.3.1 release (unless it was happening in 3.2.0 too).

**Comment by haszari** [comment] 2020-09-08 20:12
> For now I'm adding this to the 3.4.0 milestone as a blocker because at a minimum it should be fixed before the next blocks release. However if this is happening in 3.3.0 we may want to consider a 3.3.1 release (unless it was happening in 3.2.0 too).

Woops sorry I didn't include that info initially. This was first observed in 3.3.0 (released plugin) and then later in current dev build (3.4.0-dev). I've added info to description, and I'll test 3.2.0 to see if it's introduced (which could help narrow down the cause).

@nerrad I'm thinking this might be worth a 3.3.1 patch release even if it's not newly introduced (unless it's rare/hard to reproduce).

**Comment by haszari** [comment] 2020-09-08 21:59
Reproduced this on 3.2 release plugin as well - possibly introduced in 3.2? (3.2 included reordering of payment method tabs.)

**Comment by nerrad** [comment] 2020-09-08 23:04
With this being reproduced in 3.2 I don't think the urgency is increased given we have 3.4.0 coming up on Monday. It effectively means this has been in the wild for 4-5 weeks and we haven't had reports that I'm aware of regarding this.

**Comment by haszari** [comment] 2020-09-09 03:46
Did some black box/binary testing of recent PRs (#2934 and #2975 from 3.2 release) that touch payment methods code, to see if I could narrow this down to a specific PR. 

According to my testing, this issue was introduced in #2975 - I can reproduce in 892bbcf but not in 2c64052ace791ec91d0425e91c8e7f0f243285e2 (last commit before that PR merged). 

So I'm investigating in that area ..

**Comment by haszari** [comment] 2020-09-09 04:31
OK I think I'm getting close to a fix. In PaymentMethodDataContext there's an effect which ensures that there is a payment option selected - i.e. sets a default. This was firing, and selecting `bacs`, even if the user has a saved card. 

The fix is to only set the default if it's really needed - i.e. no saved cards/payment methods. I'm opening a PR with this surgical fix, but will need some good eyes/review/testing to make sure we've covered all the scenarios. cc @Aljullu

**Closed** 2020-09-10 20:48 UTC
Labels: type: bug, ◼️ block: checkout
