### ISSUE TITLE
WooCommerce Shipping and Tax support - automatically update shipping rates/methods

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gutenberg-products-block#5821] opened 2022-02-12 04:38 UTC
## Describe the bug
If you update the items on the cart page, you'll need to reload the page to view the shipping rates (**Legacy USPS live rates**) from [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038).

## To reproduce

1. Add an item to the cart
2. Update the quantity to 2
3. Notice that the shipping method is now gone, and only shows up when you reload the page:

    ![https://d.pr/i/6ujSTv+](https://d.pr/i/6ujSTv+)
4. This cannot be replicated on the regular cart/checkout page with shortcodes
5. This is also the case when you visit the checkout page directly after adding a product to cart
6. You need to reload the checkout page in order to view the shipping methods

## Expected behavior

Automatically display the available shipping methods offered by Shipping and Tax extension without reloading

### WordPress (please complete the following information):
* Core version: 5.9
* Gutenberg version (if installed): N/A
* WooCommerce version: 6.2
* WooCommerce Blocks version: 6.9.0
* Site language: Any
* Any other plugins installed: N/A

### Desktop (please complete the following information):
* OS: Any / N/A
* Browser: Any / N/A
* Version: Latest

### Smartphone (please complete the following information):
* Device: Any / N/A
* OS: Any / N/A
* Browser: Any / N/A
* Version: Latest 

## Additional context

Customer reports: 4716884-zen
Slack discussion: p1644570107233679-slack-C7U3Y3VMY

*Please move this to the WooCommerce Servies repo if this belongs there*

*Edit: I intended to post this as an enhancement request. Can I please request someone to update this as such?*

**Comment by tarunvijwani** [comment] 2022-02-18 16:28
Hi there @AashikP! 👋

We couldn't reproduce this issue. Could you please share the detailed testing steps and information about how to set up the USPS method?

**Comment by AashikP** [comment] 2022-02-21 07:59
Hello @tarunvijwani 👋 

> Could you please share the detailed testing steps and information about how to set up the USPS method?

By default, [this is only enabled on Legacy sites](https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-shipping/#section-10) that had the `Live Rates` enabled for them.

I've added further details in this slack discussion: p1645430308540519-slack-C8X6Q7XQU

**Comment by ralucaStan** [comment] 2022-03-02 15:35
Hi there @AashikP,
thank you for the update.
> By default, [this is only enabled on Legacy sites](https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-shipping/#section-10) that had the Live Rates enabled for them
From what I've read here it means that the feature is discontinued, and that makes it impossible for me to reproduce this bug. Without reproducible steps we aren't able to fix it.

However, integrating with the Cart & Checkout blocks is the responsibility of the extensions. With this in mind, I propose that we transfer this issue to the WooCommerce Services as they might have a better understanding of why this bug is happening.

**Comment by ralucaStan** [comment] 2022-03-02 15:53
@AashikP, unfortunately I am not able to transfer the issue because it is under another organisation. Please reopen the issue on the WooCommerce Services repo, I am going to close this one.

**Closed as completed by ralucaStan** 2022-03-02 15:53 UTC
Labels: type: enhancement

**Comment by AashikP** [comment] 2022-03-03 02:08
Created a new issue on the other repo 👍
