### ISSUE TITLE
Checkout i2: missing spacing in Terms and conditions checkbox

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#4713] opened 2021-09-10 13:38 UTC
## To reproduce

1. Create a post or page and add the Checkout i2 block.
2. Select the Terms and Conditions inner block.
3. In the _Display options_, check _Require checkbox_.
4. Notice that in the editor, there is no spacing between the checkbox and the text.

![imatge](https://user-images.githubusercontent.com/3616980/132861987-a8f6b11c-ec82-4208-8bc5-773ace622dd2.png)

**Comment by senadir** [comment] 2021-09-10 14:00
What theme are you running? I can't reproduce this in Storefront
![image](https://user-images.githubusercontent.com/6165348/132865284-d7ec951e-df98-46c8-9118-38ea156429ab.png)

**Comment by Aljullu** [comment] 2021-09-10 14:25
@senadir I'm running Storefront as well, did you test it in the editor?

**Comment by mikejolley** [comment] 2021-09-10 14:30
Don't worry, I saw this one just before I merged the styling PR. It's fixed :)

**Closed as completed by mikejolley** 2021-09-10 14:30 UTC
Labels: type: bug, block: checkout
