### ISSUE TITLE
MYSQL Syntax error in frontend when using MariaDB

### ISSUE THREAD

**Issue by alexflorisca** [woocommerce/woocommerce-gutenberg-products-block#5303] opened 2021-12-03 16:27 UTC
Kristófer Reykjalín reported a SQL syntax error appearing on the front-end. From Kristófer:

> When I’m using the latest version of the WooCommerce Blocks extension in my local development environment I see this database error on my frontpage (screenshot in thread):
WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND meta_key LIKE 'attribute\\_%'' at line 1]

> The problem goes away when I disable the Blocks extension, or downgrade to version 6.2.0.

I haven't been able to reproduce this yet, and have reached out to Kristófer on [Slack](p1638492039225700-slack-C8X6Q7XQU) for more details. Essentially these are the steps they reported:

1. Install WP with MariaDB as detailed in [this post](pcqRLn-nG-p2)
2. Install WC & WC Blocks plugin
3. Visit any front-end page

## Expected behavior
No SQL Error should appear on front end

## Screenshots
![image (1)](https://user-images.githubusercontent.com/3966773/144636488-76e0d7fc-6530-4209-b39f-d537c7fc0aae.png)

### WordPress (please complete the following information):
* Core version: 5.8.2
* WooCommerce version: 5.9.0
* WooCommerce Blocks version: 6.4.0
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: macOS]

## Additional context

Error from debug.log:

```
[03-Dec-2021 00:42:01 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to us
       │ e near ') AND meta_key LIKE 'attribute\\_%'' at line 1 for query SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value FROM wp_postmeta WHERE post
       │ _id IN () AND meta_key LIKE 'attribute\\_%' made by require('index.php'), require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/storefront
       │ /template-fullwidth.php'), get_template_part, locate_template, load_template, require('/themes/storefront/content-page.php'), do_action('storefront_page'), WP_Hook->do_action, WP_Ho
       │ ok->apply_filters, storefront_page_content, the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_blocks, render_block, WP_Block->render, Automattic\WooCommerce\Bloc
       │ ks\BlockTypes\AbstractBlock->render_callback, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->render, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->get
       │ _products, Automattic\WooCommerce\Blocks\BlockTypes\AbstractProductGrid->prime_product_variations
```

Slack conversation here: p1638492039225700-slack-C8X6Q7XQU

**Comment by reykjalin** [comment] 2021-12-07 01:21
## Some relevant version numbers

Nginx and MariaDB, installed via [`valet install`](https://laravel.com/docs/8.x/valet#installation).

```
$ nginx -version
nginx version: nginx/1.21.3
```

```
$ mariadb --version
mariadb  Ver 15.1 Distrib 10.6.4-MariaDB, for osx10.16 (arm64) using readline 5.1
```

PHP, installed via `brew install php@7.4`.

```
$ php -v
PHP 7.4.26 (cli) (built: Nov 24 2021 11:12:31) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
```

WordPress: 5.8.2
WooCommerce: 5.9.0
WooCommerce Blocks: 6.4.0 (or 6.3.x)

MacOS: Monterey Version 12.0.1 (21A559)
My mac is an M1 MacBook Pro.


## Reproduction steps

> **Note:** Make sure you set `WP_DEBUG`, `WP_SCRIPT_DEBUG`, `WP_DEBUG_LOG`, and `WP_DEBUG_DISPLAY` to `true`.

1. Install WordPress.
2. Install and activate WooCommerce from **Plugins > Add New**.
3. Install Storefront.
4. Go through the automated store creation + example products flow in **Appearance > Storefront**.
5. Install and activate the WooCommerce Blocks plugin from **Plugins > Add New**.
6. Go to the store's front page and notice the error from the screenshot above.

(Alternative)

After step 5:

6. Open **Pages > Cart** or **Page > Checkout**.
7. Remove the shortcode cart/checkout block.
8. Add the WooCommerce Cart/Checkout block.
9. Try to save the page.
10. Notice there's an API error.

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/13835680/144948099-3cfbae2a-4128-4c35-a358-0344630db09f.png">

11. Notice that if you go back to wp-admin and open the Cart/Checkout page again that it was actually updated despite the API error.
    - A message is briefly displayed about a database error, but it's covered by the block editor before I can read it. I think it's the same as the one I initially reported.

<details><summary>WooCommerce System Report</summary>

```
`
### WordPress Environment ###

WordPress address (URL): http://blocks.test
Site address (URL): http://blocks.test
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.4.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.21.3
PHP Version: 7.4.26
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.80.0
(SecureTransport) OpenSSL/1.1.1l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.4-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 4.86MB
Database Data Size: 3.43MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 9
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Blocks: by Automattic – 6.4.0
WooCommerce: by Automattic – 5.9.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 26
Oldest: 2021-12-07 01:09:54 +0000
Newest: 2021-12-07 01:10:20 +0000

Pending: 1
Oldest: 2021-12-08 01:10:20 +0000
Newest: 2021-12-08 01:10:20 +0000


### Status report information ###

Generated at: 2021-12-07 01:14:15 +00:00
`
```

</details>

**Comment by sunyatasattva** [comment] 2021-12-09 23:28
Hey @reykjalin !

Thanks for the further instructions. I was able to reproduce the error, and stripped away a few extra steps of the post you shared that are not strictly required to reproduce, but only if one wants to setup a full dev environment. I'll bring this to the backlog.

Fastest setup I could come up with is the following:

1. `brew install mariadb`
2. `mysql.server start`
3. In the MariaDB shell: `CREATE DATABASE my_db;`
4. `GRANT ALL PRIVILEGES ON my_db.* to my_user@localhost identified by 'my_password';`
5. Install WordPress, follow the on-screen configuration, then you can follow the reproduction steps reported by @reykjalin above.

(For reference, this was the full post: pcqRLn-nG-p2)

**Comment by dinhtungdu** [comment] 2022-05-30 17:05
@reykjalin @sunyatasattva I try to reproduce this issue with `wp-env` which uses MariaDB but I can't reproduce this issue using `trunk`. Can you check on your side if this issue is still reproducible?

**Comment by reykjalin** [comment] 2022-06-04 00:15
I think it's safe to close this issue. I can no longer reproduce the issue using the testing instructions in https://github.com/woocommerce/woocommerce-blocks/issues/5303#issuecomment-987476560.

The versions I used now for the various products:

Nginx and MariaDB, installed via [`valet install`](https://laravel.com/docs/8.x/valet#installation).

```
$ nginx -version
nginx version: nginx/1.21.6
```

```
 $ mariadb --version
mariadb  Ver 15.1 Distrib 10.7.3-MariaDB, for osx10.17 (arm64) using  EditLine wrapper
```

PHP, installed via `brew install php@7.4`.

```
$ php -v
PHP 7.4.28 (cli) (built: Feb 28 2022 07:33:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v7.4.28, Copyright (c), by Zend TechnologiesWordPress: 5.8.2
```

WordPress: 6.0
WooCommerce: 6.5.1
WooCommerce Blocks: 7.7.0

MacOS: Monterey Version 12.4 (21F79)
My mac is an M1 MacBook Pro.

**Comment by sunyatasattva** [comment] 2022-06-04 00:39
Thanks a lot for trying that again @reykjalin, I appreciate! I'm going to go ahead and close the issue, then!

**Closed as completed by sunyatasattva** 2022-06-04 00:39 UTC
Labels: type: bug, priority: critical, type: compatibility
