### ISSUE TITLE
Translation Errors still exist in Version 6.3.1

### ISSUE THREAD

**Issue by DarianDev** [woocommerce/woocommerce-gutenberg-products-block#5181] opened 2021-11-17 20:40 UTC
## Describe the bug
I have reported this bug before, they said it will be fixed in 6.3.0. Unfortunately, the error still exists.

## To reproduce
Use Woocommerce Blocks Checkout

In the wordpress editor is the language right (in this case german) but if you leave the editor and visit the site normally its in english.

## Expected behavior
Display the right language. The Error come with the version 6.2.0 therefore its worked fine.

## Screenshots
In the editor:

![1](https://user-images.githubusercontent.com/17782319/142279083-de8b6075-17ff-4223-80d6-5a40f30771cf.PNG)
View the page normally:
![2](https://user-images.githubusercontent.com/17782319/142278543-33385651-2802-403a-b765-bf622d168fea.PNG)

![22222](https://user-images.githubusercontent.com/17782319/142278575-1de8cbc9-0d54-40e7-92c6-2f010601a475.PNG)

### WordPress (please complete the following information):
* Core version: 5.8.2
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: 5.9
* WooCommerce Blocks version: 6.3.1
* Site language: german

## Additional context
https://wordpress.org/support/topic/translation-errors-10/#post-15078871

**Comment by nielslange** [comment] 2021-11-18 07:43
Hello @DarianDev 👋

I addressed the problem that you mentioned in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5112. Unfortunately, that fix hasn't been tested yet and was therefore not part of the recent release. I can understand that not being able to see the cart and the checkout pages in the desired language is a dealbreaker. 

I'll discuss options internally and hope that we can ship the fix soon. For now, I'll close this issue, to avoid that we're discussing the same topic in multiple places.

---

Duplicate of #5005.

**Closed as completed by nielslange** 2021-11-18 07:43 UTC
Labels: type: bug, focus: i18n
