### ISSUE TITLE
Dark mode or color controls on Price Slider?

### ISSUE THREAD

**Issue by vivialice** [woocommerce/woocommerce-gutenberg-products-block#7202] opened 2022-09-22 11:09 UTC
I was testing out my site with different style presets and noticed the price filter slider is still black. Could we pic up a different color from the theme styles, apply a dark mode, or prioritise setting controls? Ideally, it would swap out on its own when choosing a new theme style. 

<img width="461" alt="Screenshot 2022-09-22 at 12 06 21" src="https://user-images.githubusercontent.com/9888201/191731422-a4a312dc-638d-4eeb-b6ff-b30d2d806a24.png">

For example, the mini cart picked up this accent color to work with the theme's dark backgound: 
<img width="282" alt="Screenshot 2022-09-22 at 12 08 58" src="https://user-images.githubusercontent.com/9888201/191731465-59e7d74f-8e19-444b-b556-8327294f384b.png">

**Comment by senadir** [comment] 2022-09-22 12:33
Cart/Checkout has a dark mode toggle, it would be nice to:
- Continue using that pattern.
- Switch to something that plays well directly with Global Styles.

**Comment by Aljullu** [comment] 2022-10-27 08:57
Closing because it seems to be a duplicate of #7130. Using CSS's `currentColor` seems a simpler approach than adding global styles specific to the range or adding a dark mode toggle IMO.

**Closed as completed by Aljullu** 2022-10-27 08:57 UTC
Labels: type: bug, block: filter by price, focus: global styles
