### ISSUE TITLE
Error on checkout: "Invalid parameter owner[name]. Owner name must be at least 3 character long."

### ISSUE THREAD

**Issue by Moosinams** [woocommerce/woocommerce-gutenberg-products-block#9038] opened 2023-04-14 09:20 UTC
Dear all,

I'm sorry to ask, but I receive this message now and then testing my checkout page [www.moosinams.nl/checkout](http://www.moosinams.nl/checkout) :
![Schermafbeelding 2023-04-11 om 10 58 14](https://user-images.githubusercontent.com/126246807/232003096-b3b58513-9d98-426a-ae24-6087773bd8a0.jpg)

I'm using Astra theme and Astra child theme, WPRocket and Jetpack
I'm not sure if WPRocket has to do with this error, how to use "preload cache" or "never cache this page"?
Or does autofill has to do with this error?

I hope anyone can help me with this nasty problem.

Many thanks in advance!

Warm regards,
Moos
![Schermafbeelding 2023-04-11 om 10 58 14](https://user-images.githubusercontent.com/126246807/232003147-f8adc020-e425-40d6-9fae-4499fe265f3f.jpg)

**Comment by wavvves** [comment] 2023-04-14 13:47
Hi @Moosinams, thank you for reporting this.

Can you please share the technical specifications of your installation?
You can get this information by going to `WooCommerce` > `Status` > `Get System Report`> `Copy for Support`

**Comment by Moosinams** [comment] 2023-04-15 10:18
Thanks for helping me out!!
Moos

Here's is the System report:
`
### WordPress Environment ###

WordPress address (URL): https://moosinams.nl
Site address (URL): https://moosinams.nl
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 10.0.0
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.18
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.74.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.7.40-43-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Totale database grootte: 45.98MB
Database gegevens grootte: 40.79MB
Database index grootte: 5.19MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine
InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index:
0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine
InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB +
Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine
InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine
InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.36MB + Index: 0.47MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.33MB + Index: 0.20MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.28MB + Index: 0.23MB + Engine InnoDB
wp_bwg_album: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwg_album_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwg_file_paths: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_bwg_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwg_image: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_bwg_image_comment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwg_image_rate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwg_image_tag: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwg_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bwg_theme: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_check_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine
InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB +
Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine
InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine
InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB +
Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine
InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine
InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB
+ Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine
InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine
InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine
InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.06MB + Index: 0.03MB + Engine
InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB +
Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.19MB + Index: 0.11MB + Engine
InnoDB
wp_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_pictures: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 12.52MB + Index: 0.19MB + Engine InnoDB
wp_postmeta: Data: 18.52MB + Index: 0.67MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.14MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine
InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine
InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdslayer: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdsslide: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdsslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wpr_rocket_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpsmtp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 97
bwg_gallery: 1
bwg_share: 1
custom_css: 3
customize_changeset: 45
e-landing-page: 1
elementor_library: 3
mailpoet_page: 1
nav_menu_item: 16
ngg_album: 1
ngg_gallery: 1
ngg_pictures: 69
page: 13
post: 1
postman_sent_mail: 2
product: 16
revision: 338
shop_coupon: 2
shop_order: 53
shop_order_refund: 28
sp_wps_shortcodes: 1
wcpcsu-custom-post: 1
wds-slider: 1
wp_global_styles: 3
wp_template: 1
wp_template_part: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Child Theme Configurator: door Lilaea Media – 2.6,1
Code Snippets: door Code Snippets Pro – 3.3.0
Elementor: door Elementor.com – 3.12.1
Jetpack: door Automattic – 12.0
Kadence WooCommerce Email Designer: door Kadence WP – 1.5.10
Mailchimp for WooCommerce: door Mailchimp – 2.8.3
Manage Notification E-mails: door Virgial Berveling – 1.8.4
UpdraftPlus - Backup/Restore: door UpdraftPlus.Com
DavidAnderson – 1.23.3

WooCommerce Blocks: door Automattic – 10.0.0
Product Slider and Carousel with Category for WooCommerce: door WP
OnlineSupport
Essential Plugin – 2.8

WooCommerce Payments: door Automattic – 5.7.0
WooCommerce Product Image Flipper: door jameskoster – 0.4.2
WooCommerce: door Automattic – 7.6.0
WP Rocket: door WP Media – 3.13.0.2
Smush: door WPMU DEV – 3.12.6

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Winkelbasis: #328 - /webshop/
Winkelwagen: #554 - /shoppingbag/
Afrekenen: ❌ Pagina heeft geen [woocommerce_checkout] shortcode of het
woocommerce/checkout blok.
Mijn account: #553 - /my-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Astra Child
Version: 4.1.3.1680978427
Author URL:
https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.1.3
Parent Theme Author URL:
https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: astra-child/woocommerce/checkout/thankyou.php
/data/sites/web/moosinamsnl/www/wp-content/plugins/woo-gutenberg-products-block/templates/notices/error.php
/data/sites/web/moosinamsnl/www/wp-content/plugins/woo-gutenberg-products-block/templates/notices/notice.php
/data/sites/web/moosinamsnl/www/wp-content/plugins/woo-gutenberg-products-block/templates/notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-15 18:29:22 +01:00
Options: ✔
Notes: 105
Onboarding: completed

### WooCommerce Payments ###

Version: 5.7.0
Connected to WPCOM: Ja
Blog ID: 203118369
Account ID: acct_1KlBLF2EnRUnEdtM

### Action Scheduler ###

Canceled: 4
Oldest: 2023-04-13 15:33:22 +0000
Newest: 2023-04-14 09:05:00 +0000

Complete: 1.038
Oldest: 2023-03-15 11:07:08 +0000
Newest: 2023-04-15 10:16:55 +0000

Failed: 79
Oldest: 2022-04-05 12:43:29 +0000
Newest: 2023-04-14 06:50:58 +0000

Pending: 2
Oldest: 2023-04-15 10:17:55 +0000
Newest: 2023-04-15 10:54:14 +0000


### Status report information ###

Generated at: 2023-04-15 11:17:01 +01:00
`


Op vr 14 apr 2023 om 13:47 schreef Paulo Arromba ***@***.***>:

**Comment by Moosinams** [comment] 2023-04-15 10:24
Hi,

After a refresh of the website page, after the error report, the checkout
is working

Moos


Op za 15 apr 2023 om 10:18 schreef Maud van Bavel ***@***.***>:

**Comment by Moosinams** [comment] 2023-04-15 10:30
Hi,

it now also gives an error message: invalid e-mail address.
After refreshing page with same details, checkout working

Moos

Op za 15 apr 2023 om 10:24 schreef Maud van Bavel ***@***.***>:

**Comment by Moosinams** [comment] 2023-04-18 12:00
I switch to a different plugin for checkout, which works for me now

Multi-Step checkout

Best regards
Moos

Op za 15 apr 2023 om 12:30 schreef Maud van Bavel ***@***.***>:

**Comment by tarunvijwani** [comment] 2023-04-20 12:29
@Moosinams This could be caused by either a conflict with another plugin. Maybe Smush or WPRocket. 

The best way to determine this is to:

– Disable all plugins except for WooCommerce and WooCommerce Blocks
– Repeat the action that is causing the problem

If you’re not seeing the same problem after completing the conflict test, then you know the problem was with the plugins. To figure out which plugin is causing the problem, reactivate your other plugins one by one, testing after each, until you find the one causing conflict.

You can read more about this here: https://docs.woocommerce.com/document/how-to-test-for-conflicts

**Comment by wavvves** [comment] 2023-05-17 16:07
> I switch to a different plugin for checkout, which works for me now

Closing this issue.

**Closed as completed by wavvves** 2023-05-17 16:07 UTC
