### ISSUE TITLE
Incompatible Extension Notice

### ISSUE THREAD

**Issue by paymentplugins** [woocommerce/woocommerce-gutenberg-products-block#8185] opened 2023-01-13 22:53 UTC
## Describe the bug
On the block editor page for the cart and checkout blocks, the following notice is shown for all express payment methods: 
```
The following extensions are incompatible with the block-based checkout. [Learn more(opens in a new tab)](https://woocommerce.com/document/cart-checkout-blocks-support-status/)

Stripe Apple Pay
Stripe Google Pay
```

## To reproduce

Install the Payment Plugins for Stripe WooCommerce plugin. Once the plugin is installed, navigate to the Checkout Block editor page. Click on the express payment methods block.

1. Install the Payment Plugins for Stripe WooCommerce plugin
2. Once the plugin is installed, navigate to the Checkout Block editor page
3. Click on the express payment methods block.

## Expected behavior

The express payment methods for GPay and Apple Pay are supported so that notice should not show.

## Screenshots

[Screenshot 1](https://imgur.com/a/uS6RT97#RjjVC6t)

### WordPress (please complete the following information):

-   WordPress version: 6.1
-   WooCommerce version: 7.3
-   WooCommerce Blocks version: 9.3.0
-   Site language: EN

## Additional context

The issue appears to be related to how the `incompatiblePaymentMethods` property located in the redux store `'wc/store/payment'` is being set.

In file `assets/js/data/payment/reducers.ts` and case statement `ACTION_TYPES.SET_AVAILABLE_PAYMENT_METHODS`, the `incompatiblePaymentMethods` is set based on a filter. If the payment method ID isn't in the list of paymentMethods, it's added. The problem with that logic is the `action.paymentMethods` object consists only of the payment methods added via the `registerPaymentMethod` function.

The payment methods added via the `registerExpressPaymentMethod` function are ignored and thus added to the list of incompatible payment methods.

 [Here is the line of code](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/data/payment/reducers.ts#L124)

Kind Regards,
Payment Plugins

**Comment by senadir** [comment] 2023-01-15 15:24
@tarhi-saad would you be kind to assist in resolving this?

A couple of notes:
- I'm not sure why this is being handled on the data store level? it seems editor only and isn't related to the flow of Checkout.
- To my understanding the current flow is: get php payment plugins - get JS payment plugins = incompatibilite payment plugins, maybe such logic should be expanded to account for express payment only plugins.

**Comment by tarhi-saad** [comment] 2023-01-16 19:32
Hello @paymentplugins! 👋 Thank you for reporting this bug! 🙌 We created a PR that fixes and shows the correct incompatible payment gateways. It will be included in this week's release. We want to double-check with you regarding the Credit Card payment method (the default payment gateway). Is this one still incompatible with the Cart & Checkout Blocks?

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/14235870/212752494-3572b27b-9cde-4e2b-a4f6-2d4af3885c3e.png">

**Comment by paymentplugins** [comment] 2023-01-16 19:59
Hi @tarhi-saad,

All of the payment methods provided in our Stripe plugin are compatible with WooCommerce Blocks, whether that be via the Express Checkout section or the payment methods section located toward the bottom of the block checkout.

I would image that if a gateway is registered via the `registerPaymentMethod` or `registerExpressPaymentMethod` they would be considered compatible.

Kind Regards,
Payment Plugins

**Comment by tarhi-saad** [comment] 2023-01-16 21:31
Thank you, @paymentplugins, for the reply! 🙌 You are right! If a gateway is registered using `registerPaymentMethod` or `registerExpressPaymentMethod`, it should be recognized by our plugin.

I was testing the other payment gateways. All of them were recognized by our plugin. Then I simply disabled and re-enabled the Credit Card gateway, and it was fixed! This may be another bug that isn't related to the incompatibility notice. For now, I'm not sure if this is an issue from our end. It looks like the `registerPaymentMethod` of the Credit Card doesn't run the first time the plugin is installed or runs at an early stage, and our plugin doesn't get the necessary information. This happens only when installing the `Payment Plugins for Stripe WooCommerce` plugin for the first time. We can't reproduce this bug by simply removing and re-installing the plugin.

**Comment by paymentplugins** [comment] 2023-01-16 21:37
Hi @tarhi-saad 

Thanks for getting back to us. This may be something specific to the Block Editor because on the frontend checkout block, the credit card gateway always loads if it's enabled. 

We'll take a closer look at the Block Editor and try to replicate the behavior that you have reported.

Kind Regards,
Payment Plugins

**Closed as completed** 2023-01-16 22:06 UTC
Labels: type: bug, status: blocker
