### ISSUE TITLE
Page panier impossible !

### ISSUE THREAD

**Issue by PPB-LesMotsPourLeDire** [woocommerce/woocommerce-gutenberg-products-block#12097] opened 2023-12-08 15:12 UTC
Bonjour, la page panier est impossible à mettre à jour avec ce que je vends. Il est très difficile de trouver les fonctions pour, par exemple vendre mes modules de formation à l'écriture créative. Rien n'est fluide, rien n'est intuitif, une véritable galère !!! 

—

Hello, the cart page is impossible to update with what I am selling. It is very difficult to find functions to, for example, sell my creative writing training modules. Nothing is fluid, nothing is intuitive, a real hassle!!!

**Comment by mikejolley** [comment] 2023-12-11 13:20
Hello,

This is the issue tracker for the cart and checkout blocks feature plugin—it sounds as though you're having issues getting started setting up your store?

I would suggest starting here:

https://woo.com/documentation/woocommerce/getting-started/
https://woo.com/document/build-online-store/#section-8

This runs you through store creation, adding products, and setting up the cart pages etc which is probably what you're after. [The various product types you can create are listed here.](https://woo.com/document/build-online-store/#section-8)

I will mark this issue closed as its not a bug report or something actionable on our side. Thank you.

**Closed as completed by mikejolley** 2023-12-11 13:20 UTC
Labels: type: community contribution
