### ISSUE TITLE
Proceed to checkout

### ISSUE THREAD

**Issue by ihabalfaqeh** [woocommerce/woocommerce-gutenberg-products-block#2621] opened 2020-06-03 16:57 UTC
**Describe the bug**
1 Proceed to checkout doesn't appear on mobile phone
2 YITH PayPal Express Checkout for WooCommerce doesn't appear on **desktop and mobile**

* OS: [android]
* Browser [e.g. chrome, ]
* Version [last]

* Device: [a51

**Comment by nerrad** [comment] 2020-06-04 13:16
Hi there 👋,

Thanks for submitting this issue! 

Regarding item 1:

> Proceed to checkout doesn't appear on mobile phone

Unfortunately, I'm unable to reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. Please provide us with more details about your environment and anything you can remember about when this issue surfaced for you. Screenshots are also helpful. Hopefully, this will help us with reproducing and evaluating it further.

> YITH PayPal Express Checkout for WooCommerce doesn't appear on desktop and mobile

As noted [in the release post for the Cart and Checkout blocks](https://woocommerce.wordpress.com/2020/05/27/woocommerce-blocks-2-6-0-release-notes/), there is a limited set of payment methods available for the initial iteration of the preview. You can read more information about this in the post I linked to.

**Comment by nerrad** [comment] 2020-06-09 14:38
I'm going to close this issue because we don't have enough information to reproduce. If you discover more info feel free to add it to the issue and we can reopen this if needed.

**Closed by nerrad** 2020-06-09 14:38 UTC
Labels: ◼️ block: checkout
