### ISSUE TITLE
Prepaid Method not reflecting on Checkout Page 

### ISSUE THREAD

**Issue by Shoppables** [woocommerce/woocommerce-gutenberg-products-block#4343] opened 2021-06-13 12:07 UTC
## Describe the bug
I made a shopify style checkout page using Woocommerce blocks, everything is fine except one thing that I'm not getting the Prepaid payment options on the checkout page and its by default selecting cash on delivery options. Earlier I was getting the Card and netbanking option but since I have created a shopify style page I'm not getting the prepaid options.

![image](https://user-images.githubusercontent.com/85830171/121806551-efb43b80-cc6d-11eb-9aab-ef0acf5ec8b3.png)

**Comment by Aljullu** [comment] 2021-06-14 07:02
Hi @Shoppables, do you know what payment gateway your store is using? The Cart and Checkout blocks are quite new and some payment gateways hadn't updated yet to support them. You can see a list of supported payment gateways in this page:

https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/#section-4

Hope it helps! I will close this issue for now. We can reopen it if the issue is somewhere else. :slightly_smiling_face:

**Closed as completed by Aljullu** 2021-06-14 07:02 UTC
Labels: type: bug
