### ISSUE TITLE
Update the path of WooCommerce templates to match the new Gutenberg folders

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-gutenberg-products-block#5343] opened 2021-12-09 09:21 UTC
In https://github.com/WordPress/gutenberg/pull/36647, Gutenberg changed the folder names of block themes to use `templates` and `parts` instead of `block-templates` and `block-template-parts`. In WooCommerce, [we are using the old ones](https://github.com/woocommerce/woocommerce-gutenberg-products-block/tree/de2dd8e9b5584ea9e7d79972b9ff3ec13d166556/templates), it's not a big deal because we are not a theme and are loading them via hooks, but still, it would be great to update our directory structure to use the new one.

**Comment by tjcafferkey** [comment] 2021-12-23 15:26
Closing as this is a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/5450 and I believe has now become more important as we are checking theme files for the existence of templates before loading our own.

**Comment by tjcafferkey** [comment] 2021-12-26 18:25
>Closing as this is a duplicate of #5450 and I believe has now become more important as we are checking theme files for the existence of templates before loading our own.

Reopening this issue. It's not quite the same as #5450 where we need to update the paths of the theme file locations we are checking. This PR should just be scoped to renaming the Woo Block directories where we are storing Core block templates

**Closed as completed** 2022-01-05 18:28 UTC
Labels: type: bug, priority: low, focus: FSE
