### ISSUE TITLE
When you try to change the Checkout endpoint to "check" it appends "-2" automatically

### ISSUE THREAD

**Issue by namiokuzono** [woocommerce/woocommerce-gutenberg-products-block#10553] opened 2023-08-11 19:35 UTC
## Describe the bug

When you try to change the Checkout endpoint to "check" it appends "-2" automatically

## To reproduce

1. Newly install WP installation and set up Woo
2. Try changing the endpoint for checkout to "check" (WooCommerce > Settings > Advanced > Page Setup > Checkout > Try changing the endpoint from "checkout" to "check")
3. This would append "-1" automatically, so it looks like "check-2" 

## Screenshots

Screen Recording: https://woonami.xyz/c114RFpz

### WordPress (please complete the following information):

-   WordPress version: 6.3
-   WooCommerce version: 8.0.1
-   WooCommerce Blocks version: 10.8.3
-   Site language: en_US
-   Any other plugins installed:
    - Code Snippets: by Code Snippets Pro – 3.4.2
    - Companion Plugin: by Osk – 1.30
    - Jetpack: by Automattic – 12.4
    - WooCommerce: by Automattic – 8.0.1
    - WordPress Importer: by wordpressdotorg – 0.8.1
    - (Inactive) Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
    - (Inactive) Hello Dolly: by Matt Mullenweg – 1.7.2

### Desktop (please complete the following information):

-   OS: macOS
-   Browser: Chrominium/Vivaldi

**Comment by senadir** [comment] 2023-08-15 13:04
I'm unable to reproduce this locally.

WordPress would append -2 if an existing page with that slug already exists, so check for that?

**Comment by mikejolley** [comment] 2023-09-05 11:11
Thanks for the report @namiokuzono. I've just seen this issue and can confirm it was noticed and fixed in https://github.com/woocommerce/woocommerce-blocks/pull/10640, so the latest release of blocks should have cleared this up. 

Thank you

**Closed as completed by mikejolley** 2023-09-05 11:11 UTC
Labels: type: bug
