### ISSUE TITLE
Specific payments not showing up in checkout

### ISSUE THREAD

**Issue by wieham** [woocommerce/woocommerce-gutenberg-products-block#4481] opened 2021-07-20 13:40 UTC
I have the problem that the checkout does not show payment options like "Paypal" or "Stripe SEPA Direct Debit". 
They are activated and should be supported by Woocommerce Blocks.  

![image](https://user-images.githubusercontent.com/87698608/126333980-a3c2d290-d408-4fa4-b423-19ad7be1f97d.png)
![image](https://user-images.githubusercontent.com/87698608/126334036-6d769e17-2960-458f-bd16-b115849a5f68.png)

**Comment by mikejolley** [comment] 2021-07-20 15:28
Closing as a Duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4480

**Closed as completed by mikejolley** 2021-07-20 15:28 UTC
