### ISSUE TITLE
Failed to load resources - Product review block

### ISSUE THREAD

**Issue by MrGKanev** [woocommerce/woocommerce-gutenberg-products-block#2581] opened 2020-05-28 08:58 UTC
**Describe the bug**
Product review block doesn't load anything and in the console log, we can see a 404 error. Before the last update, everything worked as it should. 

**WordPress (please complete the following information):**

* Core version: 5.4.1
* WooCommerce version: 4.1.1
* WooCommerce Blocks version: 2.6.0 
* Site language: Bulgarian
* Any other plugins installed: https://pastebin.com/Ansa2ac9

**Comment by Aljullu** [comment] 2020-05-28 09:16
Hi @MrGKanev, thanks for filling this issue. We might need some more info in order to investigate what's going on. Any kind of info that you can provide us will be helpful:
* I understand in the frontend of your site the _Product Reviews_ block is not visible, correct? Is that a block you recently added (after updating to 2.6.0) or a block you added previously?
* When you add the block in the editor, is there any error message? Is the block visible in the editor?
* You say you got a 404 error, could you tell us which was the URL of that request?
* Lately, I would suggest trying in a staging site whether deactivating other plugins fixes the issue. Some times, there might be conflicts between plugins and that might be the cause. You can read more about it in the [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4).

**Comment by MrGKanev** [comment] 2020-05-28 09:23
Hi @Aljullu, thanks for the fast reply.

- The block is an old one. More than 2-3 months.
-  Yes, when I open the block editor I can see it working.
- (domain)wp-json/wc/blocks/products/reviews?order=desc&orderby=date_gmt&per_page=10&offset=0&_locale=user 
with code in it 
`{"code":"rest_no_route","message":"\u041d\u044f\u043c\u0430 \u043d\u0430\u043c\u0435\u0440\u0435\u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043e\u0442\u0433\u043e\u0432\u0430\u0440\u044f\u0449\u0430 \u043d\u0430 URL \u0437\u0430\u044f\u0432\u043a\u0430\u0442\u0430 \u0438 \u043c\u0435\u0442\u043e\u0434\u0430.","data":{"status":404}}`
When tested the only plugins which were left were connected with the theme. They have not been updated for more than a year.

**Comment by Aljullu** [comment] 2020-05-29 10:15
Thanks for the details @MrGKanev! I'm unable to figure out what might be going on, I did another round of testing and _Reviews by Product_ is working fine for me.

In your case, if the block is working in the editor but not in the frontend, it might be related to your server blocking some requests.

Some things that might help debug this would be to check if other blocks that interact with the API work: other review blocks and the _All Products_ block, for example. You could also try if setting up your website locally or in another server helps.

**Comment by nerrad** [comment] 2020-06-02 12:52
Hi @MrGKanev, thanks for your report, since we are unable to reproduce given the information you've provided, we're going to close this for now. However, if you come across any additional information please feel free to add it to this issue and we can reopen if necessary!

**Closed by nerrad** 2020-06-02 12:52 UTC
Labels: type: support
