### ISSUE TITLE
Edit Single Product Template > conversion > summary block encountered an error

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#9060] opened 2023-04-14 13:55 UTC
## Describe the bug

Converting Single Product to the new FSE version displayed an error message

## To reproduce

1. Go to Editor, to Edit the single Product template
2. Convert it to FSE with the dedicated blue conversion button
3. Observe the new layout with blocks
4. See error "this block has encountered an error and cannot be previewed"

## Expected behavior

User do not know what to do to fix this, such a message should not be displayed

## Screenshots

![image](https://user-images.githubusercontent.com/919332/232062386-76ab63b0-51f3-4aea-9acc-9ed8158a3223.png)

## Environment

- WP 6.2
- Woo 7.6
- Woo Blocks 10.0
- TT2 theme

### Desktop (please complete the following information):

-   Windows 10
-   Firefox latest (112)

**Comment by Aljullu** [comment] 2023-04-18 13:05
Thanks for filling this issue, @Marc-pi! I can reproduce as well in `trunk`, with this error in the console: `Uncaught TypeError: can't access property "excerpt", t.supports is undefined`.

Environment:

* WP 6.2.0
* WC 7.5.1
* WC Blocks `trunk`
* TT3 theme

@gigitux @thealexandrelara is that something on your radar?

**Comment by gigitux** [comment] 2023-04-18 13:16
@Marc-pi Are you using the new product editor? If yes, it could depend on this issue https://github.com/woocommerce/woocommerce/issues/37619.

The patch will be shipped with WooCommerce 7.7

**Comment by Marc-pi** [comment] 2023-04-18 15:42
@gigitux no, i do use the legacy one, did not test the new product editor yet ;-(

**Comment by gigitux** [comment] 2023-04-19 07:24
Thanks for your answer! The issue is related to a Gutenberg change introduced in the last version. You can find more details in the PR that I created https://github.com/WordPress/gutenberg/issues/49898

**Comment by gigitux** [comment] 2023-06-22 14:02
I will close this issue since that https://github.com/WordPress/gutenberg/issues/49898 has been fixed!

**Closed as completed by gigitux** 2023-06-22 14:02 UTC
Labels: type: bug, block-type: product elements, focus: template
