### ISSUE TITLE
Storefront child theme issue #4: Alignment and space issues.

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-gutenberg-products-block#3833] opened 2021-02-11 17:51 UTC
**I made a comprehensive analysis and tested all the themes listed in the [Storefront Themes ](https://woocommerce.com/product-category/themes/storefront-child-theme-themes/?categories=Themes&collections=theme&page=1&orderby=date) in WooCommerce website.**

You can check the [Issues map I've created in Figma](https://www.figma.com/file/vm7kZzr5uIFwacpKKZzMb5/Storefront-child-themes?node-id=1%3A142), where you will find all the issues divided by theme.

You will find in GitHub different issues where I grouped similar/ same problems and created different issues for each problem group.

__________________________________________________________________________________________________________

# Issue
There are some alignment and space issues.

# Bookshop
(Child theme)
## 1. In the cart page, the dropdown titles and icons have no padding. There is also an issue with the color of the text.
![Frame 215](https://user-images.githubusercontent.com/69914963/107658947-6c55ef80-6c65-11eb-9cdd-2edd69da3111.png)

### Solution
We should add padding to the dropdown and adjust the text and icon colors.
![Frame 216](https://user-images.githubusercontent.com/69914963/107659887-6c0a2400-6c66-11eb-849b-ed3f58a67b14.png)

# Homestore
(Child theme)
## 1. Flat rate number should have more bottom padding. (Also seen on the other themes)

![Frame 216](https://user-images.githubusercontent.com/69914963/107675421-daef7900-6c76-11eb-913e-604dfd15ca85.png)

### Solution
![Frame 217](https://user-images.githubusercontent.com/69914963/107675623-04a8a000-6c77-11eb-881b-f0f24fd22982.png)

# Stationery
(Child theme)
## 1. There is no space between buttons in the cart widget. The PayPal button has no left-right padding.
![Frame 136](https://user-images.githubusercontent.com/69914963/107675942-5c470b80-6c77-11eb-962e-a4fa04035ef3.png)

# Artisan
## 1. Wrong alignment on the "Proceed to checkout" button
![Frame 148](https://user-images.githubusercontent.com/69914963/107676135-91535e00-6c77-11eb-89cf-e46954d7ea19.png)

## 2. Wrong alignment on the "Apply coupon" button
![Frame 152](https://user-images.githubusercontent.com/69914963/107676215-a5975b00-6c77-11eb-93c8-97e89abb248e.png)

## 3. Wrong alignment between the radio buttons and the payment titles.
![Frame 153](https://user-images.githubusercontent.com/69914963/107676254-ad56ff80-6c77-11eb-9a80-94fe40685807.png)

## 4 . Wrong alignment in the checkout form.
![Frame 150](https://user-images.githubusercontent.com/69914963/107676313-c1026600-6c77-11eb-8e9f-fce33cd90488.png)

# Threads
## 1. Wrong alignment on the "Proceed to checkout" button and "Apply coupon" button.
![Frame 157](https://user-images.githubusercontent.com/69914963/107676544-04f56b00-6c78-11eb-9d04-32aff3bb9b71.png)

## 2. Wrong alignment between the radio buttons and the payment titles.
![Frame 162](https://user-images.githubusercontent.com/69914963/107676590-13438700-6c78-11eb-859a-f9d1f40ed640.png)

## 3 . Wrong alignment in the checkout form.
![Frame 163](https://user-images.githubusercontent.com/69914963/107676769-471eac80-6c78-11eb-957b-6ca09b83efca.png)

# Block shop
## 1. Wrong alignment on the  "Apply coupon" button.
![Frame 171](https://user-images.githubusercontent.com/69914963/107676836-5867b900-6c78-11eb-83b6-34bab7b732d1.png)

# Matthew
## 1. Wrong alignment on the  product picture and the price.
![Frame 179](https://user-images.githubusercontent.com/69914963/107676977-7fbe8600-6c78-11eb-9491-2518c7c846e4.png)

### Solution
The product picture and the price should be aligned to the top.
![Frame 218](https://user-images.githubusercontent.com/69914963/107677453-0b381700-6c79-11eb-89db-76c1294eac6c.png)

**Comment by nerrad** [comment] 2021-02-12 19:38
@Aljullu, another question here about where these issues should be fixed. I'm leaning towards them being addressed by the themes themselves? If you agree, I'll take care of creating issues in the individual repositories for addressing.

**Comment by Aljullu** [comment] 2021-02-15 15:26
Agree, everything listed here seems to be something that needs to be fixed individually by each theme.

> 1. Flat rate number should have more bottom padding. (Also seen on the other themes)

That might have been fixed in #3797.

> Matthew

I inspected the source code of Matthew and it looks like aligning elements in the middle is intentional. Those styles were written specially targeting WC Blocks, so that's probably not a bug. :slightly_smiling_face:

**Comment by nerrad** [comment] 2021-02-22 16:02
I moved this report into individual issues (in progress)

### Bookshelf

- Fix issues with collapsible section container toggle in Cart blocks (35-gh-woocommerce/bookshop)

### Homestore

- Improve padding for between rate information and bottom of shipping section. (91-gh-woocommerce/homestore)

### Artisan

This isn't a Storefront Child Theme. @Spacepol can you please file a report with the owner of Artisan?

### Threads

This isn't a Storefront Child Theme. @Spacepol can you please file a report with the owner of Threads?

### Block Shop

This is not a Storefront child theme. @Spacepol can you please file a report with the owner of Block Shop.

**Closed as completed** 2021-02-22 19:17 UTC
Labels: type: bug
