### ISSUE TITLE
Checkout Block is Missing

### ISSUE THREAD

**Issue by jfidelsolutions** [woocommerce/woocommerce-gutenberg-products-block#3786] opened 2021-02-03 23:31 UTC
/Checkout Block is missing. My site was using the checkout block to customize my woocommerce checkout page and now the block is non-existent. 

I don't have Gutenberg installed, but this wasn't an issue before. 

### WordPress (please complete the following information):
* Core version: [e.g. 5.5
* Gutenberg version (if installed): NA
* WooCommerce version: 3.1
* WooCommerce Blocks version: 4.4
* Site language: English
* Any other plugins installed: 
* 
Akismet Anti-Spam
Akismet Anti-Spam
Better Search Replace
Bot Protection
Contact Form 7
Disable Cart Fragments
Duplicate Page
Elementor
Elementor Pro
Essential  Addons for Elementor
Icegram   - Popups, Optins, CTAs & lot more...
Kadence   WooCommerce Email Designer
Smash   Balloon Instagram Feed
Smush
Variation Images Gallery for WooCommerce
WooCommerce
WooCommerce Blocks
WooCommerce Payments
WooCommerce   PayPal Checkout Gateway
WooCommerce   Shipping & Tax
WooCommerce  Stripe Gateway
WP   File Manager
WP   Force SSL
WP   Mail SMTP
WP Rocket (Deactivated)
Yoast SEO

**Comment by mikejolley** [comment] 2021-02-04 14:36
This might be obvious, but can you please double check WooCommerce Blocks plugin is actually activated and that the System Status page lists WooCommerce Blocks 4.4 in the section at the top.

I'm not having any issues running the checkout block using the version from WordPress.org on a clean install.

**Comment by nerrad** [comment] 2021-02-12 19:00
Another thing you may want to do is make sure your version of WooCommerce Core is up to date. I see you are using WooCommerce Core 3.1 - currently WooCommerce Blocks requires at least WooCommerce 4.3.

If you've updated all your plugins and WordPress to the latest version on your site and still are having issues, please do report back with any additional information. However, since we're not able to reproduce I'm going to close this issue.

**Closed as completed by nerrad** 2021-02-12 19:00 UTC
Labels: type: bug
