### ISSUE TITLE
My cart can't jump to the check out interface. How to solve it?

### ISSUE THREAD

**Issue by 3173605074** [woocommerce/woocommerce-gutenberg-products-block#10026] opened 2023-06-28 14:25 UTC
## What do you like about the Cart & Checkout blocks?
My cart can't jump to the check out interface. How to solve it?
## What do you think is missing from the Cart & Checkout blocks?
My cart can't jump to the check out interface. How to solve it?

**Comment by wavvves** [comment] 2023-06-30 14:45
Hello @3173605074, thank you for reporting this. Can you provide us with more details about your setup? eg. the output of WooCommerce > Status and a working dev environment link

**Comment by 3173605074** [comment] 2023-06-30 15:15
I've taken care of it. Thank you for helping me



---Original---
From: "Paulo ***@***.***&gt;
Date: Fri, Jun 30, 2023 22:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [woocommerce/woocommerce-blocks] My cart can't jump to the checkout interface. How to solve it? (Issue #10026)




 
Hello @3173605074, thank you for reporting this. Can you provide us with more details about your setup? eg. the output of WooCommerce &gt; Status and a working dev environment link

**Comment by tarunvijwani** [comment] 2023-07-07 11:09
@3173605074 Great to hear that. I'm closing this because the issue is resolved at your end.

**Closed as completed by tarunvijwani** 2023-07-07 11:09 UTC
Labels: type: community contribution
