### ISSUE TITLE
checkout page submit button callback hooks

### ISSUE THREAD

**Issue by nvgandhi123** [woocommerce/woocommerce-gutenberg-products-block#11018] opened 2023-09-21 03:29 UTC
Hello !!!

Currently, no hook is provided for callback after the checkout button is clicked and validation is fired and complete. 

I am implementing reCaptcha for the checkout block but I am stuck here as I need a callback to check if the form has an error after the submit button is clicked so that I can refresh the captcha.

Thanks

**Comment by senadir** [comment] 2023-09-25 15:19
Here's a list of events that fire and their order, did nothing here was of use?
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-block/how-checkout-processes-an-order.md

**Comment by nvgandhi** [comment] 2023-09-25 15:42
@senadir 

Those events are only available in the Payment Interface.
If you can provide any example will be very helpful.


Thanks

**Comment by nvgandhi123** [comment] 2023-10-01 16:30
@senadir 

Yes, Look like those events are only available in Payment Interface.

Please help me to provide any example If it is available for non payment interface.

Thanks

**Comment by tarunvijwani** [comment] 2023-10-17 08:39
@nvgandhi123 We're exploring the possible solution for this and will get back to you at our earliest. 
Internal discussion: p1697527882608839-slack-C8X6Q7XQU

**Comment by opr** [comment] 2023-10-17 10:30
Hi @nvgandhi123 would it be possible for your component that renders the captcha to add a validation error to the [`wc/store/validation` data store](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/validation.md) using [`setValidationErrors`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/validation.md#setvalidationerrors).

When the captcha is completed successfully the error would be removed using [`clearValidationError`](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/validation.md#clearvalidationerror).

When the place order button is clicked, the checkout process is halted if any errors exist in that store.

You'd need to add a component that outputs the validation error, for example `ValidationInputError` which can be used like so:

`<ValidationInputError propertyName="your-error-id" />` where `your-error-id` is the ID of the error you stored using `setValidationErrors`.

Hope this is helpful but please feel free to reach out again if it's not working right!

**Comment by nvgandhi** [comment] 2023-10-17 10:43
@opr 


Problem is not for captcha validation, the Problem is when the checkout form (whole form) contains an error after submission, I need to reset reCaptcha, So I must need some hook for this.

So valid callbacks are needed. The same is available in old WooCommerce Jquery based then if possible in React please consider adding it, Not only me other developers also may in need in the future.

Thanks

**Comment by opr** [comment] 2023-10-17 11:00
Ok sorry I understand a little better now.

Using `wc/store/checkout` you can use the `getStatus` or `hasError` selectors to check the status of checkout.

Your component could have a useEffect that resets the captcha if the value of `hasError` becomes `true`?

```tsx
import { useSelect } from '@wordpress/data';

const reCaptchaComponent = () => {

    const hasError = useSelect( ( select ) => {
        return select( 'wc/store/checkout' ).hasError();
    } );
    
    useEffect( () => {
        if ( hasError ) {
            resetCaptcha();
        }
    }, [ hasError ] );
    
    return <ReCaptcha />
}
```

I'll actually reopen this issue until we figure out something that works!

**Comment by nvgandhi** [comment] 2023-10-17 11:14
@opr Thanks, I will check above if that work

**Comment by nvgandhi** [comment] 2023-10-20 05:09
@opr 

Thanks for the example you have given, It seems working and that has solved my problem.

Also any help for publishing block? My plugin is 128mb in size which I don't think is suitable 

Thanks

**Comment by opr** [comment] 2023-10-20 10:32
Hi @nvgandhi 128mb is quite large, are you also including assets like images/videos in your plugin or is this purely code? 🤔 

Do you know which files are the biggest and why? Does your plugin also bundle the `node_modules` folder too? I'd recommend excluding that from your archive.

Some other common ones I see included in archives are the `.idea` folder from JetBrains products, and the `.vscode` folder from VS Code.

Also feel free to use https://www.npmjs.com/package/webpack-bundle-analyzer to check for places you might be able to make improvements on bundle size.

Given the original issue is solved, I'll close this issue but feel free to reply if you need further help.

**Closed as completed by opr** 2023-10-20 10:32 UTC
Labels: type: enhancement, category: extensibility, type: community contribution

**Comment by nvgandhi** [comment] 2023-10-20 10:36
@opr,

Yes, It is due to node_modules folder. But as soon as I remove it, It starts showing the block has error. So how could I remove it? Sorry for these silly questions as I am a PHP developer not much known this.

Thanks

**Comment by opr** [comment] 2023-10-20 10:41
> Yes, It is due to node_modules folder. But as soon as I remove it, It starts showing the block has error.

This seems like you're using the development files in production. You should be building your files and compiling them into a "bundle" where everything needed is stored in a smaller set of files.

Are you using `@wordpress/scripts` to build/run your project? If so, have you extended the webpack config and are you using the `@woocommerce/webpack-dependency-extraction-plugin` for webpack?

Is your plugin open source? I'll take a look if so and see if I can spot anything.

**Comment by nvgandhi** [comment] 2023-10-20 10:51
Hello @opr 

This is my plugin [https://woocommerce.com/products/recaptcha-for-woocommerce/](https://woocommerce.com/products/recaptcha-for-woocommerce/)

I am adding reCaptcha support to block-based WooCommerce's Checkout block. I have added reCaptcha by learning the newsletter example block.

I am adding the webpack config below and package JSON file as attachment from that if anything you can suggest ?

`const path = require('path');
const defaultConfig = require('@wordpress/scripts/config/webpack.config');
const WooCommerceDependencyExtractionWebpackPlugin = require('@woocommerce/dependency-extraction-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

// Remove SASS rule from the default config so we can define our own.
const defaultRules = defaultConfig.module.rules.filter((rule) => {
	return String(rule.test) !== String(/\.(sc|sa)ss$/);
});

module.exports = {
	...defaultConfig,
	entry: {
		index: path.resolve(process.cwd(), 'src', 'index.js'),
		'i13checkoutcaptchablock-checkout-recaptcha-front-block-frontend': path.resolve(
			process.cwd(),
			'src',
			'js',
			'checkout-recaptcha-front-block',
			'frontend.js'
		),
	},
	module: {
		...defaultConfig.module

	},
	plugins: [
		...defaultConfig.plugins.filter(
			(plugin) =>
				plugin.constructor.name !== 'DependencyExtractionWebpackPlugin'
		),
		new WooCommerceDependencyExtractionWebpackPlugin(),
		new MiniCssExtractPlugin({
			filename: `[name].css`,
		}),
	],
};
`

[package.json](https://github.com/woocommerce/woocommerce-blocks/files/13053361/package.json)

Thanks

**Comment by opr** [comment] 2023-10-20 10:56
Thanks, what happens if you run `npm run build`? You _should_ get some files in the `build` directory. If you enqueue those files on the site it shouldn't error if `node_modules` isn't also there (because the deps are built into the bundle). Please also see the example of how to enqueue those in the `IntegrationInterface` in this plugin: https://github.com/woocommerce/wceu23-shipping-workshop-final/blob/main/shipping-workshop-blocks-integration.php

**Comment by nvgandhi** [comment] 2023-10-20 11:08
@opr 

Thank you sir for your help. Running npm run build is the solution, Now not getting an error when I remove node_modules thanks.

Last question so when I submit a zip plugin to WooCommerce, Should I keep the **src** folder or should I remove it too ?
Thanks

**Comment by senadir** [comment] 2023-10-20 11:26
The WordPress plugin directory might require the src files, generally speaking, the src files should be small, only the `node_modules` is what causes the problem here.

**Comment by nvgandhi** [comment] 2023-10-20 11:30
@senadir Thanks
