### ISSUE TITLE
Already have an account? Log in button not redirecting to My Account page.

### ISSUE THREAD

**Issue by furnitureking** [woocommerce/woocommerce-gutenberg-products-block#3137] opened 2020-09-10 07:21 UTC
The "Already have an account" Log in button goes to wordpress login page... Not the "My account" page like it should.

Click Log in on checkout page.

1. Go to 'checkout'
2. Click on 'log in'
3. See error

Expected it to go to "My Account" page. NOT WORDPRESS LOGIN.

### WordPress (please complete the following information):
* Core version: [e.g. 5.0.3]
* Gutenberg version (if installed): [e.g. 4.8.0]
* WooCommerce version: [e.g. 3.5.3]
* WooCommerce Blocks version: [e.g. 1.3.1]
* Site language:
* Any other plugins installed:

### Desktop (please complete the following information):
* OS: [e.g. macOS, Windows]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by senadir** [comment] 2020-09-14 10:44
my-account has no `redirect to` functionality that I'm aware of, so a user will have to manually go back to checkout after he finishes.

**Comment by nerrad** [comment] 2020-09-17 15:32
There is this code which seems to suggest that `my-account` _could_ have redirects:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L937-L948

In principle, I agree with the feature request here - we defaulted to the `wp_login_url` as a quick implementation but I think there are plans in future iterations to either:

- point to the my-account login form OR
- have in context login (preferable).

**Comment by senadir** [comment] 2020-09-17 15:40
I can't seem to get it to work by testing
```
https://woo.local/my-account/?redirect=https%3A%2F%2Fwoo.local%2Fcheckout%2F
```
I suspect we will need to activate it somehow, will need a bit of digging to discover this, this filter `woocommerce_login_redirect` might play into this.

I will leave this issue for someone to pick it up

**Comment by senadir** [comment] 2020-09-25 09:59
this is a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2918, closing in favor of that one.

**Closed by senadir** 2020-09-25 09:59 UTC
Labels: type: enhancement, ◼️ block: checkout
