### ISSUE TITLE
npm run package-plugin error

### ISSUE THREAD

**Issue by method7** [woocommerce/woocommerce-gutenberg-products-block#3789] opened 2021-02-04 14:05 UTC
## issue

trying to package my build and after running: $ npm run package-plugin I am getting the below error. i am alos getting errors for the alternate packaging commands:
$ npm run package-plugin:dev
$ npm run package-plugin:zip_only

I wonder if someone can point me in the right direction - i cant seem to find any related issues in the archive - which concerns me a little and partly encouraged me to raise this as a bug - i can fully understand it this is closed immediately but would appreciate some pointers - any help would be much appreciated 

## terminal output
`===========================

Generating production build... 👷‍♀️

===========================

@woocommerce/block-library@4.4.0 /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block
├─┬ @storybook/addon-docs@6.0.28
│ └─┬ @storybook/core@6.0.28
│   └── webpack@4.44.2  deduped
├─┬ @storybook/react@6.0.28
│ └── webpack@4.44.2  deduped
├─┬ @wordpress/dependency-extraction-webpack-plugin@2.8.0
│ └── webpack@4.44.2  deduped
├─┬ @wordpress/scripts@13.0.1
│ └── webpack@4.44.2  deduped
└── webpack@4.44.2 

> @woocommerce/block-library@4.4.0 build /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block
> rimraf build/* && cross-env BABEL_ENV=default NODE_ENV=production webpack

/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/rimraf/bin.js:46
      throw er
      ^

[Error: EACCES: permission denied, rmdir 'build/atomic-block-components/add-to-cart--atomic-block-components'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'rmdir',
  path: 'build/atomic-block-components/add-to-cart--atomic-block-components'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @woocommerce/block-library@4.4.0 build: `rimraf build/* && cross-env BABEL_ENV=default NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @woocommerce/block-library@4.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/method7/.npm/_logs/2021-02-04T13_46_25_529Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @woocommerce/block-library@4.4.0 package-plugin: `rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @woocommerce/block-library@4.4.0 package-plugin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

## logs
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/method7/.nvm/versions/node/v12.20.1/bin/node',
1 verbose cli   '/home/method7/.nvm/versions/node/v12.20.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package-plugin'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose run-script [ 'prepackage-plugin', 'package-plugin', 'postpackage-plugin' ]
5 info lifecycle @woocommerce/block-library@4.4.0~prepackage-plugin: @woocommerce/block-library@4.4.0
6 info lifecycle @woocommerce/block-library@4.4.0~package-plugin: @woocommerce/block-library@4.4.0
7 verbose lifecycle @woocommerce/block-library@4.4.0~package-plugin: unsafe-perm in lifecycle true
8 verbose lifecycle @woocommerce/block-library@4.4.0~package-plugin: PATH: /home/method7/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/.bin:/home/method7/.nvm/versions/node/v12.20.1/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/method7/.avn/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/method7/Android/Sdk/emulator:/home/method7/Android/Sdk/tools:/home/method7/Android/Sdk/tools/bin:/home/method7/Android/Sdk/platform-tools
9 verbose lifecycle @woocommerce/block-library@4.4.0~package-plugin: CWD: /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block
10 silly lifecycle @woocommerce/block-library@4.4.0~package-plugin: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh'
10 silly lifecycle ]
11 silly lifecycle @woocommerce/block-library@4.4.0~package-plugin: Returned: code: 1  signal: null
12 info lifecycle @woocommerce/block-library@4.4.0~package-plugin: Failed to exec package-plugin script
13 verbose stack Error: @woocommerce/block-library@4.4.0 package-plugin: `rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/method7/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/method7/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid @woocommerce/block-library@4.4.0
15 verbose cwd /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block
16 verbose Linux 5.4.0-64-generic
17 verbose argv "/home/method7/.nvm/versions/node/v12.20.1/bin/node" "/home/method7/.nvm/versions/node/v12.20.1/bin/npm" "run" "package-plugin"
18 verbose node v12.20.1
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error @woocommerce/block-library@4.4.0 package-plugin: `rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh`
22 error Exit status 1
23 error Failed at the @woocommerce/block-library@4.4.0 package-plugin script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by method7** [comment] 2021-02-04 16:20
I got a little deeper into this, it looks like my file path has a space in one of the directory names `/home/method7/Local Sites` I am using [local](https://localwp.com/) as my wp dev environment and this is the default file path.

error that shows noe is:
`===========================


Creating archive... 🎁

sh: 0: Can't open /home/method7/Local
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @woocommerce/block-library@4.4.0 package-plugin: `rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @woocommerce/block-library@4.4.0 package-plugin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

and the log: 
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/method7/.nvm/versions/node/v12.20.1/bin/node',
1 verbose cli   '/home/method7/.nvm/versions/node/v12.20.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package-plugin'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose run-script [ 'prepackage-plugin', 'package-plugin', 'postpackage-plugin' ]
5 info lifecycle @woocommerce/block-library@4.4.0~prepackage-plugin: @woocommerce/block-library@4.4.0
6 info lifecycle @woocommerce/block-library@4.4.0~package-plugin: @woocommerce/block-library@4.4.0
7 verbose lifecycle @woocommerce/block-library@4.4.0~package-plugin: unsafe-perm in lifecycle true
8 verbose lifecycle @woocommerce/block-library@4.4.0~package-plugin: PATH: /home/method7/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block/node_modules/.bin:/home/method7/.nvm/versions/node/v12.20.1/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/method7/.avn/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/method7/Android/Sdk/emulator:/home/method7/Android/Sdk/tools:/home/method7/Android/Sdk/tools/bin:/home/method7/Android/Sdk/platform-tools
9 verbose lifecycle @woocommerce/block-library@4.4.0~package-plugin: CWD: /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block
10 silly lifecycle @woocommerce/block-library@4.4.0~package-plugin: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh'
10 silly lifecycle ]
11 info lifecycle @woocommerce/block-library@4.4.0~package-plugin: Failed to exec package-plugin script
12 verbose stack Error: @woocommerce/block-library@4.4.0 package-plugin: `rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/method7/.nvm/versions/node/v12.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:314:20)
12 verbose stack     at maybeClose (internal/child_process.js:1022:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
13 verbose pkgid @woocommerce/block-library@4.4.0
14 verbose cwd /home/method7/Local Sites/pure-naturals-dev/app/public/wp-content/plugins/woocommerce-gutenberg-products-block
15 verbose Linux 5.4.0-64-generic
16 verbose argv "/home/method7/.nvm/versions/node/v12.20.1/bin/node" "/home/method7/.nvm/versions/node/v12.20.1/bin/npm" "run" "package-plugin"
17 verbose node v12.20.1
18 verbose npm  v6.14.10
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error @woocommerce/block-library@4.4.0 package-plugin: `rimraf woocommerce-gutenberg-products-block.zip && ./bin/build-plugin-zip.sh`
23 error spawn ENOENT
24 error Failed at the @woocommerce/block-library@4.4.0 package-plugin script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]`

**Comment by opr** [comment] 2021-02-05 11:21
Hi, thanks for your work to narrow down the cause for this! I can see that the script is failing because of spaces in the working directory path.

I could get the `npm run package-plugin:zip-only` command working by changing these lines in `/bin/build-plugin-zip.sh`:

https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/bin/build-plugin-zip.sh#L130-L131

to

```bash
sh "$SOURCE_PATH/bin/copy-plugin-files.sh" "$SOURCE_PATH" "$SOURCE_PATH/zip-file"
cd "$(pwd)/zip-file"
```

Bear in mind that the zip file won't build if you have a dirty working directory after changing this file, so you'll need to commit your changes if you want to build.

I recommend changing your working directory to one that doesn't contain spaces as a much simpler workaround for this for the time being.

I'll open another issue for this because the problem may exist in several files that reference the current working directory.

Please subscribe to #3799 for further updates regarding a fix for this.

**Closed as completed** 2021-02-05 11:21 UTC
Labels: type: bug

**Comment by method7** [comment] 2021-02-09 11:11
Hi @opr many thanks for looking at this and providing the solution so quickly, the fix does indeed work and the plugin.zip now  builds.
