### ISSUE TITLE
block spacing account fields

### ISSUE THREAD

**Issue by flaureli** [woocommerce/woocommerce-gutenberg-products-block#7615] opened 2022-11-08 16:54 UTC
The margins between the different fields are too large.  I would like to be able to edit this.  Otherwise this is ABSOLUTELY AWESOME.  Thank you so much.

**Comment by wavvves** [comment] 2022-11-08 17:22
Hi @flaureli, thank you for the feedback. Currently, there is no configuration control to change those margins, but it is possible to do it via CSS code. Feel free to tag me if you need further assistance with that.

On a curious note, can you share a print screen of the problem? Spacing by default is actually pretty standard, I wonder if there might be some plugin, theme, or custom CSS on your WordPress installation affecting these margins.

**Comment by tarunvijwani** [comment] 2022-11-25 08:24
@flaureli I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by tarunvijwani** 2022-11-25 08:24 UTC
