### ISSUE TITLE
Products by Category block: no pagination

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce-gutenberg-products-block#2656] opened 2020-06-05 21:02 UTC
**Describe the bug**

There currently seems to be no pagination in the `Products by Category` block. 

**To Reproduce**

1. Create a product category and assign perhaps 10 products to it or so (I have 22). 
2. Create a post or a page and add `Products by Category` block on it - select the products of the category you created in step 1 to display. 
3. I have set for the layout to be 3 columns + 2 rows:

![layout](https://user-images.githubusercontent.com/19143190/83921553-95c09200-a74c-11ea-93a2-5962c7b4dced.jpg)

4. Publish the post/page.
5. Navigate to that post/page at the front-end and note that there is no pagination on that page so there is no way to actually get to other products that are not being displayed (only 6 out of 22 in my case is displayed):

![Screen Shot 2020-06-05 at 4 52 30 PM](https://user-images.githubusercontent.com/19143190/83921753-1089ad00-a74d-11ea-89ae-e973cffca803.png)

**Expected behavior**

I expected the pagination to automatically work at the front-end when visiting the page I created with the `Product by Category` block so that I could navigate through all the products of the category. 

**Screenshots**

See above. 

**WordPress (please complete the following information):**

* Core version: 5.4.1
* Gutenberg version (if installed): not installed
* WooCommerce version: 4.2
* WooCommerce Blocks version: not installed (WC 4.2 includes Blocks version 2.5.16)
* Site language: English
* Any other plugins installed: Akismet Anti-Spam, Jetpack by WordPress.com, Query Monitor, WooCommerce Beta Tester

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.4
* Browser: Chrome
* Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by nerrad** [comment] 2020-06-07 10:31
Hi @juliaamosova , thanks for the really well written enhancement request 😃!

This is definitely something on our radar and there are a number of other similar issues:

- #854
- #2373 (which would potentially allow the same logic powering All Products to power all the individual product grid blocks - adding pagination etc).
- #1705 (similar to above).

**Comment by juliaamosova** [comment] 2020-06-08 13:18
Thanks @nerrad! Noted other similar issues.

**Comment by persone21** [comment] 2020-07-18 06:52
Hi @juliaamosova, you have found a solution to the pagination problem?

**Comment by jagomezgil** [comment] 2020-11-07 10:15
I've the same problem, Its necessary the pagination as option on all products list, the same functionallity like shortcodes.
Thanks for your job.

**Comment by nerrad** [comment] 2020-12-08 16:42
The current blocks are intentionally designed to _not_ be replacements for archive pages which have pagination. So pagination is not something we will add to the current product grid blocks. In our roadmap, as a part of building for the future of WordPress themes (block based themes) there will likely be a base product grid type block that will have various options for setting default query parameters and filtering values that would be used in the context of Store archive pages and it would include pagination (much like how the current "All Products" block functions). It would also incorporate elements of #2373.

With this in mind, I'm going to close this issue because for now we have no plans to add pagination to the existing product grid type blocks.

**Closed by nerrad** 2020-12-08 16:42 UTC
Labels: type: enhancement, ◼️ block: products by category

**Comment by kentsor** [comment] 2020-12-20 20:42
I'm not understanding the logic here. The block is _useless_ as it is without pagination.

**Comment by djekanovic** [comment] 2021-03-18 02:16
Hey @nerrad, did you know that your name in our language actually means "not working". I guess that is what is happening here 👎

**Comment by nerrad** [comment] 2021-03-18 10:57
Hi there @djekanovic,

I see you feel very strongly about this, however personal slurs really won't get you very far and I'm not really sure what your goal is with your comment. 

I'm writing this for others that might stumble on this thread. Every maintainer of open source projects have to make decisions around what to focus their effort and time on given the resources available and it's worth noting that sometimes a course of action we take is one we ourselves wish we didn't have to.  Closing the issue is not necessarily saying that the requests are a bad idea or don't make sense but just an acknowledgement that it's not a direction we plan on taking. As I noted, there will be things we'll do in future work that will address the need.

In the meantime, the beauty of open source is that if folks feel strongly enough about a feature and disagree with the choices maintainers have made - you **do have the option** to either build that thing yourself (if you have the skills or desire to learn) or hire someone to build it for you.

**Comment by djekanovic** [comment] 2021-03-19 03:06
Then you guys are spending time on useless blocks. 

Products by attribute issues:

* It shows only 9 of them
* No pagination also

I don't see the goal of the blocks, when you can use Elementor and build it the same way, but with much more options.

Overall WordPress and Blocks path without many options is a wrong path, i guess few years from now, blocks will have lot of options, including pagination. But for now, that is "a bad idea".

**Comment by senad-redzic** [comment] 2021-08-19 10:35
@nerrad , is there any estimation when this could be done? 
We really need pagination. I totally understand your point, but 20 products is not enough even for marketing purposes. Sometimes we have 26 or 30 products, which makes the block not usable.

**Comment by nerrad** [comment] 2021-08-19 11:31
Sorry I can't give you an ETA. I can tell you this isn't on our immediate roadmap for now. However, it is likely something that will be addressed in some way as a part of the work on readying WooCommerce for full site editing in WordPress.

**Comment by nunavailabul** [comment] 2022-03-31 00:08
Agree with many above.  A lot of these blocks are effectively pointless without pagination. *left scratching my head*

**Comment by mimiseku93002** [comment] 2022-11-09 13:47
Hey @nerrad , can we expect an update about that?

**Comment by nerrad** [comment] 2022-11-09 14:44
We're working on a Product Query block which will include pagination, and more controls. You can read more about it in the latest [Roadmap Update](https://developer.woocommerce.com/2022/11/04/store-editing-roadmap-update-q4-2022/).

**Comment by mimiseku93002** [comment] 2022-11-09 20:50
Okok that's good news, just need more patience then ;)

**Comment by kieran408** [comment] 2023-01-17 04:29
The query block works but it is not intuitive and requires a lot of styling. At least it works though. Thanks.

**Comment by kevinmf94** [comment] 2024-01-21 18:54
I have the same problem, any alternative to that?
