### ISSUE TITLE
Champs Adresse

### ISSUE THREAD

**Issue by 321-Soleil** [woocommerce/woocommerce-gutenberg-products-block#3639] opened 2021-01-05 10:41 UTC
Bonjour, j'ai installer woo block, excellent, seul soucis, sur mon champs d adresse il y a écrit "Adresse& nbsp;
" j'aimerais le changer en "Adresse" comment est ce possible?
Merci d avance.
Cordialement

**Comment by Aljullu** [comment] 2021-01-06 11:23
Closing as duplicate of #3649. I suggested the translation update but it's up to the localization community to accept it or not.

**Closed as completed by Aljullu** 2021-01-06 11:23 UTC
