### ISSUE TITLE
[GlobalStep - WooCommerce 4.9 RC1] "Oops!" error message is displayed at frontend even after refresh, when a page is viewed after switching WooCommerce version from backend.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#3657] opened 2021-01-06 15:57 UTC
## Bug Description:
"Oops!" error message is displayed at frontend even after refresh when a page is viewed after switching WooCommerce version from backend.

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)
                
 
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins.
1. Complete the Onboarding setup wizard 
1. Add products, set up taxes and Shipping.
1. Create a Page say "Products" by clicking on the "Add New" option under the Page tab
1. Add the "All Products" block to the page just created and Save the Draft then Preview it.
1. Go to the backend, Switch WooCommerce version from 4.9 RC 1 to 4.8, or any other version.
1. Go back to the frontend and refresh the Product page.
1. Observe that "Oops! There was an error loading the content, Error: unidentified is not an object" error message is displayed. 

**Note**:
Once switched back to 4.9 RC 1, The error message disappears upon refreshing the page.
It occurs only once per website, if tried to switch again for the same website to any other version say 4.9 RC 1 to 4.7 after switching to 4.8, It displays no error message.

## Actual Result:
"Oops!" error message is displayed at frontend even after refresh when a page is viewed after switching WooCommerce version from backend.

 
## Expected Result:
No error message should be displayed at frontend when a page is viewed after switching the WooCommerce version from 
backend

## Video:

https://user-images.githubusercontent.com/41110392/103795721-55235100-506c-11eb-951e-9343a28463d9.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
### WordPress Environment ###

WordPress address (URL): https://outstanding-marmoset.jurassic.ninja
Site address (URL): https://outstanding-marmoset.jurassic.ninja
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.2
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.13
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.32-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 3.93MB
Database Data Size: 2.49MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 27
page: 8
post: 2
product: 18
product_variation: 7
revision: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Query Monitor: by John Blackbourn – 3.6.5
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.2.4 – Installed version not tested with active version of WooCommerce 4.0
Facebook for WooCommerce: by Facebook – 2.2.0
Jetpack by WordPress.com: by Automattic – 9.2.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.6
Mailchimp for WooCommerce: by Mailchimp – 2.5.0
Razorpay for WooCommerce: by Team Razorpay – 2.6.0
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce: by Automattic – 4.9.0-rc.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: woocommerce/woocommerce#6 - /shop/
Cart: woocommerce/woocommerce#7 - /cart/
Checkout: woocommerce/woocommerce#8 - /checkout/
My account: woocommerce/woocommerce#9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-01-06 07:12:25 +0000
Newest: 2021-01-06 07:12:25 +0000

`
```
</details>

**Comment by nerrad** [comment] 2021-01-08 12:53
Thanks for the report. This could be a problem with cached assets when switching versions but I also notice that from the SSR that WC Blocks 4.0.0 is active on this site. 

Whoever investigates this as porter, I've mostly assigned this to the requested pipeline to see if you can reproduce and identify what is causing it, also try and determine if there's a workaround (I assume refreshing the block in the editor might work). If it's reproducible, the cause is known, and whether there is a workaround - we can triage further for when we focus on fixing.

**Comment by budzanowski** [comment] 2021-01-28 09:34
I was not able to reproduce the problem. I have followed the scenario and it still has worked. I tried switching to different versions and still nothing. Maybe this is WP version dependent. I also think that switching versions using the Beta Tester plugin may introduce some flukes - but that is just a wild guess.
This is an edge case scenario, it is still important, but bc it is hard to reproduce we don't want to spend too much time on this. If it would happen each time it would be a bigger problem. Closing for now.

**Comment by tammullen** [comment] 2021-03-23 16:54
I have ran into this issue a few times today when using WC 5.1 and 5.2 Beta 1

Adding my observations

## To reproduce
Steps to reproduce the behavior:

1. On a site (I tried with JN and Pressable) with WooCommerce 5.1 only (no separate WooCommerce Blocks plugin)
2. Go to add new page
3. Add all products block
4. Error displayed "This block has encountered an error and cannot be previewed"
![Screenshot 2021-03-23 at 14 13 43](https://user-images.githubusercontent.com/24649833/112160761-64815780-8be2-11eb-81fd-0796904febff.png)

5. Publish Page
6. See Error "Oops! There was an error loading the content. Error: Cannot read property 'call' of undefined"
![Screenshot 2021-03-23 at 14 14 03](https://user-images.githubusercontent.com/24649833/112160776-69460b80-8be2-11eb-8eba-7a43fb840b56.png)

7. On WooCommerce 5.2 Beta 1 a different error is displayed
![Screenshot 2021-03-23 at 14 24 12](https://user-images.githubusercontent.com/24649833/112161920-7adbe300-8be3-11eb-81a4-c1b0125927f1.png)

## Expected behavior
No Errors

## Environment
### WordPress (please complete the following information):
* Core version: 5.7
* Gutenberg version (if installed): n/a
* WooCommerce version: 5.2 Beta 1
* WooCommerce Blocks version: 4.7
* Any other plugins installed: Have been able to reproduce with only WC installed, but most of the time Jetpack and WC Beta tester were installed.

### Desktop (please complete the following information):
* OS:  macOS
* Browser: Chrome

## Additional context
I'm only able to sporadically reproduce this on WC 5.1 but I can reproduce more consistently on 5.2 Beta 1 on new and existing sites. However I can't consistently reproduce this every time.

**Comment by nerrad** [comment] 2021-03-23 17:09
@senadir can you look into this please and see if you can determine what might be happening here?

**Comment by senadir** [comment] 2021-03-23 17:10
I will.

**Comment by nerrad** [comment] 2021-03-23 17:14
@tammullen are you able to reproduce this anywhere _without_ using the beta tester plugin to switch versions? I'm wondering if this is an issue with all the files not being setup correctly in the Woo install via that method of switching versions. From the original report, it sounds like that was the issue in that case as well.

The reason why I'm thinking this may be the cause, is the errors you are reporting usually happen when files are missing (404s for example) and inconsistency points to something environment specific.

**Comment by senadir** [comment] 2021-03-23 17:26
Hey @tammullen I'm not able to reproduce locally (using git) or on Jurassic ninja (first installing 5.1 and using beta switcher to install 5.2 beta). I will try more, and have a team member try as well.

**Comment by senadir** [comment] 2021-03-23 17:48
I tested 4 websites (locally, pressable, 2 jurassic ninja), going back and forth between 5.1 RC, 5.1, and 5.2 beta 1 and I was still unable to reproduce.
I used WooCommerce Beta tester but there was still nothing.

As others said, this seems to be an issue with a missing file due to some faulty setup. Without being able to reproduce, I can't fix this.

**Closed as completed by senadir** 2021-03-23 17:48 UTC
Labels: type: bug, block: all products, priority: high

**Comment by nerrad** [comment] 2021-03-23 18:03
Thanks Nadir! @tammullen I think a good next step here would be to examine your environment when you are reproducing to check if the file paths for the missing js files are correct for where your site is hosted. I suspect that either:

a. There's some dynamic path switching happening when switching between versions that might be confusing caches OR
b. There's a bad installation of the Woo version switched to where not all files are getting installed.

Either of the above would produce the symptoms you are experiencing. We know from testing that Nadir and others have done that there doesn't appear to be anything wrong with existing code that lives in Woo Core - so it appears to be some external factor involved here.

**Comment by tammullen** [comment] 2021-03-23 22:46
Thanks @senadir and @nerrad for looking into this!

Good to see it isn't widespread, thanks for checking.

I had been able to trigger it earlier on some new JN sites with nothing else installed and then installing 5.2 beta manually however this didn't happen every time and was very inconsistent (albeit I realised in hindsight I was using the same browser window for all of these). Since then now in a new browser window with multiple new JN sites I haven't been able to reproduce it on JN.

On an existing pressable site (with wc beta tester) where I can see the error right now the error doesn't appear if I open the same page in incognito mode. Maybe this points to something cache related?
![Screenshot_2021-03-23_at_22_35_39](https://user-images.githubusercontent.com/24649833/112228175-c795dd00-8c28-11eb-9e9f-30ecfaa333c1.png)

I also had a team member try it and they couldn't reproduce it so I think it is fine to assume this is a rare issue and just keep an eye for any other reports.
