### ISSUE TITLE
No checkbox for GDPR Compliance

### ISSUE THREAD

**Issue by US199** [woocommerce/woocommerce-gutenberg-products-block#3295] opened 2020-10-17 20:04 UTC
## What do you think is missing from the Cart & Checkout blocks? 

Unfortunately I am highly missing the Checkbox to accept the terms and conditions, data privacy regulations and other legal stuff. I am not able to customize the checkout page. I really tried hard with a lot of plugins. I even searched for the .php to put in the code below. But I don't know in which file I have to insert the snippet. Snippet Plugins didn't work. Can't go live without this checkbox. 

```
add_action( 'woocommerce_review_order_before_submit', 'bbloomer_add_checkout_privacy_policy', 9 );
    
function bbloomer_add_checkout_privacy_policy() {
   
woocommerce_form_field( 'privacy_policy', array(
   'type'          => 'checkbox',
   'class'         => array('form-row privacy'),
   'label_class'   => array('woocommerce-form__label woocommerce-form__label-for-checkbox checkbox'),
   'input_class'   => array('woocommerce-form__input woocommerce-form__input-checkbox input-checkbox'),
   'required'      => true,
   'label'         => 'I\'ve read and accept the <a href="/privacy-policy">Privacy Policy</a>',
)); 
   
}
   
// Show notice if customer does not tick
    
add_action( 'woocommerce_checkout_process', 'bbloomer_not_approved_privacy' );
   
function bbloomer_not_approved_privacy() {
    if ( ! (int) isset( $_POST['privacy_policy'] ) ) {
        wc_add_notice( __( 'Please acknowledge the Privacy Policy' ), 'error' );
    }
}

```

**Comment by US199** [comment] 2020-10-17 20:12
I also can't fully customize the checkout in the Wordpress editor. I can't add the input field phone number (required).

**Comment by nerrad** [comment] 2020-10-18 17:55
Hi there, 

Thanks for taking the time to leave the feedback. 

The report in the title and initial comment is a duplicate of #3258.

Regarding [your comment on the phone number issue](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3295#issuecomment-711073801), that is something different and is reported in #3231.

**Closed by nerrad** 2020-10-18 17:55 UTC
