### ISSUE TITLE
Checkout Block Low Stock Badge Not Respecting "Stock Display Format" Setting

### ISSUE THREAD

**Issue by drewskix86** [woocommerce/woocommerce-gutenberg-products-block#6428] opened 2022-05-19 11:56 UTC
The WooCommerce Checkout Block shows the Low Stock Badge & numbers on all low stock items, regardless of the "Stock Display Format" setting found from WooCommerce>Settings>Products>Inventory.

**Comment by tarunvijwani** [comment] 2022-05-20 09:41
Hi @drewskix86! Thank you for reporting this issue. Unfortunately, I couldn't reproduce the problem. Could you please help me with the steps to reproduce this bug as well as a screenshot of your checkout block page?

Looking forward to hearing back from you.

**Comment by drewskix86** [comment] 2022-05-20 10:02
Hi @tarunvijwani,

I've attached screenshots below of the checkout showing the stock number remaining and woocommerce setting:
![image](https://user-images.githubusercontent.com/31920225/169502033-74bdd368-126c-415f-b147-bbc414f741da.png)
![image](https://user-images.githubusercontent.com/31920225/169503806-59ca5089-6dc6-4384-9606-bd70ca2207c1.png)

System Report: 
`
### WordPress Environment ###

WordPress address (URL): https://staging2.reefpurero.com.au
Site address (URL): https://staging2.reefpurero.com.au
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1n-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.0
WC Database Prefix: wp_
Total Database Size: 190.27MB
Database Data Size: 118.45MB
Database Index Size: 71.82MB
wp_woocommerce_sessions: Data: 3.52MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 54.59MB + Index: 43.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 1.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.17MB + Index: 0.15MB + Engine MyISAM
wp_comments: Data: 6.65MB + Index: 2.16MB + Engine MyISAM
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hermes_user_like_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.38MB + Index: 0.08MB + Engine MyISAM
wp_postmeta: Data: 23.39MB + Index: 10.75MB + Engine MyISAM
wp_posts: Data: 1.88MB + Index: 0.44MB + Engine MyISAM
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sendlelogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stock_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 3.09MB + Index: 1.54MB + Engine MyISAM
wp_users: Data: 0.14MB + Index: 0.12MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 1.52MB + Index: 1.47MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 3.52MB + Index: 4.02MB + Engine InnoDB
wp_wc_order_stats: Data: 0.38MB + Index: 0.36MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 1.52MB + Index: 1.89MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_url_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_user_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.17MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 452
nav_menu_item: 61
oembed_cache: 3
page: 18
post: 8
product: 239
product_variation: 14
revision: 2
shop_coupon: 14
shop_order: 4507
shop_order_refund: 27
vc_grid_item: 1
wp_global_styles: 1
wpcf7_contact_form: 2
wpsl_stores: 40
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Template Library and Redux Framework: by Extendify – 4.3.13
Contact Form 7: by Takayuki Miyoshi – 5.5.6.1
Delete Me: by Clinton Caldwell – 3.0
Facebook for WooCommerce: by Facebook – 2.6.14
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
LionThemes Helper: by LionThemes – 1.2.1
Mailchimp for WooCommerce: by Mailchimp – 2.6.2
Sendle Shipping Plugin: by Joovii – 5.5
Product XML Feeds for WooCommerce: by WPWhale – 2.5
Slider Revolution: by ThemePunch – 6.2.1
WooCommerce Shippit: by Shippit Pty Ltd – 1.6.6
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
User Switching: by John Blackbourn & contributors – 1.5.8
WooCommerce Blocks: by Automattic – 7.6.0
WooCommerce Composite Products: by WooCommerce – 8.4.2
WooCommerce Filter Orders by Product: by Md. Kowsar Hossain – 3.2
WooCommerce Stripe Gateway: by WooCommerce – 6.3.0
WooCommerce Gift Cards: by WooCommerce – 1.11.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.9
WooCommerce PayPal Payments: by WooCommerce – 1.8.0
WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 2.14.5
WooCommerce Product Bundles: by WooCommerce – 6.15.3
Stock Manager for WooCommerce: by StoreApps – 2.8.3
WooCommerce Waitlist: by Neil Pie – 2.3.2
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27.5
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.2
WooCommerce Xero Integration: by WooCommerce – 1.7.42
WooCommerce: by Automattic – 6.5.1
Yoast SEO: by Team Yoast – 18.9
Bootstrap Blocks: by Liip AG – 4.2.0
WP Store Locator: by Tijmen Smit – 2.2.235

### Inactive Plugins (3) ###

Australia Post WooCommerce Extension PRO: by WPRuby – 2.1.1
SiteGround Optimizer: by SiteGround – 7.1.0
WP Maintenance Mode & Coming Soon: by Themeisle – 2.4.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hermes Child
Version: 1.6
Author URL: http://lion-themes.com/
Child Theme: ✔
Parent Theme Name: Hermes
Parent Theme Version: 1.8.0
Parent Theme Author URL: https://lion-themes.net/
WooCommerce Support: ✔

### Templates ###

Overrides: hermes-child/woocommerce/archive-product.php
hermes-child/woocommerce/cart/cart.php
hermes-child/woocommerce/cart/cross-sells.php
hermes/woocommerce/checkout/form-checkout.php
hermes-child/woocommerce/checkout/form-login.php
hermes/woocommerce/checkout/review-order.php
hermes-child/woocommerce/checkout/thankyou.php
hermes-child/woocommerce/content-product.php
hermes-child/woocommerce/content-single-product.php
hermes-child/woocommerce/content-widget-product.php
hermes-child/woocommerce/emails/customer-on-hold-order.php
hermes-child/woocommerce/emails/email-styles.php
hermes/woocommerce/global/breadcrumb.php
hermes/woocommerce/loop/loop-end.php
hermes/woocommerce/loop/loop-start.php
hermes-child/woocommerce/loop/orderby.php
hermes-child/woocommerce/loop/result-count.php
hermes-child/woocommerce/myaccount/form-edit-account.php
hermes-child/woocommerce/myaccount/form-login.php
hermes-child/woocommerce/myaccount/my-account.php
hermes/woocommerce/myaccount/navigation.php
hermes/woocommerce/product-searchform.php
hermes/woocommerce/single-product/price.php
hermes-child/woocommerce/single-product/rating.php
hermes-child/woocommerce/single-product/related.php
hermes/woocommerce/single-product/review.php
hermes/woocommerce/single-product/sale-flash.php
hermes/woocommerce/single-product/short-description.php
hermes-child/woocommerce/single-product/title.php
hermes/woocommerce/single-product/up-sells.php
hermes-child/woocommerce/single-product-reviews.php
hermes/woocommerce/single-product.php
hermes/woocommerce/content-product_cat.php


### Composite Products ###

Database Version: 8.4.2
Loopback Test: ✔
Template Overrides: –

### Gift Cards ###

Database Version: 1.11.0
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 6.15.3
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AU
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: ✔

### Action Scheduler ###

Complete: 2,811
Oldest: 2022-01-30 04:19:53 +0000
Newest: 2022-05-20 10:01:14 +0000

Pending: 41
Oldest: 2022-03-02 03:50:06 +0000
Newest: 2022-05-20 10:01:16 +0000

Failed: 36
Oldest: 2021-03-21 12:22:43 +0000
Newest: 2021-03-21 12:47:30 +0000

Cancelled: 5
Oldest: 2022-02-09 09:02:35 +0000
Newest: 2022-02-27 03:49:20 +0000


### Status report information ###

Generated at: 2022-05-20 20:01:34 +10:00
`

**Comment by tarunvijwani** [comment] 2022-05-20 10:26
Thank you for sharing the screenshot! It helped a lot to understand the issue. 

`Stock display format` at WooCommerce > Settings > Products > Inventory is only allowing to display stock on the product page, not on the checkout or checkout block page. 

It could be a plugin or theme conflict. Could you please disable all plugins except WooCommerce and WooCommerce blocks, and switch your theme to check if you're able to see the stock on the check block page? Let us know what you find out. Thank you!

**Comment by drewskix86** [comment] 2022-05-20 11:24
Hi @tarunvijwani,

I have disabled all plugins as requested, the only remaining plugins are woocommerce and woocommerce blocks. Storefront theme screenshot attached:
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/31920225/169517767-9000448d-224d-427d-bfb0-b163393d0060.png">

New system report attached:
`
### WordPress Environment ###

WordPress address (URL): https://staging2.reefpurero.com.au
Site address (URL): https://staging2.reefpurero.com.au
WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.6.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 5.9.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.33
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1n-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.4.0
WC Database Prefix: wp_
Total Database Size: 190.28MB
Database Data Size: 118.46MB
Database Index Size: 71.82MB
wp_woocommerce_sessions: Data: 3.52MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 54.59MB + Index: 43.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.52MB + Index: 1.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.17MB + Index: 0.15MB + Engine MyISAM
wp_comments: Data: 6.65MB + Index: 2.16MB + Engine MyISAM
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hermes_user_like_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.38MB + Index: 0.08MB + Engine MyISAM
wp_postmeta: Data: 23.39MB + Index: 10.75MB + Engine MyISAM
wp_posts: Data: 1.88MB + Index: 0.44MB + Engine MyISAM
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sendlelogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stock_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 3.10MB + Index: 1.54MB + Engine MyISAM
wp_users: Data: 0.14MB + Index: 0.12MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 1.52MB + Index: 1.47MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 3.52MB + Index: 4.02MB + Engine InnoDB
wp_wc_order_stats: Data: 0.38MB + Index: 0.36MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 1.52MB + Index: 1.89MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_url_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wysija_user_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wysija_user_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.17MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.17MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 452
nav_menu_item: 61
oembed_cache: 3
page: 18
post: 8
product: 239
product_variation: 14
revision: 2
shop_coupon: 14
shop_order: 4507
shop_order_refund: 27
vc_grid_item: 1
wp_global_styles: 2
wpcf7_contact_form: 2
wpsl_stores: 40
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Blocks: by Automattic – 7.6.0
WooCommerce: by Automattic – 6.5.1

### Inactive Plugins (32) ###

Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
Australia Post WooCommerce Extension PRO: by WPRuby – 2.1.1
Bootstrap Blocks: by Liip AG – 4.2.0
Contact Form 7: by Takayuki Miyoshi – 5.5.6.1
Delete Me: by Clinton Caldwell – 3.0
Facebook for WooCommerce: by Facebook – 2.6.14
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
LionThemes Helper: by LionThemes – 1.2.1
Mailchimp for WooCommerce: by Mailchimp – 2.6.2
Product XML Feeds for WooCommerce: by WPWhale – 2.5
Sendle Shipping Plugin: by Joovii – 5.5
SiteGround Optimizer: by SiteGround – 7.1.0
Slider Revolution: by ThemePunch – 6.2.1
Stock Manager for WooCommerce: by StoreApps – 2.8.3
Template Library and Redux Framework: by Extendify – 4.3.13
User Switching: by John Blackbourn & contributors – 1.5.8
WooCommerce Composite Products: by WooCommerce – 8.4.2
WooCommerce Filter Orders by Product: by Md. Kowsar Hossain – 3.2
WooCommerce Gift Cards: by WooCommerce – 1.11.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.9
WooCommerce PayPal Payments: by WooCommerce – 1.8.0
WooCommerce PDF Invoices & Packing Slips: by WP Overnight – 2.14.5
WooCommerce Product Bundles: by WooCommerce – 6.15.3
WooCommerce Shippit: by Shippit Pty Ltd – 1.6.6
WooCommerce Stripe Gateway: by WooCommerce – 6.3.0
WooCommerce Waitlist: by Neil Pie – 2.3.2
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.2
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27.5
WooCommerce Xero Integration: by WooCommerce – 1.7.42
WP Maintenance Mode & Coming Soon: by Themeisle – 2.4.4
WP Store Locator: by Tijmen Smit – 2.2.235
Yoast SEO: by Team Yoast – 18.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.1.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2,811
Oldest: 2022-01-30 04:19:53 +0000
Newest: 2022-05-20 10:01:14 +0000

Pending: 41
Oldest: 2022-03-02 03:50:06 +0000
Newest: 2022-05-20 11:21:03 +0000

Failed: 36
Oldest: 2021-03-21 12:22:43 +0000
Newest: 2021-03-21 12:47:30 +0000

Cancelled: 6
Oldest: 2022-02-09 09:02:35 +0000
Newest: -0001-11-30 00:00:00 +0000


### Status report information ###

Generated at: 2022-05-20 21:23:37 +10:00
`

**Comment by senadir** [comment] 2022-05-23 17:13
Thank you @drewskix86 for reporting this, this is indeed an issue, it should be fixed in https://github.com/woocommerce/woocommerce-blocks/pull/6444

**Comment by drewskix86** [comment] 2022-05-24 00:30
Thanks!

**Closed as completed** 2022-05-27 19:55 UTC
Labels: block: checkout
