### ISSUE TITLE
Styles found in Woo Core need consolidating into Blocks plugin

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gutenberg-products-block#2418] opened 2020-05-06 15:17 UTC
There are a number of theme specific styles for blocks in core which ideally should be moved to blocks so both plugins are not fighting for specificity. 

Example: 
https://github.com/woocommerce/woocommerce/blob/master/assets/css/twenty-twenty.scss#L2103-L2140

From a quick scan, it only appears to affect Twenty Twenty. These particular styles are causing issues on the All Products Block, so they will need updating when merged back to blocks:

![Screenshot 2020-05-06 at 16 01 27](https://user-images.githubusercontent.com/90977/81194761-f1b0c300-8fb4-11ea-89e7-94c8803ee8b3.png)

**Comment by Aljullu** [comment] 2020-05-15 08:53
I created a PR in Core (https://github.com/woocommerce/woocommerce/pull/26516) that should fix the glitches caused by these styles. So this issue can be exclusively about moving those styles to WC Blocks without any changes.

From the file @mikejolley [linked](https://github.com/woocommerce/woocommerce/blob/master/assets/css/twenty-twenty.scss), we would need to move all selectors that start with `.wc-block`.

In `product-list/style.scss` we also have some [styles targeting specific 20xx themes](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/assets/js/base/components/product-list/style.scss#L353-L376).

As we build new blocks and new WP core themes are released, theme specific styles might keep increasing. So I think we should consider building a system to only load theme-specific styles if that theme is enabled, like they have in core. Does that sound reasonable @mikejolley?

**Comment by mikejolley** [comment] 2020-05-15 08:58
@Aljullu Possibly yes, if the volume of styles causes an increase in file size we're not happy with.

**Comment by Aljullu** [comment] 2020-05-22 10:50
After #2513 was merged, I think we can close this issue. If in the future we see a system to dynamically import CSS for specific themes is needed, we can open an issue for that.

**Closed by Aljullu** 2020-05-22 10:50 UTC
Labels: type: bug
