### ISSUE TITLE
Variation Price shown as Sale price in Cart Block

### ISSUE THREAD

**Issue by Roxane66** [woocommerce/woocommerce-gutenberg-products-block#4072] opened 2021-04-18 12:26 UTC
### Original Issue 
Bonjour, 
J'ai des produits personnalisés et le blocs panier considère le prix de mes variations comme étant un prix promo. Cela pose problème quand il m'affiche le prix initial, barré, et le prix avec option juste après.
Auriez vous une solution ?
Merci d'avance, 
Roxane

### Translated
Good morning,

I have customisable products but the Cart block is considering my variation price as a sale price, this creates a problem because it shows the initial price striked, and the price with an add-on after it.

![Capture](https://user-images.githubusercontent.com/82761231/115145500-141adf80-a052-11eb-917c-daececa61a11.PNG)

**Comment by senadir** [comment] 2021-04-19 13:26
Hey there @Roxane66 

I went along and translated your issue because our team's primary language is English.

I also tried to reproduce your issue with several combinations but wasn't able to reproduce it correctly.

Can you share the link of your website and steps to create this product so we can reproduce the issue?

**Comment by Roxane66** [comment] 2021-04-19 13:54
Thanks for your feedback,
I don't have the site online yet.
But I'll be sure to send it to you as soon as I do.
I have hidden my problem in CSS for now.
Have a good day

Bonjour,
Merci pour votre retour,
Je n'ai pas encore le site en ligne.
Mais je ne manquerai pas de vous l'envoyer dès que ce sera le cas.
J'ai masqué mon problème en CSS pour le moment.
Bonne journée
Roxane

Le lun. 19 avr. 2021 à 15:27, Seghir Nadir ***@***.***> a
écrit :

**Comment by senadir** [comment] 2021-04-26 20:18
Hey @Roxane66 I'm gois to close this for now, when you have a working example, feel free to open this again.

Have a good day!

**Closed as completed by senadir** 2021-04-26 20:18 UTC
Labels: type: bug
