### ISSUE TITLE
Translation of T&C Text on Checkout not shown

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gutenberg-products-block#7038] opened 2022-09-01 06:49 UTC
## Describe the bug
On the Checkout Page there is this text. https://github.com/woocommerce/woocommerce-blocks/blob/d68bd4a2e38ef36e961828d82d9991880e719ce2/assets/js/blocks/checkout/inner-blocks/checkout-terms-block/constants.js#L24

Although its correctly translated in German (https://translate.wordpress.org/projects/wp-plugins/woo-gutenberg-products-block/stable/de/default/?filters%5Bterm%5D=By+proceeding+with+your+purchase+you+agree&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) and also translated in the customizer (WooCommerce -> Checkout)
![image](https://user-images.githubusercontent.com/6242098/187849928-92f2ad45-6041-4bfb-b3e1-648bed41ca87.png)

-> its not shown on the new Checkout Block:

![image](https://user-images.githubusercontent.com/6242098/187849652-559a9dd3-3f9c-4fdb-b8fa-58718241ac24.png)

It works though on the old Checkout (shortcodes)
![image](https://user-images.githubusercontent.com/6242098/187849783-2c66bdc4-3599-473b-a7f6-0793a2524cb3.png)

## To reproduce

1. Setup a new store, switch language to german
2. Go to Customizer
3. Click on WooCommerce -> Checkout -> Terms and conditions Area
4. Translate the text
5. Go to checkout
6. You'll still see the english message

## Expected behavior
The Text should show in the translated language.

## Screenshots
see above

## Environment
Newest WordPress, newest Woo & newest Woo Blocks

**Comment by nielslange** [comment] 2022-09-05 06:40
Hello @masteradhoc,

Thanks for reaching out on this. The Checkout block works indeed a bit different from the shortcode-based solution. The T&C text from the Customizer only affects the old checkout, not the Checkout block:

<img width="296" alt="Screenshot 2022-09-05 at 13 32 57" src="https://user-images.githubusercontent.com/3323310/188378346-1557be5b-f680-4a91-9340-df445d000098.png">

That said, let's focus on the Checkout block. In your testing steps above I see that you translated the text in the Customizer, which only affects the old checkout, as mentioned before. To get the T&C section on the Checkout block translated, you need to fetch the German translations of the WooCommerce Block, via `/wp-admin/update-core.php`, after you switched the site language to German. Once you fetched the German translations, the T&C section should automatically appear in German. In case you're still seeing the T&C section in English, please try to remove the Checkout block in the editor, ;save the page and then add the Checkout block again. This should then let the whole Checkout block, including the T&C section, appear in German.

I hope this helps to solve the current problem!

**Comment by masteradhoc** [comment] 2022-09-05 06:55
Hi @nielslange 
1) my site language already is german (at least now not sure of when i added the block)
2) removed the block from checkout and saved the page
3) added the block again and it showed up in german


looks fine :) still not sure why all other text we're translated fine but not this one..

**Comment by nielslange** [comment] 2022-09-05 07:30
Hello @masteradhoc,

I'm glad to hear that the T&C section is now visible in German.

> still not sure why all other text we're translated fine but not this one..

There are various reasons, which might have led to this:
- You were using an older version of the Checkout block, that didn't support translations for the T&C section yet.
- The text of the T&C section had been accidentally touched, saving the English text, as seen in the editor, directly to the database.
- A previous German translation file didn't contain the translated strings for the T&C section.

It's always a bit tricky to pinpoint what was causing this, but removing and re-adding a certain block, when the translations are up-to-date, helps in most cases.

Again, I'm happy to hear that the problem is solved, and I'll close this issue for now. If you need any further assistance, please don't hesitate to create a new issue. 😀

**Closed as completed by nielslange** 2022-09-05 07:30 UTC
Labels: type: bug
