### ISSUE TITLE
Filter by attribute block > don't use Hn html tag to style filter's name !!!

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#7869] opened 2022-12-07 11:25 UTC
## Describe the bug

Currently, the block name makes use of H3 hierarchical html tag (Hn)

## To reproduce

Just add the block and observe the block's title size / heading
It is a H3.

## Expected behavior

Don't use headings to style content that are not pure content. 
Hn headings are dedicated to semantic decorations (see w3c.org), and the Hn structure is driven by the theme and contents.
Here those are only filters, to filter contents, it is not content !!!
Just add a proper css class to define the right size.
I guess we have the issue on the other Woo blocks.

## Screenshots

![image](https://user-images.githubusercontent.com/919332/206166536-4762cabd-9a33-40bd-8a0a-6f0cc57f4784.png)

## Environment

WP6.1.1
Woo Blocks 9.1
Gutenberg plugin 14.6.1
WC 7.1
TT2 Theme

**Comment by imanish003** [comment] 2022-12-26 09:19
Hi @Aljullu, I would like to hear your opinion on this. 
There is a related issue woocommerce/woocommerce#42518

**Comment by Aljullu** [comment] 2022-12-27 11:08
Thanks for opening this issue, @Marc-pi! You should be able to change the styling of the heading from the sidebar, using the _Typography_ panel:

<img src="https://user-images.githubusercontent.com/3616980/209657743-a6d9a063-2717-449f-96ec-ed26d833352a.png" width="300" alt="Screenshot of the Typography panel" />

As you mention, that block is a heading instead of a paragraph for semantic reasons and to make it easy to navigate to it using accessibility tools. Are you facing any issues with it?

Something that we could discuss is whether it should be an _H2_ instead of an _H3_ by default. But that's difficult to predict because it depends on the structure of the page.

**Comment by kmanijak** [comment] 2023-01-13 13:52
Hi @Marc-pi, I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as not planned by kmanijak** 2023-01-13 13:52 UTC
Labels: type: bug, focus: global styles
