### ISSUE TITLE
WooCommerce 7.9 still causing Site Editor Navigation malfunction WP 6.2/WP 6.3RC3 even with Woo Blocks 10.8.0

### ISSUE THREAD

**Issue by Marc-pi** [woocommerce/woocommerce-gutenberg-products-block#10467] opened 2023-08-03 16:27 UTC
On 2 of my sites, using FSE only, i've an issue at editing Navigation component aka Menus, willing to edit them leads to Black Screen of Death.

Follow up to https://github.com/woocommerce/woocommerce-blocks/issues/10259
> the issue is still there, and it is critical (we cannot manage our menus)

ping @nefeline / @nerrad 

**How to get the issue**
1. Go to Site Editor wp-admin/site-editor.php
2. Click on Navigation
3. Click on the arrow on the navigation menu you want to edit
4. You get a black screen of death :-)

If you inactive WooCommerce plugin, the error is gone
If you inactive only Woo Block, the error is still there
> so the error is brought by WooCommerce

**Environment**
Both sites run Gutenberg 16.3.0 + WooCommerce 7.9.0 + Woo Blocks 10.8.0
and are under PHP 8.1.16
the only difference is the WP Version and the theme in use
- WP 6.2.2 + TT3 
- WP 6.3RC3 + TT2

**Comment by Marc-pi** [comment] 2023-08-03 16:38
seems a fix was shipped into a WC Blocks 10.6.2 and into WooCommerce Trunk, but not in 10.8.0 !!!
ping @gigitux 
seems not to be yet in 8.0 RC !

**Comment by gigitux** [comment] 2023-08-03 16:51
Hi @Marc-pi,

I tested the release 10.8.0 with WordPress 6.2 with the last version of Gutenberg installed and I'm unable to reproduce the issue. 

> seems not to be yet in 8.0 RC !

WC Blocks 10.6.2 is included in the [WooCommerce 8.0 RC-1](https://developer.woocommerce.com/2023/08/01/woocommerce-8-0-release-candidate/).


Can you share which env gives you the issue? Thanks!

**Comment by Marc-pi** [comment] 2023-08-03 16:59
> Can you share which env gives you the issue? Thanks!

of course, it is in my first post. Tell me if you need more.

> WC Blocks 10.6.2 is included in the [WooCommerce 8.0 RC-1

ok, i was looking for it the changelog entry on a dedicated line, it is indeed in the 10.6.2 line
https://github.com/woocommerce/woocommerce/blob/release/8.0/plugins/woocommerce/readme.txt
my mistake

**Comment by gigitux** [comment] 2023-08-03 17:04
> I tested the release 10.8.0 with WordPress 6.2 with the last version of Gutenberg installed and I'm unable to reproduce the issue.

Same result with WordPress 6.3-RC3.

Are you sure that you are using WooCommerce Blocks 10.8.0?

**Comment by Marc-pi** [comment] 2023-08-03 17:06
> Are you sure that you are using WooCommerce Blocks 10.8.0?

yep, i do confirm i run 10.8.0

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/a187c895-fe56-4bd9-ace0-8b17b7e927d1)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/323a64f3-6e69-412a-bef7-0985fc3d4cc8)


but i did not notice you've commited the fix into 10.8.0 as well, no ? Only into 10.6.x and woo trunk

**Comment by gigitux** [comment] 2023-08-03 17:14
I can confirm that the fix is in 10.8.0. If you check the branch `release/10.8.0`, you can see that the changes done into woocommerce/woocommerce#10388 are present.

Can you open the console of dev tools and check if there is an error?

**Comment by Marc-pi** [comment] 2023-08-03 17:38
yep, i've noticed i've some this afternoon.
FYI i do use Firefox 116 (latest stable), but i've also the bug on Chrome latest (black screen)

* when accessing wp-admin/site-editor.php
![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/1561955e-3ccd-43b6-8a7f-75010090aa8c)
those are coming from WP Core as long as i saw

* when clicking on menu to edit it, on  wp-admin/site-editor.php?postId=128&postType=wp_navigation
i've many more similar with "e.split is not a function"

![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/50b33938-bfb7-49f4-9195-1cbe63d9ea46)


![image](https://github.com/woocommerce/woocommerce-blocks/assets/919332/1135a7ba-b1b1-4caf-bb9a-a39e80ad33b4)

**Comment by gigitux** [comment] 2023-08-04 07:30
Did you have Gutenberg installed? If yes, can you try to disable it? Maybe it is another issue: https://github.com/WordPress/gutenberg/issues/53230

**Comment by nefeline** [comment] 2023-08-04 08:36
Thanks for the report @Marc-pi & for jumping on this @gigitux !

I can confirm the error is triggered in the site editor while having GB 16.3 enabled.

Disabling GB solves the problem. Seems to be related to https://github.com/WordPress/gutenberg/issues/53230 indeed.

**Comment by Marc-pi** [comment] 2023-08-04 09:02
whoever fixes this issue can also close 2 tickets for the same price :-)
another one is there https://github.com/woocommerce/woocommerce-blocks/issues/10628

**Comment by gigitux** [comment] 2023-08-04 09:04
> another one is there https://github.com/woocommerce/woocommerce-blocks/issues/10628

I will write a comment on this issue! Thanks for sharing the link!

**Closed as completed** 2023-08-04 14:16 UTC
Labels: type: bug, type: community contribution

**Comment by Marc-pi** [comment] 2023-08-07 11:18
@gigitux just to thank you, works like a charm with 10.8.1 release

**Comment by gigitux** [comment] 2023-08-07 11:52
> @gigitux just to thank you, works like a charm with 10.8.1 release

Thanks for your feedback!
