### ISSUE TITLE
Re-adding the no-shipping-available message hooks

### ISSUE THREAD

**Issue by dangoodman** [woocommerce/woocommerce-gutenberg-products-block#10920] opened 2023-09-12 11:10 UTC
[No Shipping Message](https://wordpress.org/plugins/wc-no-shipping-message/) currently has around 5,000 active installations. It will stop working with WooCommerce 8.4 once [Cart and Checkout blocks become the default experience](https://developer.woocommerce.com/2023/08/18/cart-and-checkout-blocks-becoming-the-default-experience/). The issue is lack of the following hooks:
- `woocommerce_cart_no_shipping_available_html`
- `woocommerce_no_shipping_available_html`
- `woocommerce_after_checkout_validation`

Are there plans on re-adding them to the blocks?

**Comment by opr** [comment] 2023-09-12 17:08
Hi, thanks for reporting this. We don't know if we'll reintroduce these _specific_ filters, however we are looking into the use-cases of developers and this is one we'll consider when looking at new interfaces to offer.

It isn't totally clear from the plugin page, but do you allow specific options to configure what is shown if the cart is overweight (e.g. Your order exceeds 10 kg. Please [contact us](https://wordpress.org/plugins/wc-no-shipping-message/#) to get a quote) or is that just a single string that displays when there are no options, regardless of the cause?

**Comment by opr** [comment] 2023-09-12 17:42
After discussing internally, you could use the following approach to get this working:

1. Register a custom block, make it a child of the `woocommerce/checkout-shipping-methods-block` block so it shows up in the correct section.
2. Inside the block, check the [`wc/store/cart` data store](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/data-store/cart.md) to determine if shipping has been calculated, and if there are no rates.
3. If so, hide the current notice with CSS and show a notice inside your block.

**Comment by dangoodman** [comment] 2023-09-15 04:33
The plugin shows the configured strings regardless of the cause.

How does it work when multiple plugins define a custom shipping methods block? I can imagine there might be many plugins customizing the shipping options area. For example, to add shipping options' descriptions or dates. In other words, it sounds like inheritance in OOP, which is sometimes good but can only be played once.

**Comment by ralucaStan** [comment] 2023-09-18 15:14
> [No Shipping Message](https://wordpress.org/plugins/wc-no-shipping-message/) currently has around 5,000 active installations. It will stop working with WooCommerce 8.4 once [Cart and Checkout blocks become the default experience](https://developer.woocommerce.com/2023/08/18/cart-and-checkout-blocks-becoming-the-default-experience/).

@dangoodman I want to highlight that the active stores won't be affected by the change. They will keep on using the classic cart and checkout. Only new stores will have by default the Cart and Checkout blocks enabled, which can be at any time replaced by their shortcode correspondent.

**Comment by senadir** [comment] 2023-09-29 15:24
Modifying shipping options happens via filters and internal blocks, so there should only be a single shipping options block.

**Comment by tarhi-saad** [comment] 2023-10-16 06:40
@dangoodman, I will close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue, and if we can reproduce, we can re-open as necessary.

**Closed as completed by tarhi-saad** 2023-10-16 06:40 UTC
Labels: type: enhancement, category: extensibility, type: community contribution
