### ISSUE TITLE
Filter by attribute issue

### ISSUE THREAD

**Issue by NinjaAtWork** [woocommerce/woocommerce-gutenberg-products-block#8105] opened 2023-01-04 20:13 UTC
Hi
I add filter by attribute block to the product by category template and the product grid will return no product found in front end after selecting a value as an attribute.
Also the filter by attribute in front end shows the whole defined values of that attribute which expected to show only available attribute value of current category.
This is while filter by price blocks works like a charm .
What can i do Please.
Thanks.

**Comment by kmanijak** [comment] 2023-01-10 11:18
Hi @NinjaAtWork! Thank you for raising this issue!

> I add filter by attribute block to the product by category template and the product grid will return no product found in front end after selecting a value as an attribute.

I've tried reproducing the issue following the steps you provided, but I was unable to reproduce the bug. Could you provide more detailed steps to reproduce or maybe record a video? Also, let us know if there are any additional conditions under which the issue occurs?

> Also the filter by attribute in front end shows the whole defined values of that attribute which expected to show only available attribute value of current category.

This is a known issue that is tracked in here: https://github.com/woocommerce/woocommerce/issues/42542. It's not something we'll start to work on really quickly, but we're aware of that and it's in our roadmap. We appreciate the feedback!

**Comment by gigitux** [comment] 2023-01-26 09:07
I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by gigitux** 2023-01-26 09:07 UTC
Labels: type: bug, block: filter by attribute
