### ISSUE TITLE
Cart/checkout layout breaks with sidebar on narrow screens

### ISSUE THREAD

**Issue by josemarques** [woocommerce/woocommerce-gutenberg-products-block#2359] opened 2020-04-29 16:00 UTC
While testing WooCommerce 4.1.0-rc.1 with Storefront using a default sidebar the cart layout breaks around 770px: 

<img width="769" alt="Screenshot 2020-04-29 at 15 29 41" src="https://user-images.githubusercontent.com/57050/80617105-98d3ae80-8a39-11ea-9de1-92930a12a671.png">

On the checkout it's not so bad but could use some work:

<img width="773" alt="Screenshot 2020-04-29 at 16 53 36" src="https://user-images.githubusercontent.com/57050/80617490-15668d00-8a3a-11ea-9a3a-117c138ef7fc.png">

**Comment by mikejolley** [comment] 2020-04-29 16:54
Thanks for reporting. This is a duplicate of https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2274

**Closed by mikejolley** 2020-04-29 16:54 UTC
