### ISSUE TITLE
Error messages in log after last update

### ISSUE THREAD

**Issue by n9yty** [woocommerce/woocommerce-gutenberg-products-block#4347] opened 2021-06-14 18:22 UTC
After the last update I am seeing this in the logs:

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')
AND meta_key IN ('attribute_pa_media-type')' at line 3 for query
SELECT post_id as variation_id, meta_key as attribute_key, meta_value as attribute_value
FROM wpscm_postmeta
WHERE post_id IN ()
AND meta_key IN ('attribute_pa_media-type')
made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Automattic\WooCommerce\Blocks\StoreApi\Routes\AbstractRoute->get_response, Automattic\WooCommerce\Blocks\StoreApi\Routes\Products->get_route_response, Automattic\WooCommerce\Blocks\StoreApi\Schemas\ProductSchema->get_item_response, Automattic\WooCommerce\Blocks\StoreApi\Schemas\ProductSchema->get_variations

**Comment by Aljullu** [comment] 2021-06-16 09:48
@n9yty thanks for opening this issue. Unfortunately, I'm unable to reproduce on my end. For some reason, the query is not built correctly for you. The offending line is [` WHERE post_id IN ()`](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/src/StoreApi/Schemas/ProductSchema.php#L584) (there should be something inside the parentheses).

My suggestion for you would be to follow the WooCommerce Self-Service guide here:

https://docs.woocommerce.com/document/woocommerce-self-service-guide/

Let us know if that helps! If it doesn't, it would be helpful if you could share with us:

* Which versions of WordPress, WooCommerce and WooCommerce Blocks are you using.
* Which versions were you using before the update.
* If that's something that you can do, you could export your products and share the CSV file with us. That would allow us to test directly on our systems with the same products that you have.

For now, I will close this issue because we don't have anything to act on, but feel free to reopen if the Self-Service guide is not working and if you can provide more details based on the questions above! :slightly_smiling_face:

**Closed as completed by Aljullu** 2021-06-16 09:48 UTC
Labels: type: bug
