### ISSUE TITLE
TT4 - Visual and Responsiveness Issues in "Footer with 3 Menus" Pattern

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11295] opened 2023-10-18 06:29 UTC
## Describe the bug

Two visual and responsiveness issues are observed in the Footer with 3 Menus Pattern in WooCommerce Blocks:

1. The Site title does not visually indicate that it's a clickable link when using the TT4 theme.
2. The pattern is not responsive on Editor side

#### Issue 1: Site title not appearing clickable

1. Apply the TT4 theme.
2. Add the Footer with 3 Menus Pattern
3. Observe that the Site title does not appear to be a clickable link.

**Before**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/14f4c4a3-976f-4ac3-9f7f-8b1b3e9fea50)

**Current**
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/382fdc37-86f9-4129-a901-de6c5cb7ff42)

#### Issue 2: Pattern not responsive

1. Add the Footer with 3 Menus Pattern
2. Reduce the browser window size on Editor
3. Observe that the pattern is not responsive.

![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/70bfcaa6-fd21-40f5-b942-66d7f33c95e4)

## Expected behavior

**Issue 1**
The Site title should be visibly distinguishable as a clickable link, especially when using themes where the text color for links is also black by default.

**Issue 2**
The pattern should be responsive and adapt to varying screen sizes gracefully on Editor side. 

## Additional context

These issues may not necessarily be bugs but can impact the user experience.

**Comment by danieldudzic** [comment] 2023-10-26 17:29
>  The Site title should be visibly distinguishable as a clickable link, especially when using themes where the text color for links is also black by default.

I believe this is a design choice of the theme. But I agree that this is not the best UX. Not sure if we should be addressing this via a pattern update, though.

>  The pattern should be responsive and adapt to varying screen sizes gracefully on Editor side.

I have noticed that the column gaps are insufficient on the front end:

<img width="1318" alt="Footer_with_3_Menus_–_Dominant_Penguin" src="https://github.com/woocommerce/woocommerce-blocks/assets/905781/a58dfbde-565c-4469-a2d2-031886940572">

**Comment by nerrad** [comment] 2023-10-27 09:02
> The Site title should be visibly distinguishable as a clickable link, especially when using themes where the text colour for links is also black by default.

I agree with @danieldudzic, we shouldn't be overriding the theme design aesthetic _unless_ we're implementing opinionated patterns (i.e. ignoring the theme styles).

> Observe that the pattern is not responsive.

Good observations, if this is not TT4 specific let's make sure there's a dedicated issue for solving that.

**Comment by danieldudzic** [comment] 2023-10-30 15:34
The columns overflow issue is caused by the change in size preset slug naming convention in Twenty Twenty-Four (compared to Twenty Twenty-Three).

I have now opened an issue in the Twenty Twenty-Four repo to discuss potential solutions: https://github.com/WordPress/twentytwentyfour/issues/710

**Comment by danieldudzic** [comment] 2023-11-03 14:59
This has been now fixed via https://github.com/woocommerce/woocommerce-blocks/pull/11544.

I'm closing this, as the conversation on the borader issue will continue here: https://github.com/woocommerce/woocommerce/issues/42150

**Closed as completed by danieldudzic** 2023-11-03 14:59 UTC
Labels: type: bug
