### ISSUE TITLE
"Doing it wrong" error triggers after navigating to "Appearance > Widgets" page

### ISSUE THREAD

**Issue by tarhi-saad** [woocommerce/woocommerce-gutenberg-products-block#10220] opened 2023-07-14 18:16 UTC
## Describe the bug
GlobalStep discovered this issue as part of critical flow testing.

A WordPress `Doing it wrong` message appears when the user clicks `Appearance > Widgets`.

```SHELL
Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). (This message was added in version 5.8.0.)
```

This check was first introduced in this WordPress commit: https://github.com/WordPress/WordPress/commit/846529de97790b9b866d4dd77a2940167374a52b. It has the following description:

> … in widgets editor

> It is common that plugins erroneously have `wp-editor` or `wp-edit-post` as a
dependency in a script that is loaded in the new widgets editor. This is a smell
since both `@wordpress/editor` and `@wordpress/edit-post` assume the existence
of a global "post" object which the widgets editor does not have.

And here is the original WordPress ticket: https://core.trac.wordpress.org/ticket/53569

The generated Woo Blocks build files `build/cart.asset.php` and `build/checkout.asset.php` does indeed include `wp-editor` as a dependency. Maybe the solution would be to dequeue the `wp-editor` script on the Widgets page.

## To reproduce

1. Use a non Block theme (I tested using the `storefront` and the `Twenty Twenty-one` themes)
2. Install and activate the [Query Monitor](https://wordpress.org/plugins/query-monitor/) plugin
3. Click on the new menu item in the admin toolbar menu to open the overview panel of the Query Monitor plugin

<img width="907" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/14235870/47db47b1-40c1-48ff-b20b-0703a4b0ab9d">

4. Go to `Appearance > Widgets`
5. Notice under the `Doing it Wrong` tab from Query Monitor's overview panel, the error message: `Function wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). (This message was added in version 5.8.0.)`

## Expected behavior

The page should be displayed without any error after navigating to "Woocommerce > Widgets".

## Screenshots

![image](https://github.com/woocommerce/woocommerce-blocks/assets/14235870/fcbdc035-b99c-472b-9339-a8407a66a7de)

### WordPress (please complete the following information):

-   WordPress version: 6.2
-   WooCommerce version: 8.0
-   WooCommerce Blocks version: 10.7
-   Site language: English (US)
-   Any other plugins installed: Query Monitor

### Desktop (please complete the following information):

-   OS: macOS
-   Browser Chrome
-   Version 114

## Additional context

- Global step ticket: https://github.com/woocommerce/woocommerce/issues/39169
- Slack thread: p1689010155432319-slack-C01DT6U03HC
- P2 comment: p6q8Tx-37X-p2#comment-7815

**Comment by tarhi-saad** [comment] 2023-07-17 01:33
Pinging @nefeline because you'll be Porter this week and @gigitux because this bug was introduced in a PR you worked on.

I've done some investigation and found out the source of this bug. In this PR #9386, we introduced the `PluginTemplateSettingPanel` slot:
https://github.com/woocommerce/woocommerce-blocks/blob/b9863242721f9cdbb16e5f6fa5ed2064ffe0277e/assets/js/templates/revert-button/index.tsx#L4

Consequently, `wp-editor` has become a dependency. However, its importation on the Widget page triggers the Doing it wrong error! We must prevent this dependency from being imported on the Widget page.

**Comment by gigitux** [comment] 2023-07-17 07:54
Hey, thanks for the ping! @nefeline, will you work on a fix?

**Comment by nefeline** [comment] 2023-07-18 18:37
Hey @tarhi-saad ! Thank you so much for reporting this issue **and** your investigation 🙏 . 

I have a few questions: am I right in my assumption that this issue is not causing any regressions in functionality? Do you believe this is a high priority that must be tackled ASAP by the Porters or can we wait until the next Cooldown?

**Comment by tarhi-saad** [comment] 2023-07-20 05:18
Hello @nefeline! I haven't delved deeper to determine whether this error leads to regressions. I'm not fully aware of our stance on `Doing it wrong` type errors, but I believe that if the solution is straightforward, we could attempt to rectify it without waiting for the cooldown. Please don't hesitate to request the team's input on this matter!

**Comment by nefeline** [comment] 2023-07-20 12:54
Thanks @tarhi-saad. Regarding:

> I haven't delved deeper to determine whether this error leads to regressions.

The reason I asked you this is because there's another issue that is [breaking the navigation block on WordPress 6.3](https://github.com/woocommerce/woocommerce-blocks/issues/10259) that was caused by https://github.com/woocommerce/woocommerce-blocks/pull/9468 , which is a PR that follows up the one you flagged over here as being the cause of this issue: https://github.com/woocommerce/woocommerce-blocks/pull/9386.

I'm still working on a fix for that problem, https://github.com/woocommerce/woocommerce-blocks/pull/10283 , which may or may not have a positive impact on what is reported here, will keep you posted.

cc: @gigitux in case you wanna share your thoughts on this since you worked on both PRs.

**Comment by nefeline** [comment] 2023-08-03 07:41
Hey @tarhi-saad ! Heads up that this problem was solved on https://github.com/woocommerce/woocommerce-blocks/pull/10388 so I'm going ahead and closing this issue. Thanks again for the report and your prompt responses here! 🙌

**Closed as completed by nefeline** 2023-08-03 07:41 UTC
Labels: type: bug
