### ISSUE TITLE
[GlobalStep] "Styles" icon fails to display after clicking on blue "Edit" button on "WP Admin » Appearance » Editor" page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#8850] opened 2023-03-24 14:19 UTC
### Bug Description:
"Styles" icon fails to display after clicking on blue "Edit" button on "WP Admin » Appearance » Editor" page.

### Environment:
Woocommerce Version:  WooCommerce 7.6.0-beta.1 
WordPress version:  WordPress 6.2-RC4

PC:
Windows 10, 
Chrome(Version 111.0.5563.111)
Firefox(Version 111.0.1)

### Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
2. Install and activate all the required plugins.
3. Install and activate Woocommerce.
4. Ensure that a block theme is installed, e.g. TT3 and install Gutenberg v15.1.0
5. Go to WP Admin » Appearance » Editor.
6. Observe that, "Styles" icon fails to display in the upper-right corner.

### Note:
Page shows loading and fails to displays the content of the page.

### instruction Link:
https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/internal-developers/testing/releases/970.md#show-cart-and-checkout-blocks-in-style-book-8489

### Actual Result:
"Styles" icon fails to display after clicking on blue "Edit" button on "WP Admin » Appearance » Editor" page.

### Expected Result:
"Styles" icon should be displayed after clicking on blue "Edit" button on "WP Admin » Appearance » Editor" page.

### Screenshot:

![#8850](https://user-images.githubusercontent.com/41110392/227549343-17b4cf05-6eb5-46d4-8c5c-e7ab793824b4.gif)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.1
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2-RC4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.56 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0
WC Database Prefix: wp_
Total Database Size: 7.82MB
Database Data Size: 5.79MB
Database Index Size: 2.03MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.41MB + Index: 0.48MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.23MB + Index: 0.17MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 28
elementor_library: 1
page: 8
post: 5
product: 18
product_variation: 7
revision: 5
shop_order: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 3.12.1
Companion Plugin: by Osk – 1.29
Gutenberg: by Gutenberg Team – 15.1.0
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WooCommerce: by Automattic – 7.6.0-beta.1
WordPress Beta Tester: by WordPress Upgrade/Install Team – 3.3.5

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 5.1
Elementor: by Elementor.com – 3.11.5
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 11.9.1

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class (Drop-in)

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-25 10:34:44 +00:00
Options: ✔
Notes: 40
Onboarding: skipped

### Action Scheduler ###

Complete: 1,024
Oldest: 2023-03-23 10:35:51 +0000
Newest: 2023-03-24 14:18:08 +0000

Failed: 1
Oldest: 2023-03-23 10:38:15 +0000
Newest: 2023-03-23 10:38:15 +0000

Pending: 9
Oldest: 2023-03-24 14:18:13 +0000
Newest: 2023-03-25 10:49:19 +0000

### Status report information ###

Generated at: 2023-03-24 14:18:34 +00:00
`

</details>

**Comment by nerrad** [comment] 2023-03-31 20:46
I'm unable to reproduce this with either of the following two environments:

## Environment One
- WP 6.2
- WooCommerce 6.2.beta.2
- Woo Blocks inactive
- Gutenberg not active

## Environment Two
- WP 6.2
- WooCommerce 6.2.beta.2
- Woo Blocks inactive
- Gutenberg 15.4.0 active

I see from the screenshot in the post that Gutenberg 15.1.0 is also active. 

It's possible this was at one point a bug within WordPress or Gutenberg but it's not present with the latest environments as noted above so I'm deprioritizing this from high priority flag.

From the attached video, I also wonder if the tester just didn't wait long enough for things to load (since the spinner was still visible). AFAIK various elements or the toolbar are rendered via Suspense so there may be a delay on slow connections.

**Comment by roykho** [comment] 2023-06-05 17:00
I've tested this also with the following:

* WP 6.2.2
* Gutenberg 15.9.1 (active and not active)
* WooCommerce 7.9-dev
* Woo Blocks 10.4-dev (active and not active)

Not able to reproduce. I will be closing this for now.

**Closed as completed by roykho** 2023-06-05 17:00 UTC
Labels: type: bug
