### ISSUE TITLE
[GlobalStep] "Left Align" appears highlighted continuously even when user selects Center or right alignment under Featured Product and Featured Category block. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2632] opened 2020-06-04 15:05 UTC
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Click on Post.
3. Click on Add New Post.
4. Select block type as Featured Product or Featured Category.
5. Tap on button alignment option.
6. Change alignment to Center or Right 
7. Again tap on button alignment option.
8. Observe that "Left Align" appears highlighted continuously even when user selects Center or right alignment under Featured Product and Featured Category block.

**Actual Result:**
"Left Align" appears highlighted continuously even when user selects Center or right alignment under Featured Product and Featured Category block.

**Expected Result:**
The selected option should be highlighted.

![#2632](https://user-images.githubusercontent.com/41110392/83774261-175be580-a6a3-11ea-97fc-c9755baf86d9.png)

**Comment by nerrad** [comment] 2020-06-04 23:51
This may be a bug in Gutenberg since we’re using a GB tool button. I’ll file this in the backlog pipeline for now.

**Comment by Aljullu** [comment] 2020-09-17 08:18
I'm unable to reproduce this issue with the latest version of `main` (see GIF below):

![Peek 2020-09-17 10-10](https://user-images.githubusercontent.com/3616980/93439247-9aa9eb80-f8ce-11ea-816c-aaf91c2898e2.gif)

If the issue was regarding the outline around 'Align left', I think that's the expected behavior since that's the outline to highlight where the keyboard focus is.

![imatge](https://user-images.githubusercontent.com/3616980/93439576-055b2700-f8cf-11ea-8e97-91223c76388f.png)

Given that, I will close this issue for now. Feel free to reopen if you think I missed something.

**Closed by Aljullu** 2020-09-17 08:18 UTC
Labels: type: bug, ◼️ block: featured category, ◼️ block: featured product
