### ISSUE TITLE
[GlobalStep] "Missing Dependencies" error is displayed upon login WPENGINE TEST SITE under Scripts section

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce-gutenberg-products-block#2620] opened 2020-06-03 15:28 UTC
**Environment:**
Windows 10: Chrome(v83.0.4103.61)
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:**
1. Go to "http://wpe.testwc.com/wp-login.php"
2. Login using valid credential.
3. Tap on Query Monitor.
4. Observe that Scripts error stating "Missing Dependencies" is displayed.

**Actual Result:**
"Missing Dependencies" error is displayed upon login WPENGINE TEST SITE under Scripts section.

**Expected Result:**
No error message should be displayed.

![#2620](https://user-images.githubusercontent.com/41110392/83656326-05177400-a5dd-11ea-9f0d-f40deec9236f.png)

**Comment by nerrad** [comment] 2020-06-03 20:00
Thanks for the report! This doesn't look like anything caused by the Blocks plugin as this is a WordPress core script (between `heartbeat` and `wp-auth-check`). Neither of those scripts are dependencies of the blocks plugin.

I don't know if it's something specific to the WPEngine environment or not, but I'm going to close this issue for now.

cc @juliaamosova in case this is something you want to follow up on with the WPEngine test site.

**Closed by nerrad** 2020-06-03 20:00 UTC

**Comment by juliaamosova** [comment] 2020-06-03 20:11
Thanks for flagging this issue @nerrad! I'll transfer it to the WooCommerce Core repository in order to make sure to take a look.
