### ISSUE TITLE
Utils::wp_version_compare casting error

### ISSUE THREAD

**Issue by timotheemoulin** [woocommerce/woocommerce-gutenberg-products-block#10563] opened 2023-08-14 11:15 UTC
https://github.com/woocommerce/woocommerce-blocks/blob/576255379d310a59afcae949dfe0628d40a9cc96/src/Utils/Utils.php#L22C28-L22C28

There is a number casting error when using the PHP `version_compare` function to assert the current WP version.
The error occurs when the locale has been set to "French" before (at least for this language) because the default separator is a comma `,` instead of a dot `.`.

So when casting `(float) '6.3'` in French, PHP returns `6,3.0` instead of `6.3`.

Here is a small example.
If you run it with PHP 8.0|8.1 values for French and English locales are the same.
```php
<?php
setlocale(LC_ALL, "en_US");  
var_dump('EN');
var_dump(version_compare('1.2',1.2));
var_dump(version_compare(1.2,1.2));
var_dump(version_compare(1.2,'1.2'));


setlocale(LC_ALL, "fr_FR");  
var_dump('FR');
var_dump(version_compare('1.2',1.2));
var_dump(version_compare(1.2,1.2));
var_dump(version_compare(1.2,'1.2'));
```
But if you run it with PHP 7.4 (current PHP version for WP 6.3), French values differ.

PHP 8.0|8.1
```php
string(2) "EN"
int(0)
int(0)
int(0)
string(2) "FR"
int(0)
int(0)
int(0)
```

PHP 7.4
```php
string(2) "EN"
int(0)
int(0)
int(0)
string(2) "FR"
int(1)
int(0)
int(-1)
```

A viable solution IMO would be to compare string in any case and convert the input value to string by replacing non alpha-numerics chars by dots. This (in summary) what [`version_compare`](https://www.php.net/manual/en/function.version-compare.php) is doing.

```php
public static function wp_version_compare( $version, $operator = null ) {
    // Replace non-alphanumeric characters with a dot
    $version = preg_replace( '/[^0-9a-zA-Z\.]+/i', '.', $version );
    
    $current_wp_version = get_bloginfo( 'version' );
    if ( preg_match( '/^([0-9]+\.[0-9]+)/', $current_wp_version, $matches ) ) {
        $current_wp_version = preg_replace( '/[^0-9a-zA-Z\.]+/i', '.', $matches[ 1 ] );
    }
    
    return version_compare( $current_wp_version, $version, $operator );
}
```

Any thoughts?

**Comment by senadir** [comment] 2023-08-15 14:02
I'm not able to reproduce this. At least, in both PHP 8 and PHP 7.4, the version I'm getting is always `6.3`. Testing with setting the website language as french.

Do you have some reproduce steps of how this might be an issue? or simple snippet I can paste?

**Comment by timotheemoulin** [comment] 2023-08-15 14:38
Can you try to run `setlocale(LC_ALL, "fr_FR");` before calling the function?

**Comment by timotheemoulin** [comment] 2023-08-16 09:06
@senadir You can see the error reproduced here. The same applies 
Result for 8.0.30, 8.1.11: OK
Result for 7.4.32: KO
https://onlinephp.io/c/ad9c9

**Comment by kilianm97** [comment] 2023-08-16 09:13
I have exactly the same problem with the french language.

**Comment by tarunvijwani** [comment] 2023-08-23 08:20
Thank you for reporting the issue. Even though we are unable to reproduce it, it is still important to fix it as a precautionary measure. Therefore, I will be moving this ticket to the backlog for further action.

Internal discussion: p1692773342122439-slack-C8X6Q7XQU

**Comment by timotheemoulin** [comment] 2023-09-26 17:39
@tarunvijwani let me know if I can be of any help on the subject

**Closed as completed** 2023-12-07 17:18 UTC
Labels: type: community contribution, team: Kirigami & Origami
