### ISSUE TITLE
local pickup has weird $0.00 crossed out?!

### ISSUE THREAD

**Issue by suze-it** [woocommerce/woocommerce-gutenberg-products-block#4154] opened 2021-04-29 19:37 UTC
## What do you like about the Cart & Checkout blocks?
I love the checkout blocks! 
## What do you think is missing from the Cart & Checkout blocks?
I don't understand why the "Local Pickup" shipping method has the $0.00 crossed out when it is selected.  Can you help me remove that?  On this screen snapshot you can see that it's surrounded by `<del> </del>`
![shippingPrices](https://user-images.githubusercontent.com/83427163/116607999-85c31b00-a8e7-11eb-8420-4a87354332e8.jpg)

**Comment by ralucaStan** [comment] 2021-05-03 09:32
Hi there @suze-it,
thank you for reaching out.

I was not able to reproduce your bug, so I need to know more details about your setup.
- What theme are you using?
- Does the shipping option name have `<del>` tags inside of it? You could check at `WooCommerce > Settings > Shipping`. If that's the case I recommend removing them to fix your issue.

**Comment by suze-it** [comment] 2021-05-03 18:44
I'm using Cakecious theme.  I checked those settings and there is no "del" tags in the name.  This snippit shows what the 'crossed out' description of mine means... it's visible here on the shopping cart.  On the checkout page it shows the "del" tags.

![cartlocalsnippit](https://user-images.githubusercontent.com/83427163/116917969-2ecd8680-ac04-11eb-8558-cdc3c22cb54c.jpg)

**Comment by suze-it** [comment] 2021-05-03 18:53
I noticed that the debug code show the del tags in it...

![localpickupcode](https://user-images.githubusercontent.com/83427163/116919413-15c5d500-ac06-11eb-967d-4d6fe143607f.jpg)

**Comment by mikejolley** [comment] 2021-05-06 10:41
Please post the report from WooCommerce > Status. This is almost certainly a plugin conflict because as far as I am aware, shipping costs are never "on sale", which the strike out indicates. I think something is filtering the display value for the cost.

**Comment by suze-it** [comment] 2021-05-06 20:28
@mikejolley I don't know which report/log you are referring to.  Sorry, can you tell me exactly what I can post that will be helpful?  I think something is doing the filtering too.  It's weird since if "Local pickup" is NOT selected, the strike out does not appear.  It appears on both the cart and checkout pages.  This is what it looks like on the Checkout page with WooCommerce Checkout Blocks.

![checkoutslocalpickupstrikeout](https://user-images.githubusercontent.com/83427163/117361300-b74f5f80-ae6e-11eb-8b34-1f0c2e9754fd.jpg)

**Comment by ralucaStan** [comment] 2021-05-07 09:16
Hi @suze-it, about the System Status report, instructions on how to provide that can be found at this URL: https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/#section-1.

Do you also have a stagging site we could take a look at? If so, did you try disabling other extensions to see if the issue is still present?

**Comment by suze-it** [comment] 2021-05-08 18:46
Hi @ralucaStan .  Thanks for the instructions on getting the status report.  Here it is.  My staging site is ckb.itb.mybluehost.me.  I'm still troubleshooting the cause.  Thank you for your help.

### WordPress Environment ###

WordPress address (URL): http://ckb.itb.mybluehost.me
Site address (URL): http://ckb.itb.mybluehost.me
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 5.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.34
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.76.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: _CNT_
Total Database Size: 37.45MB
Database Data Size: 33.33MB
Database Index Size: 4.12MB
_CNT_woocommerce_sessions: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_CNT_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
_CNT_woocommerce_tax_rates: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_CNT_woocommerce_tax_rate_locations: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_CNT_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_a4barcode_custom_formats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_a4barcode_custom_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_a4barcode_paper_formats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_actionscheduler_actions: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
_CNT_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_actionscheduler_logs: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
_CNT_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_CNT_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_options: Data: 4.49MB + Index: 0.13MB + Engine MyISAM
_CNT_postmeta: Data: 2.03MB + Index: 1.06MB + Engine MyISAM
_CNT_posts: Data: 0.88MB + Index: 0.15MB + Engine MyISAM
_CNT_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_slides: Data: 0.24MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_termmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
_CNT_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
_CNT_term_relationships: Data: 0.07MB + Index: 0.15MB + Engine MyISAM
_CNT_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_CNT_tinvwl_analytics: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_tinvwl_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_tinvwl_lists: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_usermeta: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
_CNT_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
_CNT_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
_CNT_wc_category_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_wc_order_product_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
_CNT_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_wc_product_meta_lookup: Data: 0.08MB + Index: 0.11MB + Engine MyISAM
_CNT_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_CNT_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
_CNT_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_wffilemods: Data: 13.55MB + Index: 0.00MB + Engine InnoDB
_CNT_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_CNT_wfhoover: Data: 4.52MB + Index: 1.52MB + Engine InnoDB
_CNT_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_CNT_wfknownfilelist: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
_CNT_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_CNT_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_CNT_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_CNT_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_CNT_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_CNT_wfstatus: Data: 0.19MB + Index: 0.13MB + Engine InnoDB
_CNT_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_CNT_woobe_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woobe_history_bulk: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_woof_query_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_wpforms_tasks_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
_CNT_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_yith_wcwl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_yith_wcwl_lists: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_yoast_indexable: Data: 0.23MB + Index: 0.10MB + Engine MyISAM
_CNT_yoast_indexable_hierarchy: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
_CNT_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_CNT_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_CNT_yoast_seo_links: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
_CNT_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

attachment: 173
custom_css: 2
customize_changeset: 10
kor_events: 1
nav_menu_item: 45
oembed_cache: 3
page: 41
post: 7
product: 1159
product_variation: 49
revision: 90
shop_order: 27
tribe_events: 2
tribe_organizer: 1
tribe_rsvp_attendees: 1
tribe_rsvp_tickets: 1
tribe_venue: 2
tt_project: 8
tt_testimonial: 4
wpcf7_contact_form: 5
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Print Barcodes on Label Sheets for Wordpress & WooCommerce (demo): by UkrSolution – 2.14.2
bLoyal: by bLoyal – 3.0.510.02
Bluehost: by Bluehost – 2.6.2
Embed bLoyal Tabs: by bLoyal – 1.0.510.01
Event Tickets: by The Events Calendar – 5.1.3
Jetpack by WordPress.com: by Automattic – 9.7
WPBakery Page Builder: by Michael M - WPBakery.com – 6.6.0
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
Quantity Field on Shop Page for WooCommerce: by Wooassist – 1.3.0
Slider Revolution: by ThemePunch – 6.4.3
Templatation Framework: by Templatation – 3.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.56

EasyPost Shipping PRO for WooCommerce: by OneTeamSoftware – 1.5.3
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.3.11
BEAR - Bulk Editor and Products Manager: by realmag777 – 1.0.8.1
WooCommerce Blocks: by Automattic – 5.0.0
Woocommerce Table Rate Shipping: by JEM Plugins – 2.1.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 5.1.0
WooCommerce Product Categories Selection: by PluginForage.com – 2.0
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.5.3
WooCommerce Shipping & Tax: by WooCommerce – 1.25.12
WooCommerce: by Automattic – 5.2.2
Wordfence Security: by Wordfence – 7.5.2
WP Fastest Cache: by Emre Vona – 0.9.1.7
WP Maintenance Mode: by Designmodo – 2.3.0
WPForms Lite: by WPForms – 1.6.6

### Inactive Plugins (15) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Contact Form 7: by Takayuki Miyoshi – 5.4.1
Elementor: by Elementor.com – 3.2.3
Event Tickets Plus: by The Events Calendar – 5.2.2.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.17.0
OptinMonster: by OptinMonster Team – 2.3.2
Product CSV Import Export (BASIC): by WebToffee – 1.9.3
Stripe For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.0

The Events Calendar: by The Events Calendar – 5.6.0
TI WooCommerce Wishlist: by TemplateInvaders – 1.25.4
Woocommerce KORONA Connector: by COMBASE USA
Inc – 1.0

Woocommerce Product Page Social Share: by Sajjad Hossain Sagor – 2.0.2
WooCommerce USA ePay Gateway: by SkyVerge – 1.9.0
Yoast SEO: by Team Yoast – 16.2

### Dropin Plugins (1) ###

db-error.php: db-error.php

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.0.5
SSO: by Garth Mortensen
Mike Hansen – 0.3


### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2467 - /shop/
Cart: #2468 - /cart/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #2470 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Cakecious
Version: 5.1
Author URL: https://bolvo.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: cakecious/woocommerce/content-product.php
cakecious/woocommerce/content-single-product.php
cakecious/woocommerce/loop/loop-end.php
cakecious/woocommerce/loop/loop-start.php
cakecious/woocommerce/loop/orderby.php
cakecious/woocommerce/loop/result-count.php


### Action Scheduler ###

Complete: 267
Oldest: 2021-05-06 19:00:36 +0000
Newest: 2021-05-08 18:28:17 +0000

Pending: 7
Oldest: 2021-05-09 06:09:42 +0000
Newest: 2021-05-13 21:33:41 +0000


### Status report information ###

Generated at: 2021-05-08 18:42:24 +00:00
`

**Comment by mikejolley** [comment] 2021-05-10 09:40
I see you're using some other rates like Table Rates - I wonder if the actual Local Pickup (dedicated) shipping method is being used here, or if it's setup as a table rate instead or similar? Perhaps a method which lets you input multiple costs per rate like weight based shipping?

**Comment by suze-it** [comment] 2021-05-11 05:04
Thanks @mikejolley for the suggestion.  I deactivated the WooCommerce Table Rates Shipping since I'm using the EasyPost Shipping PRO for WooCommerce to do my shipping.  That didn't affect it and it's still acting weird.

**Comment by Aljullu** [comment] 2021-05-13 12:40
Thanks for coming back to us @suze-it. Figuring out which plugin is causing the issue might a bit laborious but shouldn't be difficult. You will need to deactivate all plugins except WooCommerce + WooCommerce Blocks and verify that `Local pickup` shows up correctly. After that, you can reactivate all other plugins one-by-one and repeat the testing until you find which plugin is causing the issue. Once you know it, I suggest contacting the developers to let them know about it.

We have some information about how to debug plugin conflicts in this docs page:

https://docs.woocommerce.com/document/how-to-test-for-conflicts/

Before doing the conflict testing, we recommend making a backup of your site or doing the testing in a staging site so your production site is not affected.

Hope that helps!

**Comment by nerrad** [comment] 2021-05-26 18:22
I'm going to close this issue because there currently isn't anything actionable on our end and it's been 13 days since the last response. If anything has changed that gives more information for helping to reproduce this then please add it to the issue. Thanks!

**Closed as completed by nerrad** 2021-05-26 18:22 UTC
Labels: block-type: local pickup
