### ISSUE TITLE
[CYS Woo Express] Centered header menu with search 

### ISSUE THREAD

**Issue by verofasulo** [woocommerce/woocommerce-gutenberg-products-block#11389] opened 2023-10-23 08:17 UTC
Please review `Centered header menu with search`. 

How it currently looks like:

<img width="1728" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/72e3e1a0-83b6-486a-807b-323e5e198eb6">

<img width="1726" alt="image" src="https://github.com/woocommerce/woocommerce-blocks/assets/98944206/1634e963-0f5e-4609-b04a-bdff4895fc6b">

---

How it's supposed to look like:

[Figma - Large screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2283-35758&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/7fd4703f-fc36-432f-9b7e-441752bb7623)

[Figma - Small screens](https://www.figma.com/file/F5AAbRJOGbTeEweXPFtHgf/%5Btemplates-%26-patterns%5D-Woo-Starting-Layouts?type=design&node-id=2242-34330&mode=design&t=qkpAGsXW7rY6XBmF-4)

![image](https://github.com/woocommerce/woocommerce-blocks/assets/98944206/1118179d-b70d-4d49-991f-cd3909df37ae)

**Comment by nefeline** [comment] 2023-10-23 17:13
Quick note regarding the icon size: that will be worked on by Guidorah as part of https://github.com/woocommerce/woocommerce/issues/40947 : we should not be hardcoding the width of the icon in patterns.

**Comment by gigitux** [comment] 2023-10-27 13:47
Duplicate of https://github.com/woocommerce/woocommerce-blocks/issues/11253

**Closed as completed by gigitux** 2023-10-27 13:47 UTC
Labels: type: bug, priority: high
