### ISSUE TITLE
Since this block was added, my integration with Mollie payments doesn't work anymore...

### ISSUE THREAD

**Issue by Deezerfly** [woocommerce/woocommerce-gutenberg-products-block#9718] opened 2023-06-05 11:18 UTC

**Comment by nielslange** [comment] 2023-06-07 05:18
Hello @Deezerfly 👋

Thanks for reaching out. Can you please provide more context on the problem that you are facing? You mentioned that Mollie isn't working since you added "this block". By "this block", are you referring to WooCommerce Blocks in general or to the Cart or Checkout block in specific? It might be handy to provide your system status report so that we can see which extensions you have installed. On https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/, you can find detailed steps on how to create the system status report.

**Comment by Deezerfly** [comment] 2023-06-08 05:11
Hi!
I was talking about the new checkout block. I have since then found out, it will not work well with the "Mollie" service and replaced it with the old shortcode. Everything is working again as it should.

**Comment by tarhi-saad** [comment] 2023-06-08 15:53
Hi @Deezerfly! 👋 Thank you for reporting this issue! 🙌 

> I have since then found out, it will not work well with the "Mollie" service

The [Mollie Payments for WooCommerce](https://woocommerce.com/products/mollie-payments-for-woocommerce/) extension added support for the WooCommerce Blocks (i.e., Cart & Checkout Blocks) in `v7.0.0`. And we recently did [an audit](https://github.com/woocommerce/woocommerce-blocks/issues/9227) to look for compatibility issues between the Mollie Payments extensions and the WooCommerce Blocks. We confirmed that [the functionality was working as expected](https://github.com/woocommerce/woocommerce-blocks/issues/9227#issuecomment-1534456305). It would be a great help if you could share with us more information about [your website's environment ](https://github.com/woocommerce/woocommerce-blocks/issues/9718#issuecomment-1579914603) and more details about this bug! You can use the following template to fill out the bug report:

## Describe the bug

A clear and concise description of what the bug is.

## To reproduce

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Screenshots

If applicable, add screenshots to help explain your problem.

## Environment

### WordPress (please complete the following information):

-   WordPress version: [e.g. 5.9]
-   Gutenberg version (if installed): [e.g. 12.0.0]
-   WooCommerce version: [e.g. 6.1]
-   WooCommerce Blocks version: [e.g. 7.0.0]
-   Site language:
-   Any other plugins installed:

### Desktop (please complete the following information):

-   OS: [e.g. macOS, Windows]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

### Smartphone (please complete the following information):

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

## Additional context

Add any other context about the problem here.

**Comment by nielslange** [comment] 2023-06-23 07:40
Hello @Deezerfly, I’m going to close this because there still isn’t anything actionable for us on this issue. If/when you have additional details, you can still add them to this issue and if we’re able to reproduce, we can re-open as necessary.

**Closed as completed by nielslange** 2023-06-23 07:40 UTC
Labels: type: community contribution
