### ISSUE TITLE
Description on the cart and checkout page

### ISSUE THREAD

**Issue by msroky** [woocommerce/woocommerce-gutenberg-products-block#5310] opened 2021-12-04 14:14 UTC
I would like you to remove this product description from the cart and checkout page in the next upgrade because I think it is unnecessary and just takes up space.

![Capture4](https://user-images.githubusercontent.com/12650820/144712615-16f843f2-cc6d-42c0-b775-f7739e8d716b.PNG)
![Capture5](https://user-images.githubusercontent.com/12650820/144712621-2331bb25-e538-49cb-8580-43e348fdaeb3.PNG)

I removed it using display: block; but it still loads in the background!

**Comment by sunyatasattva** [comment] 2021-12-07 00:14
Hi there @msroky !

Thank you for reaching out to us with your request!

~I believe your issue is dependent on the theme you are currently using and is not specific to us. Which theme are you currently using? It would be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment.~

Disregard what I said above. Again, thank you for your suggestion. After talking internally with the team, we identified two issues that are very similar to what you are asking.

Here are the links:

* [Option to show/hide Product Metadata](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4045)
* [Strip images from Product Summary shown on cart](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3142)

We definitely do have plans to provide more control around how certain parts of the cart are shown, so please follow those issues for more details and updates. In the meantime, we can close this one.

Thanks again for the feedback!

**Comment by sunyatasattva** [comment] 2021-12-07 14:39
Duplicate of #4045

**Closed as completed** 2021-12-07 14:38 UTC
Labels: type: duplicate
