### ISSUE TITLE
Empty cart smiley image needs work 

### ISSUE THREAD

**Issue by josemarques** [woocommerce/woocommerce-gutenberg-products-block#2358] opened 2020-04-29 15:43 UTC
While testing with Gutenberg 7.9.1 and WooCommerce 4.1.0-rc.1 with Storefront the smiley sad image for empty cart is aligned to left and looks overall a bit weird:

<img width="780" alt="Screenshot 2020-04-29 at 16 41 44" src="https://user-images.githubusercontent.com/57050/80616043-56f63880-8a38-11ea-9e07-1be18877c25d.png">

<img width="1454" alt="Screenshot 2020-04-29 at 15 27 40" src="https://user-images.githubusercontent.com/57050/80616086-607fa080-8a38-11ea-991f-51632fe43269.png">

**Comment by nerrad** [comment] 2020-04-29 21:11
Thanks for the report, this is a duplicate of #2297

**Closed by nerrad** 2020-04-29 21:11 UTC
