### ISSUE TITLE
[TT4] Featured Category block - Editor UI Issues: List Style and Button Contrast

### ISSUE THREAD

**Issue by imanish003** [woocommerce/woocommerce-gutenberg-products-block#11302] opened 2023-10-18 07:35 UTC
## Describe the bug

In the Featured Category block, there are a few UI issues that need to be addressed within the editor:
1. List styles are showing up incorrectly.
2. Poor button contrast on hover for the "Shop Now" button.
3. Another contrast issue appears after adding an image as background.

## To reproduce

1. Go to the editor and add a 'Featured Category' block.
2. Observe the list styles within the block.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/f41e7e05-f40e-450e-8770-8c74a51125e8)

3. Hover over the "Shop Now" button and notice the contrast issues.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/ee419927-2fbc-4310-8ded-6677b5551e85)

4. Add an image as background to the block and observe further contrast issues.
![image](https://github.com/woocommerce/woocommerce-blocks/assets/16707866/cc62b064-815d-46fe-9610-b5cbd83c3822)

**Comment by danieldudzic** [comment] 2023-10-26 16:25
Thanks Manish for reporting.

> 1. List styles are showing up incorrectly.

@sunyatasattva reported the same issue here: https://github.com/woocommerce/woocommerce-blocks/issues/11327

> 2. Poor button contrast on hover for the "Shop Now" button and 3. Another contrast issue appears after adding an image as background.

Not sure if these can be considered as bugs. Those are a result of a different color choice for the theme colors for TT4.

The block seems to be functioning as expected to me.

**Comment by nerrad** [comment] 2023-10-27 09:26
The first issue is a duplicate of #11327 and I agree with Daniel on the second reported issue not being a bug.

**Closed as completed by nerrad** 2023-10-27 09:26 UTC
Labels: type: bug, block: featured category
